### ISSUE TITLE
Response on upload error

### ISSUE THREAD

**Issue by makunomark** [gotev/android-upload-service#101]
I am aware of the server response when a file is successfully uploaded. However, a feature where a response is availed when the file upload fails would be very important in some cases. Thanks

**Comment by gotev** [comment]
Got it. However, that is not always possibile (e.g. the connection between your device and the server drops, the server process crashes unexpectedly, ..).
Could you please provide a minimal server implementation with which to reproduce this exact use case?

**Comment by makunomark** [comment]
Yes, Ill provide a minimal implementation shortly

**Comment by gotev** [comment]
@makunomark Thank you! If you could provide the server side code with an example to reproduce your use case, we could find a way to handle it and to include the needed modifications in milestone 2.1, which I plan to release as soon as I'm done with #95

**Comment by makunomark** [comment]
The server side code is sort of proprietary, if I could explain how it works I believe we could have it worked out. Actually I have never seen how its implemented but I believe its in Java. And it sends response if the file fails to upload. Like the way you receive a response on successful upload, the server responds when the file is not successfully uploaded, for instance with a status code 401

**Comment by gotev** [comment]
@makunomark Implemented endpoint which responds with 401 and a JSON
Request with cURL:
```
curl -d"a=1" -D - http://localhost:3000/upload/forbidden
```
Response:
```
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 85
ETag: W/"55-mWd+MzHLLzpnX6S7f6W1cQ"
Date: Thu, 31 Mar 2016 14:17:19 GMT
Connection: keep-alive

{"success":false,"message":"this endpoint always returns 401! It's for testing only"}
```

By using the latest library snapshot with demo app, what I get in the LogCat is the following:
```
D/UploadService: HttpUploadTask - Starting upload task with ID c69db9b1-df8b-429b-ba2a-be25481745d0
D/UploadService: HurlStackConnection - creating new connection
D/UploadService: HttpUploadTask - Broadcasting upload progress for c69db9b1-df8b-429b-ba2a-be25481745d0 Uploaded bytes: 163 out of 71071
I/UploadServiceDemo: The progress of the upload with ID c69db9b1-df8b-429b-ba2a-be25481745d0 is: 0
D/UploadService: HttpUploadTask - Server responded with HTTP 401 to upload with ID: c69db9b1-df8b-429b-ba2a-be25481745d0
D/UploadService: HttpUploadTask - Broadcasting upload completed for c69db9b1-df8b-429b-ba2a-be25481745d0
I/UploadServiceDemo: Upload with ID c69db9b1-df8b-429b-ba2a-be25481745d0 is completed: 401, {"success":false,"message":"this endpoint always returns 401! It's for testing only"}
D/UploadService: UploadService - c69db9b1-df8b-429b-ba2a-be25481745d0 now un-holded the foreground notification
D/UploadService: UploadService - All tasks finished. UploadService is about to shutdown...
```
So, when the upload fails with a 4xx error code, you will get the response in BroadcastListener's `onCompleted` method as expected
```java
@Override
public void onCompleted(String uploadId, int serverResponseCode, byte[] serverResponseBody) {
    Log.i(TAG, "Upload with ID " + uploadId + " is completed: " + serverResponseCode + ", "
               + new String(serverResponseBody));
}
```
Therefore, I consider this issue resolved.

**Comment by makunomark** [comment]
@gotev thankyou so much. It works :+1:
