### ISSUE TITLE
not show progress ( very fast )

### ISSUE THREAD

**Issue by sajadpm** [gotev/android-upload-service#103]
when upload a file with small size like 600 kb progress is 0 and after 4 or 6 sec show upload success ... 
how to show progress uploaded file 1% by 1% ? thanks

**Comment by gotev** [comment]
The upload progress depends entirely on how much data you are uploading and your bandwidth. The upload transfers 4KB chunks at a time, as you can see in HttpUploadTask class. So, if you have a little file to upload and a large bandwidth, that's what you will see. If you try to upload a bigger file (e.g. 50MB) with the same bandwidth, you will notice the progress. It's perfectly normal behaviour.
