### ISSUE TITLE
how can i get callBack from server in MultipartUploadRequest?

### ISSUE THREAD

**Issue by milaptank** [gotev/android-upload-service#104]
Hello 
This is not bug but my question is when i use MultipartUploadRequest it will return UploadID but can i receive response from server from same MultipartUploadRequest as callBack ?

**Comment by gotev** [comment]
Since the service communicates status updates with broadcast intents, it's not possible to have callbacks with the current release. However, you can achieve the same behaviour by extending the `UploadServiceBroadcastReceiver` to filter only the events for a specific uploadID:
```java
public class SingleUploadBroadcastReceiver extends UploadServiceBroadcastReceiver {
    
    private String mUploadID;
    
    public void setUploadID(String uploadID) {
        mUploadID = uploadID;
    }

    @Override
    public void onProgress(String uploadId, int progress) {
        if (!uploadId.equals(mUploadID)) return;
    }

    @Override
    public void onProgress(String uploadId, long uploadedBytes, long totalBytes) {
        if (!uploadId.equals(mUploadID)) return;
    }

    @Override
    public void onError(String uploadId, Exception exception) {
        if (!uploadId.equals(mUploadID)) return;
    }

    @Override
    public void onCompleted(String uploadId, int serverResponseCode, byte[] serverResponseBody) {
        if (!uploadId.equals(mUploadID)) return;
    }

    @Override
    public void onCancelled(String uploadId) {
        if (!uploadId.equals(mUploadID)) return;
    }
}
```
Then, in your activity:
```java
public class YourActivity extends Activity {

    private static final String TAG = "AndroidUploadService";

    private final SingleUploadBroadcastReceiver uploadReceiver =
    new SingleUploadBroadcastReceiver() {

        @Override
        public void onProgress(String uploadId, int progress) {
            super.onProgress(uploadId, progress);
            // your implementation
        }

        @Override
        public void onProgress(final String uploadId,
                               final long uploadedBytes,
                               final long totalBytes) {
            super.onProgress(uploadId, uploadedBytes, totalBytes);
            // your implementation
        }

        @Override
        public void onError(String uploadId, Exception exception) {
            super.onError(uploadId, exception);
            // your implementation
        }

        @Override
        public void onCompleted(String uploadId,
                                int serverResponseCode,
                                byte[] serverResponseBody) {
            super.onCompleted(uploadId, serverResponseCode, serverResponseBody);
            // your implementation
        }

        @Override
        public void onCancelled(String uploadId) {
            super.onCancelled(uploadId);
            // your implementation
        }
    };

    @Override
    protected void onResume() {
        super.onResume();
        uploadReceiver.register(this);
    }

    @Override
    protected void onPause() {
        super.onPause();
        uploadReceiver.unregister(this);
    }

    public void uploadMultipart(final Context context) {
        try {
            String uploadId = UUID.randomUUID().toString();
            uploadReceiver.setUploadID(uploadId);

            new MultipartUploadRequest(context, uploadId, "http://upload.server.com/path")
                .addFileToUpload("/absolute/path/to/your/file", "your-param-name")
                .setNotificationConfig(new UploadNotificationConfig())
                .setMaxRetries(2)
                .startUpload();

        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }
    }

}
```

**Comment by milaptank** [comment]
Hey @gotev Your work helps me a lot thank you so much :+1:  :100: % working 
I want this and i got it 

 @Override
    public void onCompleted(int serverResponseCode, byte[] serverResponseBody) {
      JSONObject response = new JSONObject(new String(serverResponseBody, "UTF-8"));
    }

**Comment by gotev** [comment]
You're welcome :smile:

**Comment by C130187** [comment]
I am not able to see any result of my implementation in the onCompleted()..I have followed exactly what is said here..I dont see any toast or anything printed in the debugger as well..please help

**Comment by gotev** [comment]
Open a new issue and fill in the requested information

**Comment by gotev** [comment]
Updated example of `SingleUploadBroadcastReceiver` here: https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status#single-upload-broadcast-receiver

**Comment by danielprad0** [comment]
i've tried as well the code, but can't make it work, i can't see a toast, or alert when there's an error uploading the file. some help please!

**Comment by gotev** [comment]
Check out the demo example app and refer to the instructions provided in the "monitoring" wiki page. Also, enabling debug log may help you

**Comment by danielprad0** [comment]
Once everthing's done you have to call the method uploadMultipart right but what parameters do i have to use ?

**Comment by gotev** [comment]
You shouldn't call that method. Just build up the upload request and start it. Make sure your broadcast receiver is registered. Check the recipes and monitoring wiki pages for detailed instructions. If you don't receive any event, probabily something is not setup.

**Comment by danielprad0** [comment]
Ok, thanks. definitely im not doing something right because when i put the marker on the uploadMultipart method, it says "Method uploadMultipart(android.content.Context) is never used"

**Comment by rushikeshruda** [comment]
oncompleted is not getting executed after the upload is completed plzz help..

**Comment by muneradam** [comment]
hi gotev I implement you code above but i got error in atatment         uploadReceiver.unregister(this); 
and         uploadReceiver.register(this); 
iam use this version implementation 'net.gotev:uploadservice:2.1' 
so i need to know what is the probleam

**Comment by gotev** [comment]
This is really old and not supported anymore. Please update to newer 3.x or 4.x versions.
