### ISSUE TITLE
How to auto upload all file in folder?

### ISSUE THREAD

**Issue by vanloc0301** [gotev/android-upload-service#105]
I want browser all file in 1 folder filter by extension file like *.mp4. And upload all to my server.

How to do this? Thanks.

**Comment by gotev** [comment]
Hi! You can do that by listing all the files in a folder with a filter for `mp4` files, using Java's `File` class. After you've done that, just add all the files in the list to your request by calling `addFileToUpload` multiple times. Check the Recipes in the Wiki. 
I'm closing this ticket, as this issue tracker is used to track library issues and improvements, but this is a "how to" question. Next time, please ask such questions on StackOverflow, thank you :)
