### ISSUE TITLE
Can't using getLayoutInflater() when extends Service

### ISSUE THREAD

**Issue by vanloc0301** [gotev/android-upload-service#106]
I am using MultipleUpload in my class extends Service.

But not found getLayoutInflater() function and can't upload a file to the server.

How to fix this problem?
Thank you very much.

**Comment by gotev** [comment]
Have you read the [asking for help](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help) page in the wiki? This is not the proper place to ask for support :(
