### ISSUE TITLE
Remove android:allowBackup from AndroidManifest

### ISSUE THREAD

**Issue by psmorandi** [gotev/android-upload-service#109]
Hello there,

I'm using your library in my application and I got this error:

`
Error:Execution failed for task ':<omitted>:processDevDebugManifest'.
 Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:16:9-36
	is also present at [net.gotev:uploadservice:2.0.1] AndroidManifest.xml:16:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:14:5-125:19 to override.
`

I know how to correct this error, but that got me thinking. Your library "really" need this allowBackup flag? I think this should be delegated to the application itself. My application for instance, can't allowBackup of it's configurations by design.

Same thing for the other flag used in Manifest: `android:supportsRtl="true"`.

If you put this just because of some "lint" rule, I would suggest you to turn this rule off, since for a library, in my opinion, this is not needed.

That's all and please keep up with your work, it's going to help me a lot!

Thanks

**Comment by gotev** [comment]
Yeah, I agree with your analysis

**Comment by gotev** [comment]
The modification will be included in the upcoming 2.1 release. Thank you for the suggestion!
