### ISSUE TITLE
OutOfMemory Exception on 35MB File Upload

### ISSUE THREAD

**Issue by quantum0813** [gotev/android-upload-service#114]
I am getting an OutOfMemory exception when trying to upload a 35MB file. This is occurring on a Samsung Galaxy S5 running Android 4.4.2. Here is the stack trace:
```
E/dalvikvm-heap(10845): Out of memory on a 33550500-byte allocation.
I/dalvikvm(10845): "pool-3-thread-1" prio=5 tid=27 RUNNABLE
I/dalvikvm(10845):   | group="main" sCount=0 dsCount=0 obj=0x42e8e1c8 self=0x7a90c0e0
I/dalvikvm(10845):   | sysTid=12717 nice=0 sched=0/0 cgrp=apps handle=2056308024
I/dalvikvm(10845):   | state=R schedstat=( 347603340 78194787 397 ) utm=21 stm=13 core=3
I/dalvikvm(10845):   at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:~91)
I/dalvikvm(10845):   at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
I/dalvikvm(10845):   at com.android.okhttp.internal.http.RetryableOutputStream.write(RetryableOutputStream.java:64)
I/dalvikvm(10845):   at net.gotev.uploadservice.a.a.b.a(HurlStackConnection.java:75)
I/dalvikvm(10845):   at net.gotev.uploadservice.f.a(HttpUploadTask.java:205)
I/dalvikvm(10845):   at net.gotev.uploadservice.m.c(MultipartUploadTask.java:128)
I/dalvikvm(10845):   at net.gotev.uploadservice.m.a(MultipartUploadTask.java:61)
I/dalvikvm(10845):   at net.gotev.uploadservice.f.a(HttpUploadTask.java:149)
I/dalvikvm(10845):   at net.gotev.uploadservice.f.run(HttpUploadTask.java:100)
I/dalvikvm(10845):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
I/dalvikvm(10845):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
I/dalvikvm(10845):   at java.lang.Thread.run(Thread.java:841)
```

**Comment by gotev** [comment]
1. Can you sistematically replicate this behaviour every time with the same file?
2. Try to switch to `OkHttp` stack without changing anything else and tell me if you have the same behaviour

**Comment by gotev** [comment]
@quantum0813 I think the problem is exactly the same reported [here](https://code.google.com/p/android/issues/detail?id=64348). It's a bug in the old OkHttp implementation used by Android 4.4, which has been fixed, so try to switch the http stack as I've described and let me know. If you target multiple android versions, then I definitely advise you to do that, to have a consistent networking behaviour.

**Comment by quantum0813** [comment]
Thanks for your quick reply. I have updated my app to use the OkHttp stack implementation. I'll do some more testing, and report back.

**Comment by gotev** [comment]
@quantum0813 are your tests successful?

**Comment by gotev** [comment]
Closing due to lack of feedback. Made some tests with the proposed solution, and the problem doesn't occur
