### ISSUE TITLE
FTP upload

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#116]
With the new extensions made in #112 it's now possible to implement also non-HTTP upload protocols. Implement FTP upload [RFC959](https://tools.ietf.org/html/rfc959) (by using [Apache Commons Net FTP](https://commons.apache.org/proper/commons-net/dependency-info.html) library) as a plug-in distributed as a separate maven artifact, so a user could make also FTP uploads by adding something like the following into its Gradle dependencies:
```java
compile 'net.gotev:uploadservice-ftp:3.0'
```
and then create an upload request with a code like this:
```java
public void uploadFTP(final Context context) {
    try {
        String uploadId =
          new FTPUploadRequest(context, "ftp.company.com", 21)
            .setUsernameAndPassword("username", "password")
            .addFileToUpload("/absolute/path/to/your/file", "/remote/path/")
            .setNotificationConfig(new UploadNotificationConfig())
            .useCompressedFileTransferMode(true)
            .setMaxRetries(2)
            .setAutoDeleteFilesAfterSuccessfulUpload(true)
            .startUpload();
    } catch (Exception exc) {
        Log.e("AndroidUploadService", exc.getMessage(), exc);
    }
}
```

Android devices may have problems supporting FTP active mode, so implement only passive mode.

Since FTP keeps successfully uploaded files even if the connection drops, if I have 10 files to upload and I have successfully uploaded the first 5 and the connection drops while I'm uploading the 6th file, the upload should resume from the beginning of the 6th file. Check also if Apache Commons Net FTP supports resuming of partially uploaded file.

**Comment by moraisholanda** [comment]
I can not download upload-service-ftp to compile 'net.gotev:uploadservice-ftp:2.2'

**Comment by gotev** [comment]
@moraisholanda It's not been released yet 😀 I'll release it together with 3.0 release when it's ready

**Comment by moraisholanda** [comment]
@gotev  I understand, I would love to be able to use, including setting was at that time the server for testing. Do you have any prediction?

**Comment by gotev** [comment]
@moraisholanda hopefully before the end of may, as I'm really busy in this period. I'll notify you once 3.0 is released.

**Comment by moraisholanda** [comment]
thank you, I'll wait.

**Comment by moraisholanda** [comment]
Hello, all right, I'm not able to use the UploadServiceBroadcastReceiver in a service. I'm using as instructed:
If you use it in a {@link android.app.Service}, you have to
      * Call this method inside {@link android.app.Service # onCreate ()}, after {@code super.onCreate ();}.
  @Override
     public void onCreate () {
         super.onCreate ();
         uploadReceiver.register (this);
     }

**Comment by gotev** [comment]
@moraisholanda OT here, open a new issue instead
