### ISSUE TITLE
Keeping UploadServiceBroadcastReceiver alive

### ISSUE THREAD

**Issue by dht** [gotev/android-upload-service#120]
I followed the docs and created an UploadServiceBroadcastReceiver to wait for an onCompleted call. I registered the receiver in "onResume" and unregistered in "onPause".

This means that if the user leaves the activity I stop receiving the broadcast. As this plugin is perfect for long upload processes I would love to have an example of how to keep receiving progress calls until the upload finishes. 

Couldn't find such an example in the docs or examples. Perhaps a service?

**Comment by gotev** [comment]
Actually, how to achieve this is already explained in the [wiki](https://github.com/gotev/android-upload-service/wiki/Monitoring%20upload%20status). You have to create a subclass of `UploadServiceBrodcastReceiver`, add your business logic in it and then register it in your manifest. I've added some more explanations to make it clear that that's the way to go if you want to listen for events outside your activities and services.

If you want to listen for events in one of your services, you can do that, too, and the docs linked by the wiki page already specify exactly where you should register and unregister the listener.

**Comment by dht** [comment]
Thank you! works like a charm. Probably missed it before.
