### ISSUE TITLE
Passing raw data along side a BinaryUploadRequest

### ISSUE THREAD

**Issue by dht** [gotev/android-upload-service#121]
Working with parse.com REST API I am looking for a way to pass a data parameter with a BinaryUploadRequest. Is it possible?

From Parse.com docs (https://parse.com/docs/rest/guide#files):

curl -X POST \
  -H "X-Parse-Application-Id: wEtdPD7LQAVOpy13OvySdZKt8lAtIqjaNYwEV0TJ" \
  -H "X-Parse-REST-API-Key: vXEH8cstdpRMroEQCb7vZCH0nflpW1XW6Lb7b0yv" \
  -H "Content-Type: application/json" \
  -d '{
        "name": "Andrew",
        "picture": {
          "name": "...profile.png",
          "__type": "File"
        }
      }' \
  https://api.parse.com/1/classes/PlayerProfile

**Comment by gotev** [comment]
Of course. What you need to do is to save the content of the binary upload inside a file. In your case:
```java
{
    "name": "Andrew",
    "picture": {
        "name": "...profile.png",
        "__type": "File"
    }
}
```
and then add it to the binary upload request, together with the three headers.

**Comment by dht** [comment]
Thank you, you've pointed me to the right direction. I appriciate your kind attention.
