### ISSUE TITLE
OkHttp interceptors are not supported when using OkHttp Stack

### ISSUE THREAD

**Issue by emanzanoaxa** [gotev/android-upload-service#122]
I was trying to upload an image to a protected service that requires an autorization header but it's failing.
The headers are set on a OkHttp interceptor, also I tried to add an OkHttp logging interceptor and is not logging anything. 
Is the library overwritting the OkHttp interceptors?

**Comment by gotev** [comment]
The library does not overwrite OkHttp interceptors. Post your code. Also enable library logging as described in the wiki.

**Comment by gotev** [comment]
@emanzanoaxa have you solved your issue?

**Comment by emanzanoaxa** [comment]
I couldn't figure out why the Authorization headers are not being set by the interceptors, but I set the headers manually from the BinaryUploadRequest builder and is working. 
Now I have another problem, I am launching several services to upload up to 10 images in parallel and only the first one is being uploaded correctly, the weird thing is the upload services responds with a 200 response code. It can be a race condition issue?
I've forked your repository to try to add multiple binary uploads in the same service but I don't know if it's possible with the current implementation or it will require a lot of code refactoring.

**Comment by gotev** [comment]
Have you tried performing the parallel uploads by using the provided demo server? Never had such issues. I don't think it's a matter of race condition. Every Upload task is executed in its own thread. You can get an insight on how things works internally by looking at the developer's manual section in the wiki. It refers to the current master branch, but the architecture is the same as 2.1, except that I've introduced base classes which are independent from the protocol used to perform upload, to be able to write also other protocols, like FTP, as plugins, and rely on all the existing automations and features provided by the upload service.

**Comment by gotev** [comment]
I can confirm that with the following code used to set up network interceptors in OkHttp, the headers `myheader` and `mysecondheader` are not set in the requests.
```java
OkHttpClient client = new OkHttpClient.Builder()
        .followRedirects(true)
        .followSslRedirects(true)
        .retryOnConnectionFailure(true)
        .connectTimeout(15, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .addNetworkInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request request = chain.request();
                Request newRequest;

                newRequest = request.newBuilder()
                            .addHeader("myheader", "myvalue")
                            .addHeader("mysecondheader", "mysecondvalue")
                            .build();
                return chain.proceed(newRequest);
            }
        })
        .cache(null)
        .build();

UploadService.HTTP_STACK = new OkHttpStack(client);
```
I think the reason resides in how `OkHttpStackConnection` is implemented, as it uses the `HttpUrlConnectionImpl` class which wraps the `OkHttpClient` and I don't know how it handles the interceptors chains at the moment. Setting the headers in the `BinaryUploadRequest` and `MultipartUploadRequest` surely works.

**Comment by hendrawd** [comment]
Actually it is not only happens on OkHttpStack only. When i use the default stack(HurlStack), the problem still exist. Now i can't authenticate to server using HTTP header

**Comment by gotev** [comment]
@hendrawd have you already checked [this](https://github.com/gotev/android-upload-service/wiki/Recipes#http-basic-auth-) and [this](https://github.com/gotev/android-upload-service/wiki/Recipes#cookies-) ?

**Comment by hendrawd** [comment]
Actually my approach for auth is not using username and password, but using auth token, so i don't think .setBasicAuth("username", "password"); will work.

I tried
CookieManager cookieManager = new CookieManager();
CookieHandler.setDefault(cookieManager);
but that didn't worked too. I don't know if it is because of i used volley with OkHttpStack3.

Usually i just set the cookie directly to the header for authentication.

**Comment by gotev** [comment]
@hendrawd Correct me if I'm wrong.
1. You have setup Volley + OkHttp3
2. You setup a persistent cookie store on HttpUrlConnection
3. You use HurlStack with Upload Service
3. You perform an authentication request to your server with Volley
4. You try to upload a file with an Upload Service request

**Comment by hendrawd** [comment]
1. yes
2. i set the cookie for authentication on getHeaders() method of volley's request
3. yes
4. yes
5. yes

**Comment by gotev** [comment]
@hendrawd so, with your setup, Upload Service is using HttpUrlConnection stack. Cookies are handled internally by Volley + OkHttp3 when you perform authentication requests. No cookies are stored in the HttpUrlConnection's Cookie Manager, which is used by Upload Service, so the behaviour you are observing at the moment is not a bug, but a consequence of how everything is setup.

I can think of two options here:

1. After that you setup Volley + OkHttp3, pass the same `OkHttpClient` instance also to the Upload Service (be sure to add the needed gradle dependency that you get from the Setup wiki page):
  ```java
  UploadService.HTTP_STACK = new OkHttpStack(client);
  ```

2. Leaving your setup as is now, find a way in which you could get cookies from Volley + OkHttp3, and set them in the Upload Service requests

**Comment by hendrawd** [comment]
Yes i though of that too, thank you for your response @gotev, i will let you know about the update :)

**Comment by gotev** [comment]
@emanzanoaxa Investigated further and found the answer. As stated [here](https://github.com/square/okhttp/wiki/Interceptors#availability) interceptors do not work with `OkUrlFactory`. By looking at [how it works internally](https://github.com/square/okhttp/blob/2b1f9a20bac5d99acf5a8be36754e5a1dadaf448/okhttp-urlconnection/src/main/java/okhttp3/OkUrlFactory.java#L72) I discovered that it instantiates the `HttpURLConnectionImpl` the same way as the [Upload Service implementation currently does](https://github.com/gotev/android-upload-service/blob/9dfbee62bb9f550d5508db6d7767144516abd075/uploadservice-okhttp/src/main/java/net/gotev/uploadservice/okhttp/OkHttpStackConnection.java#L33), so interceptors are not supported adn that's why you could not set headers from there. I think that a total rewrite of the `uploadservice-okhttp` module will be needed, as Square has deprecated `HttpURLConnectionImpl` as stated [here](http://square.github.io/okhttp/3.x/okhttp-urlconnection/okhttp3/OkUrlFactory.html).

**Comment by mandrachek** [comment]
Such a shame, because otherwise this looks like a great library.

Not having interceptors means stetho doesn't work.  And if you're doing something more complicated like bearer token authentication, it's pretty much a non-starter.

**Comment by gotev** [comment]
@mandrachek You're welcome to help developing ok-http module to support also interceptors. The library was originally designed to work with HttpUrlConnection. OkHttp was added later with the HttpUrlConnection implementation. To support all the OkHttp features, it's needed to totally rewire the networking layer to work with the OkHttp's request/response API.

**Comment by rlazar** [comment]
+1 interceptors are needed.

**Comment by gotev** [comment]
After https://github.com/gotev/android-upload-service/commit/290f4f89168b7d29005209ceda6f240bc445cf6a and https://github.com/gotev/android-upload-service/commit/f9358f1f1e669cc88816cd7287d230e8e25bc475, this example works: https://github.com/gotev/android-upload-service/issues/122#issuecomment-216577406

so request interceptors are now supported
