### ISSUE TITLE
Implement callbacks to listen for upload requests status, instead of using the broadcast receiver

### ISSUE THREAD

**Issue by pawankumar01** [gotev/android-upload-service#124]

**Comment by gotev** [comment]
This has already been asked and responded in #104 (also reported in the wiki) if you want a quick way to achieve the same behaviour as with callbacks. 

Some design decisions has to be made to have callbacks without the broadcaster. Every Upload task runs in a separate background thread (you can see the internal architecture in the developer's manual page in the wiki), which means that if I add a listener to it, events will be dispatched in the same thread, so you have to make sure you are in your UI thread if you want to update your UI and if you do something blocking in the listener, the upload will be also affected. As it is now, event handling happens in the UI thread and the upload in a background thread.

I'm open to new ideas and software design, so if you have something to propose, you're welcome!

**Comment by pawankumar01** [comment]
In my scenario, I need to make other server call on completion of request which I need to unnecessary put the code in activity and initiate the request again from activity. A  It would be much better If we can initiate request from callback without touching activity.

How about taking the callback(onSuccess and onError) as a parameter and if it's not null, trigger that callback as well as broadcaster. 
This way we will be able to use both as required.

**Comment by gotev** [comment]
So, your idea will be to have something as:
```java
new MultipartUploadRequest(context, "http://server.com")
    .addFileToUpload("/path/to/file", "param-name")
    .setDelegate(delegate)
    .start();
```

Where `delegate` is a class which implements the same methods exposed by the actual `UploadServiceBroadcastReceiver`.

As you can see from the architecture in the developer's manual on the wiki, the `UploadRequest` classes generates an `Intent` which is sent to the service. The intent gets processed by the `UploadService` which instantiates a new task in a new thread. the challenge here is how to pass the delegate instance to the thread which actually performs the upload. As far as I know, you can't serialize it in an Intent. The only way I could think of doing that is to have a separate class in which to set the delegate instance for that particular uploadID, and to get the instance from the thread, but personally I don't like that approach. Do you have better ideas to achieve that?

**Comment by gotev** [comment]
@pawankumar01 just to clarify, you don't need to create an extra activity just to handle the broadcast receiver events in order to perform the network calls you need, as you can use it also inside a Service or you can create a subclass of `UploadServiceBroadcastReceiver` and register it in your manifest, so everything will happen in the background even if no activities of your app are running. You can find examples in the monitoring page of the wiki. Tell me if the provided examples or explanations are not clear enough.

**Comment by pawankumar01** [comment]
@gotev correct I was thinking something like setDelegate(). Your provided examples are clear :) 
The problem with single entry Receiver would be that for every upload we need to keep track from where this upload request was initiated so that give handle back. Callback will solve that implicitly.

As you stated one option can be create a separate class and have static map in that and call as required or may be having BroadcasterReceiver registered within library itself, which will calls delegate method.

The other could be if we set the callback Map in UploadService 
(http://stackoverflow.com/questions/14710765/passing-parameter-from-an-activity-to-a-thread-in-a-service) and update the service  and service calls relative delegate method. 

Not sure, if they are the best solution.

**Comment by gotev** [comment]
Having a `BroadcastReceiver` inside the library in which to register the object instances which implements the delegate methods is a good idea, but then there's another challenge: how to register the broadcast receiver in the manifest of the upload service, considering that the user can change the broadcast action string?
```xml
<receiver android:name="MyReceiver">
    <intent-filter>
        <action android:name="com.yourcompany.yourapp.uploadservice.broadcast.status" />
    </intent-filter>
</receiver>
```
`com.yourcompany.yourapp` is chosen by the user when he performs the initial setup. This is needed to be able to have multiple apps on the same device which uses the Upload Service simultaneously. This leaves us with the static Map option only. I have to think of a way in which I could provide an implementation of `setDelegate` method in the base `UploadTask` class, so that all the upload tasks could have the callback option available out of the box and without exposing publicly the static Map. Another thing to think about is how to properly remove delegate instances when the upload task is completed, in order to dispose them, otherwise we would have a huge memory leak. I'm open to suggestions.

**Comment by gotev** [comment]
@pawankumar01 made an implementation of what we've discussed. You can try that in a project too. Follow this guide to add the dependency for the snapshot artifacts in your Gradle build file: https://jitpack.io/#gotev/android-upload-service/d84ca6e2a6

Then, you can try it out like this:
```java
new MultipartUploadRequest(context, "http://server.com")
    .addFileToUpload("/path/to/file", "param-name")
    .setDelegate(new UploadStatusDelegate() {
        @Override
        public void onProgress(UploadInfo uploadInfo) {

        }

        @Override
        public void onError(UploadInfo uploadInfo, Exception exception) {

        }

        @Override
        public void onCompleted(UploadInfo uploadInfo, ServerResponse serverResponse) {

        }

        @Override
        public void onCancelled(UploadInfo uploadInfo) {

        }
    })
    .startUpload();
```
Let me know if it works for you or if you have some issues.

**Comment by pawankumar01** [comment]
@gotev Great! thanks for such a quick implementation. Its almost working. However I observed that when the file is successfully uploaded with http response code 200 then onCompleted is not getting called. 
For other http response codes onCompleted is getting called and onError also looks to be working fine.

**Comment by gotev** [comment]
@pawankumar01 Hmm, that's strange. The `onCompleted` method always gets called, as you can see [here](https://github.com/gotev/android-upload-service/blob/628eb35e5a5673239e84d2f4f1649d19428868b8/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L246). In my tests I've placed the following code into the `onCompleted` method
```java
Log.i(TAG, String.format(Locale.getDefault(),
                "ID %1$s: completed in %2$ds at %3$.2f Kbit/s. Response code: %4$d, body:[%5$s]",
                uploadInfo.getUploadId(), uploadInfo.getElapsedTime() / 1000,
                uploadInfo.getUploadRate(), serverResponse.getHttpCode(),
                serverResponse.getBodyAsString()));
```
and when the upload is successful by using the [demo server](https://github.com/gotev/android-upload-service/wiki/Testing%20and%20working%20examples), in the LogCat I can see correctly:
```
ID 87aa531f-986d-46ee-a19b-50e87eed6d90: completed in 22s at 2493,09 Kbit/s. Response code: 200, body:[Upload Ok!]
```
Could you please post your code here?

**Comment by pawankumar01** [comment]
I am using the following code and uploading the file to Amazon S3.
````
String uploadId =
                    new MultipartUploadRequest(App.context, url2)
                            .addFileToUpload(file.getAbsolutePath(), "ql")
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .setMethod("PUT")
                            .setDelegate(new UploadStatusDelegate() {
                                @Override
                                public void onProgress(UploadInfo uploadInfo) {

                                }

                                @Override
                                public void onError(UploadInfo uploadInfo, Exception exception) {
                                    Console.log("Upload failed");

                                }

                                @Override
                                public void onCompleted(UploadInfo uploadInfo, ServerResponse serverResponse) {
                                    System.out.print("successful" + serverResponse);
                                    if (serverResponse.getHttpCode() == 200)
                                        RestClient.notifyServerFileUploaded(file, obj);
                                    else {
                                        Console.log("Something went wrong" + serverResponse.getBodyAsString());
                                    }

                                }

                                @Override
                                public void onCancelled(UploadInfo uploadInfo) {

                                }
                            })
                            .startUpload();

        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }
````

**Comment by gotev** [comment]
Never used `System.out.print` on Android, so I don't know if you can see the log message in the LogCat. Try using ,`Log.i` instead to log messages for this test and tell me which messages you see during the Upload. I'm Pretty sure that you will see the successful message. Also, from where are you launching the Upload.. an Activity, a Service, a static class? Is your app running or is in the background?

**Comment by pawankumar01** [comment]
Now I am not able to reproduce the issue.  Now its printed properly with both `Log.i` and `System.out.print`. 
I am launching the Upload from Fragment and app is running in the foreground. 
Will let you know if I see the issue again. Thanks a lot!

**Comment by gotev** [comment]
You're welcome! I consider this issue resolved. If some errors arises, create a new issue and be as detailed as possible in describing how to replicate the error.

**Comment by herry-trium** [comment]
Hello @gotev 
I am trying this solution since very long. But when i clear my app from from recent apps/memory, i loose contact with my service and delegate methods as well. Please help.

**Comment by gotev** [comment]
@herry-trium there's no solution to that, as it's how Android is designed. Look #100 for all the details.

**Comment by herry-trium** [comment]
Okay, thanks!
