### ISSUE TITLE
POST request using BinaryUploadRequest

### ISSUE THREAD

**Issue by gaurnagchauhan** [gotev/android-upload-service#127]
Can you help me to know that how to set HTTP POST BODY in BinaryUploadRequest.

```java
String bodyContent = String.format("{\"title\": \"%s\",\"name\":\"%s\"}", filename, filename);
RequestBody body = RequestBody.create(MediaType.parse("application/json"), bodyContent);

final OkHttpClient client = new OkHttpClient();

Request request = new Request.Builder()
        .url(serverUrlString)
        .addHeader("Authorization", String.format("Bearer %s", accessToken))
        .addHeader("Content-Type", "application/json")
        .addHeader("X-Upload-Content-Type", "image/jpg")
        .addHeader("X-Upload-Content-Length", String.valueOf(fileLength))
        .post(body).build();
```

I use this two dependencies 
```
compile 'net.gotev:uploadservice:2.1'
compile 'net.gotev:uploadservice-okhttp:2.1'
```
My code is working with okHttp call

**Comment by gotev** [comment]
Stack trace? Log from library? Log from server?

**Comment by gaurnagchauhan** [comment]
i use this to dependencies 
    compile 'net.gotev:uploadservice:2.1'
    compile 'net.gotev:uploadservice-okhttp:2.1'

how to add body in BinaryUploadRequest?

**Comment by gotev** [comment]
It's explained in the Recipes page on the wiki. What is the issue?

**Comment by gaurnagchauhan** [comment]
Issue is when i upload file in google dive drive. i give my all credentials but it gives me 400 parseError.

**Comment by gotev** [comment]
Post the code you use to make the request. If the server responds like that, you've missed something. Have you checked Google docs regarding how the expected request should be made? Searched for "Google drive 400 parse error" on Google and found this: http://stackoverflow.com/questions/33917281/parse-error-while-making-watch-requests-to-google-drive

**Comment by gaurnagchauhan** [comment]
my code is working with okHttp call

**Comment by gotev** [comment]
If you think it's a bug in the library, post the code you used and be as detailed as possible in explaining how to replicate your issue. Without the code I really can't do anything to help you.

**Comment by gaurnagchauhan** [comment]
can you help me to know that how to set HTTP POST BODY in BinaryUploadRequest.

String bodyContent = String.format("{\"title\": \"%s\",\"name\":\"%s\"}", filename, filename);
                            RequestBody **## body** = RequestBody.create(MediaType.parse("application/json"), bodyContent);

                            final OkHttpClient client = new OkHttpClient();

                            Request request = new Request.Builder()
                                    .url(serverUrlString)
                                    .addHeader("Authorization", String.format("Bearer %s", accessToken))
                                    .addHeader("Content-Type", "application/json")
                                    .addHeader("X-Upload-Content-Type", "image/jpg")
                                    .addHeader("X-Upload-Content-Length", String.valueOf(fileLength))
                                    .post(***## *body****).build();

**Comment by gotev** [comment]
From what I see you need a basic POST request. I don't see any file in your request, but a plain JSON string which you send to the server. Android Upload Service purpose is for file uploads, not simple POST requests, for which I advise you to keep using the excellent `OkHttp`, however, I'll tell you how to achieve the same result.

Place this somewhere in your code:
```java
public static String writeToFileAndGetPath(Context context, String data) throws IOException {
    OutputStreamWriter outputStreamWriter = null;

    try {
        File outputFile = File.createTempFile(UUID.randomUUID().toString(),
                                              "json", context.getCacheDir());
        outputStreamWriter = new OutputStreamWriter(new FileOutputStream(outputFile));
        outputStreamWriter.write(data);

        return outputFile.getAbsolutePath();

    } finally {
        if (outputStreamWriter != null) {
            try {
                outputStreamWriter.close();
            } catch (Exception ignored) { }
        }
    }
}
```

And then:
```java
private String postData(Context context, String accessToken, String filename) throws IOException {
    String json = String.format("{\"title\": \"%s\",\"name\":\"%s\"}", filename, filename);
    String filePath = writeToFileAndGetPath(context, json);
    long fileLength = new File(filePath).length();

    return new BinaryUploadRequest(context, "http://server.com")
            .addHeader("Authorization", String.format("Bearer %s", accessToken))
            .addHeader("Content-Type", "application/json")
            .addHeader("X-Upload-Content-Type", "image/jpg")
            .addHeader("X-Upload-Content-Length", String.valueOf(fileLength))
            .setFileToUpload(filePath)
            .setAutoDeleteFilesAfterSuccessfulUpload(true)
            .setUsesFixedLengthStreamingMode(true)
            .setMaxRetries(2)
            .startUpload();
}
```
I've written this on-the-go, so some adjustments may be needed.

**Comment by gaurnagchauhan** [comment]
thanks sir. I will check this code and inform you it is working or not.

**Comment by gotev** [comment]
Just out of curiosity I've checked which APIs do Google Drive expose. You can use the `MultipartUploadRequest` to upload your files: https://developers.google.com/drive/v3/web/manage-uploads#multipart and the example from the recipes covers all you need to perform that successfully

**Comment by gotev** [comment]
@gaurnagchauhan are you trying to achieve the resumable upload type? https://developers.google.com/drive/v3/web/manage-uploads

**Comment by gaurnagchauhan** [comment]
now i successfully upload files in google drive. But now i facing new issue to upload files in oneDrive. Its give me 405 method not allowed.

**Comment by gotev** [comment]
Check how you build the request and [this](https://msdn.microsoft.com/en-us/library/office/dn631844.aspx#Returned_status_codes) table. If you have an evidence of a bug in the library, create a new issue with the code you used and the steps to reproduce, so I can address it. I'm closing this issue, as the original question has been answered.

**Comment by SilvaEngComp** [comment]
Hi! I'm trying upload a simple user resister with image user. This is my cod:

try{

            String upload = UUID.randomUUID().toString();
            new MultipartUploadRequest(context,upload,wd.getUrl())
//                    .addFileToUpload(wd.getImgUrl(), "foto")
                    .addParameter("nome", wd.getNome())
                    .addParameter("email", wd.getEmail())
                    .addParameter("senha", wd.getSenha())
                    .addParameter("data", wd.getData())
                    .addParameter("cpf", wd.getCpf())
                    .addParameter("op", wd.getOperation())
                    .addParameter("token", wd.getToken())
                    .setMethod("POST")
                    .setUtf8Charset()
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload();
        }catch(Exception e){

        }

I'm inicializating:

import net.gotev.uploadservice.BuildConfig;
import net.gotev.uploadservice.UploadService;

public class Initializer extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        // setup the broadcast action namespace string which will
        // be used to notify upload status.
        // Gradle automatically generates proper variable as below.
        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
        // Or, you can define it manually.
//        UploadService.NAMESPACE = "com.yourcompany.yourapp";
    }
}

So! My phone show upload is done, but my php server not receive that. Someone can to hep me?
