### ISSUE TITLE
Support for multipart/related requests

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#128]
Popular Google Drive APIs allow upload with `multipart/related` requests (RFC2387): https://developers.google.com/drive/v3/web/manage-uploads#multipart

Currently Upload Service supports only `multipart/form-data` (RFC2388). Adding this to the library will allow more people to make use of it without implementing custom upload request classes.

**Comment by vikramviswanathan** [comment]
Hello Alex,

Need help on sending multipart data in the form of body in the api I'm using. Could you please post a sample on how to send data in MultipartEntity format in MultipartUploadRequest class?

**Comment by gotev** [comment]
@vikramviswanathan OT here. You can check the Recipes page in the wiki or look at #127

**Comment by gotev** [comment]
Closing this due to no interest about this protocol, which is not intensively used.
