### ISSUE TITLE
404 Error while uploading

### ISSUE THREAD

**Issue by moosabaloch** [gotev/android-upload-service#131]
I have implemented this Upload library approx 20 days ago then it was working fine but today when i have updated my android studio and support libraries it gives me an error of 404 not found 
i have tested my API's through POSTMAN its working fine..
and the code i am using is so simple 
```java
new MultipartUploadRequest(context,URLs.UPLOADING_USER_IMAGE_URL)
    .addFileToUpload(pictureAbsolutePath, "image")
    //.setNotificationConfig(new UploadNotificationConfig())
    .setMaxRetries(3)
    .startUpload();
```
My support library version is:
```java
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:support-v4:23.4.0'
compile 'com.android.support:recyclerview-v7:23.4.0'
compile 'com.android.support:design:23.4.0'
```
and below the application logs when i am uploading images...
```java
I/moosa: UL---> Starting service with namespace: com.alisons.trippr, upload pool size: 2, 1s idle thread keep alive time. Foreground execution is enabled 
D/moosa: UL---> Successfully created new task with class: net.gotev.uploadservice.MultipartUploadTask 
D/moosa: UL---> Starting upload task with ID f62ea481-fff2-42e0-8dbc-d629a95f372d 
D/moosa: UL---> creating new connection 
D/moosa: UL---> Broadcasting upload progress for f62ea481-fff2-42e0-8dbc-d629a95f372d Uploaded bytes: 147 out of 161855 
D/moosa: The progress of the upload with ID f62ea481-fff2-42e0-8dbc-d629a95f372d is: 0 
D/moosa: The progress of the upload with ID f62ea481-fff2-42e0-8dbc-d629a95f372d is: 0 
D/moosa: UL---> Server responded with HTTP 404 to upload with ID: f62ea481-fff2-42e0-8dbc-d629a95f372d 
D/moosa: UL---> Broadcasting upload completed for f62ea481-fff2-42e0-8dbc-d629a95f372d 
D/moosa: UL---> All tasks finished. UploadService is about to shutdown... 
D/moosa: UL---> closing connection 
D/moosa: Upload with ID f62ea481-fff2-42e0-8dbc-d629a95f372d has been completed with HTTP 404.`
```

**Comment by gotev** [comment]
Try to start the the node.js demo server provided [in the examples](https://github.com/gotev/android-upload-service/wiki/Testing%20and%20working%20examples) on your computer, try to run the same upload and post the output that you will get, so if it's a bug I can replicate it, too.

**Comment by gotev** [comment]
@moosabaloch have you solved your issue?

**Comment by moosabaloch** [comment]
Wait lemme try
i have to install npm then...

**Comment by moosabaloch** [comment]
Thanks Bro its working....

**Comment by moosabaloch** [comment]
i am checking my PHP server...

**Comment by gotev** [comment]
@moosabaloch you're welcome!

**Comment by moosabaloch** [comment]
@gotev Can you please guide me what the problem is  occurring and where to debug...?
i have tested my PHP server its working perfect from POSTMAN but not from android app.
and the android app is working perfectly with Node.js server.

**Comment by gotev** [comment]
The best you can do in this case is to dump network traffic with tcpdump on your server when you perform a request with Postman and then do another dump when you perform the request from Android. After this, open the dumps with wireshark and see how HTTP requests are made. You should be able to spot the difference between the two and I think it may have to do with headers. For example, if you are using OkHttp with interceptors to set the headers, that is not going to work, as described in #122
