### ISSUE TITLE
cant upload binary file

### ISSUE THREAD

**Issue by omryros** [gotev/android-upload-service#132]
hi first of all thanks for this library,
I am trying to upload a binary file to a server 
this is my code :
```java
Log.e("FILE NAME",file.getName() +" " + file.getAbsolutePath());
String uploadId = new BinaryUploadRequest(context, serverURL)
        .setFileToUpload(file.getAbsolutePath())
        .setNotificationConfig(new UploadNotificationConfig())
        .setMaxRetries(2)
        .startUpload();
```
and when i run this i always either get a failed upload or it says it uploaded successfully but the file on the server appears empty, any tips on how to handle this?

**Comment by gotev** [comment]
I advise you to check you server-side code and to perform the checks suggested in the [Troubleshooting](https://github.com/gotev/android-upload-service/wiki/Troubleshooting) wiki page.

**Comment by omryros** [comment]
the server is on production and is active at all times so he works for sure, any other ideas maybe? i would be so damn grateful :/ i cant find any library that can send this request for some reason

**Comment by gotev** [comment]
Binary upload works with the example test server provided in the examples. You should try to send your requests to it, so you can see if there are some missing headers that needs to be set. There's nothing better than performing a network traffic dump in this case. You can find hints on the troubleshooting page. If you have a working case and and a non-working case, there is something different between the two requests for sure. Find that difference, and bingo! If you use `OkHttp` for example, you have to know that setting headers in the interceptors is not going to work, as described in #122

**Comment by omryros** [comment]
the only difference seems to be that one is binary and the other is not and that the one which isnt binary has a name field for the file

**Comment by omryros** [comment]
String uploadId =
                        new MultipartUploadRequest(context, serverURL)
                                .addFileToUpload(file.getAbsolutePath(),"name")
                                .setNotificationConfig(new UploadNotificationConfig())
                                .setMaxRetries(2)
                                .startUpload();



      String uploadId =
                            new BinaryUploadRequest(context, serverURL)
                            .setFileToUpload(file.getAbsolutePath())
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .startUpload();

**Comment by gotev** [comment]
So, you are sending both multipart and binary upload requests to the same server endpoint, right?

**Comment by omryros** [comment]
the multipart is being recieved as a text file, when i checked Postman app and sent with binary file it worked, but for some reason i cant get it to work from my app

**Comment by gotev** [comment]
@omryros as I told you before, do a network traffic dump on your server or on your computer and your device and check which are the differences between the two. To me there's no evidence of a bug in the library, but some setting in how the request is made. Also, a screenshot of your POSTMAN request setup would be helfpul, otherwise I don't have the needed details to eventually replicate your condition.

**Comment by gotev** [comment]
Closing this due to insufficient details to replicate. By tests made, both binary and multipart uploads works as expected.
