### ISSUE TITLE
Add placeholder for the number of successfully uploaded files

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#133]
Instead of individual upload notification, it will be better if we can add new feature that show number on notification when we upload several files to the server.
So the notification is only 1 for progress, and 1 for the result.
Example:
(Notification)Uploading 6/9 files
(Notification)Upload success 4/9 files, fail 1/9 file

**Comment by gotev** [comment]
If you add multiple files to a single multipart request, you can already have that behaviour. If you start multiple concurrent uploads, you will see multiple notifications, in which case a [summary notification](https://developer.android.com/training/wearables/notifications/stacks.html) has to be implemented.

**Comment by hendrawd** [comment]
Oh i will try it with one request. Looks like i missed this feature, thanks alot

**Comment by hendrawd** [comment]
@gotev by add multiple files here, did you mean we must specify each file's parameter name here? 
Like this:
multipartUploadRequest.addFileToUpload(path1, "file1")
.addFileToUpload(path2, "file2")
.addFileToUpload(path3, "file3");

Because the file count to send to server is not fix, so i think it's not possible to use that style.
Currently server only get 1 parameter name, that is "file".

**Comment by gotev** [comment]
You have two options:
* pass all the files with the same parameter name
* pass every file with a different parameter name

On your server, in the first case you have to handle an array of files coming in with the same parameter name, in the latter you will have different parameter name for every file.

**Comment by hendrawd** [comment]
I tried with first case, but it doesn't give me that behaviour. Behaviour here i mean it will show the number of files instead of just uploading info.
Here is my code to upload to the server. And server is successfully accepted the files.
```
UploadNotificationConfig uploadNotificationConfig = new UploadNotificationConfig()
.setClickIntent(someIntent)
.setClearOnAction(true)
.setRingToneEnabled(false);

final MultipartUploadRequest multipartUploadRequest = new MultipartUploadRequest(this, url)
.addFileToUpload("some path1", "upload[]")
.addFileToUpload("some path2", "upload[]")
.setNotificationConfig(uploadNotificationConfig)
.setMaxRetries(2);
```

**Comment by gotev** [comment]
Currently only the upload progress is grouped and you can't display the number of files

**Comment by hendrawd** [comment]
Oh i see, looks like i should implement the number manually. Do you think you can add this feature for future update?

**Comment by gotev** [comment]
3.0 has support for placeholders in notification strings, so this could be added

**Comment by kinsleykajiva** [comment]
when is 3.0 coming...

**Comment by gotev** [comment]
As soon as I can. I'm really busy in this period and this is a project I do in my spare time...

**Comment by hendrawd** [comment]
how to use this placeholder?

**Comment by gotev** [comment]
Refer to Placeholders class for reference of the supported placeholders. You can use them in UploadNotificationConfig strings
