### ISSUE TITLE
When connection is poor or not stable upload fail and onError not called

### ISSUE THREAD

**Issue by vervatovskis** [gotev/android-upload-service#136]
Hi,

When I interupt wifi or 3g/4g onError is called and I can handle this.
But when connection is poor or not stable upload fail and onError not called, in that case I cannot re-queue the upload.

**Comment by gotev** [comment]
Enable debug log and try to replicate the issue. When you are able to replicate it, post only the library debug log.

**Comment by vervatovskis** [comment]
Seems to be complicated, to reproduce it, I have to move far from the router to reduce the signal. I cannot reproduce it in front of my pc with a plugged phone.

**Comment by vervatovskis** [comment]
`public class PhotoUploadStatusReceiver extends UploadServiceBroadcastReceiver {

    private static final String TAG = "PhotoUploadStatus";
    private Context mContext;

    @Override
    public void onReceive(Context context, Intent intent) {
        if (mContext == null){
            mContext = context;
        }
        super.onReceive(context, intent);
    }


    @Override
    public void onError(String uploadId, Exception exception) {

        updateUploadStatus(uploadId);
    }

    @Override
    public void onCompleted(String uploadId,
                            int serverResponseCode,
                            byte[] serverResponseBody) {

        clearUploadStatus(uploadId);

    }

    private void clearUploadStatus(String uploadId){

        Intent mServiceIntent = new Intent(mContext, DataService.class);
        mServiceIntent.putExtra(IntentConstant.TASK_ID, IntentConstant.CLEAR_UPLOAD_TASK_ID);
        mServiceIntent.putExtra(IntentConstant.UPLOAD_TASK_ID, uploadId);
        mContext.startService(mServiceIntent);
    }

    private void updateUploadStatus(String uploadId){

        Intent mServiceIntent = new Intent(mContext, DataService.class);
        mServiceIntent.putExtra(IntentConstant.TASK_ID, IntentConstant.UPDATE_UPLOAD_TASK_ID);
        mServiceIntent.putExtra(IntentConstant.UPLOAD_TASK_ID, uploadId);
        mContext.startService(mServiceIntent);

    }
}
`

Here my code.

**Comment by gotev** [comment]
I understand, but in this case the code doesn't help me address the issue, since we are talking about a specific behaviour. You should log persistently on a file or in the cloud, replicate the issue on mobile network and then get the log when you connect the phone to your pc. To log persisttently there are a wide variety of solutions which I'm not going to mention here. You just need to make your own [logger delegate implementation](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-).

**Comment by vervatovskis** [comment]
I created a persistent Log file. The "ERROR" is just a tag.
I tried 5 pictures upload, 3 succeeded and two failed (Same conditions poor/unstable network).

[log4j.txt](https://github.com/gotev/android-upload-service/files/305180/log4j.txt)

**Comment by vervatovskis** [comment]
Well, I confirm that I received all the errors broadcasts :) You can close the ticket please.
