### ISSUE TITLE
Register UploadServiceBroadcastReceiver  when using service not working

### ISSUE THREAD

**Issue by moraisholanda** [gotev/android-upload-service#139]
Hello, all right, I'm not able to use the UploadServiceBroadcastReceiver in a service. I'm using as instructed:
If you use it in a {@link android.app.Service}, you have to
* Call this method inside {@link android.app.Service # onCreate ()}, after {@code super.onCreate ();}.
@Override
public void onCreate () {
super.onCreate ();
uploadReceiver.register (this);
}

**Comment by hendrawd** [comment]
Can you show full code of your service and the method that you used to start your service?

**Comment by oneidc** [comment]
Method for getting server responses after uploading (like json returns)

**Comment by gotev** [comment]
@moraisholanda in my experience this works. Can you give us some feedback about that?

**Comment by hendrawd** [comment]
Yes, i have tested it myself and it works

**Comment by gotev** [comment]
Thank you @hendrawd 
So, since we haven't got any feedback and there isn't any evidence of a bug in the library, I'm closing this.
