### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#140]
ToDo list to release version 3.0

Write docs for:
- [x] upload request callbacks
- [x] how to use placeholders in notification strings
- [x] how to monitor upload requests with the new public API
- [x] how to tune exponential backoff algorithm used to automatically retry uploads by setting `INITIAL_RETRY_WAIT_TIME`, `BACKOFF_MULTIPLIER` and `MAX_RETRY_WAIT_TIME`.
- [x] how to migrate from release 2.1 to 3.0
- [x] FTP module
  - [x] How to create an FTP upload request
  - [x] How to test FTP upload
  - [x] Module JavaDocs

- [x] Update the demo app to support HTTP multipart, binary and FTP uploads

- [x] Release 3.0 artifacts on jCenter and Maven Central
  - [x] uploadservice
  - [x] uploadservice-okhttp
  - [x] uploadservice-ftp

**Comment by hendrawd** [comment]
Yeay! Thank you for the update Alex :)

**Comment by gotev** [comment]
3.0 has been released!
