### ISSUE TITLE
Method for getting server responses after uploading (like json returns)

### ISSUE THREAD

**Issue by oneidc** [gotev/android-upload-service#141]
I develop a print application, and i want to recieve all web urls path of uploaded photos.
Urls web path of my photos is a json response from the server

**Comment by gotev** [comment]
You get that in the Broadcast receiver's onCompleted method. Refer to the wiki.

**Comment by oneidc** [comment]
but the only worry is muti files to upload in one upload notification,

**Comment by gotev** [comment]
@onedic it depends also on your server-side implementation. Dump network traffic (refer to the wiki troubleshooting page) when you perform that request and post it here.
