### ISSUE TITLE
How to include the retrofit parameters inside the upload service 

### ISSUE THREAD

**Issue by saran2somu** [gotev/android-upload-service#143]
Hi , 

  how to upload the images , with retrofit parameters inside in upload service

**Comment by gotev** [comment]
You have to get the full path of the images on the device and then build up the requests as shown in the Recipes page on the wiki. There is no integration with retrofit at the moment.

**Comment by saran2somu** [comment]
Thanks Alex Gotev . I have used addParameter() method for send the data . Thanks, its working good.
