### ISSUE TITLE
add a delay before upload starts

### ISSUE THREAD

**Issue by AngleV** [gotev/android-upload-service#144]
Hi there
is it possible to add a delay before starting the uploading process

e.g

```
 req.startUpload(int delay); //in millis 

```

Due to my app needs that would be awesome feature

**Comment by gotev** [comment]
This is not a feature I'm going to add to the project, however you can easily achieve that by creating an AsyncTask with a sleep before the invocation of the startUpload method.

**Comment by AngleV** [comment]
Yes you're right !!
Thank you
