### ISSUE TITLE
How to get speed of uploading for each request?

### ISSUE THREAD

**Issue by helloyxc** [gotev/android-upload-service#146]
we have a requirement that **gets speed of uploading for each request** and **gets total speed for the request list**. But I do not know how to do it, could you please tell me?

**Comment by gotev** [comment]
You have to wait for 3.0 release (#140) which is planned for this weekend. 
Then, in the `UploadInfo` that you will get in the broadcast listener or delegate, you can get what you need by invoking the `getUploadRate()` method. You can also display it in the notifications by using placeholders (#117).

**Comment by helloyxc** [comment]
I am waiting for the 3.0 release.
