### ISSUE TITLE
Disable parallel uploads

### ISSUE THREAD

**Issue by konalegi** [gotev/android-upload-service#147]
Is there a way to disable parallel uploads?
It's required for me, when i am uploading folder of files with poor internet connection. Currently i am using  workaround, with saving uploads firstly to database (sqlite3), and after successful upload, starting new one.

**Comment by gotev** [comment]
You don't need a workaround for this, as it is already possible to have only one upload taska at a time. Added explanation in the [wiki](https://github.com/gotev/android-upload-service/wiki/Advanced-topics#tune-the-number-of-parallel-uploads)
