### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by vikramviswanathan** [gotev/android-upload-service#148]
Hello gotev,

I'm facing an import issue for UploadStatusDelegate, ServerResponse, UploadInfo in my Android Studio.

I'm using the following versions of support libraries
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'

and 

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'
}

could you please help/guide me to resolve this?
![uploadservice_issue](https://cloud.githubusercontent.com/assets/10057902/16358087/b1b87130-3b26-11e6-8180-3aa842b07ceb.PNG)

**Comment by gotev** [comment]
3.0 is not release yet, so you're using 2.1, and so you can't import those classes

**Comment by vikramviswanathan** [comment]
Yes. I'm using the 2.1 version

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.+'
    compile 'net.gotev:uploadservice:2.1'
    compile 'net.gotev:uploadservice-okhttp:2.1'
}

**Comment by gotev** [comment]
Youbhave to wait for 3.0, which will be released tomorrow.

**Comment by vikramviswanathan** [comment]
Sorry to keep bothering you. What do I need to do if I want to use the 2.1 version?

**Comment by vikramviswanathan** [comment]
Also getting an error on this line 
String uploadID = req.setDelegate(this).startUpload();
at setDelegate(this).

I'm following the example provided in this link
https://github.com/gotev/android-upload-service/blob/master/examples/app/app/src/main/java/net/gotev/uploadservicedemo/MainActivity.java

**Comment by gotev** [comment]
Currently the master branch is what will be released as 3.0. The wiki has been updated for 3.0. The new release is scheduled for today. Hold on and use 3.0 when I release it later today.
