### ISSUE TITLE
add parallel upload file

### ISSUE THREAD

**Issue by patelanil2007** [gotev/android-upload-service#149]

**Comment by hendrawd** [comment]
Actually it's already parallel if you start multiple upload requests at once

**Comment by gotev** [comment]
[Refer to the Wiki](https://github.com/gotev/android-upload-service/wiki/Advanced%20topics#tune-the-number-of-parallel-uploads)

**Comment by patelanil2007** [comment]
@gotev its working in series

**Comment by hendrawd** [comment]
@patelanil2007 As @gotev mentioned before, have you checked the wiki? Maybe your phone have only a single core or you run on simulator?

**Comment by gotev** [comment]
You can actually see the number of upload threads when you set the log level to debug (check Recipes) and you start the library
