### ISSUE TITLE
addFileToUpload from online URL

### ISSUE THREAD

**Issue by oneidc** [gotev/android-upload-service#151]
I want to upload image i've just fetched from instagram.
[https://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13584225_272232403138665_855511386_n.jpg](url)
is there a possibility to add file to request from external url like website, ftp?

**Comment by gotev** [comment]
This is not possibile. You have to download it somwwhere on the device and pass the absolute path to the file to the upload request.
