### ISSUE TITLE
Pass context and intent to callbacks in UploadServiceBroadcastReceiver?

### ISSUE THREAD

**Issue by cskilbeck** [gotev/android-upload-service#152]
I notice that the Context and Intent which are passed as parameters to the onReceive function are discarded. Would it be useful to pass these through to the handlers? I'd like to do launch an activity in my onCompleted handler and not having a Context is a pain...

Or is this by design? I'm a total newbie to Android so I might be just missing the right way to do this...

**Comment by gotev** [comment]
You can get the context inside a `BroadcastReceiver` by calling `getReceiverContext()`

**Comment by cskilbeck** [comment]
Ah, brilliant! Thanks.
 
 
On Fri, Jul 8, 2016, at 01:37 PM, Alex Gotev wrote:
> You can get the context inside a BroadcastReceiver by calling
> getReceiverContext()
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>
 

Links:

  1. https://github.com/gotev/android-upload-service/issues/152#issuecomment-231348569
  2. https://github.com/notifications/unsubscribe/AEw3KxQm2V0KOkEN9H4fd6d_HkTGeDMTks5qTkRzgaJpZM4JH-KG

**Comment by cskilbeck** [comment]
Sorry, I can't find that function, I've looked all over Google etc and
in the docs but it's not showing up. Is it a public/protected member of
BroadcastReceiver?
 
 
On Fri, Jul 8, 2016, at 01:54 PM, Charlie Skilbeck wrote:
> Ah, brilliant! Thanks.
>
>
> On Fri, Jul 8, 2016, at 01:37 PM, Alex Gotev wrote:
>> You can get the context inside a BroadcastReceiver by calling
>> getReceiverContext()
>> — You are receiving this because you authored the thread. Reply to
>> this email directly, view it on GitHub[1], or mute the thread[2].
>>
>
 

Links:

  1. https://github.com/gotev/android-upload-service/issues/152#issuecomment-231348569
  2. https://github.com/notifications/unsubscribe/AEw3KxQm2V0KOkEN9H4fd6d_HkTGeDMTks5qTkRzgaJpZM4JH-KG

**Comment by gotev** [comment]
It's protected. You can access it because `UploadServiceBroadcastReceiver` is a subclass of `BroadcastReceiver`

**Comment by gotev** [comment]
@cskilbeck added also helper to get context [in the Wiki](https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status)

**Comment by cskilbeck** [comment]
OK, that's weird, I get compiler error: cannot find symbol method
getReceiverContext()
 
This is my event receiver code, I've tried it with and without the line:

@TargetApi(Build.VERSION_CODES.LOLLIPOP_MR1)
 
Any ideas? I'm targeting API 23, build tools 21.0.1

*package *com.dogtail;

*import **android.annotation.TargetApi*; *import
**android.content.Context*; *import **android.os.Build*; *import
**com.Log.log*; *import **net.gotev.uploadservice.ServerResponse*;
*import **net.gotev.uploadservice.UploadInfo*; *import
**net.gotev.uploadservice.UploadServiceBroadcastReceiver*;

*import **java.io.File*; *import **java.io.FileWriter*; *import
**java.io.IOException*; *import **java.io.PrintWriter*;

*public class **UploadEventReceiver **extends
**UploadServiceBroadcastReceiver *{    *private static final **String
***TAG **= "UploadEventReceiver";

    *@Override **public void *onProgress(*UploadInfo *uploadInfo) {
    *log*.**i**(**TAG**, *String*.**format**("Upload progress
    %d",uploadInfo.getProgressPercent())); }

    *@Override **public void *onCancelled(*UploadInfo *uploadInfo) {
    *log*.**i**(**TAG**, "Upload cancelled!"); }

    *@Override **public void *onError(*UploadInfo *uploadInfo,
    *Exception *exception) {    *log*.**i**(**TAG**, "Upload
    failed!"); }

    *@TargetApi*(*Build.VERSION_CODES*.**LOLLIPOP_MR1**) *@Override
    **public void *onCompleted(*UploadInfo *uploadInfo, *ServerResponse
    *serverResponse) {    *Context *ctx = getReceiverContext();
    *log*.**i**(**TAG**, "Upload completed!");    *try *{        *File
    *f = *Utils*.**createFile**(ctx, "uploaded.txt");*
    **FileWriter *fw = *new *FileWriter(f, *true*);        *PrintWriter
    *p = *new *PrintWriter(fw);        *for*(*String *s:
    uploadInfo.getSuccessfullyUploadedFiles()) {
                p.println(s); }
            p.close(); fw.close(); } *catch *(*IOException *e) {
              *log*.**e**(**TAG**, e.getMessage()); } } }
 
 
On Fri, Jul 8, 2016, at 04:20 PM, Alex Gotev wrote:
> @cskilbeck[1] added also helper to get context in the Wiki[2]
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].
>
 

Links:

  1. https://github.com/cskilbeck
  2. https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status
  3. https://github.com/gotev/android-upload-service/issues/152#issuecomment-231388425
  4. https://github.com/notifications/unsubscribe/AEw3KzTISPO_FQXLAo4uFme0vJHYLa2_ks5qTmrHgaJpZM4JH-KG
