### ISSUE TITLE
uploading jpg's sometimes got corrupted files

### ISSUE THREAD

**Issue by AngleV** [gotev/android-upload-service#155]
Most of the times it uploads the file normally. 
But sometimes i get corrupted images.
Take a look at the following image 

![20160716163142115731560477152936280](https://cloud.githubusercontent.com/assets/7430985/16896688/edce7412-4ba2-11e6-94ba-006def3f3376.jpg)

**Comment by gotev** [comment]
Apparently something wrong is happening during the upload. I need [more details](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help#bug-reporting). One thing you could do is calculate [SHA1 or MD5 checksums](http://karanbalkar.com/2013/05/tutorial-28-implement-sha1-and-md5-hashing-in-android/) of the file on Android and then on the server and check if the two corresponds.

**Comment by AngleV** [comment]
Strange thing is that this happens only sometimes and NOT always. As i all ready stated most of the times jpg files uploads normally. 
Code i am using to upload is the following


```
            MultipartUploadRequest req = new MultipartUploadRequest(this, SERVER_UPLOAD_STRING)
                    .addFileToUpload(filesToUploadString, PARAM_NAME_STRING)
                    .addArrayParameter("user", loggedUserID)
                    .addArrayParameter("name", name)
                    .addArrayParameter("region", region)
                    .addArrayParameter("country", country)
                    .addArrayParameter("country_code", country_code)
                    .addArrayParameter("latitude", latitude)
                    .addArrayParameter("longitude", longitude)
                    .addArrayParameter("comments", description.getText().toString())

                    .setNotificationConfig(getNotificationConfig())
                    .setCustomUserAgent(USER_AGENT)
                    .setAutoDeleteFilesAfterSuccessfulUpload(false) // TODO set this to TRUE on release
                    .setMaxRetries(5);

            req.setUtf8Charset();
            req.startUpload();

````

on server side my script is 

```
if ($_FILES["uploaded_file"]["error"] > 0) {
    echo "Error: " . $_FILES["uploaded_file"]["error"] . "<br>";
} else {
   	move_uploaded_file($_FILES["uploaded_file"]["tmp_name"], $target_file);
}

```

Calculating the SHA's checksums as you suggested is a nice trick to take further action but is not solving the issue i guess.

**Comment by gotev** [comment]
From your description and the code, I think the problem is on the wire. The most useful thing is to dump the network traffic when it happens, to see exactly what happens during the transfer of the bytes from the device to the server. Without this information, there's nothing helpful that can be done. If it's a bug in the library, with the dump we can find the exact circumstances in which it happens, replicate the problem and solve it.

**Comment by AngleV** [comment]
Write now i am switching to okhttp as stack and performing some tests to see if it will be any difference.
you think is wise or waste of time ?

**Comment by gotev** [comment]
@AngleV I highly recommend you to use OkHttp stack. I use it in production. I'm considering to make it the default HTTP stack in a future release. Let me know

**Comment by AngleV** [comment]
Since i use [Glide](https://github.com/bumptech/glide) to my project i have included com.github.bumptech.glide:okhttp-integration:1.4.0 

and in my Application class 

````
 OkHttpClient mClient = new OkHttpClient();

        mClient.setFollowRedirects(true);
        mClient.setFollowSslRedirects(true);
        mClient.setRetryOnConnectionFailure(true);
        mClient.setConnectTimeout(15,TimeUnit.SECONDS);
        mClient.setWriteTimeout(30, TimeUnit.SECONDS);
        mClient.setReadTimeout(30, TimeUnit.SECONDS);
        mClient.setCache(null);

        UploadService.HTTP_STACK = new OkHttpStack(mClient);

```

Unfortunately it does not work

i got the upload notification that runs for ever and nothing happens.  Any advise ?

**Comment by gotev** [comment]
@AngleV Do you still have the issue using OkHttp?

**Comment by gotev** [comment]
Closing this for lack of feedback. Reopen the issue if the error still persists after using OkHttp stack.
