### ISSUE TITLE
abnormal behavior on poor connectivity

### ISSUE THREAD

**Issue by AngleV** [gotev/android-upload-service#156]
in case user has poor mobile network connectivity i am getting a strange behavior.
Progress seems not to stop when it reaches 100% percent. it keeps going and going and when finally stops it has upload the same file twice.
![20160724_125908](https://cloud.githubusercontent.com/assets/7430985/17083167/c68fdfe2-519e-11e6-8bf0-adc82e754c69.png)

**Comment by gotev** [comment]
Which kind of upload are you using (multipart, binary, ftp) ?
The library debug log will be helpful to be able to spot what happens in this case, as it seems to be a library bug! Post as many details as you can, thank you!

**Comment by konalegi** [comment]
Having the same issue, have only screenshot of debug log. 
![image](https://cloud.githubusercontent.com/assets/1387057/17094984/0fd4728c-525b-11e6-8006-ee9f73bc0111.png)

**Comment by gotev** [comment]
@konalegi Thank you, although it would be helpful to see the entire error stack trace at the bottom. Are you guys using HurlStack or OkHttp stack? I've see that socket timeout error happening with HurlStack

**Comment by konalegi** [comment]
Error trace of timeout error, i hope it helps.
![image](https://cloud.githubusercontent.com/assets/1387057/17095758/d9ecdfa2-525e-11e6-9a61-8552ff463fe6.png)

**Comment by gotev** [comment]
@konalegi thank you! The socket timeout happens because of the poor network connectivity and that's fine, because it's a network issue and not a programming issue. What the library should do in this case is retry the upload until `maxRetries` gets reached and the percent of the operation should start from 0 again. If you have the same behaviour as described by @AngleV it will be helpful to enable [library debug log](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) and see exactly what happens, to be able to spot the cause of the issue.

**Comment by AngleV** [comment]
@gotev 
Yes im using OkHttp stack. still cant figure out what is wrong...

**Comment by gotev** [comment]
The behaviour you experienced maybe the same as #161

**Comment by gotev** [comment]
Merging this with #161

**Comment by amitsharma492** [comment]
I am facing same issue on Lastest Version of lib. Got some solution?

**Comment by gotev** [comment]
Try to replicate that behavior and collect some evidence logs

**Comment by amitsharma492** [comment]
I am facing this issue on some Mi Android Device in the poor network. Can we do something with Retry policy? this might be an issue but I didn't find anything to control retry option.

**Comment by gotev** [comment]
Just check the wiki for retry explanation

**Comment by amitsharma492** [comment]
I have set maximum retry to zero but still request going twice or more than two while uploading the photo.
