### ISSUE TITLE
RuntimeException: WakeLock under-locked UploadService

### ISSUE THREAD

**Issue by long-greg-c** [gotev/android-upload-service#158]
Similar to issue #125 
[This line](https://github.com/gotev/android-upload-service/blob/592b9b439848a9701a5f66e11e51cc976d2c010a/uploadservice/src/main/java/net/gotev/uploadservice/UploadService.java#L316) caused a RuntimeException.

The root cause was i accidentally attempted to upload the **same** file twice with each upload request set to **delete** the file after a successful upload.

Perhaps an exception could be thrown on a second upload request of the same file if the auto delete option is enabled.

**Comment by gotev** [comment]
The check if the file exists is performed when you build the upload request. Probabily what happened in your case is that when you built the two requests, the file existed, then the first one completed and the second one caused the problem.
