### ISSUE TITLE
Need to set x-csrf-token header

### ISSUE THREAD

**Issue by AndrewBryukhov** [gotev/android-upload-service#162]
Feature request.
Need to set x-csrf-token header, how i can do this?
I need for upload photos on sap server.

> Authorization: Basic ...
> X-Csrf-Token:  d-eoJSMQ8mS5nIKzwTqbxg==

**Comment by gotev** [comment]
That's explained in the Recipes section of the Wiki

**Comment by AndrewBryukhov** [comment]
I'm using retrofit and got dependency conflict:
java.lang.NoSuchMethodError: No virtual method internalCache(Lokhttp3/OkHttpClient;)Lokhttp3/internal/InternalCache;
