### ISSUE TITLE
Notification Icon - Colors

### ISSUE THREAD

**Issue by mmintz** [gotev/android-upload-service#164]
So, are you using the application compatibility notification builder? I tried with a normal png but on some marshmallow devices the icon was completely white. Then i tried to use siluet by saving png but my icon was really small with no colors but was showing at least. So what is happening. Can you make the notification more customizable ? Also is it possible to have different colors in the notification icon ? Great work guys.

**Comment by gotev** [comment]
Never had such an issue with the notification icon. I suggest you to generate the notification icon by using Android Asset Studio by Roman Nurik. Upload your PNG and the web app will do the rest. Download the zip and put the files in your resources

**Comment by mmintz** [comment]
Thank you very much. However the images generated have no color.

**Comment by mmintz** [comment]
The original file is has a blue arrow. But when the app is showing the notification the arrow is white.
![app4](https://cloud.githubusercontent.com/assets/4306732/17399267/f995e86c-5a38-11e6-996c-c2604a756657.png)
![screenshot_20160804-114315](https://cloud.githubusercontent.com/assets/4306732/17399278/10d7e2fa-5a39-11e6-9f97-db4040835c36.png)

**Comment by gotev** [comment]
Sorry, but this concern is completely out of scope here. The colors of the icons does not depend on the upload service library nor the Android support library.

**Comment by mmintz** [comment]
I was just saying that it would be nice if we could use custom notification. Are you creating the notification using Compat ? I am sorry if i am getting out of scope. I was just asking.
