### ISSUE TITLE
Unit and integration tests

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#166]
The library needs to have some automatic unit and integration tests to be sure it behaves correctly in many cases and to prevent regressions in newer releases. Since it's a network library, it should have also a mock server to perform the tests. At the moment I have not found a suitable framework or library to do that. Suggestions are welcome.

**Comment by ar-g** [comment]
Need to have them, one of the things which stops from using a library. A couple of things which came to the mind are using robolectric or using a separate app with espresso tests.

**Comment by gotev** [comment]
@ar-g you're welcome to create a demo app with Express tests

**Comment by gotev** [comment]
Closing this due to prolonged inactivity. At this time I don't have enough time for this. Feel free to reopen it if you are willing to implement testing with a PR :wink:
