### ISSUE TITLE
Rebuilded by gradle jar is freezed

### ISSUE THREAD

**Issue by AndrewBryukhov** [gotev/android-upload-service#167]
Today i was download latest soruce code, and try to compile it **without** any changes (only 23.0.2->23.0.3 in build.gradle):

> 2823-3881/package D/UploadService: UploadRequest - null or empty upload ID. Generating it
> 2823-3881/package D/UploadService: UploadRequest - Created new upload request to [url] with ID: 0d2753a3-5c91-4ea0-9730-4e0511c54237

and after i see nothing
where is no post requests in http sniffer too

With official jar all work (**i replace only jar file**/1 dependency), but i need to make some changes in source code.
I'm use jar from _android-upload-service-master\uploadservice\build\intermediates\bundles\release_

**Comment by AndrewBryukhov** [comment]
[ul.zip](https://github.com/gotev/android-upload-service/files/401616/ul.zip)

**Comment by gotev** [comment]
Replacing the jar like you've done is not something I'm supporting in any way. The only change in the latest master is a wake lock release. Nothing else was changed, so I suggest you to stick with the latest official release.

**Comment by AndrewBryukhov** [comment]
I can't use official release becouse i have a dependency conflict with retrofit for okhttp

**Comment by AndrewBryukhov** [comment]
> Contributions are welcome and encouraged! Just fork the project and then send a pull request.

lol
