### ISSUE TITLE
Where i can download latest commit official jar?

### ISSUE THREAD

**Issue by AndrewBryukhov** [gotev/android-upload-service#168]
Where i can download latest commit official jar?

**Comment by gotev** [comment]
You can use jitpack

**Comment by AndrewBryukhov** [comment]
This is similar maven, it is not last jar

**Comment by gotev** [comment]
You have to click on commits in JitPack and then select the last one from the list. I've done that for you this time: https://jitpack.io/#gotev/android-upload-service/754f15bea4

**Comment by gotev** [comment]
@AndrewBryukhov just released 3.0.1 which updates OkHttp from 3.2.0 to 3.4.1. I suggest you to use that instead of JitPack dependency. Try it and let me know.
