### ISSUE TITLE
How can I change notification icon on upload completion?

### ISSUE THREAD

**Issue by doublefree** [gotev/android-upload-service#173]
I want to set icon to represent "finish upload" on completion.
How can I do?

**Comment by gotev** [comment]
At the moment a single icon is used for both the progress notification and the upload completed notification. [UploadNotificationConfig] (https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadNotificationConfig.java) could be extended by adding `setCompletedIcon(int resourceID)` method and then getting the icon resource ID in [UploadTask's updateNotificationCompleted method](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L451)

**Comment by gotev** [comment]
@doublefree upgrade to 3.0.2 and you will be able to set both error and success notification icons. Refer to [UploadNotificationConfig](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/UploadNotificationConfig.html).

**Comment by doublefree** [comment]
that works!
