### ISSUE TITLE
Shall i go with is for uploading Video/Audio files to Amazons3

### ISSUE THREAD

**Issue by SkyNite** [gotev/android-upload-service#174]
HI @gotev ,

Thanks for sharing this.

Here is my actual need, 

1. I continuously record a audio once it reach max size i upload this to Amazon S3.
For amazon s3 i used cognito credentials for authentication purpose. The recording may continue x-Hours.. simultaneously i need to upload the content to s3.  For this currently i used Intent service class  with TransferManager (as per s3 documentation i used) class, it seems too slow and some parts are missing while uploading... To avoid this i wish to use your library, before that let me know this will suit for my approach.

Thanks.

**Comment by gotev** [comment]
If Amazon S3 supports standard HTTP Multipart requests you can use the library out of the box. If it uses some other proprietary upload protocol, to use the library you will need to create a new subclass of UploadRequest and UploadTask base classes, as described in the developer's manual and implement it. The library is open for extension :)
