### ISSUE TITLE
Binary upload notworking (3.0.3)

### ISSUE THREAD

**Issue by thuantan2060** [gotev/android-upload-service#176]
I used last version (3.0.3) and i also use you server nodejs. But I cannot use binary upload

#Addition 
- Client side seem ok
- Server side: on request header don't have "file-name" field (line 113)
I think you forget put field "file-name" some where on client side

**Comment by thuantan2060** [comment]
I working when i use .addHeader("file-name", new File(path).getName()).

**Comment by gotev** [comment]
Updated [Recipes](https://github.com/gotev/android-upload-service/wiki/Recipes) wiki
