### ISSUE TITLE
Add custom actions to notifications

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#179]
It will be useful to be able to add custom actions to `UploadNotificationConfig`, like this:

``` java
new UploadNotificationConfig()
    .addAction(actionIconResourceID, buttonText, pendingIntent)
```

addAction should have the following signature:

```
public final UploadNotificationConfig addAction(
    int iconResourceID, String text, PendingIntent action)
```

[This](http://stackoverflow.com/a/38692159) explains how to marshal and unmarshal `PendingIntents` to/from `Parcelable`

**Comment by gotev** [comment]
@hendrawd if you need help with the implementation, let me know here

**Comment by hendrawd** [comment]
it's ok for marshal and un-marshal PendingIntent, but i think it is better if we can add more than 1 actions there, so i work on List instead of just 1 PendingIntent. I have tried with more than 1 actions, and 3 is the best(visible). What do you think?

**Comment by gotev** [comment]
@hendrawd Yes. When `addAction` is invoked, a new element has to be added to the underlying list. We can log a warning message if the upload notification config has more than three buttons

**Comment by mnaswin3** [comment]
Hi guys, 
any update on this feature?

**Comment by gotev** [comment]
@mnaswin3 not yet, but you can send a PR!

**Comment by gotev** [comment]
Implemented actions for notifications. Major refactor to `UploadNotificationConfig `class was needed, to have a better structure, less method count (#248) and easier code readability. It drops retro-compatibility but for the better. Updated demo app. This feature will be available starting from release `3.3`.

Read the code example below, which is taken from the demo app's BaseActivity.

`Before 3.3`:
```java
protected UploadNotificationConfig getNotificationConfig(@StringRes int title) {
    return new UploadNotificationConfig()
            .setIcon(R.drawable.ic_upload)
            .setCompletedIcon(R.drawable.ic_upload_success)
            .setErrorIcon(R.drawable.ic_upload_error)
            .setCancelledIcon(R.drawable.ic_cancelled)
            .setIconColor(Color.BLUE)
            .setCompletedIconColor(Color.GREEN)
            .setErrorIconColor(Color.RED)
            .setCancelledIconColor(Color.YELLOW)
            .setTitle(getString(title))
            .setInProgressMessage(getString(R.string.uploading))
            .setCompletedMessage(getString(R.string.upload_success))
            .setErrorMessage(getString(R.string.upload_error))
            .setCancelledMessage(getString(R.string.upload_cancelled))
            .setClickIntent(new Intent(this, MainActivity.class))
            .setClearOnAction(true)
            .setRingToneEnabled(true);
}
```
In `3.3`:
```java
protected UploadNotificationConfig getNotificationConfig(String uploadId, 
                                                         @StringRes int title){
    UploadNotificationConfig config = new UploadNotificationConfig();

    PendingIntent clickIntent = PendingIntent.getActivity(
            this, 1, new Intent(this, MainActivity.class),
            PendingIntent.FLAG_UPDATE_CURRENT);

    config.setTitleForAllStatuses(getString(title))
            .setRingToneEnabled(true)
            .setClickIntentForAllStatuses(clickIntent)
            .setClearOnActionForAllStatuses(true);

    config.getProgress().message = getString(R.string.uploading);
    config.getProgress().iconResourceID = R.drawable.ic_upload;
    config.getProgress().iconColorResourceID = Color.BLUE;
    config.getProgress().actions.add(new UploadNotificationAction(
            R.drawable.ic_cancelled,
            getString(R.string.cancel_upload),
            NotificationActions.getCancelUploadAction(this, 1, uploadId)));

    config.getCompleted().message = getString(R.string.upload_success);
    config.getCompleted().iconResourceID = R.drawable.ic_upload_success;
    config.getCompleted().iconColorResourceID = Color.GREEN;

    config.getError().message = getString(R.string.upload_error);
    config.getError().iconResourceID = R.drawable.ic_upload_error;
    config.getError().iconColorResourceID = Color.RED;

    config.getCancelled().message = getString(R.string.upload_cancelled);
    config.getCancelled().iconResourceID = R.drawable.ic_cancelled;
    config.getCancelled().iconColorResourceID = Color.YELLOW;

    return config;
}
```
It's more verbose now, but you can finely tune every aspect of every notification, in a way which was not possible before (#293), and it's easier to read. Check out the new utility functions in `UploadNotificationConfig` which lets you set a property globally for all the notification statuses.

The demo app has been updated to show an example of how you can cancel an upload task from the notification.

**Comment by gotev** [comment]
3.3 released and this feature is now available!

**Comment by VSG24** [comment]
`config.getCancelled().message = getString(R.string.upload_cancelled);`

This coding style is horrible and not appropriate for Java or any other lang as far as I can tell.

**Comment by gotev** [comment]
@VSG24 Fine. If you implemented that part, how would you do it instead? I have reasons for that kind of implementation, but I want to hear your feedback and suggestions

**Comment by hendrawd** [comment]
@VSG24 Do you want to use setter and getter for message?

**Comment by VSG24** [comment]
@gotev @hendrawd Just taking a look at other libraries and even Android SDK itself, I think it's pretty clear how it should be done.

**Comment by gotev** [comment]
@VSG24 Ok but no value added with your comments yet and it's a pity. I like to discuss about software design a lot! A part the obvious, what do toi suggest? It's open source, everything can be changed for the better :smiley:
