### ISSUE TITLE
How to use FTP Upload

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#182]
So, i tried to use FTPUploadRequest directly to my project, but it doesn't seem to work. 
Then i use the example project directly, and have changed the username and password to match my ftp username and password but it doesn't work too.
I run ftp on localhost with mac machine, and already check via terminal and browser that my ftp work as expected.
Did i missed something?

![screen shot 2016-08-30 at 4 18 28 pm](https://cloud.githubusercontent.com/assets/9481791/18083630/2541ab96-6ece-11e6-9218-3527352d4c8c.png)
![screenshot_2016-08-30-16-16-43](https://cloud.githubusercontent.com/assets/9481791/18083701/622c5b00-6ece-11e6-9509-c921bf5a50b9.png)

**Comment by gotev** [comment]
Ho have to put your PC ip address, not localhost

**Comment by hendrawd** [comment]
Oh yes, i forgot that i do upload with different ip address on phone. I feel stupid atm, lol. Thanks @gotev

**Comment by Pantela777** [comment]
Please write exp. URL... **ftp://user:password@ipaddress**
