### ISSUE TITLE
File list on FTPUploadRequest is not reset

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#184]
After success upload via FTPUploadRequest, then i try to upload again with a new files, the previous files will be added too to the current upload.

So if previously i upload 10 files, then i upload 20 files, current upload will be 30 files(previous upload included)

**Comment by hendrawd** [comment]
Here is the snippet of the code that i use for FTPUpload
```
protected void doUploadFTP() {
    final String serverUrlString = "192.168.2.1";

    FTPUploadRequest request = new FTPUploadRequest(this, serverUrlString, 21)
            .setUsernameAndPassword("user", "password")
            .setMaxRetries(4)
            .setNotificationConfig(getNotificationConfig("File upload"))
            .useCompressedFileTransferMode(true)
            .setAutoDeleteFilesAfterSuccessfulUpload(false);

    for (String mCurrentPhotoPath : mCurrentPhotoPaths) {
        try {
            Uri uriToUpload = Uri.parse(mCurrentPhotoPath);
            request.addFileToUpload(uriToUpload.getPath(), "/dir/subdir/");
        } catch (FileNotFoundException exc) {
        } catch (IllegalArgumentException exc) {
        }
    }

    try {
        request.startUpload();
    } catch (MalformedURLException e) {
        e.printStackTrace();
    }
}
```
As you can see, i always re-create the request everytime i want to upload, so it is not because of re-useable request.

**Comment by gotev** [comment]
`mCurrentPhotoPaths` is your own variable which has the paths to the files to upload. Reset that once the upload is successful and before selecting new files, otherwise you will have the behaviour you described.

**Comment by hendrawd** [comment]
@gotev Yes, you are right. Looks like i forgot include mCurrentPhotoPaths.clear(); when changing MultipartUploadRequest to FTPUploadRequest
