### ISSUE TITLE
Cancel Upload Notification Message

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#188]
Currently when we upload, then cancel the upload via UploadService.cancel(uploadId);, the error message will show up("Error during upload"). I think it is better if we can replace with cancel message like "File upload cancelled", because error and cancel is different action

**Comment by hendrawd** [comment]
This related to https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L329

**Comment by gotev** [comment]
@hendrawd implemented! You can try the latest snapshot which includes the new feature:
```groovy
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```
```groovy
compile 'com.github.gotev:android-upload-service:277dc4e40a'
```
Example of how to configure cancelled icon, message and auto clear behaviour:
```java
private UploadNotificationConfig getNotificationConfig(String title) {
    return new UploadNotificationConfig()
            .setIcon(R.drawable.ic_upload)
            .setCompletedIcon(R.drawable.ic_upload_success)
            .setErrorIcon(R.drawable.ic_upload_error)
            .setCancelledIcon(R.drawable.ic_cancelled)
            .setTitle(title)
            .setInProgressMessage("Uploading...")
            .setCompletedMessage("Upload completed successfully!")
            .setErrorMessage("Error while performing upload!")
            .setCancelledMessage("Upload has been cancelled!")
            .setAutoClearOnCancel(false)
            .setAutoClearOnSuccess(true)
            .setClearOnAction(true)
            .setRingToneEnabled(true);
}
```
then simply set `UploadNotificationConfig` as usual in the `UploadRequest`.

The following methods have been added to `UploadNotificationConfig`:
```java
.setCancelledIcon(R.drawable.ic_cancelled)
.setCancelledMessage("Upload has been cancelled!")
.setAutoClearOnCancel(false)
```
