### ISSUE TITLE
Add a tag to UploadInfo 

### ISSUE THREAD

**Issue by NitroG42** [gotev/android-upload-service#189]
This lib already does a great job but I'm missing one feature : If we have multiple kind of upload through our app, it's difficult to recognize each one if we don't keep the uploadId in a singleton (to make it survives the user navigation in the app). It would be simpler if we could pass a simple String (a tag) to the UploadRequest that would be in the upload info (it could be the id of the model linked to the picture to upload, etc...)
I understand you are parceling UploadInfo, that's why I think a String would be the simplest thing to implement with the best flexibility.

**Comment by alexbbb** [comment]
@NitroG42 you can already [set a custom uploadID](https://github.com/gotev/android-upload-service/wiki/Recipes#what-is-the-upload-id) to your upload request, [check JavaDocs](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/MultipartUploadRequest.html#MultipartUploadRequest-android.content.Context-java.lang.String-java.lang.String-).

**Comment by NitroG42** [comment]
Oh I'm really sorry, I missed this part of the doc ! 
Thank you for the info
