### ISSUE TITLE
Convert ServerResponse string to object

### ISSUE THREAD

**Issue by folol** [gotev/android-upload-service#190]
I have an activity where i am uploading a video file to server like this - 

            MultipartUploadRequest req = new MultipartUploadRequest(VideoPlayerActivity.this, ApplicationConstants.BASE_API_URL.concat("video/"+String.valueOf(id)+"/upload"))
                    .addFileToUpload(path, "file")
                   // .addParameter("email",Preferences.getAppPrefs().getUserInfo().getEmail())      //change email to Preference.getUserInfo().getEmail();
                    .setNotificationConfig(getNotificationConfig("Video"))
                    .setAutoDeleteFilesAfterSuccessfulUpload(false)
                    .setUsesFixedLengthStreamingMode(false);

            req.addHeader("Key", ApplicationConstants.APP_SECRET);
            req.addHeader("Accept", "applicaton/json");
            req.addHeader("Client", ApplicationConstants.CLIENT_CODE);
            req.addHeader("Authorization", "Bearer " + Preferences.getAppPrefs().getToken());

            String uploadID = req.startUpload();

and i want to convert ServerResponse object that i am getting into Java objects by using retrofit with okhttp .

How can i do that ? Please help!

**Comment by gotev** [comment]
You can do that in your `onCompleted` implementation like this:
```java
@Override
public void onCompleted(UploadInfo uploadInfo, ServerResponse serverResponse) {
    YourClass obj = new Gson().fromJson(serverResponse.getBodyAsString(), YourClass.class);
}
```

**Comment by folol** [comment]
@gotev  thanks a lot
