### ISSUE TITLE
Progress bar over 100%

### ISSUE THREAD

**Issue by misaelemc** [gotev/android-upload-service#191]
Very good library, but I have a small problem with the progress bar of notifications, while it is uploading a file, reaches a point where the percentage of the progress bar goes above 100%.

I'm using these dependencies:
    compile 'net.gotev: uploadservice: 3.0.1'
    compile 'net.gotev: uploadservice-okhttp: 3.0.3'

And my code is:
```

mMultiPartUpload = new MultipartUploadRequest (mContext, mUploadFile.getName (), PATH_URL);
mMultiPartUpload.setMaxRetries (1);
mMultiPartUpload.addFileToUpload (mUploadFile.getPath (), "file", mUploadFile.getName (), "application / octet-stream");
  
mNotificationUpload.setTitle (mContext.getString (R.string.file_upload))
                .setAutoClearOnSuccess (true)
                .setInProgressMessage (mContext.getString (R.string.uploading_at))
                .setErrorMessage (mContext.getString (R.string.error_while_uploading))
                .setCompletedMessage (mContext.getString (R.string.upload_completed));
mMultiPartUpload.setNotificationConfig (mNotificationUpload);
mMultiPartUpload.startUpload ();
```

I'll appreciate your help. :+1:

**Comment by gotev** [comment]
Just update `uploadservice` to [3.0.3](https://github.com/gotev/android-upload-service/milestone/14?closed=1), it has been fixed. Always check that your upload service dependencies are aligned to the latest release. You can find it in the setup wiki page.
