### ISSUE TITLE
FTP Upload - filename characters become "?" on the server

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#192]
I tried FTP Upload with Korean characters on the file name, but the characters become "?" instead. I reproduce it with the sample project you provided.
Maybe related to #82

### Version info
* Android Upload Service version: 3.0
* Android version and API version: Kitkat, 19
* HTTP stack (e.g. HurlStack or OkHttpStack): default stack from example project(OkHttp)

### What did you expect?
Correct characters name for uploaded files

### What happened instead?
File names replaced with "?" characters

### Steps to reproduce (if applicable):
Use Korean letters to file name, upload via FTP

### Additional info
![screen shot 2016-09-19 at 3 20 23 pm](https://cloud.githubusercontent.com/assets/9481791/18626192/9ef326ea-7e7d-11e6-85e4-078ec9955627.png)
The first 3 is the uploaded files from android, and the last one, i renamed it directly on my computer to check if it's my computer problem.

**Comment by gotev** [comment]
The FTP Upload module uses [Apache Commons Net FTP](https://commons.apache.org/proper/commons-net/dependency-info.html). I think the issue is [because of the default filename encoding](http://stackoverflow.com/questions/9535925/filename-encoding).

**Comment by gotev** [comment]
@hendrawd upgrade your dependencies for [FTP module 3.0.4](https://github.com/gotev/android-upload-service/tree/master/uploadservice-ftp), try and let me know. Check you have enabled UTF-8 as the default character encoding on your FTP server, otherwise you won't be able to use non-ASCII file names.

**Comment by hendrawd** [comment]
I have tested on sample project and it's working fine :)
