### ISSUE TITLE
Need Little help to make put request

### ISSUE THREAD

**Issue by YasirAmeen** [gotev/android-upload-service#193]
I am using your library and its great. Thank you for creating this. I need little help, i want to send put request according to the following, videos are name with GUID and it can be many.

**Add An Event**
Adds an event to the system. Administrator or videographer role required.
Request
PUT /events
X-UnderPar-Auth: security_token
Content-Type: application/json

{
  ClubID: 10,
  EventDate: "2016-08-11T19:03:04.5562161Z",
  VideographerID: 10,
  Videos: [
    Index: 1, // indexing the entries for easier debugging purposes
    Email: "geri@underpar.com",
    Name: "Geri Shelnev",
    Guid: "284923840293ur90df23jf230",
    AspectRatio: 1.33,
    Created: "2016-08-11T19:03:04.5562161Z",
  ],
}
Response
{
  “EventID”: 100,
  “NumberOfVideos”: 150
}

**Comment by gotev** [comment]
This is not an HTTP Multipart, FTP or binary upload, so it's not supported by this library. However, [you should ask this kind of questions on StackOverflow](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help).
