### ISSUE TITLE
Is there any way to cancel Uploads

### ISSUE THREAD

**Issue by YasirAmeen** [gotev/android-upload-service#196]
Hi, Thank you for the great library. I want to know if there is any way to stop/cancel uploads.

Thanks

**Comment by gotev** [comment]
@YasirAmeen please read the [Wiki](https://github.com/gotev/android-upload-service/wiki/Recipes#stop-upload-tasks-) before opening issues like this

**Comment by YasirAmeen** [comment]
ok Thank you i got it :-)
