### ISSUE TITLE
Can i use this example for Download files?

### ISSUE THREAD

**Issue by ddpatel2606** [gotev/android-upload-service#197]
Your effort is extremely good but I have a question that,

Can, I use your code for the purpose of download multiple files?

Thanks,
Dixit Patel

**Comment by gotev** [comment]
The library is for upload only. To download files you should rely on Android's integrated Download Manager or on JobScheduler.

**Comment by ddpatel2606** [comment]
okay...

**Comment by gotev** [comment]
@ddpatel2606 however, you are free to fork the library and add that functionality if you need it
