### ISSUE TITLE
Upload image from URI

### ISSUE THREAD

**Issue by brunoramonalmeida** [gotev/android-upload-service#203]
I'm trying to upload a image file, I'm passing the argument "myuri.getPath()" to the method "addFileToUpload", but it's not working. 

It would be nice if we can upload a URI directly. What's the right way to get absolute file path from a URI to pass to addFileToUpload method?

Thanks.

**Comment by gotev** [comment]
URI support is work in progress (uri_support branch) and is part of 3.1 release, which will be released very soon. Then you can simply pass the strigified version of your `file://` or `content://` URI.
