### ISSUE TITLE
Apps Powered by Android Upload Service

### ISSUE THREAD

**Issue by Habibah28** [gotev/android-upload-service#204]
Hello!

I use your Upload Service as part of my apps [MyCyberLaw](https://play.google.com/store/apps/details?id=com.mycyberlaw). I am really thankful for this Upload Service.

One question: Is there a way to show the end progress like _Upload completed successfully!_ and _Error during upload_ in Alert Dialog?

**Comment by hendrawd** [comment]
@Habibah28 If you read the wiki, there is already a documentation about how to achieve that
[https://github.com/gotev/android-upload-service/wiki/Monitoring%20upload%20status](behavior)

**Comment by gotev** [comment]
@Habibah28 added MyCyberLaw. It will be visible on the main README when I release 3.1
