### ISSUE TITLE
Internal server error | Status code - 500

### ISSUE THREAD

**Issue by shoebhoney** [gotev/android-upload-service#206]
Hey Alex,

Greetings!
Hope you are doing Great!

I have used your library in my previous apps, which worked like a charm.
BUT now when i need to use in my new app, i am getting below error -
`
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Database Error</title><style type="text/css">::selection { background-color: #E13300; color: white; }::-moz-selection { background-color: #E13300; color: white; }body {	background-color: #fff;	margin: 40px;	font: 13px/20px normal Helvetica, Arial, sans-serif;	color: #4F5155;}a {	color: #003399;	background-color: transparent;	font-weight: normal;}h1 {	color: #444;	background-color: transparent;	border-bottom: 1px solid #D0D0D0;	font-size: 19px;	font-weight: normal;	margin: 0 0 14px 0;	padding: 14px 15px 10px 15px;}code {	font-family: Consolas, Monaco, Courier New, Courier, monospace;	font-size: 12px;	background-color: #f9f9f9;	border: 1px solid #D0D0D0;	color: #002166;	display: block;	margin: 14px 0 14px 0;	padding: 12px 10px 12px 10px;}#container {	margin: 10px;	border: 1px solid #D0D0D0;	box-shadow: 0 0 8px #D0D0D0;}p {	margin: 12px 15px 12px 15px;}</style></head><body>	<div id="container">		<h1>A Database Error Occurred</h1>		<p>Error Number: 1048</p><p>Column 'user_id' cannot be null</p><p>INSERT INTO `gallery` (`user_id`, `cadidate_id`, `image`, `created`) VALUES (NULL, NULL, '', '2016-11-06 04:53:06')</p><p>Filename: models/User_model.php</p><p>Line Number: 66</p>	</div></body></html>`

Here is my request - 

  final UploadRequest request = new UploadRequest(getActivity(),
                UUID.randomUUID().toString()
                , WebserviceConstant.MAIN_BASE_URL + WebserviceConstant.addGalleryImage);

        //add header
//        request.addHeader(Constant.Cookie, sPref.getString(Constant.Cookie, ""));
        //add parameters

        SharedPreferences mPrefs = getActivity().getSharedPreferences(Constant.SPREF, Context.MODE_PRIVATE);
        Gson gson = new Gson();
        String json = mPrefs.getString(Constant.LoginModal, "");
        LoginModal mLoginModal = gson.fromJson(json, LoginModal.class);
        request.addParameter("user_id", mLoginModal.getUserDetail().get(0).getUserId());
        request.addParameter("candidate_id", mLoginModal.getCandidateId());

        request.addFileToUpload(fileToUploadPath, "gallery_image", System.currentTimeMillis() + ".png", ContentType.APPLICATION_OCTET_STREAM);

Can you please suggest me, what i am doing wrong.
Because when i upload file from postman tool, then it works fine. 
So i believe that something wrong at my end.

Thanks

**Comment by gotev** [comment]
As the error says, you are passing a null or invalid user_id to your server. Check the parameters you are sending in the request.
