### ISSUE TITLE
Different Pending Intent for case of error in uploading and different for success ?

### ISSUE THREAD

**Issue by folol** [gotev/android-upload-service#207]
### Version info
* Android Upload Service version:3.0.3
* Android version and API version:
* HTTP stack  -  OkHttpStack 

I just wanted to know that if there is any way to set different Pending Intent in case that uploading of file failed because i want to open different activity for that case and also how can i let user retry the uploading of file from the click of a button in notification or something if it uploading fails?

Thanks in advance

**Comment by gotev** [comment]
You can specify a single intent for an Upload request. What you do after that is up to you. So you could launch an activity for example and decide where to redirect the user from there.

Number of retries are set in the upload request when you create them. If the request fails even after the automatic retries, is up to you to decide how to allow users to retry the same request. 

All the above is like that on purpose, as the library is designed to be as simple as possible, to be more flexible and allow many different implementations and behaviours.
