### ISSUE TITLE
starts uploading when internet connectivity is resumed ??

### ISSUE THREAD

**Issue by prashermanas** [gotev/android-upload-service#209]
Does this library considers network connectivity. such as upload files when internet connectivity resumes and pause when internet connectivity is not there

**Comment by hendrawd** [comment]
Not yet. The upload will fail immediately if the connection is interupted

**Comment by gotev** [comment]
@prashermanas HTTP Multipart and Binary uploads does not support resume, as per RFC specifications. Only FTP uploaded supports resume. If you want to upload or retry downloads only when a connection is available, you have to implement your own strategy. [Here] you can find some hints.
