### ISSUE TITLE
Notification place holder ([[PROGRESS]]) is always 0

### ISSUE THREAD

**Issue by sandeshlasnapure** [gotev/android-upload-service#210]
In 3.0.3 the notification place holder not working.
I have invoke the progress delegate but onProgress(UploadInfo uploadInfo) gets called only once now am not able to track the progress any more, meanwhile all file uploading works perfectly fine.
Please need help asap. I have gone through the wiki and used the exact same code.

**Comment by gotev** [comment]
Whatbis your Upload ed files size?

**Comment by sandeshlasnapure** [comment]
I am trying to upload two file having 120-300 kb size each.
My progress delegate is in foreground activity.

**Comment by gotev** [comment]
The files are really small, so if you have a good bandwidth from client to server, it's possible that the onProgress gets called only once at the start and then the onCompleted gets called.
