### ISSUE TITLE
Can not resume ftp upload

### ISSUE THREAD

**Issue by Bekakk** [gotev/android-upload-service#211]
Hi
I'm using your library.I successfully uploaded file with Ftp.I have one problem.I have large file.File uploading has started successfully,I turn offed internet connection and then turn on and resume not worked
is it a possible to resume file upload when i use Ftp ?
thank

**Comment by gotev** [comment]
Resume is supported for the entire Upload operation, not partially uploaded files. For example if you have 3 files and you upload 2 of them successfully and the third one interrupts, the upload will continue by retrying the third one from the start. This is because I've not found a way to do that using the apache Commons net library (which is the library used to add FTP capability). If you know how it's done, suggestions, code snippets or pull requests are welcome!

**Comment by Bekakk** [comment]
thanks Alex your attention
Is it a possible to retry file uploading  when something wrong?

**Comment by gotev** [comment]
Of course. Check the wiki Recipes page

**Comment by Bekakk** [comment]
Alex
Can you show me code snippets how to can retry Ftp uploading if something wrong?
thanks

**Comment by gotev** [comment]
Check out the demo app and [read this](https://github.com/gotev/android-upload-service/blob/master/uploadservice-ftp/README.md)

**Comment by Bekakk** [comment]
` @OnClick(R.id.ftpUploadButton)
    void onUploadFTPClick() {
        final String serverUrlString = serverUrl.getText().toString();

        final String filesToUploadString = filesToUpload.getText().toString();
        final String[] filesToUploadArray = filesToUploadString.split(",");

        FTPUploadRequest request = new FTPUploadRequest(this, serverUrlString, 21)
                .setUsernameAndPassword("app_stock", "0R4h8K3rD1f8V1z8")
                .setMaxRetries(4)
                .setNotificationConfig(getNotificationConfig("File upload"))
                .useCompressedFileTransferMode(true)
                //.setCreatedDirectoriesPermissions(new UnixPermissions("777"))
                .setAutoDeleteFilesAfterSuccessfulUpload(autoDeleteUploadedFiles.isChecked());

        for (String fileToUploadPath : filesToUploadArray) {
            try {
                request.addFileToUpload(fileToUploadPath, "/", new UnixPermissions("777"));
            } catch (FileNotFoundException exc) {
                showToast(exc.getMessage());
            } catch (IllegalArgumentException exc) {
                showToast("Missing some arguments. " + exc.getMessage());
            }
        }

        try {
            String uploadID = request.setDelegate(this).startUpload();
            addUploadToList(uploadID, "FTP upload");

        } catch (IllegalArgumentException exc) {
            showToast("Missing some arguments. " + exc.getMessage());
        } catch (MalformedURLException exc) {
            showToast(exc.getMessage());
        }
    }`
This is my source.I tryed to upload large file with Ftp.I disconnected internet connection and then connected ,but retry still not working
what is a wrong in my source?can you help me?
thanks

**Comment by gotev** [comment]
Enable library debug log and you will see what is going on internally. I'm sure retry is working. The code seems ok. The library has a back off timer in the retries, so the next retry is not bound to internet connectivity change but it's done after an increasing delay (check wiki for details). If you think it's a bug, provide more details and steps to reproduce.
