### ISSUE TITLE
XLSX doc is not uploading

### ISSUE THREAD

**Issue by sitansu12568204** [gotev/android-upload-service#219]
Be sure to check [Asking for help](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help) page on the Wiki before opening a new issue! Delete this text when you create a new issue.

### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by sitansu12568204** [comment]
XLSX doc is not uploading to server.

**Comment by gotev** [comment]
Ok, how can I replicate your scenario? Please fill in the required information in the issue
```
XLSX doc is not uploading to server
```
is insufficient as information to be able to address an eventual bug in the library.

**Comment by gotev** [comment]
Marking as invalid and closing due to lack of information
