### ISSUE TITLE
Not compiling when using uploadservice-okhttp with okhttp dependency

### ISSUE THREAD

**Issue by vgevorgyan** [gotev/android-upload-service#225]
Hello,

### Version info
* Android Upload Service version: 3.1
* Android version and API version: -
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### What did you expect?

Compile and run.

### What happened instead?

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okhttp3/internal/ws/RealWebSocket$1.class

### Steps to reproduce (if applicable):

```groovy
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:design:25.1.0'
    compile 'com.android.support:cardview-v7:25.1.0'
    compile 'com.google.android.gms:play-services:10.0.1'
    compile 'com.google.firebase:firebase-crash:10.0.0'
    compile 'com.google.firebase:firebase-messaging:10.0.0'

    //  Networking
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.5.0'

    // UI
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'com.afollestad.material-dialogs:commons:0.9.1.0'

    compile 'es.guiguegon:gallerymodule:1.3.1'
    compile 'com.sandrios.android:sandriosCamera:1.0.4'

    compile 'com.squareup.picasso:picasso:2.5.2'

    compile 'com.github.clans:fab:1.6.4'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.5@aar') {
        transitive = true;
    }
    compile('com.twitter.sdk.android:twitter:2.2.0@aar') {
        transitive = true;
    }
    compile 'com.facebook.android:facebook-android-sdk:4.17.0'

    compile 'org.greenrobot:eventbus:3.0.0'

    compile('io.socket:socket.io-client:0.7.+') {
        exclude group: 'org.json', module: 'json'
    }

    compile 'net.gotev:uploadservice:3.1'
    compile 'net.gotev:uploadservice-okhttp:3.1'
}
```

### Library initialization code:
```java
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
Logger.setLogLevel(Logger.LogLevel.DEBUG);
UploadService.INITIAL_RETRY_WAIT_TIME = 10;
UploadService.BACKOFF_MULTIPLIER = 1;
```

#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
How have you solved it?

**Comment by vgevorgyan** [comment]
That was my mistake, sorry :)

It was not related with android-upload-service.
Issue was socket-io and okhttp. Just updated socket-io version which using the same okhttp version that I'm using.

But problem came when I started using uploadservice-okhttp, be cause there you are using okhttp 3.5 version, but I used 3.3.1, to not have duplication issue I have changed okhttp version to 3.5, which make issue with socket-io, which fixed by moving socket-io to latest version.

By the way I have an other issue, when I call startUpload() it shows up notification and immediately write error, I have checked logs nothing there, but this is happening not always, but conditions are the same (same file, even same runtime). But maybe I need to create an other issue for this :)

Thanks, for response :)

**Comment by gotev** [comment]
Thank you for the explanation! Upload Service aims to target always the latest version of the dependencies, to be up to date. If you have problems, you can rely on Gradle's [conflict resolution strategies](https://docs.gradle.org/current/userguide/dependency_management.html#sec:dependency_resolution), to use the most appropriate version of OkHttp for your project, avoiding you to do multiple library dependencies updates in a row for a particular build, like you experienced. 

If you have problems with the library, create new issues, with as much detail as you can to help replicate your scenario.

**Comment by efkan** [comment]
@vgevorgyan updating `socket-io` version works for my app too. It stopped me for 2 days. Thanks for sharing this!
