### ISSUE TITLE
Non permanent issue when trying to upload file.

### ISSUE THREAD

**Issue by vgevorgyan** [gotev/android-upload-service#226]
### Version info
* Android Upload Service version: 3.1
* Android version and API version: any
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### What did you expect?

Upload file

### What happened instead?

In notification shows up "Error during upload".

### Library initialization code:
```java
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
Logger.setLogLevel(Logger.LogLevel.DEBUG);
UploadService.INITIAL_RETRY_WAIT_TIME = 10;
UploadService.BACKOFF_MULTIPLIER = 1;

final OkHttpClient client = new OkHttpClient.Builder()
        .followRedirects(true)
        .followSslRedirects(true)
        .retryOnConnectionFailure(true)
        .connectTimeout(15, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .cache(null)
        .build();
UploadService.HTTP_STACK = new OkHttpStack(client);
```

### Request code:
```java
final UploadStatusDelegate delegate = new UploadStatusDelegate() {
            @Override
            public void onProgress(Context context, UploadInfo uploadInfo) {
            }

            @Override
            public void onError(Context context, UploadInfo uploadInfo, Exception exception) {
                exception.printStackTrace();
            }

            @Override
            public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
            }

            @Override
            public void onCancelled(Context context, UploadInfo uploadInfo) {
            }
        };
        try {
            final UploadNotificationConfig notificationConfig = new UploadNotificationConfig();
            notificationConfig.setIcon(R.mipmap.ic_launcher);
            notificationConfig.setTitle(context.getString(R.string.app_name));
            notificationConfig.setInProgressMessage(context.getString(R.string.uploading));
            notificationConfig.setCompletedIcon(R.mipmap.ic_launcher);
            notificationConfig.setCompletedMessage(context.getString(R.string.uploaded));
            notificationConfig.setErrorIcon(R.mipmap.ic_launcher);

            final MultipartUploadRequest request = new MultipartUploadRequest(context, Constants.BASE_URL + "/uploadFile");
            request.addFileToUpload(fileUri.getPath(), "file", fileName);
                request.setNotificationConfig(notificationConfig);
            request.setMaxRetries(10);
            request.setDelegate(delegate);
            request.startUpload();
        } catch (MalformedURLException | FileNotFoundException e) {
            e.printStackTrace();
        }
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [x] Other class (add additional info about it)
Calling from model, which is called from activity.

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
01-20 15:23:19.894 10841-10841/{PACKAGE_NAME} D/UploadService: UploadRequest - null or empty upload ID. Generating it
01-20 15:23:19.894 10841-10841/{PACKAGE_NAME} D/UploadService: UploadRequest - Created new upload request to http://example.com/uploadFile with ID: 1571f5f8-af89-4b50-90b8-b5dadd6c7e3b
01-20 15:23:19.894 10841-10841/{PACKAGE_NAME} D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Auto-detected MIME type for /storage/emulated/0/Android/data/{PACKAGE_NAME}/tmp/1484911399805 is: application/octet-stream
01-20 15:23:19.894 10841-10841/{PACKAGE_NAME} D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Using custom file name: 677_1.jpg
01-20 15:23:19.904 10841-10841/{PACKAGE_NAME} I/UploadService: UploadService - Starting service with namespace: {PACKAGE_NAME}, upload pool size: 4, 1s idle thread keep alive time. Foreground execution is enabled
01-20 15:23:19.914 10841-10841/{PACKAGE_NAME} D/UploadService: UploadService - Successfully created new task with class: net.gotev.uploadservice.MultipartUploadTask
01-20 15:23:19.914 10841-15392/{PACKAGE_NAME} D/UploadService: HttpUploadTask - Starting upload task with ID 1571f5f8-af89-4b50-90b8-b5dadd6c7e3b
01-20 15:23:19.914 10841-15392/{PACKAGE_NAME} D/UploadService: OkHttpStackConnection - creating new connection
01-20 15:23:20.114 10841-15392/{PACKAGE_NAME} D/UploadService: UploadTask - Broadcasting upload progress for 1571f5f8-af89-4b50-90b8-b5dadd6c7e3b: 155 bytes of 97913
01-20 15:23:20.715 10841-15392/{PACKAGE_NAME} D/UploadService: HttpUploadTask - Server responded with HTTP 200 to upload with ID: 1571f5f8-af89-4b50-90b8-b5dadd6c7e3b
01-20 15:23:20.715 10841-15392/{PACKAGE_NAME} D/UploadService: UploadTask - Broadcasting upload completed for 1571f5f8-af89-4b50-90b8-b5dadd6c7e3b
01-20 15:23:20.715 10841-10841/{PACKAGE_NAME} D/UploadService: UploadRequest - null or empty upload ID. Generating it
01-20 15:23:20.725 10841-10841/{PACKAGE_NAME} D/UploadService: UploadRequest - Created new upload request to http://example.com/uploadFile with ID: b91c2471-a994-48b4-a2c6-6d579954b953
01-20 15:23:20.735 10841-10841/{PACKAGE_NAME} D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Auto-detected MIME type for /storage/emulated/0/Pictures/{PACKAGE_NAME}/VID_2017_01_05_15_52_53.mp4 is: video/mp4
01-20 15:23:20.735 10841-10841/{PACKAGE_NAME} D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Using custom file name: 677_2.mp4
01-20 15:23:20.765 10841-15392/{PACKAGE_NAME} D/UploadService: UploadService - All tasks finished. UploadService is about to shutdown...
01-20 15:23:20.775 10841-15392/{PACKAGE_NAME} D/UploadService: OkHttpStackConnection - closing connection
01-20 15:23:20.815 10841-10841/{PACKAGE_NAME} I/UploadService: UploadService - Starting service with namespace: {PACKAGE_NAME}, upload pool size: 4, 1s idle thread keep alive time. Foreground execution is enabled
01-20 15:23:20.825 10841-10841/{PACKAGE_NAME} D/UploadService: UploadService - Successfully created new task with class: net.gotev.uploadservice.MultipartUploadTask
01-20 15:23:20.835 10841-10841/{PACKAGE_NAME} D/UploadService: UploadService - Stopping foreground execution
01-20 15:23:20.835 10841-10841/{PACKAGE_NAME} D/UploadService: UploadService - UploadService destroyed
01-20 15:23:20.855 10841-15417/{PACKAGE_NAME} D/UploadService: UploadService - b91c2471-a994-48b4-a2c6-6d579954b953 now holds the foreground notification
01-20 15:23:20.855 10841-10841/{PACKAGE_NAME} E/ViewRootImpl: sendUserActionEvent() mView == null
01-20 15:23:20.865 10841-14539/{PACKAGE_NAME} V/FA: Recording user engagement, ms: 4341
01-20 15:23:20.865 10841-14539/{PACKAGE_NAME} D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=4341, _sc=AddNewsActivity, _si=-4456511121292222203}]
01-20 15:23:20.875 10841-15417/{PACKAGE_NAME} D/UploadService: UploadTask - Broadcasting cancellation for upload with ID: b91c2471-a994-48b4-a2c6-6d579954b953
01-20 15:23:20.885 10841-15417/{PACKAGE_NAME} D/RingtoneManager: getActualDefaultRingtoneUri  type    :2
01-20 15:23:20.885 10841-15417/{PACKAGE_NAME} D/RingtoneManager: checkDefaultRingtoneProperUri : InternalMediaAudio uriString not null    type:2
01-20 15:23:20.895 10841-15417/{PACKAGE_NAME} D/UploadService: UploadService - All tasks finished. UploadService is about to shutdown...
01-20 15:23:20.955 10841-14539/{PACKAGE_NAME} V/FA: Activity paused, time: 3143786
01-20 15:23:20.965 10841-14539/{PACKAGE_NAME} V/FA: Activity resumed, time: 3143813
01-20 15:23:25.970 10841-14539/{PACKAGE_NAME} V/FA: Inactivity, disconnecting from the service
```

### Additional info
In logcat you will see two upload tasks, first one uploads image and onCompleted() upload video file.
For image upload I'm not using notification configuration, only for video upload, be cause it may take longer. Above request example for video file upload.
Issue is not permanent. Also, as you can see from logcat there is no any error message there. Delegate onError() not calling.

**Comment by gotev** [comment]
What do you mean by "issue is not permanent"? 
From the log I can see that the first upload is completed successfully, so you should see the upload successful notification. The second upload is cancelled, so the `onCancelled` delegate method will be called and you should see the error notification. I don't see anything strange here.

Just two notes. You can write the code like this by using the supported builder pattern:
```java
notificationConfig.setIcon(R.mipmap.ic_launcher)
                  .setTitle(context.getString(R.string.app_name))
                  .setInProgressMessage(context.getString(R.string.uploading))
                  .setCompletedIcon(R.mipmap.ic_launcher)
                  .setCompletedMessage(context.getString(R.string.uploaded))
                  .setErrorIcon(R.mipmap.ic_launcher);
```
```java
new MultipartUploadRequest(context, Constants.BASE_URL + "/uploadFile")
    .addFileToUpload(fileUri.getPath(), "file", fileName)
    .setNotificationConfig(notificationConfig)
    .setMaxRetries(10)
    .setDelegate(delegate)
    .startUpload();
```

**Comment by vgevorgyan** [comment]
Hi,

I have fixed my issue by adding delay between first and second uploads.
In first upload onCompleted, I wait one second then start second upload, and problem was gone.

I have debug code, but couldn't understood why it was cancel the second upload.

Non-permanent means, it is not happening every time.

Regards

**Comment by gotev** [comment]
@vgevorgyan this is really strange, because it shouldn't happen. I've tried to make multiple requests at the same time, but no upload gets cancelled automatically like in your log. If you could provide a snippet (or a demo app) with which this happens systematically, feel free to re-open the issue and post everything here, so I could replicate it and solve it. Thank you!

**Comment by mbernier85** [comment]
hi @gotev 
I got the same issue as above. 
From what I understand of the error, when you start a new upload in the onCompleted method, the cancel service message is sent, and it seems to cancel the old upload that was completed but also the new upload that is currently in progress.

`
02-27 17:58:37.411 16668-16668/packageName D/UploadService: UploadRequest - null or empty upload ID. Generating it
02-27 17:58:37.411 16668-16668/packageName D/UploadService: UploadRequest - Created new upload request to https://example.com/upload-photo with ID: 15aeb0a5-715d-4513-af76-af4f09908ce3
02-27 17:58:37.421 16668-16668/packageName D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Auto-detected MIME type for /storage/emulated/0/DCIM/9fca8e70dccc11e6bf0525aa8ba682ea_77791.jpg.jpg is: image/jpeg
02-27 17:58:37.422 16668-16668/packageName D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Using original file name: 9fca8e70dccc11e6bf0525aa8ba682ea_77791.jpg.jpg
02-27 17:58:37.503 16668-16668/packageName I/UploadService: UploadService - Starting service with namespace: packageName, upload pool size: 8, 1s idle thread keep alive time. Foreground execution is enabled
02-27 17:58:37.512 16668-16668/packageName D/UploadService: UploadService - Successfully created new task with class: net.gotev.uploadservice.MultipartUploadTask
02-27 17:58:37.518 16668-17457/packageName D/UploadService: UploadService - 15aeb0a5-715d-4513-af76-af4f09908ce3 now holds the foreground notification
02-27 17:58:37.522 16668-17457/packageName D/UploadService: HttpUploadTask - Starting upload task with ID 15aeb0a5-715d-4513-af76-af4f09908ce3
02-27 17:58:37.526 16668-17457/packageName D/UploadService: OkHttpStackConnection - creating new connection
02-27 17:58:37.531 16668-17457/packageName D/OkHttp: Content-Type: multipart/form-data; boundary=-------AndroidUploadService1488236317512
02-27 17:58:37.653 16668-17457/packageName D/UploadService: UploadTask - Broadcasting upload progress for 15aeb0a5-715d-4513-af76-af4f09908ce3: 129 bytes of 1400143
02-27 17:58:37.819 16668-17457/packageName D/UploadService: UploadTask - Broadcasting upload progress for 15aeb0a5-715d-4513-af76-af4f09908ce3: 651671 bytes of 1400143
02-27 17:58:38.133 16668-17457/packageName D/UploadService: HttpUploadTask - Server responded with HTTP 200 to upload with ID: 15aeb0a5-715d-4513-af76-af4f09908ce3
02-27 17:58:38.133 16668-17457/packageName D/UploadService: UploadTask - Broadcasting upload completed for 15aeb0a5-715d-4513-af76-af4f09908ce3
02-27 17:58:38.136 16668-16668/packageName D/UploadService: UploadRequest - null or empty upload ID. Generating it
02-27 17:58:38.137 16668-16668/packageName D/UploadService: UploadRequest - Created new upload request to https://example.com/upload-photo with ID: 8ca47cdd-dab6-4fe6-a770-c70d3d80cf97
02-27 17:58:38.137 16668-16668/packageName D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Auto-detected MIME type for /storage/emulated/0/DCIM/9fca8e70dccc11e6bf0525aa8ba682ea_32211.jpg.jpg is: image/jpeg
02-27 17:58:38.137 16668-16668/packageName D/UploadService: net.gotev.uploadservice.MultipartUploadRequest - Using original file name: 9fca8e70dccc11e6bf0525aa8ba682ea_32211.jpg.jpg
02-27 17:58:38.140 16668-17457/packageName D/UploadService: UploadService - 15aeb0a5-715d-4513-af76-af4f09908ce3 now un-holded the foreground notification
02-27 17:58:38.140 16668-17457/packageName D/UploadService: UploadService - All tasks finished. UploadService is about to shutdown...
02-27 17:58:38.141 16668-17457/packageName D/UploadService: OkHttpStackConnection - closing connection
02-27 17:58:38.141 16668-16668/packageName I/UploadService: UploadService - Starting service with namespace: packageName, upload pool size: 8, 1s idle thread keep alive time. Foreground execution is enabled
02-27 17:58:38.144 16668-16668/packageName D/UploadService: UploadService - Successfully created new task with class: net.gotev.uploadservice.MultipartUploadTask
02-27 17:58:38.145 16668-16668/packageName D/UploadService: UploadService - Stopping foreground execution
02-27 17:58:38.148 16668-16668/packageName D/UploadService: UploadService - UploadService destroyed
02-27 17:58:38.150 16668-17469/packageName D/UploadService: UploadService - 8ca47cdd-dab6-4fe6-a770-c70d3d80cf97 now holds the foreground notification
02-27 17:58:38.153 16668-17469/packageName D/UploadService: UploadTask - Broadcasting cancellation for upload with ID: 8ca47cdd-dab6-4fe6-a770-c70d3d80cf97
02-27 17:58:38.161 16668-17469/packageName D/UploadService: UploadService - All tasks finished. UploadService is about to shutdown...
`

**Comment by gotev** [comment]
Tried to replicate with this code, which gets invoked inside a button's `OnClick` listener, but everything works as expected, even when pressing the button many times in a row:
```java
private void multipleRequests() {
    final String endpoint = "http://posttestserver.com/post.php";
    final int maxRetries = 2;

    try {
        new MultipartUploadRequest(this, endpoint)
                .setMethod("POST")
                .setNotificationConfig(new UploadNotificationConfig().setAutoClearOnSuccess(true))
                .addParameter("color", "#ffffff")
                .setMaxRetries(maxRetries)
                .setDelegate(new UploadStatusDelegate() {
                    @Override
                    public void onProgress(Context context, UploadInfo uploadInfo) {

                    }

                    @Override
                    public void onError(Context context, UploadInfo uploadInfo, Exception exception) {

                    }

                    @Override
                    public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
                        try {
                            new MultipartUploadRequest(MainActivity.this, endpoint)
                                    .setMethod("POST")
                                    .setNotificationConfig(new UploadNotificationConfig().setAutoClearOnSuccess(true))
                                    .addParameter("color", "#ffffff")
                                    .addParameter("test", "value")
                                    .addParameter("new", "parameter")
                                    .setMaxRetries(maxRetries)
                                    .startUpload();
                        } catch (Exception exc) {
                            Log.e(getClass().getSimpleName(), "second request error", exc);
                        }
                    }

                    @Override
                    public void onCancelled(Context context, UploadInfo uploadInfo) {

                    }
                })
                .startUpload();
    } catch (Exception exc) {
        Log.e(getClass().getSimpleName(), "multipleRequests Error", exc);
    }
}
```
@mbernier85 is it similar to your code which has the issue?

**Comment by gotev** [comment]
with the last commit, the issue should be fixed, as by running it in the demo app, no more requests are being cancelled. The problem was [here](https://github.com/gotev/android-upload-service/commit/3e2afd0a38a94b9e98d8c41b088576904348ef50#diff-f0fbcc8d8677824dae1f58e2469c0468L343) because after a task was completed, a check was made to see if there were other running tasks, and if not, the service was shut down. This woudn't let child requests to run, because of the following sequence of operations which happened:
```
request completed -> fire onCompleted event
no more running tasks? begin service shutdown
new request started from onCompleted callback
the service performs shutdown operations (see UploadService onDestroy), 
    which in turn cancels all the running tasks -> fire onCancelled event
stop the service
```
So, the service's auto-shutdown strategy should be re-thinked
