### ISSUE TITLE
Add Doze support

### ISSUE THREAD

**Issue by ianschmitz** [gotev/android-upload-service#227]
Doze mode in some cases will override partial wake locks/network requests and enter Doze even when the service performing the network request is running in a foreground service. Specifically a foreground service can enter Doze mode if the activity is also in the foreground.

You can read about this issue:
https://code.google.com/p/android/issues/detail?id=193802#c14
and
https://commonsware.com/blog/2015/11/18/another-doze-edge-case-foreground.html

Sounds like Google's recommendation is to run the foreground service in a different process. There is an exhaustive thread discussing the issue in detail at https://plus.google.com/+AndroidDevelopers/posts/94jCkmG4jff. Specifically the posts by Dianne Hackborn.

**Comment by ianschmitz** [comment]
There may be some caveats to running in a different process depending on the implementation in this repo. Some mentioned in the google issue at https://code.google.com/p/android/issues/detail?id=193802#c14:

1) Since the service is in a different process, you wont' be able to stop on any debugger breakpoints in the service until you have Android Studio switch over to or attach to this other process.
2) If you've been using local `BroadcastReceiver` via `LocalBroadcastManager` for communication between your app UI and the foreground service, you'll need to switch to full a `BroadcastReceiver` because you're now into the realm of inter-process communication.
3) `SharedPreferences` won't work correctly in multi-process so you need to use a content provider or other way how to make you processes communicate.

**Comment by gotev** [comment]
I think the library already has all the needed prerequisites to run in a separate process

1. Android Studio is used for library development. By enabling library debug log, many things can be spotted without using a debugger at all.
2. The library does not use `LocalBroadcastManager` but already sends global broadcasts and the receiver implementation is based on `BroadcastReceiver`.
3. The library does not use `SharedPreferences`. It only has in-memory state. Task, queue or state management outside the memory is up to the library user on purpose, to be as generic an indipendent as possible.

If you want to start making tests, you can fork the library and safely add the `android:process=":uploadservice"` attribute in the manifest. The two semicolons at the beginning of the name indicates that the new process is private to the app which created it, which is what we want.

You can use the provided demo app in the examples directory, which is already linked to the local project to make tests.

**Comment by gotev** [comment]
[Here](https://developer.android.com/training/monitoring-device-state/doze-standby.html) there is some useful information about Doze and how to test it. Reporting testing here.

### Testing your app with Doze

You can test Doze mode by following these steps:

1. Configure a hardware device or virtual device with an Android 6.0 (API level 23) or higher system image.
2. Connect the device to your development machine and install your app.
3. Run your app and leave it active.
4. Force the system into idle mode by running the following command:
```shell
    $ adb shell dumpsys deviceidle force-idle
```
5. Observe the behavior of your app after you reactivate the device. Make sure the app recovers gracefully when the device exits Doze.

### Testing your app with App Standby

To test the App Standby mode with your app:

1. Configure a hardware device or virtual device with an Android 6.0 (API level 23) or higher system image.
2. Connect the device to your development machine and install your app.
3. Run your app and leave it active.
4. Force the app into App Standby mode by running the following commands:
```shell
    $ adb shell dumpsys battery unplug
    $ adb shell am set-inactive <packageName> true
```
5. Simulate waking your app using the following commands:
```shell
    $ adb shell am set-inactive <packageName> false
    $ adb shell am get-inactive <packageName>
```
6. Observe the behavior of your app after waking it. Make sure the app recovers gracefully from standby mode. In particular, you should check if your app's Notifications and background jobs continue to function as expected.

**Comment by ianschmitz** [comment]
Most likely won't have the capacity to do this for the next little while. Is there someone else that can take this on?

**Comment by gotev** [comment]
After some tests on an Android emulator (qemu) and on a Nexus 5X with Android 7.1.2 (API 25) with the following procedures, Doze does not seem to affect foreground uploads in current 3.2.x UploadService:

## Prerequisites
1. Running demo server provided in the examples
2. Running demo app provided in the examples on a device or virtual device connected to adb and Android Studio's LogCat
3. Terminal open in the `utils/doze-test` directory (it requires adb to be in the PATH of your system)

## Doze
1. Open the demo app
2. Select a large file (>= 50 MB) and upload it with a multipart upload
3. Using scripts in `utils/doze-test`, execute `./doze-enable`
4. Check adb log to see if the upload continues
5. If it continues after some time, execute `./doze-disable`

## App standby
1. Open the demo app
2. Select a large file (>= 50 MB) and upload it with a multipart upload
3. Using scripts in `utils/doze-test`, execute `./app-standby-enable`
4. Check adb log to see if the upload continues
5. If it continues after some time, execute `./app-standby-disable`

So, after those tests, it seems Doze mode is fully supported. If you have a device on which is not working, reopen the issue and provide as many details as you can to replicate the scenario.
