### ISSUE TITLE
Explicitly create instances of FileSchemeHandler and ContentSchemeHandler

### ISSUE THREAD

**Issue by ianschmitz** [gotev/android-upload-service#228]
Currently the `SchemeHandlerFactory.get()` method returns an instance of either `FileSchemeHandler` or `ContentSchemeHandler` depending on the value of the `path` param. However the instance returned is created using `getDeclaredInstructor` which isn't an explicit reference to the constructor method.

The lack of an explicit reference causes the constructors to be stripped from both `FileSchemeHandler` and `ContentSchemeHandler` during release builds of a Xamarin Android project when using this library from a Xamarin Android Binding library. Presumably, the Xamarin Android project appears to strip the constructors out since during some form of static analysis it deems it not to be used.

I confirmed the issue to be resolved when referencing the constructors directly. I changed the source for `ContentSchemeHandler.get()` to the following, which solved the issue:

```java
    public SchemeHandler get(String path) throws FileNotFoundException {
        if (path.startsWith("/")) {
            return new FileSchemeHandler(path);
        }

        if (path.startsWith("content://")) {
            return new ContentSchemeHandler(path);
        }

        throw new UnsupportedOperationException("No handlers for " + path);
    }
```

**Comment by gotev** [comment]
> The lack of an explicit reference causes the constructors to be stripped from both FileSchemeHandler and ContentSchemeHandler during release builds of a Xamarin Android project when using this library from a Xamarin Android Binding library.

I don't know Xamarin.Android but maybe it uses ProGuard or something similar. At that point in the code, Java Reflection is used. Since the constructors are not public, they are stripped down and you get the exception. Is there a way in Xamarin to add exceptions or `keepClass` attributes like in ProGuard on Android? I think it's the better option, because I would keep the implementation as it is now by using reflection, which makes extensions easier and reduces boilerplate code.

**Comment by ianschmitz** [comment]
There are exceptions that you can use in the Android binding library to control classes/fields/methods/etc. The method isn't stripped at this layer in the build process. It is stripped during the build of the Android app project. The method is actually removed from the `classes.dex` when being copied from the binding library. There aren't any ways i have found to control that specific behavior. 

Disabling linking on the app project unfortunately doesn't have an effect on this issue. Seems specific to `Debug` vs `Release` build configuration.

**Comment by gotev** [comment]
Reflection is also used in [task creation](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadService.java#L288), but in that case classes and the constructors are all public, and you don't have issues there. Maybe Xamarin simply strips down everything non public.

**Comment by ianschmitz** [comment]
Agreed that the public vs private definitely has an effect. Logically I can see their reasoning for stripping it. It is indeed a private class/constructor, and nobody internally in the package references the constructor. The `SchemeHandler` interface is public, so the remaining methods besides constructor are left in the resulting dex bundle.

I have confirmed that other private fields/methods aren't stripped, but they were explicitly referenced in the package.

**Comment by gotev** [comment]
made constructors public and changed the reflection method used. Tried on Android and it works. Please try and check if you still have the runtime error in Xamarin Android

**Comment by ianschmitz** [comment]
Just grabbed the latest from master with your included changes. Still observing the constructor removed in the generated classes.dex

![image](https://cloud.githubusercontent.com/assets/6355370/22169452/0d203818-df29-11e6-92b6-8b5e28045f69.png)

**Comment by gotev** [comment]
@ianschmitz thank you! I've changed the reflection pattern used in SchemeHandlers, so a custom constructor is not needed anymore. I think it should be fine now.

I've seen that Xamarin uses NuGet for dependency management. It will be fantastic to have Android Upload Service published there. Do you know how to do it and if it's possible to automate it? All I need is a command line script (+ a bunch of other files if needed) which builds the library bindings for Xamarin Android and then publishes them to NuGet. This way everytime I make a new release, it will be available also on NuGet.

**Comment by ianschmitz** [comment]
Looks good.

I don't have any experience publishing Android binding libraries to NuGet unfortunately. It would likely involve building a test suite to test the API surface of the generated C# wrapper. I just noticed that a recent commit changing the inheritance structure of MultipartUploadRequest (https://github.com/gotev/android-upload-service/commit/41994edbb565a16593f0e26ccb19c0f80c316222#diff-ed86f756af0dc22f04c2f52c6d6b5753) broke some of the method return types in the C# wrapper. It seems like the whole thing can be pretty brittle depending on how you structure your Java code.

**Comment by gotev** [comment]
@ianschmitz yes, but were you able to do the bindings again without problems after that change? What I've used is simply Java Generics.

**Comment by ianschmitz** [comment]
The changes made by https://github.com/gotev/android-upload-service/commit/80f425610ea2a12830c8e32804a3d6ae2928936f appeared to fix the issue with the missing methods in the `classes.dex`. Applying just those changes worked fine.

Pulling the latest from master including the changes to inheritance created a broken C# wrapper. Specifically methods like `HttpUploadRequest.AddHeader()` now return `Java.Lang.Object` instead of `HttpUploadRequest` like they did before the changes. So i can no longer link together the method calls like i was previously:

```java
string uploadId = new MultipartUploadRequest(Application.Context, ApiClient.GetMediaUploadEndpointUrl(audioData, sendEmail))
                .AddFileToUpload(FileSystem.GetAudioStorageFilePath(audioData.FileName), "contentFile", "Audio_Recording.m4a", "audio/mp4")
                .AddHeader("Cookie", cookieHeaderValue)
                .SetNotificationConfig(notificationConfig)
                .SetMaxRetries(3)
                .StartUpload();
```

**Comment by gotev** [comment]
Some research is needed on this, because from your report it seems Xamarin bindings have serious trouble in mapping Java Generics, which I've introduced to ease the native Android development of the library

**Comment by ianschmitz** [comment]
Agreed. May not be worth your time to try to support a Xamarin binding as it could make you much less flexible/agile with your development on this library.

A quote from https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/troubleshooting-bindings/

> Binding an Android library (an .aar or a .jar) file is seldom a straightforward affair; it usually requires additional effort to mitigate issues that result from the differences between Java and .NET. These issues will prevent Xamarin.Android from binding the Android library and present themselves as error messages in the build log.

**Comment by gotev** [comment]
http://stackoverflow.com/questions/36533263/xamarin-android-binding-to-java-type-which-inherits-generic-type

**Comment by gotev** [comment]
I think it would be nice to support also Xamarin.Android, because not so many libraries out there are supported out of the box. Do this work?
```java
MultipartUploadRequest request = new MultipartUploadRequest(Application.Context,
                ApiClient.GetMediaUploadEndpointUrl(audioData, sendEmail));

request.AddFileToUpload(FileSystem.GetAudioStorageFilePath(audioData.FileName),
                        "contentFile", "Audio_Recording.m4a", "audio/mp4");
request.AddHeader("Cookie", cookieHeaderValue);
request.SetNotificationConfig(notificationConfig);
request.SetMaxRetries(3);

string uploadId = request.StartUpload();
```
If it works, it's certainly less elegant, but requires zero effort to bind it and you can easily use the library in Xamarin. Then, to make it elegant again, it would be sufficient to extend `MultipartUploadRequest` in pure C# (e.g. `CMultipartUploadRequest`)  and override all the methods so you can use the builder pattern again:
```java
string uploadId = new CMultipartUploadRequest(Application.Context, ApiClient.GetMediaUploadEndpointUrl(audioData, sendEmail))
                .AddFileToUpload(FileSystem.GetAudioStorageFilePath(audioData.FileName), "contentFile", "Audio_Recording.m4a", "audio/mp4")
                .AddHeader("Cookie", cookieHeaderValue)
                .SetNotificationConfig(notificationConfig)
                .SetMaxRetries(3)
                .StartUpload();
```
The library supports `MultipartUploadRequest` and `BinaryUploadRequest` in the core, plus `FTPUploadRequest` with a plugin module, which can be binded to C# the same way. What do you think about this?

**Comment by ianschmitz** [comment]
Yes referencing the `MultipartUploadRequest` when calling the methods works just fine.

The binding library supports ways to transform the output of the C# wrapper. So an example would be transforming the return type of `HttpUploadRequest.

There's more information here: https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/customizing-bindings/java-bindings-metadata/
