### ISSUE TITLE
No option to upload only extra parameters using Multipart entities

### ISSUE THREAD

**Issue by hak-tpl** [gotev/android-upload-service#232]
HI,

In my scenario the files are not the mandatory element for uploading data on server. Whenever I try to upload data I get an exception stating that I should add atleast one File to upload. Is there any option so that I can disable this check?

Thanks

**Comment by gotev** [comment]
Multipart protocol is used when you have both files and parameters. If you have only parameters, you needn't a multipart request, but a simple POST request. Upload Service request builders does the linting and launches an exception if no file is provided.

**Comment by gotev** [comment]
#244 makes this possible
