### ISSUE TITLE
How to check FileName in onCompleted method

### ISSUE THREAD

**Issue by Bekakk** [gotev/android-upload-service#239]
Hi
I'm using your library to upload files in my server with FTP.Everything working perfect,but I have one two questions.
1)Is it a possible to check upload file name in onCompleted method?
2) Is it a possible to file upload limit in your library?
Thanks

**Comment by gotev** [comment]
1. In the UploadInfo you have the list of the successfully uploaded files
2. You mean limiting the upload bandwidth?

**Comment by Bekakk** [comment]
1)For example,I uploaded myfirst.zip file successfully,How I can get my file name in  onCompleted method? can you show me code?
2) Yes,You are right.

**Comment by gotev** [comment]
```java
List<String> files = uploadInfo.getSuccessfullyUploadedFiles();
for (String file : files) {
    //Do something with each file
}
```
You can see this in action in the demo app as well.

At the moment, there's no way to implement client side rate limiting for the uploads. Do you have an idea on how to do it?

**Comment by Bekakk** [comment]
unfortunately i don't.
Thanks your attention
