### ISSUE TITLE
java.lang.NoSuchMethodException release build with proguard

### ISSUE THREAD

**Issue by Shakezulla57** [gotev/android-upload-service#240]
Similar to #216

Using `net.gotev:uploadservice:3.1`

Everything works fine when not minifying for release. Is there anything that I may need to include in my proguard file.

Here's what I currently have

```
-keep public class net.gotev.uploadservice.** {
  public protected *;
}
```

**Comment by gotev** [comment]
try with:
```java
-keep class net.gotev.uploadservice.** { *; }
```

**Comment by BobCat931** [comment]
Experienced same issue after updating to 3.1 - worked after adding that line to my proguard file. Thanks

**Comment by gotev** [comment]
@BobCat931 thanks for the feedback. Added to https://github.com/gotev/android-upload-service/wiki/Advanced-topics

**Comment by Shakezulla57** [comment]
Yep this worked. Sorry for the late follow up.

**Comment by ivujosevic** [comment]
@gotev Even `-keep class net.gotev.uploadservice.schemehandlers.** { *; }` is more than enough.

Setting `-keep class net.gotev.uploadservice.** { *; }` excludes the whole library from ProGuard processing which is unnecessary and defies the sole purpose of ProGuard.

I excluded the whole `schemehandlers` package as I didn't have time to find the exact class or method that makes the problem, but I'm sure that even that excludes more than necessary.

**Comment by gotev** [comment]
> Setting -keep class net.gotev.uploadservice.** { *; } excludes the whole library from ProGuard processing which is unnecessary and defies the sole purpose of ProGuard.

I know. What methods and classes to keep depends on which features of the library are you using, so providing a ProGuard configuration which is suitable for all the scenarios is not possible. Thank you for your feedback, using `-keep class net.gotev.uploadservice.schemehandlers.** { *; }` can certainly be a better fit in most of the cases and can help reduce methods.

**Comment by gotev** [comment]
Improved [wiki](https://github.com/gotev/android-upload-service/wiki/Advanced-topics#proguard)
