### ISSUE TITLE
Multiple File Upload Notification

### ISSUE THREAD

**Issue by markusf** [gotev/android-upload-service#243]
Hey,

is there a way to show a notification, which is handling the total progress for multiple file upload (using multiple requests) out of the box?

Best regards

**Comment by gotev** [comment]
I'd love to see a PR with that feature!

**Comment by mostafaspace** [comment]
Hello,

In the topic of Multiple File Upload Notifiation, I've been trying to reach a notification like this:
http://i.imgur.com/bsV3rRd.png

Is this is possible with the current notification config or It can't be done?

Thanks.

**Comment by gotev** [comment]
yes, a multipart upload request with threee files

**Comment by mostafaspace** [comment]
Thanks so much for you answer,

Can you tell me where to look about making 1 by 1 progress? 

And is this what you mean?
`
                for (String photo : selectedPhotos){
                    uploadRequest.addFileToUpload(photo, "image[]");
                }
`

Thanks.

**Comment by gotev** [comment]
You can use placeholders in notification messages. https://github.com/gotev/android-upload-service/wiki/Recipes#notification-configuration

**Comment by gotev** [comment]
And yes, you can add multiple files like that

**Comment by mostafaspace** [comment]
Hello, 
Thank you so much.

I tried it and its ok, but I find it difficult to track upload errors, Tried to get callbacks from server and then update the notification error, but it didn't work as I need it to. So I just added the whole request in the for loop and send 1 request for each image, this way I get single notification for each image for failed messages.. 

One other thing, in the `image[]` way , the progress bar is combining the whole request, not uploading them 1 by 1. What I had in mind was a progress bar for each uploaded file, and only if failed it gets own notification with the file name and the reason.

Thank you for your great work ;)

**Comment by gotev** [comment]
So, you need something a library doesn't support yet: multiple parallel multipart requests which has to be aggregated on a single notification, but with separate error handlers for each upload. To support that, a library redesign may be needed and your help is greatly appreciated.

**Comment by mostafaspace** [comment]
I'm not really sure what to call it. But here I'll try to simplify what I mean:

-Send all photos in one request using `image[]`
-Upload each of them 1 by 1, but in one notification bar e.g. 1 of 3 (http://i.imgur.com/bsV3rRd.png) 
-Each photo of them has its own progress bar and error callback
-If has error, show the error and  file name in a new notification

I think i reached that but without the "one request" or "error callbacks" part.
http://i.imgur.com/LCodsGW.png
For now I added `.setAutoClearOnSuccess(true)` to leave only the errors, and I have only mime-type and file-size checks, so I just wrote the "might" be too large error and Photopicker. but in case there is more checks, it needs to read from a server callback better.

Overall, it works fine, It just needed to be more accurate for the user to know the exact error and the file name so he can take the needed action.

Thank you so much

**Comment by gotev** [comment]
if you send all the images in a single request, you can't make 1 by 1 uploads, because all the files are added in the same request. That's how multipart works. Also, since the multipart request is not resumable, if at some point the upload fails, you have to start over from the beginning. To make 1 by 1 uploads you will have to make N Multipart requests and handle each one of them separately.

If you want to have N multipart requests, but see their progress in a single notification with overall progress, it has to be implemented.

Being said that, if you have a single multipart request, you can display the total number of files and the uploaded files with the following upload notification config:
```java
protected UploadNotificationConfig getNotificationConfig() {
    return new UploadNotificationConfig()
            .setInProgressMessage(Placeholders.UPLOADED_FILES + " of " + 
                                  Placeholders.TOTAL_FILES + ". Speed: " + 
                                  Placeholders.UPLOAD_RATE)
            .setCompletedMessage("upload completed")
            .setErrorMessage("error while uploading files")
            .setCancelledMessage("upload aborted")
            .setRingToneEnabled(true);
}
```

> in case there is more checks, it needs to read from a server callback better.

What do you mean by `read from a server callback better`?

From my point of view, the better choice for more complex use cases is to use the broadcast receivers, either globally or inside an activity, depending on your use case. Both are documented [here](https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status). You can have whatever checks you need in the `onCompleted` where you have the HTTP status and response body from the server.

**Comment by mostafaspace** [comment]
I get what you mean, so lets forget about the `image[]` and send one photo per request.

What I mean by _read from server callbacks_ is each request does send a callback in the `onCompleted` but in case there is an error, can you update the notification error to be the message of  `onCompleted`?

**Comment by gotev** [comment]
@mostafaspace maybe #259 addresses exactly what you need

**Comment by azizarc88** [comment]
Hello,

Can you please help me..?
i just try your library using MultipartUploadRequest
but i got an error, it say

`java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.sigapp.id-2/base.apk)`

and i using com.android.support:support-v4:25.+

Thanks before.

**Comment by gotev** [comment]
@azozarc88 open a new issue instead of poating here, thanks

**Comment by zoptaltechnical** [comment]
I am unable to upload multiple files due to lack of code example , Please provide complete code to upload multiple files, Correct me if i have missed anything , Thanks

**Comment by PhilLab** [comment]
@zoptaltechnical This is the code example you are looking for: https://github.com/gotev/android-upload-service/wiki/Recipes#multipart . Just call``addFileToUpload()`` multiple times. Please don't use this issue for further questions as it is about a (slightly) different feature

**Comment by PhilLab** [comment]
@gotev Do you have plans for the 
> multiple parallel multipart requests which has to be aggregated on a single notification
right now or would this be something open for community contributions?
You said this would need a library redesign - will this feature really mean widespread code changes?

**Comment by gotev** [comment]
Unfortunately I don't have plans to do it myself due to lack of time, but contributions are always welcome, so feel free to make your own implementation and send a PR

**Comment by ChadhaAashish** [comment]
My api is giving me success code 200 but the request is failed 
Any idea how to handle it?

Because onProgress is changing the status of notification bar and not the onError or onCompleted

**Comment by gotev** [comment]
Closing this due to lack of contributions so far. Feel free to reopen it if you have a PR ;)

**Comment by PhilLab** [comment]
@gotev is this something which is contained in / easier to solve in UploadService 4?

**Comment by gotev** [comment]
@PhilLab Yes! It's out of the box 🎉  https://github.com/gotev/android-upload-service/wiki/Configuration#notification-handler

**Comment by PhilLab** [comment]
@gotev This are very good news, thanks for the effort you put in 👍 We will start moving from version 3 to 4, I guess 😄

**Comment by gotev** [comment]
@PhilLab it's been a lot of work, but the library needed to be modernized from the ground up. Everything is new down below. It will be interesting if you documented the process and then we can include it in the Wiki (or a Medium article if you prefer) as a concrete real world migration example. Bear in Mind 4.x has [minAPI 21 and other breaking changes](https://github.com/gotev/android-upload-service/issues/450) but it's definitely worth it from every point of view when compared to 3.x
