### ISSUE TITLE
How to change the encoding of UploadFile ?

### ISSUE THREAD

**Issue by fishwjy** [gotev/android-upload-service#249]
I want to use UTF-8 for file name. But I didn't find the function to realize it.

/**
     * Gets the HTTP/Multipart header for this file.
     * @return multipart header bytes
     * @throws UnsupportedEncodingException if the device does not support US-ASCII encoding
     */
    public byte[] getMultipartHeader() throws UnsupportedEncodingException {
        StringBuilder builder = new StringBuilder();

        builder.append("Content-Disposition: form-data; name=\"")
                .append(paramName).append("\"; filename=\"")
                .append(fileName).append("\"").append(NEW_LINE);

        builder.append("Content-Type: ").append(contentType).append(NEW_LINE).append(NEW_LINE);

        return builder.toString().getBytes("US-ASCII");
    }

I want to getBytes("UTF-8") at the final line. Btw, I'm using 2.0 version.

**Comment by gotev** [comment]
As reported in the recipes wiki, javadocs and [demo app for multipart upload request](https://github.com/gotev/android-upload-service/blob/master/examples/app/demoapp/src/main/java/net/gotev/uploadservicedemo/MultipartUploadActivity.java), just call `setUtf8Charset` method on the request builder.
