### ISSUE TITLE
No UploadNotificationConfig leads to NullPointerException 

### ISSUE THREAD

**Issue by fishwjy** [gotev/android-upload-service#251]
I don't want to display the notification when uploading the files.

I build a MultipartUploadRequest and don't set UploadNotificationConfig (Actually it's the same result when I set it to null ). There will be a NullPointerException produced when I cancel the request.

And I saw the code it's will be crash at line 346 of UploadTask.java. 
`final UploadNotificationConfig notificationConfig = params.getNotificationConfig();
 updateNotification(uploadInfo, notificationConfig.getCancelledMessage(),//notificationConfig will be null
notificationConfig.isAutoClearOnCancel(),notificationConfig.getCancelledIconResourceID(),notificationConfig.getCancelledIconColorResourceID())`

Temporary Solution:
I do this to avoid NullPointerException before this bug is fixed.
`UploadNotificationConfig config = new UploadNotificationConfig();
                config.setCancelledMessage(null);
                request.setNotificationConfig(config);`

**Comment by gotev** [comment]
With which version are you experiencing this problem?

**Comment by fishwjy** [comment]
compile 'net.gotev:uploadservice:3.2.1'
I use this version.

**Comment by gotev** [comment]
released 3.2.2 which fixes this issue
