### ISSUE TITLE
It's posible not add file to upload?

### ISSUE THREAD

**Issue by AlbertoMrFz** [gotev/android-upload-service#252]
Be sure to check [Asking for help](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help) page on the Wiki before opening a new issue! Delete this text when you create a new issue.

### Version info
* Android Upload Service version:
* Android version and API version: 21
* HTTP stack (e.g. HurlStack or OkHttpStack):

### What did you expect?
It's posible not add file to upload, only upload strings parameters?

### What happened instead?
java.lang.IllegalArgumentException: You have to add at least one file to upload

### Steps to reproduce (if applicable):
 new MultipartUploadRequest(context, uploadId, urlString)
                        .addParameter(nombreParametro, parametros) //Adding text parameter to the request
                        .setNotificationConfig(uploadConfig)
                        .setMaxRetries(2)
                        .startUpload(); //Starting the upload

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
This has been resolved in #244, which is part of 3.2 release. Just upgrade to the latest 3.2.2 release.
