### ISSUE TITLE
Error in version: 3.2.2

### ISSUE THREAD

**Issue by AlbertoMrFz** [gotev/android-upload-service#253]
Be sure to check [Asking for help](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help) page on the Wiki before opening a new issue! Delete this text when you create a new issue.

### Version info
* Android Upload Service version:
* Android version and API version: 19
* HTTP stack (e.g. HurlStack or OkHttpStack):

### What did you expect?
Icopy the code from this isue: [104](https://github.com/gotev/android-upload-service/issues/104)
### What happened instead?
And i have this error: method does not override or implement a method from a supertype

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ x ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)
#104

**Comment by gotev** [comment]
It's simply because the example you copied and pasted is really old and the public API of the broadcast receiver has been changed since then.
