### ISSUE TITLE
Permission WRITE_EXTERNAL_STORAGE should NOT be mandatory

### ISSUE THREAD

**Issue by kevinmeresse** [gotev/android-upload-service#254]
Hi, my uploads are failing because `android.permission.WRITE_EXTERNAL_STORAGE` is not granted. The thing is I don't need and don't want to force my users to grant that permission. My app is not asking to select files from the device, I'm generating them programmatically and storing them in the cache. I don't need the upload service to delete the uploaded files once it's successful as I'm handling it myself. Pleeeease remove that check!!!
It shouldn't be the library's responsibility. It's ok to try to delete the file, but it's also ok if it fails.
Thanks!!!

**Comment by gotev** [comment]
I agree with you. Haven't considered this use case when introduced that check.

**Comment by gotev** [comment]
released version 3.2.3 with the check removed

**Comment by keiferstone** [comment]
@gotev I know this is a very old closed issue, but the WRITE_EXTERNAL_STORAGE permission is still declared in AndroidManifest.xml, causing it to be pulled into my merged manifest.

This is causing an issue for us as Google Play is requiring developers to provide a valid explanation for declaring that permission as of May 5th. Apps may be subject to removal from Google Play for failing to provide a valid explanation. See https://developer.android.com/about/versions/11/privacy/storage?authuser=1#scoped-storage and https://support.google.com/googleplay/android-developer/answer/10467955?hl=en&ref_topic=2364761

This should be an easy, low-risk change as the usage of this permission was already removed on #255.
