### ISSUE TITLE
Create a service to upload file

### ISSUE THREAD

**Issue by judemanutd** [gotev/android-upload-service#256]
I read the documentation but got a little confused as there is a bit much information there.All i want to do is upload a file to the server and this should happen even if the user switches to another activity.Should i just create a service and put the code to upload in that or do i need something to do with the broadcast receivers?

**Comment by gotev** [comment]
Follow the setup instructions in the wiki, then go to recipes. Probabily you need a multipart upload. To monitor status, check the monitoring upload page.

**Comment by gotev** [comment]
You should use the broadcast receiver

**Comment by judemanutd** [comment]
@gotev i was a little confused about that.Should i create a class make it extend a service and then within that declare a broadcast receiver?So just 1 class in total?

**Comment by gotev** [comment]
Just invoke the multipart request from everwhere you have a context. This will launch the upload service, which will be executed eveb if the user goes away from the activity. To listen for the status, create a new broadcast receiver which extends the UploadServiceBroadcastReceiver, register it in your manifest and you're done. There are instructions in the monitoring wiki page. 

Any suggestions on how to improve the docs and make it more easily understandable?

**Comment by judemanutd** [comment]
@gotev sorry for the late reply.I think the docs are pretty understandable,me being an amateur is probably what made the process a little tedious but it think i got it now,thank you.

**Comment by amitsharma492** [comment]
How to Monitor the Status of uploading in MainActivity if Upload Service is Called from a class other than MainActivity?

**Comment by gotev** [comment]
Just check the monitoring wiki page and follow the instructions for a global broadcast receiver

**Comment by amitsharma492** [comment]
How Can I apply custom Intent Filter I don't want to monitor every upload but from some specific activity/service.
I am uploading Video from Different Class and Image from a different class, so I want to monitor only Video Upload not Image Upload.

**Comment by gotev** [comment]
You can specify custom uploadIDs. Just create a naming convention like: 

`"videoUpload-" + System.currentTimeMillis()`

And then you can differentiate uploads in delegates and broadcast receivers by matching uploadIDs starting with `videoUpload-` or whatever else you decide.
