### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Ric17101** [gotev/android-upload-service#257]
I want to ask if someone of you encountered this error during the test of the example project.

I have installed correctly and compiled the project,
I have input the correct parameters of my file to be passed on the server on the **MultipartUploadActivity**.

I am using codeigniter and xampp for the testing the API, is there some sort of configurations that I need to set on my server side in order to accept the request from this app? plz help, thank!

I used the delegates in order to see whats happening on the server side...

**THIS is the response I've got so far using delgates**
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
webmaster@mydomain.com and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>`

**FULL LOG:**
`03-20 17:04:35.023 9550-9695/net.gotev.uploadservicedemo D/OpenGLRenderer: endAllStagingAnimators on 0x7f66042b00 (RippleDrawable @29cd3fc6) with handle 0x7f77b09ba0
03-20 17:04:35.025 9550-10105/net.gotev.uploadservicedemo D/OkHttp: --> POST http://myAPI/servicejob_uploads http/1.1
03-20 17:04:35.027 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Content-Type: multipart/form-data; boundary=-------AndroidUploadService1490000674917
03-20 17:04:35.027 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Content-Length: 98710
03-20 17:04:35.027 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Connection: close
03-20 17:04:35.027 9550-10105/net.gotev.uploadservicedemo D/OkHttp: User-Agent: AndroidUploadService/3.2.3
03-20 17:04:35.028 9550-10105/net.gotev.uploadservicedemo D/OkHttp: --> END POST
03-20 17:04:35.044 9550-10105/net.gotev.uploadservicedemo I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
03-20 17:04:35.044 9550-10105/net.gotev.uploadservicedemo D/libc-netbsd: [getaddrinfo]: hostname=MYHOST.com; servname=(null); cache_mode=(null), netid=0; mark=0
03-20 17:04:35.044 9550-10105/net.gotev.uploadservicedemo D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
03-20 17:04:35.057 9550-10105/net.gotev.uploadservicedemo D/libc-netbsd: [getaddrinfo]: hostname=; servname=(null); cache_mode=(null), netid=0; mark=0
03-20 17:04:35.057 9550-10105/net.gotev.uploadservicedemo D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
03-20 17:04:35.063 9550-10105/net.gotev.uploadservicedemo D/libc-netbsd: getaddrinfo: MYDOMAIN get result from proxy >>
03-20 17:04:35.063 9550-10105/net.gotev.uploadservicedemo I/System.out: propertyValue:true
03-20 17:04:35.074 9550-10105/net.gotev.uploadservicedemo I/System.out: [CDS]rx timeout:30000
03-20 17:04:35.075 9550-10105/net.gotev.uploadservicedemo I/System.out: [socket][0] connection MYHOST.com/103.15.232.50:80;LocalPort=59281(15000)
03-20 17:04:35.075 9550-10105/net.gotev.uploadservicedemo I/System.out: [CDS]connect[MYHOST.com/103.15.232.50:80] tm:15
03-20 17:04:35.076 9550-10105/net.gotev.uploadservicedemo D/Posix: [Posix_connect Debug]Process net.gotev.uploadservicedemo :80 
03-20 17:04:35.163 9550-10105/net.gotev.uploadservicedemo I/System.out: [socket][/192.168.13.60:59281] connected
03-20 17:04:35.182 9550-10105/net.gotev.uploadservicedemo I/System.out: [CDS]rx timeout:30000
03-20 17:04:35.192 9550-10105/net.gotev.uploadservicedemo D/UploadService: UploadTask - Broadcasting upload progress for 021d72e4-70da-4423-9aae-1f2c4f58535d: 174 bytes of 98710
03-20 17:04:35.195 9550-10105/net.gotev.uploadservicedemo W/wilfredo: setLights argb:0, but we support only white color!!!!
03-20 17:04:35.290 9550-9550/net.gotev.uploadservicedemo V/TextView: stopSelectionActionMode()
03-20 17:04:35.291 9550-9695/net.gotev.uploadservicedemo D/OpenGLRenderer: Flushing caches (mode 0)
03-20 17:04:35.291 9550-9695/net.gotev.uploadservicedemo D/OpenGLRenderer: Flushing caches (mode 0)
03-20 17:04:35.301 9550-9550/net.gotev.uploadservicedemo D/ActivityThread: ACT-DESTROY_ACTIVITY handled : 1 / android.os.BinderProxy@1643f4bc
03-20 17:04:35.305 9550-9695/net.gotev.uploadservicedemo D/Surface: Surface::setBuffersDimensions(this=0x7f77ab2000,w=720,h=1280)
03-20 17:04:35.308 9550-9695/net.gotev.uploadservicedemo D/GraphicBuffer: register, handle(0x7f66d5ed40) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
03-20 17:04:35.777 9550-10105/net.gotev.uploadservicedemo D/OkHttp: <-- 500 Internal Server Error http://MYAPI/servicejob_uploads (749ms)
03-20 17:04:35.777 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Date: Mon, 20 Mar 2017 09:04:01 GMT
03-20 17:04:35.777 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Server: Apache
03-20 17:04:35.777 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Content-Length: 681
03-20 17:04:35.777 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Connection: close
03-20 17:04:35.777 9550-10105/net.gotev.uploadservicedemo D/OkHttp: Content-Type: text/html; charset=iso-8859-1
03-20 17:04:35.777 9550-10105/net.gotev.uploadservicedemo D/OkHttp: <-- END HTTP
03-20 17:04:35.778 9550-10105/net.gotev.uploadservicedemo I/System.out: [CDS]close[59281]
03-20 17:04:35.779 9550-10105/net.gotev.uploadservicedemo D/UploadService: HttpUploadTask - Server responded with HTTP 500 to upload with ID: 021d72e4-70da-4423-9aae-1f2c4f58535d
03-20 17:04:35.779 9550-10105/net.gotev.uploadservicedemo D/UploadService: UploadTask - Broadcasting upload completed for 021d72e4-70da-4423-9aae-1f2c4f58535d
03-20 17:04:35.780 9550-9550/net.gotev.uploadservicedemo D/MultipartUploadActOK: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
                                                                                 <html><head>
                                                                                 <title>**500 Internal Server Error**</title>
                                                                                 </head><body>
                                                                                 <h1>Internal Server Error</h1>
                                                                                 <p>The server encountered an internal error or
                                                                                 misconfiguration and was unable to complete
                                                                                 your request.</p>
                                                                                 <p>Please contact the server administrator,
                                                                                  mywebmaster@email.com and inform them of the time the error occurred,
                                                                                 and anything you might have done that may have
                                                                                 caused the error.</p>
                                                                                 <p>More information about this error may be available
                                                                                 in the server error log.</p>
                                                                                 <p>Additionally, a 404 Not Found
                                                                                 error was encountered while trying to use an ErrorDocument to handle the request.</p>
                                                                                 </body></html>
03-20 17:04:35.791 9550-10105/net.gotev.uploadservicedemo I/RingtoneManager: Get actual default ringtone uri= content://media/internal/audio/media/22`

**Comment by gotev** [comment]
I have to remind you this is not a server-side project and this is not a support forum. Issues here has to be pertinent to library errors. I encourage you to head to the troubleshooting section of the wiki and to make your tests also with the provided node server example, which I'm sure that behaves correctly

**Comment by Ric17101** [comment]
Ok, thanks BTW.  I will troubleshoot the error on the server side as per the wiki suggested.
