### ISSUE TITLE
Call onCompleted only when the server response code is >= 200 and < 400

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#259]
Actually the `onError` callback gets called only if the request cannot reach the server due to networking errors, even after the retries. 

If the request successfully reaches the server, the `onCompleted` gets called with the server's response. 

This has to be changed, because it's not intuitive and practical for error handling when the server responds with http codes which indicate errors, such as `4xx` or `5xx` and does not allow to show the error message configured for the notification.

The callback methods should be called in this way:
* `onCompleted` when the server responds with an HTTP code >= 200 and < 400
* `onError` if the request could not reach the server or if the server responds with a code >= 400

This means changing the public API of the callback's `onError` method, which will be the following:
```java
/**
 * Called when an error happens during the upload, after that all the retries have been 
 * completed without success. Override this method to add your own logic.
 *
 * @param context context
 * @param uploadInfo upload status information
 * @param serverResponse response got from the server
 * @param exception exception that caused the error
 */
void onError(final Context context, final UploadInfo uploadInfo, 
             final ServerResponse serverResponse, final Exception exception);
```

This issue is open for discussion

**Comment by mostafaspace** [comment]
What if the request reached the server, and there was a custom error I created? The HTTP code will still be 200, and you get success message but the file did not actually upload. 
For example: "max file size is 5mb", its a simple if/else check on server-side where the request is received but the file did not moved to folder to say its "uploaded". 

I'm no expert on requests but I think `onError` will not get the job done. checking server error codes only is not enough. You can use `onCompleted` to do both, check server errors and check custom errors. and whatever the error, let it be shown in the notification error.

**Comment by gotev** [comment]
> I'm no expert on requests but I think onError will not get the job done

Actually, I think it can solve the problem, and I'm going to explain why IMHO.

> What if the request reached the server, and there was a custom error I created? 

When implementing whatever endpoint, you should always follow the [HTTP Status codes definition in RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) to be standard compliant and to not reinvent the wheel.

> For example: "max file size is 5mb", its a simple if/else check on server-side where the request is received but the file did not moved to folder to say its "uploaded".

`Fail fast` is a good approach when dealing with requests to a server. If the client is not allowed to perform an action, you should kick it as soon as possible.
Following the RFC, to implement your example, you should simply return `413 Request Entity Too Large` and not accept the request at all, so you don't consume network bandwidth and resources both on the client and the server. You can always return a response body with HTTP status `4xx`. In fact, if you have more complex checks which does not find any matches in the `4xx` error codes, practice suggests to send a `400 Bad Request` with the error detail in the response body. 

E.g.:
`HTTP Status: 400 Bad Request`
Response body:
```json
{
  "error": "you should accept the privacy polocy agreements in your profile to be able to upload photos"
}
```

Let's examine a more complex scenario. You upload a file which has to be validated by the server after it has been uploaded. You let the client perform the upload, and after it has been completed you perform the server-side checks. After the checks have been performed, you return a `2xx` if everything is ok or a `4xx` with all the relevant details which tells the client exactly what has gone wrong.

Having said that, I like your idea to be able to modify the notification message from the callbacks, because it allows you to display more details to the user after the request has been completed (either successfully or with an error), though I'm not sure if it's possible [with the actual architecture](https://github.com/gotev/android-upload-service/wiki/Developer's-manual#the-architecture), because each upload task manages its own notification and then sends broadcasts to notify the status outside the task.

**Comment by mostafaspace** [comment]
Wow, I really didn't know about all these server errors, all I knew was to get the file size after its uploaded, then if it doesn't match, then ignore it. and if it does, move it to uploads folder.

Well, about the complex scenario, What if u can trigger the error at `onCompleted` and take the message to the notification?
`if (jsonObject.has("error")) {
triggerError(jsonObject.getString("error"));
}`
But in this way it will be a must to have `error` in the returned json. same can be done for `success`.

**Comment by gotev** [comment]
What you return in the response body and how to parse it, is up to you, there's no official standard for that. The problem is how to update the notification from the callbacks, given the considerations of my previous post.

**Comment by mostafaspace** [comment]
Ok, Don't let each task mange its own notification. Make a global notification and update it by ID in the task. does that make sense?

**Comment by gotev** [comment]
This is getting OT here as new ideas comes. Let's continue the discussion about notifications on #260
