### ISSUE TITLE
Proposal to extend this to other cloud services such as GDrive, Dropbox, Emailing, OneDrive

### ISSUE THREAD

**Issue by NLLAPPS** [gotev/android-upload-service#261]
Hi, I use an in-house library kind of thing I've put together for uploading to GoogleDrive, Dropbox, OneDrive, AutoEmail, AutoEmail with Oauth for Gmail, WebDAV, FTP and been looking to turn it in to a proper library. 
Would you be interested? I can share its source with you and hopefully it would become part of your library.

**Comment by gotev** [comment]
That would be fantastic!

**Comment by NLLAPPS** [comment]
Great! what is your email so I can send it to you. Don't expect anything organised :)

**Comment by gotev** [comment]
Closing this due to the fact third party upload services change their implementations very often and implementing every one of them from scratch will require too much maintenance effort, so it's better to just use their SDKs, which are surely more maintained
