### ISSUE TITLE
How do I change the strings in the notification?

### ISSUE THREAD

**Issue by VSG24** [gotev/android-upload-service#262]
I would like to localize the strings that are used in the upload progress notification. Is that possible?

**Comment by gotev** [comment]
Of course yes, just use `context.getString(R.string.yourstring)` to get the strings to pass into the UploadNotificationConfig setters.

**Comment by VSG24** [comment]
Yep, that did it but I'm facing another problem now so I created a new issue #263

**Comment by gotev** [comment]
Added example in the wiki: https://github.com/gotev/android-upload-service/wiki/Recipes#notification-configuration
