### ISSUE TITLE
Only one file uploads. How to upload multiple files in a single multipart request?

### ISSUE THREAD

**Issue by VSG24** [gotev/android-upload-service#263]
Here's my code:

```
    public void uploadFilesFromList() {
        try {
            Logger.setLogLevel(Logger.LogLevel.DEBUG);

            UploadNotificationConfig uploadNotificationConfig = new UploadNotificationConfig();
            uploadNotificationConfig.setTitle(getString(R.string.univer30t_upload_content));
            uploadNotificationConfig.setErrorMessage(getString(R.string.upload_error));
            uploadNotificationConfig.setCompletedMessage(getString(R.string.upload_successfully_finished_pt1) + Placeholders.ELAPSED_TIME + getString(R.string.upload_successfully_finished_pt2));

            uploadRequest = new MultipartUploadRequest(mContext, App.SITE_BASE_URL + "/upload_file")
                    // starting from 3.1+, you can also use content:// URI string instead of absolute file
                    .setNotificationConfig(uploadNotificationConfig)
                    .setMaxRetries(2)
                    .addParameter("content_id", Integer.toString(content_id))
                    .setUtf8Charset();

            for (UploadFile uf : uploadFileArrayList) {
                addFileToUploadRequest(uf);
            }

            startUpload();
        } catch (Exception exc) {
            Log.d("AndroidUploadService", exc.getMessage(), exc);
        }
    }

    public void startUpload() {
        uploadRequest.startUpload();
    }

    public void addFileToUploadRequest(UploadFile uf) {
        try {
            uploadRequest.addFileToUpload(uf.filePath, "file");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
```

I add two files to the `request` instance using `addFileToUpload` method but it only uploads the first one.

**Comment by gotev** [comment]
The problem is due to the fact that you do this:
```java
public void addFileToUploadRequest(UploadFile uf) {
    try {
        uploadRequest.addFileToUpload(uf.filePath, "file");
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    }
}
```
So what happens on the server-side is that you see only the last file, even if also the others are present in the upload payload. This is not a library problem, but how the multipart protocol works. You have two options:
* use `file[]` as parameter name for all your files, so in your server-side you can handle `file` as an array. [Example](http://stackoverflow.com/a/8808915)
* assign a different parameter name to each one of your files, e.g. `file1`, `file2`, ..., `fileN` and then you have to handle them one by one on the server side. [Example](https://github.com/gotev/android-upload-service/issues/237#issuecomment-280845903)

**Comment by VSG24** [comment]
You are so right, I think another way of doing multiple uploads with the same parameter name is to call the `startUpload` multiple times.(separate calls for each file)

**Comment by gotev** [comment]
You must create a new upload request for each file then, and you will have N parallel uploads for N files, which as a consequence will generate N notifications. Consider if yo want to have N files in a single request or N requests. You should not call `startUpload` multiple times on the same upload request. Every request is one-shot.

**Comment by hmskhan** [comment]
my server side code

$myFile = $_FILES['image'];
$fileCount = count($myFile["name"]);

for ($i = 0; $i < $fileCount; $i++) {
        //file path to upload in the server 
	$file_path = "uploads/". $myFile["name"][$i];
	move_uploaded_file($myFile["tmp_name"][$i], $file_path);
}

I add N files to the request using addFileToUpload method but it only uploads the last one.
