### ISSUE TITLE
Unable to post data

### ISSUE THREAD

**Issue by kapilmohansn** [gotev/android-upload-service#264]
### Version info
* Android Upload Service version: 3.2.3

### What did you expect?

i've tries to upload 2 files along with some data.

### What happened instead?

the data send is not reflecting in db(Those tested with postman gets reflected) the images get uploaded anyway but an error is shown when including 2 images, and when i remove one image ... a successfully uploaded message is shown!

### Request code:
```java
// the code you wrote to create the upload request
```

     Toast.makeText(getApplicationContext(),"uploading",Toast.LENGTH_LONG).show();

        try {
            String uploadId =
                    new MultipartUploadRequest(this, Constants.UPLOAD_URL)
                            .addFileToUpload(bill, "uploadimg")
                            .addFileToUpload(handset,"uploadset")
                            .addParameter(prefManager.getLoginName(),"shop")
                            .addParameter(dataName,"cname")
                            .addParameter(dataPhone1,"phone")
                            .addParameter(dataPhone2,"secondaryphone")
                            .addParameter(dataAddress,"address")
                            .addParameter(dataPin,"pin")
                            .addParameter(dataCompany,"company")
                            .addParameter(dataModel,"model")
                            .addParameter(dataEmail,"email")
                            .addParameter(dataImei1,"imei1")
                            .addParameter(dataImei2,"imei2")
                            .addParameter(dataImei3,"imei3")
                            .addParameter(dataImei4,"imei4")
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .setDelegate(new UploadStatusDelegate() {
                                @Override
                                public void onProgress(Context context, UploadInfo uploadInfo) {
                                    // your code here

                                }

                                @Override
                                public void onError(Context context, UploadInfo uploadInfo, Exception exception) {
                                    // your code here
                                }

                                @Override
                                public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
                                    // your code here
                                    // if you have mapped your server response to a POJO, you can easily get it:
                                    // YourClass obj = new Gson().fromJson(serverResponse.getBodyAsString(), YourClass.class);

                                    imgSet.setImageResource(R.drawable.click_upload);
                                    imgBill.setImageResource(R.drawable.click_upload);
                                    clearForm((LinearLayout)findViewById(R.id.formCustomer));
                                    Toast.makeText(getApplicationContext(),"uploaded",Toast.LENGTH_LONG).show();

                                }

                                @Override
                                public void onCancelled(Context context, UploadInfo uploadInfo) {
                                    // your code here

                                    Toast.makeText(getApplicationContext(),"cancelled",Toast.LENGTH_LONG).show();
                                }
                            })
                            .startUpload();

#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

**Comment by gotev** [comment]
Seems a server-side problem or some header or parameter missing. I need more insights to addreas this. Please do also the following:
- post here the cURL export of the request from Postman which works
- try the above code with the demo server, by changing the endpoint of the request to `http://yourip:port/upload/multipart` (actual IP and Port will be shown once you start the server) and see if you still get an error
