### ISSUE TITLE
File upload path

### ISSUE THREAD

**Issue by Dragas** [gotev/android-upload-service#265]
Are you sure we should deal with file path but not file descriptors or even byte arrays? Android isn't the kind of OS to give out absolute pathes to files provided via intents unless you wrote them there yourself.

**Comment by gotev** [comment]
You can get either absolute path to files and also content provider paths from Android. Both are supported and a working example is implemented in the demo app, so I don't get the point of this question, but maybe I'm missing something from your point of view, so please make an example. Passing byte arrays in intents is certainly bad, especially for large content.
