### ISSUE TITLE
OkHttp stack library is forcing me to use SNAPSHOT version of OkHttp

### ISSUE THREAD

**Issue by gajicm93** [gotev/android-upload-service#270]
I included your OkHttp stack library, but it's dependecy is is listed as "3+", and for some reason it's automatically downloading 3.9.0-SNAPSHOT, while 3.8.0 is latest stable at the moment.

I tried excluding it but gradle is giving me an error for some reason.. But you should fix this anyways.

**Comment by gotev** [comment]
Wow this is definitely bad! Going to fix OkHttp to 3.8.0 and make a quick release. Stay Tuned

**Comment by gotev** [comment]
just released 3.2.4. Update your dependencies and the problem will be solved

**Comment by knordbo** [comment]
Support library is also a + dependency. I'd strongly recommend not using.
