### ISSUE TITLE
Upload issue when choosing images and videos

### ISSUE THREAD

**Issue by virengujariya** [gotev/android-upload-service#271]
So If I upload only images or only videos then everything works fine (I have extended UploadTask to use AWS s3 upload service)

However, if I upload both (images and videos) at the same time then it is not uploading videos.  My code looks like 
```
for (ChosenImage media : chosenImages) {
                try {
                    awsUploadRequest.addImageToUpload(media
                            , BucketHelper.getS3BucketName(Constants.TYPE_IMAGE)
                            , UUID.randomUUID().toString() + "." + FileUtils.getFileExtension(media.getOriginalPath()));
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }

for (ChosenVideo media : chosenVideos) {
                try {
                    awsUploadRequest.addVideoToUpload(media
                            , BucketHelper.getS3BucketName(Constants.TYPE_VIDEO)
                            , UUID.randomUUID().toString() + "." + FileUtils.getFileExtension(media.getOriginalPath()));
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }

awsUploadRequest.startUpload();
```

And `addImageToUpload` method does `params.addFile(file);`

I am using 3.2.3. I am not sure what's wrong because there is no error. Any suggestions?

**Comment by gotev** [comment]
Enable library debug logging and you will see all the library internal messages. Need more details to tell if the problem is in the implementation you made or in the core library. If you post the sources it will be a lot easier.

**Comment by virengujariya** [comment]
@gotev It was silly mistake since I was removing AWS transfer listener reference in between. It is fixed now. logging did help though. Thanks!
