### ISSUE TITLE
How to upload to the specified directory？

### ISSUE THREAD

**Issue by MinchinWang** [gotev/android-upload-service#272]

**Comment by gotev** [comment]
The library can automatically delete successfully uploaded files. Just set [setAutoDeleteFilesAfterSuccessfulUpload(true)](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/UploadRequest.html#setAutoDeleteFilesAfterSuccessfulUpload-boolean-) in your Upload Request builder. If you want to delete only specific files after successful upload, don't invoke the setter on the builder and use the standard android way to delete files in the `onCompleted` method callback.

**Comment by gotev** [comment]
I've seen you changed the question in the description. If you have multiple questions, please open a new issue for every question. Also, provide some more details about `How Upload to the specified directory?` as your question is incomplete. If you want to upload files to different directories on the server, it's your duty to implement it on the server-side. The library only provides you a way to transfer files from your device to your server. Everything else is up to your and how you want to design your system.
