### ISSUE TITLE
Proposed to increase the download, delete function?

### ISSUE THREAD

**Issue by moter** [gotev/android-upload-service#273]
Proposed to increase the download, delete function

**Comment by gotev** [comment]
Please add some more details

**Comment by moter** [comment]
How do you abort an upload task in FTPUploadRequest?

**Comment by moter** [comment]
setSocketTimeout(5000) doesn't work in FTPUploadRequest. How do you know if the server is connected?

**Comment by gotev** [comment]
FTP Module is only a wrapper of Apache Commons FTP library. I don't know if there's a way to interrupt the download. Some research is needed. What do you mean the timeout is not working?

**Comment by moter** [comment]
I get it.the FTPUploadRequest setMaxRetries(), number of maximum too large.
