### ISSUE TITLE
Cancel Upload

### ISSUE THREAD

**Issue by MeTaXaS4** [gotev/android-upload-service#285]
How can someone cancel an upload? if he/she can't, can you add that function to your library?

**Comment by gotev** [comment]
This is already supported and documented [here](https://github.com/gotev/android-upload-service/wiki/Recipes#stop-upload-tasks-). Bu stopping an upload you are actually cancelling it.

**Comment by MeTaXaS4** [comment]
sorry didn't see it, thanks
