### ISSUE TITLE
Issue with certain camera/gallery image files not uploading to server's directory

### ISSUE THREAD

**Issue by kortstin** [gotev/android-upload-service#290]
### Version info
* Android Upload Service version: 3.2.5
* Android version and API version: 
* HTTP stack (e.g. HurlStack or OkHttpStack):

### What did you expect? 
I have an app that picks an image from the images location on an android device and then displays it in an ImageView. This image is then uploaded to a server. A link to the image is sent to the database table, and the actual .jpg or.png file is sent to a folder in the server's directory. 

### What happened instead?
Unfortunately, for images taken by the camera and certain others, the link is uploaded to the table, but the image file is never uploaded to the folder. 

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
https://gist.github.com/kortstin/b75b1ff37afa25a2f5dc23a119c10201
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

php script

```
// your server side script (if applicable)
https://gist.github.com/kortstin/2a4ff80ed4bc110a0330099b78ff7465
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Try to pass the content Uri as a String directly to the upload service instead of resolving the path

**Comment by kortstin** [comment]
Thanks! What piece of code would I need to change to just pass the content Uri as a String directly?

**Comment by gotev** [comment]
Just use the Uri's `toString` [method](https://stackoverflow.com/a/17356461)
