### ISSUE TITLE
Remove final notification

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#291]
As proposed [here](https://github.com/gotev/android-upload-service/issues/260#issuecomment-310062350) add the possibility of removing the final notification of an upload

**Comment by gotev** [comment]
@PhilLab the easiest and quickest thing which can be done is to pass the notification ID in the `UploadInfo`, so you can have it in all the callbacks. The notification ID will be an `Integer` as it can be `null` when the upload request does not have a notification configuration set.

**Comment by PhilLab** [comment]
I did something like this last month in my local code and now decided to commit it. If you want to merge it see the PR

**Comment by gotev** [comment]
Now you can do the following in every callback:
```java
if (uploadInfo.getNotificationID() != null) {
    NotificationManager notificationManager = 
        (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
    notificationManager.cancel(uploadInfo.getNotificationID());
}
```
In the `onProgress` callback method you will always get a `null` notification ID because even if you passed a `NotificationConfig` when you created the request, the notification is ongoing and managed by the service. It wouldn't make sense to cancel it while in progress btw. In the other callbacks you will get the ID only if you have set an `UploadConfig` and not set auto canceling for that state.
