### ISSUE TITLE
Possible to use Android Upload Service with Tor Onion Proxy Library?

### ISSUE THREAD

**Issue by kortstin** [gotev/android-upload-service#296]
Is it possible at all to integrate the use of Tor Onion Proxy Library or NetCipher in order to add TOR support to my app. It is currently using Android Upload Service to upload images, text, and location to a server, but I also want to do so through the Tor network. Would I be able to do so? And if so, how can that be done alongside this upload library with existing code?
My MainActivity.java is linked below so my implementation can be seen:

https://gist.github.com/kortstin/3c15df6d53585a358ebdcd91b26e703f

**Comment by gotev** [comment]
Never used that library, but it's certainly possible to integrate it in UploadService as a plugin. The first step is making it work with a standard HttpURLConnection or an OkHttpClient, then I can guide you through the plugin implementation. The only thing which I need is an HttpURLConnection or an OkHttpClient  which passes through the proxy, the rest is really easy.

**Comment by kortstin** [comment]
Awesome! I was hoping it was possible. Sounds good though! When could the plugin for that feature be integrated into UploadService?

**Comment by gotev** [comment]
As soon as you provide me an example of a secured HttpURLConnection or secured OkHttpClient implementation which uses Tor Onion Proxy or NetCipher. It's up to you.

**Comment by kortstin** [comment]
Okay cool! I think there is an implementation for NetCipher using HttpURLConnection in a sample they provided. Let me see if I can find it.

**Comment by kortstin** [comment]
Okay here is a link to a sample of HttpURLConnection using NetCipher. 

https://github.com/guardianproject/NetCipher/tree/master/sample-hurl

Would this be sufficient as an example? They have one for OkHttp3 as well

**Comment by gotev** [comment]
That's pretty cool! To use it with OkHttp it's just a matter of configuration with current Upload Service release! Prepared [a wiki page here](https://github.com/gotev/android-upload-service/wiki/Proxying-requests-through-TOR)

Using HttpURLConnection requires extending existing `HurlStack` and `HurlStackConnection` and use `StrongConnectionBuilder` to create the connection, instead of the default Hurl methods. Those two classes can then be exported as a separate plugin for Upload Service.

**Comment by kortstin** [comment]
Awesome!! Thanks so much! So would that Application delegate code snippet go within the upload method I have in MainActivity?

**Comment by gotev** [comment]
I advise you to keep initialization in the Application delegate and perform only the request in the activity
