### ISSUE TITLE
Assistance with proxying requests through Tor

### ISSUE THREAD

**Issue by kortstin** [gotev/android-upload-service#300]
Hello I am proxying requests through Tor, via the NetCipher library. I have followed the setup guide detailed in the wiki for Android Upload Service and also referenced the NetCipher tutorial and docs to establish connection with Orbot, but I'm not sure if I have successfully established a connection or not. Is there anything else that I need to add to either the Initializer Application delegate or my MainActivity? Also is there a way to 

MainActivity.java
https://gist.github.com/kortstin/20b0a4b3299867a7090e08c10a6c946f

Initializer.java
https://gist.github.com/kortstin/d0352dbc5facc3de38124c2a31bd7bee

**Comment by gotev** [comment]
Print something out in the onConnected callback in the initializer and put some logging also in the other callbacks, to get more details. If you could not connect wirh Orbot, it's not an Upload Service issue

**Comment by gotev** [comment]
They don't do that automatically. Check the updated [wiki](https://github.com/gotev/android-upload-service/wiki/Proxying-requests-through-TOR)
