### ISSUE TITLE
OutOfMemory exception on 20+ MB file with HttpUrlConnection stack

### ISSUE THREAD

**Issue by parubabr** [gotev/android-upload-service#304]
Sorry, english is not my native language so I will do my best to explain the issue.

Basically I have the same issue as this guy https://github.com/gotev/android-upload-service/issues/99 but unfortunatelly he didn't explain how he solve it...

But in my case I have some points to explain. First, let me show you my Android code:

```
     UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
     UploadService.UPLOAD_POOL_SIZE = 1;

    public void uploadMultipart(final Context context, final String filePath) {
        try {
            String uploadId =
                new MultipartUploadRequest(context, "https://www.mysite.com/getfile.php") // My site has a valid SSL certificate
                    .addFileToUpload(filePath, "file")
                    .setUsesFixedLengthStreamingMode(true) // Not use chunked streaming mode
                    .setUtf8Charset()
                    .setMaxRetries(2)
                    .startUpload();
        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }
    }
```

And here is my PHP (5.6) code to receive the file (I removed all extra code for testing purposes):

```
            if ($_FILES['file']['error'] == 0) {
                $path = dirname(__FILE__).'/uploads';
                $file = $path.'/'.basename($_FILES['file']['name']);
                if (move_uploaded_file($_FILES['file']['tmp_name'], $file)) {
                    echo 'File was uploaded successfully!';
                } else {
                    echo $_FILES['file']['error'];
                }
            } else {
                echo $_FILES['file']['error'];
            }
```

PS. I already changed the php.ini configuration to accept files until 100 MB (post_max_size and upload_max_filesize)

Ok, now what happens:

1. It works perfectlly when sending files with 20 MB or less;
2. With files above 20 MB size I have an "Out of memory" error;

So I changed the code to use chunked streaming mode "setUsesFixedLengthStreamingMode(false)", and now I do not have the "Out of memory" error anymore, but in server side the $_POST array is empty.

Please, do you know what I am doing wrong? What information from Wireshark can I check (never used this software before)?

Thanks! Best regards!

Fabio

**Comment by gotev** [comment]
Please post the stack trace of the OutOfMemory error. You shouldn't get that error since the file gets uploaded with a buffer even in fixed streaming. Are you using OkHttp or HttpUrlConnection stack? On which android device and version does this happen?

**Comment by parubabr** [comment]
Hi! Thank you for trying to help me!

Here is the error:

> E/dalvikvm-heap: Out of memory on a 67100972-byte allocation.
> I/dalvikvm: "pool-1-thread-1" prio=5 tid=11 RUNNABLE
> I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x43b0d490 self=0x63501a10
> I/dalvikvm:   | sysTid=30966 nice=0 sched=0/0 cgrp=apps handle=1662775760
> I/dalvikvm:   | state=R schedstat=( 441852478 10902184 347 ) utm=25 stm=19 core=1
> I/dalvikvm:     at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:~91)
> I/dalvikvm:     at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
> I/dalvikvm:     at com.android.okhttp.internal.http.RetryableOutputStream.write(RetryableOutputStream.java:64)
> I/dalvikvm:     at net.gotev.uploadservice.http.impl.HurlBodyWriter.write(HurlBodyWriter.java:27)
> I/dalvikvm:     at net.gotev.uploadservice.http.BodyWriter.writeStream(BodyWriter.java:51)
> I/dalvikvm:     at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:141)
> I/dalvikvm:     at net.gotev.uploadservice.MultipartUploadTask.onBodyReady(MultipartUploadTask.java:66)
> I/dalvikvm:     at net.gotev.uploadservice.http.impl.HurlStackConnection.getResponse(HurlStackConnection.java:145)
> I/dalvikvm:     at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:72)
> I/dalvikvm:     at net.gotev.uploadservice.UploadTask.run(UploadTask.java:136)
> I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> I/dalvikvm:     at java.lang.Thread.run(Thread.java:841)

I am testing with an Asus Zenfone 5 and Android 4.4.2

My knoledge about this subject is limited, I didn't understand what you mean with "Are you using OkHttp or HttpUrlConnection stack?". I followed instructions here and some videos on Youtube to include your library in my little project. I also added this line to build.gradle:

compile 'net.gotev:uploadservice-okhttp:3.3.1'

Thanks again!

**Comment by parubabr** [comment]
> W/dalvikvm: threadid=11: thread exiting with uncaught exception (group=0x430f2140)
> E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
>     Process: com.mysite.testuploadfilegotev, PID: 4754
>     java.lang.OutOfMemoryError
>         at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
>         at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
>         at com.android.okhttp.internal.http.RetryableOutputStream.write(RetryableOutputStream.java:64)
>         at net.gotev.uploadservice.http.impl.HurlBodyWriter.write(HurlBodyWriter.java:27)
>         at net.gotev.uploadservice.http.BodyWriter.writeStream(BodyWriter.java:51)
>         at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:141)
>         at net.gotev.uploadservice.MultipartUploadTask.onBodyReady(MultipartUploadTask.java:66)
>         at net.gotev.uploadservice.http.impl.HurlStackConnection.getResponse(HurlStackConnection.java:145)
>         at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:72)
>         at net.gotev.uploadservice.UploadTask.run(UploadTask.java:136)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>         at java.lang.Thread.run(Thread.java:841)

**Comment by gotev** [comment]
This is the same as #114. It's a bug in the underlying network layer on Android 4.4, not in the library.
 [Follow the directions](https://github.com/gotev/android-upload-service/wiki/Setup#okhttp) to setup OkHttp and tell me if you have the same error.

**Comment by parubabr** [comment]
This solved the problem! I was searching for a solution and making tests for 2 days... Thank you so much! I hope you lot of success! Btw, I live in Brazil but all my family are from Italy! Cheers!

**Comment by gotev** [comment]
@parubabr you're welcome! Greetings from Milan!
