### ISSUE TITLE
UploadNotificationConfig leads to NullPointerException

### ISSUE THREAD

**Issue by meparam** [gotev/android-upload-service#309]
### What did you expect?
I  want to display the notification when uploading the files.

### What happened instead?
when I build a MultipartUploadRequest  then  UploadNotificationConfig  leads to crash 
### Version info
* Android Upload Service version:3.4
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

// the code you wrote to create the upload request
``` new MultipartUploadRequest(this, "http://posttestserver.com/post.php")
                            // starting from 3.1+, you can also use content:// URI string instead of absolute file
                            .addFileToUpload(getFile().toString(), "param-name")
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .addHeader("param","hello")
                            .addParameter("name","paramvir singh")
                            .setDelegate(new UploadStatusDelegate().setAutoDeleteFilesAfterSuccessfulUpload(true)
                    .addParameter("color", "#ffffff").
                    .setMaxRetries(2)
                    .startUpload();
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
`
// your LogCat output here
java.lang.NoSuchMethodError: android.support.v4.app.NotificationCompat$Builder.<init>
                                                                                     at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:451)
                                                                                     at net.gotev.uploadservice.UploadTask.run(UploadTask.java:144)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:841)

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Check your gradle file. Maybe you have you used forced dependency resolution with a support library lower than 26. You must use support library 26 to support Android O.

**Comment by meparam** [comment]
Please have a look i am sharing the complete gradle file  

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.0'
    defaultConfig {
        applicationId "com.yashoid.instacropper.sample"
        minSdkVersion 16
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    configurations.all {
        resolutionStrategy {
            force 'com.android.support:support-v4:26.+'
            force 'com.android.support:appcompat-v7:26.+'
        }
    }
}
def uploadServiceVersion = "3.4"
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile project(':instacropper')
    compile 'com.android.support:support-v4:26.+'
    compile 'com.android.support:design:26.+'
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile "net.gotev:uploadservice:$uploadServiceVersion"
}

**Comment by gotev** [comment]
change targetSdkVersion to 26

**Comment by meparam** [comment]
I have done what you have suggested. still same error , no change in error so far

**Comment by gotev** [comment]
Try the demo app on the same phone and let me know if it  works,

**Comment by meparam** [comment]
I think this is problem with only 3.4 version. Demo works fine but with gradle build it is giving error.

**Comment by gotev** [comment]
Have you enabled ProGuard?

**Comment by gotev** [comment]
Same as #311
