### ISSUE TITLE
 java.lang.NoSuchMethodError: No direct method

### ISSUE THREAD

**Issue by haneef5k** [gotev/android-upload-service#311]
### What did you expect?
Upload multipart file with notification indication.

### What happened instead?
App crashed

### Version info
* Android Upload Service version: 3.4
* Android version and API version: 25
* HTTP stack (e.g. HurlStack or OkHttpStack): 3.4

### Library initialization code:
```java
// the code you wrote in your Application subclass here
public class MainApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        // setup the broadcast action namespace string which will
        // be used to notify upload status.
        // Gradle automatically generates proper variable as below.
        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
    
    }

}

### Request code:
```java
// the code you wrote to create the upload request

public void uploadMultipart(final Context context) {

        OkHttpClient client = new OkHttpClient(); // create your own OkHttp client
        UploadService.HTTP_STACK = new OkHttpStack(client); // make the library use your own OkHttp client

        try {

            String uploadId = UUID.randomUUID().toString();

            final String request =  new MultipartUploadRequest(context, uploadId, ApiUtils.BASE_URL + "upload.php")
                            // starting from 3.1+, you can also use content:// URI string instead of absolute file
                            .addFileToUpload(getRealPathFromURI(videoUri), "file")
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .startUpload();

            Toast.makeText(getContext(), request, Toast.LENGTH_LONG).show();

        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }

    }


#### Where have you added the request code? 
- [ ] Activity
- [ ] Service
- [Fragment] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here

java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/myfile-upload-app2/split_lib_dependencies_apk.apk:classes10.dex)
                                                                             at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:451)
                                                                             at net.gotev.uploadservice.UploadTask.run(UploadTask.java:144)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Be sure to have support library 26 at compile time. Chsck your gradle dependencies.

**Comment by haneef5k** [comment]
Thank you @gotev ... .Working perfectly..!

**Comment by gotev** [comment]
You're welcome!
