### ISSUE TITLE
NPE at Android 8 with empty UploadNotificationConfig

### ISSUE THREAD

**Issue by guerrillalg** [gotev/android-upload-service#314]
### What did you expect?
I am setting up the Upload Task with empty UploadNotificationConfig, because I don't need any notifications in my app. 

### What happened instead?
NPE crash:
```
UploadService - Error while instantiating new task
                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String net.gotev.uploadservice.UploadNotificationConfig.getNotificationChannelId()' on a null object reference
                                        at net.gotev.uploadservice.UploadTask.init(UploadTask.java:126)
                                        at net.gotev.uploadservice.HttpUploadTask.init(HttpUploadTask.java:37)
                                        at net.gotev.uploadservice.MultipartUploadTask.init(MultipartUploadTask.java:38)
                                        at net.gotev.uploadservice.UploadService.getTask(UploadService.java:351)
                                        at net.gotev.uploadservice.UploadService.onStartCommand(UploadService.java:256)
```

### Version info
* Android Upload Service version: 3.4
* Android version and API version: 26
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### Request code:
```java
new MultipartUploadRequest(getBaseContext(), url)
                         .setNotificationConfig(null)
                        .startUpload();
```
#### Where have you added the request code?
 Service

### Additional info
I've checked the code, there's everywhere checks like `if (params.notificationConfig == null) return;`
However, in init method it is missing, thus causing the NPE. Solution is quite simple - add the null check.

**Comment by guerrillalg** [comment]
Tried to create pull request, and got rejected.
Code that can fix the issue:
```
protected void init(UploadService service, Intent intent) throws IOException {
        this.notificationManager = (NotificationManager) service.getSystemService(Context.NOTIFICATION_SERVICE);
        this.params = intent.getParcelableExtra(UploadService.PARAM_TASK_PARAMETERS);
        this.service = service;
        this.mainThreadHandler = new Handler(service.getMainLooper());

        if (params.notificationConfig != null) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                String notificationChannelId = params.notificationConfig.getNotificationChannelId();

                if (notificationChannelId == null) {
                    params.notificationConfig.setNotificationChannelId(UploadService.NAMESPACE);
                    notificationChannelId = UploadService.NAMESPACE;
                }

                if (notificationManager.getNotificationChannel(notificationChannelId) == null) {
                    NotificationChannel channel = new NotificationChannel(notificationChannelId, "Upload Service channel", NotificationManager.IMPORTANCE_HIGH);
                    notificationManager.createNotificationChannel(channel);
                }
            }
        }

    }
```

**Comment by gotev** [comment]
Be aware that Android O introduced many changes regarding backgrounding. I highly suggest you to show the notification for the upload in O, because it allows the service to run in foreground and to not be killed by the OS.

Docs needs to be updated regarding this ;)

**Comment by guerrillalg** [comment]
> Be aware that Android O introduced many changes regarding backgrounding.
Yes, I understand, but in any case, we would not be able to use the built-in notifications.
Our upload process is a lot more complicated(we have file pre-processing, encryption etc..) And we have to show the notification for the overall this process. If we have notifications for each of those processes, it would flood the User. That's why we need to turn off the notifications for the Upload process.

And anyway, you already have Null-checks everywhere except that mentioned place, it would make sence to put them there as well

**Comment by gotev** [comment]
> Tried to create pull request, and got rejected.

Really strange. 

> And anyway, you already have Null-checks everywhere except that mentioned place, it would make sence to put them there as well

Of course. Scheduled for the next release.

**Comment by darekxan** [comment]
Any plans on releasing 3.4.1 to fix this issue?

**Comment by gotev** [comment]
@darekxan so you are using upload service but you take care yourself of displaying a notification, not using the provided system?

**Comment by jbekas** [comment]
@gotev In my app, the progress indicator and cancel capability are built into the UI. So yes, there are occasions where the developer may want to set UploadNotificationConfig to null. This works fine for Android prior to SDK 26.

**Comment by gotev** [comment]
@jbekas they are working right now. This will be addressed for sure, but a long term solution has te thought for the long run 😃

**Comment by guerrillalg** [comment]
@gotev , Just put that NP check, and it will be working fine. In my project, I have overriden that method with the code from [https://github.com/gotev/android-upload-service/issues/314#issuecomment-329766205]( https://github.com/gotev/android-upload-service/issues/314#issuecomment-329766205) and it works as advertised.

**Comment by gotev** [comment]
@guerrillalg I know how to solve the NPE :smiley: and it will be done so you can safely use the service without a notification for API < 26. The problem is that from Android 8.0+ (API 26) background services are not started as foreground if they lack a notification and so they will be killed by the OS when your app goes to the background or when the device goes idle. To continue displaying progress and actions inside the apps without a notification in the future, a different solution has to be found when you don't want to set a Notification Config. 

For example, WhatsApp is showing a notification like "WhatsApp is being run in the background" to be able to start the sync processes, while all the progress indicators are still in the UI. Maybe we can do the same or think for a different solution. I'm open for new ideas.

Meanwhile, the fix is going to be pushed and I'll notify you here :smiley:

**Comment by gotev** [comment]
@jbekas @guerrillalg @darekxan 3.4.1 released!
