### ISSUE TITLE
[Question]   can use with Retrofit?

### ISSUE THREAD

**Issue by vishalpatel1327** [gotev/android-upload-service#317]
I love this lib but nowadays I use Retrofit and have the same task to upload files like that so Is this possible to integrate with retrofit or not ?

**Comment by gotev** [comment]
Not out-of-the-box. Support for a thing like this has to be implemented, if possible at all. I also use retrofit, but I don't know its internals to tell you if this can be accomplished. At the moment, you can share the same underlying OkHttp stack. A pull request with this feature is always welcome!
