### ISSUE TITLE
How to check data which is uploading with multipart.

### ISSUE THREAD

**Issue by ajayqualwebs** [gotev/android-upload-service#318]
### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Explain exactly what you need to accomplish and to check

**Comment by ajayqualwebs** [comment]
i want to print requestParameter which i am sending with multipart, has any option here?

**Comment by gotev** [comment]
First of all, enable library debug log (check the wiki). If that doesn't suit your needs, instructions in the setup wiki and use OkHttp stack. Then setup OkHttp logging interceptor. You can see an example of build an OkHttp stack with interceptor here: https://github.com/gotev/android-base-app/blob/master/app/src/main/java/net/gotev/baseapp/Network.java#L95
