### ISSUE TITLE
Application Crashes when Upload services tries to create a notification

### ISSUE THREAD

**Issue by trey-rosius** [gotev/android-upload-service#319]
### What did you expect?
I expected my selected image to be uploaded to the server
### What happened instead?
My application crashed, citing notification errors.
### Version info
* Android Upload Service version: 3.4
* Android version and API version: Android Marshmallow, API 26 
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Steps to reproduce (if applicable):
select image from gallery, application crashes during on Upload Start.
### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

        // using this library
        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
### Request code:
```java
// the code you wrote to create the upload request
```
                try {
                    String uploadId =
                            new MultipartUploadRequest(this, BASE_URL)
                                    .addHeader("Authorization", loginSessions.getPrefApiKey())
                                    // starting from 3.1+, you can also use content:// URI string instead of absolute file
                                    .addFileToUpload(compressedpicpath, "image")
                                    .addParameter("image", picPath.substring(picPath.lastIndexOf("/") + 1))
                                    .addParameter("comment", "")
                                    .addParameter("sticker", "")
                                    .setNotificationConfig(new UploadNotificationConfig())
                                    .setMaxRetries(2)
                                    .startUpload();

                } catch (Exception exc) {
                    Log.e("AndroidUploadService", exc.getMessage(), exc);
                }

#### Where have you added the request code?
- [x ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
09-21 11:53:43.144 23253-25224/com.rosius.tori E/UncaughtException: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.rosius.tori-1/split_lib_dependencies_apk.apk:classes70.dex)
                                                                        at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:451)
                                                                        at net.gotev.uploadservice.UploadTask.run(UploadTask.java:144)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?
example.php
```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here

```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Check this: https://github.com/gotev/android-upload-service/issues/311#issuecomment-327308479
