### ISSUE TITLE
I cant find a way to put action on notification depending on status of the Upload

### ISSUE THREAD

**Issue by Xenolion** [gotev/android-upload-service#321]
I am setting the icon for my notification and pending intent but all I can do is using the same intent for all upload statuses. And as all the methods say setforAll..., setStatus... for all it is always for all, Is there a way to do or some methods I dont see yet to respond different for different notification clicks!

**Comment by Xenolion** [comment]
I have already understood how to do it. I am closing the issue!

**Comment by gotev** [comment]
There's already a full explanation about this in the wiki

**Comment by Xenolion** [comment]
It was my problem but I have already solved it. Thanks
