### ISSUE TITLE
getting issue with notification 

### ISSUE THREAD

**Issue by akash09766** [gotev/android-upload-service#322]
should get notification when upload started

getting error:

### Version info
* Android Upload Service version: 3.4
* Android version and API version: 6.0.1 and marshmellow 

### Steps to reproduce (if applicable):
use binary upload and start upload you will get error in android studio logs.
if comment notification and use delegate then its working.

### Library initialization code:
// the code you wrote in your Application subclass here
        UploadService.NAMESPACE = "com.demo.demo";

### Request code:
// the code you wrote to create the upload request
String uploadId = new BinaryUploadRequest(this, url)
                    .setFileToUpload(filePath)
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                     .startUpload();
#### Where have you added the request code?
- in Activity

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-
// your LogCat output here
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.offerclout.offermania-1/split_lib_dependencies_apk.apk:classes31.dex)
10-06 20:00:54.677 21622-22213/com.offerclout.offermania W/System.err:     at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:451)
10-06 20:00:54.677 21622-22213/com.offerclout.offermania W/System.err:     at net.gotev.uploadservice.UploadTask.run(UploadTask.java:144)
10-06 20:00:54.677 21622-22213/com.offerclout.offermania W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-06 20:00:54.677 21622-22213/com.offerclout.offermania W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-06 20:00:54.677 21622-22213/com.offerclout.offermania W/System.err:     at java.lang.Thread.run(Thread.java:818)

### Additional info
i think it is something related to support library versions.
i am using support library with 26.0.0-alpha1

**Comment by gotev** [comment]
Double check your gradle dependencies. This is happening because at runtime the resolved version of the support library is < 26. Probabily some of your dependencies uses an older version. It happenened to other users already, check the closed issues.
