### ISSUE TITLE
Pass intent extra in onCompleted callback

### ISSUE THREAD

**Issue by kim1059** [gotev/android-upload-service#329]
I need some help here. I have looked everywhere inside issues and the code, but could not find what I need. 
I make a MultipartUploadRequest and setNotificationConfig as well. After the upload is finished I need to open Activity with a "specific id" returned inside onComplete callback. 
Currently I don't see a way to accomplish this. Is there something I am missing?

**Comment by gotev** [comment]
You can actually start services or activities from the callback since you have the context passed 😀 

What you mean by "specific ID"?

**Comment by kim1059** [comment]
In my case I upload a video. When the video is finished uploading I receive id in my db of the uploaded video. So when I click on notification I want to open activity and pass the id of the video.

**Comment by gotev** [comment]
This is not something regarding the library itself, but common Android programming. Imagine you get a JSON like this from your server: 
```json
{
  "video_id": "43839847923"
}
```
In the onCompleted method you will have to write (add Gson library to your Gradle first):
```java
@Override
public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
    JsonObject json = new Gson().fromJson(serverResponse.getBodyAsString(), JsonObject.class);
    String videoId = json.get("video_id").getAsString();

    Intent intent = new Intent(context, YourActivity.class); 
    intent.putExtra("videoId", videoId);
    context.startActivity(intent);
}
```

**Comment by kim1059** [comment]
I appreciate that you respond so quickly. 
I think you misunderstood me. 

`Intent intent = new Intent(context, YourActivity.class); 
 intent.putExtra("videoId", videoId);`

This intent I want to pass inside:
`UploadNotificationConfig().setClickIntent()`

so that after I click on notification this activity is opened.

**Comment by gotev** [comment]
So you need to add an action to the completed notification which opens the activity, right? 😃

**Comment by kim1059** [comment]
correct :) is it possible?

**Comment by gotev** [comment]
It's possible if you add an action to the completed notification. You can set a PendingIntent for each action. Please check the working example of that in the demo app provided

**Comment by kim1059** [comment]
I feel myself a bit dumb. But I think I have looked everywhere, but not sure how to use it. I did this:

`@Override
 public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
      NPost nPost = NPostFactory.toPost(gson.fromJson(serverResponse.getBodyAsString(), Content.class));
      Intent intent = new Intent(myactivity, otheractivity);
      intent.putExtra("id", nPost.getId()); 
      PendingIntent pendingIntent = PendingIntent.getActivity(Amyactivity, 1, intent, PendingIntent.FLAG_UPDATE_CURRENT);

      // this is try number 1
      config.getCompleted().actions.add(new UploadNotificationAction(drawable, null, pendingIntent ));

     // this is try number 2
     config.getCompleted().clickIntent = intent;
}`

**Comment by kim1059** [comment]
Was the last comment not well explained? :smiley:

**Comment by gotev** [comment]
What are you trying to do in the onCompleted callback is not possibile, because the notification configuration is made [once before the upload is started](https://github.com/gotev/android-upload-service/wiki/Recipes#-notification-configuration) and it's immutable. What are you trying to do is to display dynamic actions in the notifications, which at the moment is not supported. What you can do as a workaround, is to add a pending intent to a particular activity or service before starting the upload, then have that service or activity read a value from a shared preference or in-memory variable and then populate that value in the on completed method.

**Comment by kim1059** [comment]
This is it. Thanks! I used shared prefs to save the id :)
