### ISSUE TITLE
Passing Bitmap base 64 string 

### ISSUE THREAD

**Issue by bhavinsetubridge** [gotev/android-upload-service#332]
### Version info
* Android Upload Service version: 
* Android version and API version: 7.0 Nought
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
 new MultipartUploadRequest(context, uploadId, JsonConstants.LOCAL_UPLOAD)
                    .setAutoDeleteFilesAfterSuccessfulUpload(true)
                    .addFileToUpload(filePath, "image") //Adding file
                    .addParameter("name", file.getName().trim())
                    .addParameter("device_name", deviceName.trim())
                    .addParameter("device_model", deviceModel.trim())
                    .addParameter("email_id", email_id.trim())
                    .addParameter("tokenKey", tokenKey.trim())
                    .addParameter("appVersion", appverison.trim())
                    .addParameter("device_id", device_id.trim())
                    .addParameter("isProject", String.valueOf(is_Project).trim())
                    .addParameter("proj_id", proj_id)
                    .addParameter("clone_response", clone_response)
                    .addParameter("user_screenshot", user_screenshot)
                    .addParameter("mockup_screenshot", mockup_screenshot)

                    .setMaxRetries(2).startUpload();
```

### Request code:
```java
                    .addParameter("user_screenshot", user_screenshot)// bitmap base64 string
                    .addParameter("mockup_screenshot", mockup_screenshot)// bitmap base64 string
```
#### Where have you added the request code?
 while bitmap save to sd card using  Asyntask onPostExecute

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
``` failed to server 
// your server side log here
```

### Additional info
While passing bitmap base64 string to there is throw parse too long string exception .

**Comment by gotev** [comment]
If you need base 64 a custom upload type has to be implemented. The library does not support it out of the box because it's an old way of uploading, which is less efficient than multipart or binary upload, because it requires more bandwidth. The world has to move forward, but if you have to interface your app  with an old backend, don't worry, Upload Service uploads are implemented as  plugins, so you can add what you need. I suggest you to look at how Binary upload request and multipart have been implemented and refer to the developer manual in the wiki :smiley:
