### ISSUE TITLE
change notification

### ISSUE THREAD

**Issue by fatemeh2sh** [gotev/android-upload-service#335]
how can i change notification after upload completed. 
i dont mean this :
 config.getCompleted().message = getString(R.string.str_message_success_upload);
        config.getCompleted().iconResourceID = R.drawable.ic_check_white_18;
        config.getCompleted().iconColorResourceID = Color.GREEN;

.
because it is possible ,my server check options and back message failed,but upload file finish then i want to change message notification after completed.

is it possible?

**Comment by gotev** [comment]
With current version 3.4.1 you can only set messages before the upload has been started. However, if you just want to display some custom message after the upload gets completed, you can set

```java
config.getCompleted().autoClear = true
```

And then create your custom notification in the `onCompleted` callback

**Comment by fatemeh2sh** [comment]
ok, then i create my custom notification.
thanks
