### ISSUE TITLE
Image upload successfully but does not show up in the server (uploads)

### ISSUE THREAD

**Issue by abdelmounim** [gotev/android-upload-service#337]
### What did you expect?
I wanted to upload images from my phone to my server , with low quality images everything work fine , but when it comes to the photos taken by my phone it does not work.
### What happened instead?
when i try to upload big images , it says Image Upload successfully , but instead i can't find them in the server, and the wierd thing is that they are added in phpmyadmin.
any clue ?
### Version info
* Android Upload Service version: 3.1
* Android version and API version: 17
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
compile 'net.gotev:uploadservice:3.1'

### Request code:
`//Creating a multi part request
            new MultipartUploadRequest(this, uploadId, UPLOAD_URL)
                    .addFileToUpload(path, "image") //Adding file
                    .addParameter("name", name) //Adding text parameter to the request
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload(); 
#### Where have you added the request code?
- [X ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

**Comment by gotev** [comment]
It seems totally a backend issue

**Comment by Shakezulla57** [comment]
I just started seeing a similar issue when updating to 3.4.1. I've sat and tested uploading the same file multiple times. The issue I've seen is that sometimes non of the callbacks get called after a successful upload. `onError`, `onComplete` and `onCancelled don't get hit.
