### ISSUE TITLE
sample is not working

### ISSUE THREAD

**Issue by barron9** [gotev/android-upload-service#338]
the minimal sample doesn't work.trigger from intent I am trying to find out why

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        UploadService.NAMESPACE = "com.bdm5";
        UploadService.HTTP_STACK = new OkHttpStack(); // a new client will be automatically created

        Handler mHandler = new Handler(getMainLooper());
        mHandler.post(new Runnable() {
            @Override
            public void run() {

                try {
                    File f = new File("/data/data/com.bdm5.proxy/savedData.txt");
                    //f.createNewFile();

                    final FTPUploadRequest request = new FTPUploadRequest(MainActivity.this, "a", "ftp-sa.com", 21)
                            .setMaxRetries(4)
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setUsernameAndPassword("tsss", "xxxxx")
                            .setCreatedDirectoriesPermissions(new UnixPermissions("777"))
                            .setSocketTimeout(5000)
                            .addFileToUpload("/data/data/com.bdm5.proxy/savedData.txt", "/www")

                            .setConnectTimeout(5000);
                    request.startUpload();

                } catch (Exception exc) {
                    Log.d("AndroidUploadService", exc.getMessage(), exc);
                }

**Comment by gotev** [comment]
Can't understand why you need to invoke the service from a new thread

**Comment by barron9** [comment]
i have tried clean mainactivity with minimal example still notification gives error ... after 10 20 seconds21:54, 5 Aralık 2017, Alex Gotev <notifications@github.com>:Can't understand why you need to invoke the service from a new thread

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Yandex.Mail mobil uygulamasından gönderildi

**Comment by barron9** [comment]
i need simplest example only one activity how can i do that

**Comment by barron9** [comment]
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
        UploadService.EXECUTE_IN_FOREGROUND=false;
        UploadService.HTTP_STACK = new OkHttpStack(); // a new client will be automatically created
        try {
            File f = new File("/data/data/com.bdm5.proxy/savedData.txt");
            //f.createNewFile();


            final FTPUploadRequest request = new FTPUploadRequest(MainActivity.this, "a", "ftp-tempmaill.alwaysdata.net", 21)
                    .setMaxRetries(4)
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setUsernameAndPassword("tempmaill", "000000")
                    .setCreatedDirectoriesPermissions(new UnixPermissions("777"))
                    .setSocketTimeout(5000)
                    .addFileToUpload("/data/data/com.bdm5.proxy/savedData.txt", "/www")

                    .setConnectTimeout(5000);
            request.startUpload();

        } catch (Exception exc) {
            Log.d("AndroidUploadService", exc.getMessage(), exc);
        }

this code is not working notification gives upload error

**Comment by gotev** [comment]
Sorry to disappoint you but that stack trace is not referring to an error from the library, but to some media player.

Please enable library debug log and post it here, so we can spot where the problem exactly is :smiley:

**Comment by barron9** [comment]
can you please send me one page mainactivity that works??

**Comment by gotev** [comment]
@barron9 the double ?? should be avoided, as it sounds nervous. Since you are asking for help, the library debug log is really useful to spot instantly what's going wrong in your specific case, otherwise it's hard to help you. The log you posted is not referred to the FTP upload problem.

Definitely suggest you to remove this line:
```java
UploadService.EXECUTE_IN_FOREGROUND=false;
```
As you may have problems with Android Oreo. I suggest to leave that by default which is true. A foreground service is a service that the user is actively aware of and is not a candidate for the system to kill when low on memory. It doesn't mean it will be run on the main thread.

Remove also this line:
```java
UploadService.HTTP_STACK = new OkHttpStack(); // a new client will be automatically created
```
as you are using FTP and not HTTP.

This works with my test FTP server.
```java
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
Logger.setLogLevel(LogLevel.DEBUG);

try {
    final FTPUploadRequest request = new FTPUploadRequest(this, "ftp.server.com", 21)
            .setMaxRetries(4)
            .setNotificationConfig(new UploadNotificationConfig())
            .setUsernameAndPassword("username", "password")
            .setCreatedDirectoriesPermissions(new UnixPermissions("777"))
            .setSocketTimeout(5000)
            .addFileToUpload("/path/to/your/file", "/www/")

            .setConnectTimeout(5000);
    request.startUpload();

} catch (Exception exc) {
    Log.d("AndroidUploadService", exc.getMessage(), exc);
}
```
