### ISSUE TITLE
android.os.TransactionTooLargeException when server returns a large response after upload

### ISSUE THREAD

**Issue by lini** [gotev/android-upload-service#342]
### What did you expect?
After finishing a file upload, the `UploadTask.broadcastCompleted` method sends a broadcast that includes the server response. The HTTP test service I tried using returns the uploaded file contents in its response.  I expected that this will not be a problem for the upload library.

### What happened instead?
If the response body is large (because it includes the contents of the uploaded file), this will produce an error due to exceeding the maximum parcel size in Android (1MB).

App crashes or the error handler in my broadcast receiver is called after the file has finished uploading.

### Version info
* Android Upload Service version: 3.4.1
* Android version and API version: 8 / API 26
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### Steps to reproduce (if applicable):
Post a large file (>1mb) to the https://httpbin.org/post test service using BinaryUploadRequest. 

### Library initialization code:
```java
// the code you wrote in your Application subclass here
UploadService.NAMESPACE = "org.mycompany.myapp";
```

### Request code:
```java
// the code you wrote to create the upload request
 final BinaryUploadRequest request = new BinaryUploadRequest(context, "imageUpload{1}", "http://httpbin.org/post")
.setFileToUpload(file)
.setMethod("POST");

request.addHeader("Content-Type", "application/octet-stream");
request.addHeader("File-Name", "nameOfFile");
request.startUpload();
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
12-06 18:01:49.002 754-781/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 921852)
12-06 18:01:49.003 754-781/? W/BroadcastQueue: Can't deliver broadcast to org.mycompany.myapp (pid 19072). Crashing it.
12-06 18:01:49.004 754-781/? W/BroadcastQueue: Failure sending broadcast Intent { act=net.gotev.uploadservice.broadcast.status flg=0x10 (has extras) }
                                               android.os.TransactionTooLargeException: data parcel size 921852 bytes
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

https://httpbin.org/post

#### Server log (if applicable)
N/A

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

Tracing the error led to here:
https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L313

Server response is included in the data sent and there is no verification about its size.

The server returns a JSON object with all post data including the base64 encoded contents of the posted file. This response is often large due to the size of the uploaded file:

```
{
  "args": {}, 
  "data": "", 
  "files": {
    "nameOfFile": "<BIG BASE64 ENCODED STRING HERE WITH CONTENTS>"
  } 
 // ... more data returned here
}
```

**Comment by gotev** [comment]
> The HTTP test service I tried using returns the uploaded file contents in its response. I expected that this will not be a problem for the upload library.

The library has not been designed to handle big responses from the server after an upload, so at the current state of the art, it's normal you're getting this error.

Big responses cannot be passed in intents by Android design, to keep the app responsive and the whole library is based on intents to pass data to and from the service.

From my point of view, handling big responses means downloading the response body got from the server in a temporary location and then returning the path to the response payload in the intent. This could work for your use case, but it will be an overkill in the vast majority of the cases when the response is a simple json or plain text. I'm open to suggestions and considerations.

**Comment by lini** [comment]
Honestly speaking, I don't need this to be fixed, as the service that produces this issue is just used for testing. It is, however, a limitation that should be known and probably documented. It will save people some time debugging an unknown issue that crashes the whole app.

**Comment by gotev** [comment]
Completely agree with you 😃

**Comment by gotev** [comment]
Created [Known limitations](https://github.com/gotev/android-upload-service/wiki/Recipes#-known-limitations) section in the wiki. @lini thanks for the feedback

**Comment by UrielVela** [comment]
Se produce un error duran el momento de carga de la imagen, estoy usando una aplicación que permite subir fotos ya sea desde la camara o desde la galería. El servidor arroja en sus logs invalid response status 44. La carga la hago desde una app en Android.

![captura](https://user-images.githubusercontent.com/36978294/50378845-11825980-0601-11e9-80e0-fb6d34a1720c.PNG)
