### ISSUE TITLE
How to rename the file before uploading.

### ISSUE THREAD

**Issue by haneef5k** [gotev/android-upload-service#345]
### What did you expect?
I want to add new file name before uploading.

### What happened instead?

I don't see any param to pass.

### Version info
3.4.1

**Comment by gotev** [comment]
Follow recipes wiki page to see how to add files and check linked javadocs for more advanced usages. Renaming files on the device file system is up to you before uploading, not responsibility of the library. What you can do is to assign a file name to to the uploaded file, which is the file name seen by the server. That's also explained in detail in the JavaDocs. If you find some missing docs, open a new issue :smiley: providing as much detail as you can, thank you!

**Comment by haneef5k** [comment]
Thanks !
