### ISSUE TITLE
Resume FTP uploads

### ISSUE THREAD

**Issue by runryan** [gotev/android-upload-service#346]
FTPUploadRequest class just provides addFileToUpload method. I wonder if it supports the function like appendFileToUpload. I mean when upload a large file for a long time, it may be  interrupted for some reasons. can I just upload the unupload parts but all the file?

**Comment by gotev** [comment]
Currently you have to reupload the last unsuccessful file from the start. Upload Service leverages Apache FTP library, which I don't know if supports this feature, since I haven't found any docs regarding it

**Comment by MobDeveloper163** [comment]
org.apache.commons.net.ftp.FTPClient class contains such methods like "appendFileStream(String remote)". it means we can append others parts of file to the same file on server. 

we can list files from server with "FTPClient.listFiles(String remotePathname)".  Comparing the local file size with the remote file, we can find the different part. Then use  appendFileStream(String remote) method to append to the remote file.

if you think this is a way to complete it, hope you can add it to the library. Thank you for your great work!

**Comment by gotev** [comment]
@MobDeveloper163 that sounds like it could work! I'm really busy in this period, so feel free to fork and send me a PR 😉

**Comment by Weakey** [comment]
I found a sample code about this feature for your reference.

https://blog.csdn.net/voyage_mh1987/article/details/7354014

**Comment by gotev** [comment]
Closing this due to lack of contributions so far
