### ISSUE TITLE
Perform different actions in the onCompleted method based on the upload type

### ISSUE THREAD

**Issue by falary1** [gotev/android-upload-service#347]
### What did you expect?
Trigger method in OnCompleted every time an upload is completed (Broadcast receiver inside Activity).

### What happened instead?
Called multiple times, as many time as the number of total successful uploads.

### Version info
* Android Upload Service version: all
* Android version and API version: 26

### Request code:
```java
		String uploadId =
					new BinaryUploadRequest(context, UrlUpload)
							.setBasicAuth(SaveSharedPreference.getUserName(context), SaveSharedPreference.getPassword(context))
							.setFileToUpload(path)
							.setMaxRetries(3)
							.setAutoDeleteFilesAfterSuccessfulUpload(true)
							.startUpload();
```

#### Where have you added the request code?
- [ ] Activity

### Additional info
I think maybe that's the normal behavior but i just want to call a method (once) a the end of every upload. How can i achieve that?  I can't use delegates cause i need a service and maybe i have to do something with shouldAcceptEventFrom but i didn't success to manage the end of every upload one by one. If someone can show me the way i will be grateful, i'm really stuck on it;)

**Comment by gotev** [comment]
Every upload has an unique upload ID, which you can use to perform different actions in the receiver. The uploadID is a string and tou can use also a custom one. Check recipes wiki page to see how.

I'll give you an example. Imagine you have three types of uploads and so you need to perform three different actions in the receiver. You can create the upload ID like this:

```Kotlin
val uploadID = "UPLOAD_ACTION" + UUID.randomUUID().toString()
```
Where `UPLOAD_ACTION` will be different based on the upload type. Then, in the onCompleted of the broadcast receiver, you can do different things based on that

```Kotlin
if (uploadID.startsWith("UPLOAD_ACTION1")) {
    //Action 1
} else if (uploadID.startsWith("UPLOAD_ACTION2")) {
    //Action 2
}
```
