### ISSUE TITLE
I dont know how to implement Notification channel

### ISSUE THREAD

**Issue by haneef5k** [gotev/android-upload-service#351]
### What did you expect?
I want to upload multi-part files with notification.
### What happened instead?
Im facing continuous notification sound.

### Version info 3.4.1
* Android Upload Service version:27.0.2
* Android version and API version:  3.4.1

### Additional info
 How to implement notification channel in my app. Its keep shooting continuous sound in android Oreo (8.0)

i gone through sample app its bit advances.

**Comment by gotev** [comment]
Merging in #324
