### ISSUE TITLE
Uploading Notification For Android Oreo Devices

### ISSUE THREAD

**Issue by khimamsh** [gotev/android-upload-service#353]
### What did you expect?
I want show notification in android oreo running devices, which needs Channels and channel ID to be configured.

**Comment by gotev** [comment]
Help me help you. Issue templates are here for this :wink:

Provide the code and all the details of your specific implementation, thank you :smiley:

**Comment by khimamsh** [comment]
Actually you have specified code regarding notification while uploading file , That is not working in android oreo.
even i to dont have that code regarding this, Because we will be just adding dependencies .
Thank You.
Regards:Himamsh K

**Comment by varunchandran333** [comment]
Do this library have support for SFTP?

**Comment by gotev** [comment]
@varunchandran333 completely OT here

@khimamsh 

> Actually you have specified code regarding notification while uploading file, That is not working in android oreo.
Are you using broadcast receiver or the delegate?

> even i to dont have that code regarding this, Because we will be just adding dependencies .
Sorry, can't understand what you wanted to say. Can you explain it in another way?

**Comment by haneef5k** [comment]
Still even i cant achieve notification on Android Oreo..  if i enable default notification config 
 .setNotificationConfig(new UploadNotificationConfig()). i'm getting continues  notification tone. 

And  i don't see any recipe how to implement notification channel for this library as beginner.



'protected UploadNotificationConfig getNotificationConfig(final String uploadId, String title) {
        UploadNotificationConfig config = new UploadNotificationConfig();

        PendingIntent clickIntent = PendingIntent.getActivity(
                getContext(), 1, new Intent(getContext(), MainActivity.class), PendingIntent.FLAG_UPDATE_CURRENT);

        String mbrMajlisUploadChannel = "mbrmajlis_channel";

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {

            String notificationChannelId = params.notificationConfig.getNotificationChannelId();
           // notificationChannelId = params.notificationConfig.getNotificationChannelId();
            if (notificationChannelId == null) {
               // config.setNotificationChannelId(mbrMajlisUploadChannel);
                notificationChannelId = UploadService.NAMESPACE;
            }

            config.setNotificationChannelId(notificationChannelId);
            
        }

        config.setTitleForAllStatuses((title))
                .setRingToneEnabled(false)
                .setClickIntentForAllStatuses(clickIntent)
                .setIconForAllStatuses(R.mipmap.ic_launcher)
                .setLargeIconForAllStatuses(BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher))
                .setClearOnActionForAllStatuses(true);

//        config.getProgress().message = "Uploaded " + UPLOADED_FILES + " of " + TOTAL_FILES
//                + " at " + UPLOAD_RATE + " - " + PROGRESS;
//        config.getProgress().iconResourceID = R.drawable.ic_upload;
//        config.getProgress().iconColorResourceID = Color.BLUE;

        config.getCompleted().message = "Upload completed successfully";
//        config.getCompleted().iconResourceID = R.drawable.ic_upload_success;
//        config.getCompleted().iconColorResourceID = Color.GREEN;

        config.getError().message = "Error while uploading";
//        config.getError().iconResourceID = R.drawable.ic_upload_error;
//        config.getError().iconColorResourceID = Color.RED;

        config.getCancelled().message = "Upload has been cancelled";
//        config.getCancelled().iconResourceID = R.drawable.ic_cancelled;
//        config.getCancelled().iconColorResourceID = Color.YELLOW;


        return config;
    }`

**Comment by FilipMarusca** [comment]
any updates here?
