### ISSUE TITLE
Android Oreo Background Limitations

### ISSUE THREAD

**Issue by mfrtrifork** [gotev/android-upload-service#359]
### What did you expect?
I expected my upload to be executed.

### What happened instead?
App crashed due to new Background Limitations on Android Oreo.

java.lang.IllegalStateException: Not allowed to start service Intent { act=bundle.identifier.upload cmp=bundle.identifier.development/net.gotev.uploadservice.UploadService (has extras) }: app is in background uid UidRecord{6d173b4 u0a134 TRNB idle change:idle|uncached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
	at android.app.ContextImpl.startService(ContextImpl.java:1477)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at net.gotev.uploadservice.UploadRequest.startUpload(UploadRequest.java:68)
	at net.gotev.uploadservice.BinaryUploadRequest.startUpload(BinaryUploadRequest.java:94)
### Version info
* Android Upload Service version: 3.4.1
* Android version and API version: 8.1.0
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Steps to reproduce (if applicable):
I use jobdispatcher to start the upload in the background. But startService will always crash when app is in background. I would expect the service to startInForeground if Android Oreo, perhaps with a user defined notification icon.

Let me know if this is insufficient for a bug report or if further information is needed.

Thanks for an otherwise great library :)

**Comment by gotev** [comment]
Thanks for the report. If I understand correctly, you are starting the service from a scheduled job while your app is in the background, right?

**Comment by mfrtrifork** [comment]
@gotev Yes, exactly.

**Comment by gotev** [comment]
The background service starts in foreground execution by default, but I suspect this error is due to the fact that Oreo has limited the startService method while the app is in the background, so there may be no easy workaround to overcome this limitation without migrating to the JobScheduler API. I need to make some research. Help is greatly appreciated.

**Comment by mfrtrifork** [comment]
Hi @gotev.
I think a quick-fix (maybe not the most beautiful) to prevent the apps from crashing is simply to check the API level and open the service in foreground or background.
``` 
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    startForegroundService(intent);
} else {
    startService(intent);
} 
```

**Comment by gotev** [comment]
@mfrtrifork yes that's a good point. Also when on Oreo we have to force the notification config to be setup declared when making the request

**Comment by guerrillalg** [comment]
@gotev , When you are going to take a decision regarding the implementation, please keep in mind the following things:
There should be different strategies and ways of showing notifications (One notification for all uploads vs Notification per each upload).
There should be possibility to configure and control the notifications being shown from the app.

I think, all the work with notifications should be externalized to a set of Strategies, where developers could control notifications.
However, I see that in current situation it is not easy to do. It might require big changes in the code.

**Comment by mfrtrifork** [comment]
@guerrillalg @gotev - A simple temporary solution that I used is to check the API level and if Oreo then just start a foregroundService which is alive while uploading. Then the startService method call in this library is allowed since we a foregroundService and hence is in the foreground.
This also means that you can customize it with the icon and click intent you want.

**Comment by gotev** [comment]
@guerrillalg you're right. I think some big changes are required to make things more flexible and I lile yoir idea. We could open a new 4.x branch a together build the new version without having to care about retrocompatibility issues.

As a temporary fix for Oreo, I'm going to release annew version in the next few days

**Comment by gotev** [comment]
version 3.4.2 released

**Comment by theshethmilan** [comment]
After writing this line in Application subclass oncreate a very first line

UploadServiceConfig.initialize(this, CHANNEL, BuildConfig.DEBUG);

Application gets keep crashing saying

You have to set namespace to your app package name (context.packageName) in your Application subclass

I am using implementation 'net.gotev:uploadservice:4.3.1'
