### ISSUE TITLE
How to get the upload progress of all files

### ISSUE THREAD

**Issue by wang9090980** [gotev/android-upload-service#361]
Hi：
  I want to get the upload progress of all uploaded files at once.How do I deal with it?
  Thanks！

**Comment by gotev** [comment]
Unless you upload N files in the same request, this is not supported yet. If you have ideas about how to do it, you're welcome and let's talk about it 😉

**Comment by marcherdiego** [comment]
I would divide the total uploaded bytes by the sum of the whole pool of bytes to be uploaded in the first place

**Comment by gotev** [comment]
@marcherdiego it's already like that when you have all the files in the same request, but it won't be safe or clean to do it for N independent requests. What will you do of one of the New requests temporarily or permanently fail?

**Comment by Aravindraj93** [comment]
It would be great, if we can show the uploading progress within the app itself. Waiting for the update Thank you for the library.@gotev

**Comment by gotev** [comment]
Since I personally don't need to have this feature and no PR has come in a long time, I'm closing this. Feel free to reopen it if you want to contribute with a PR.
