### ISSUE TITLE
Inside app notifications.

### ISSUE THREAD

**Issue by WestBonner** [gotev/android-upload-service#365]
I'm using the following code to control the upload events:

       `public void uploadMultipart(final Context context) {
             
        String Address = 'Address'
        String City= "City";
        String Dest = "Dest";
        String Code = "Code";
        String path = "My file";
        try {
            String uploadid =
                    new MultipartUploadRequest(context, MY_UPLOAD_URL)
                            .setUtf8Charset()
                            .setAutoDeleteFilesAfterSuccessfulUpload(true)
                            .addFileToUpload(path, "image")
                            .addParameter("Address", Address)
                            .addParameter("City", City)
                            .addParameter("Dest", Dest)
                            .addParameter("Code", Code)
                            .setMaxRetries(2)
                            .setDelegate(new UploadStatusDelegate() {
                                @Override
                                public void onProgress(Context context, UploadInfo uploadInfo) {
                                Toast.makeText(getApplicationContext(), "Processing", Toast.LENGTH_LONG).show();
                                }

                                @Override
                                public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse,
                                                    Exception exception) {
                                    Toast.makeText(getApplicationContext(), "Error", Toast.LENGTH_LONG).show();
                                }

                                @Override
                                public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
                                    Toast.makeText(getApplicationContext(), "Success", Toast.LENGTH_LONG).show();

                                }

                                @Override
                                public void onCancelled(Context context, UploadInfo uploadInfo) {
                                    Toast.makeText(getApplicationContext(), "Canceled", Toast.LENGTH_LONG).show();
                                }
                            })
                            .startUpload();
        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }
    }`

When i'm connected to internet the 'Processing' and 'Sucess' messages are displayed correctly. However if I disconnect from the internet and redo the operation the "Error" message is displayed without displaying the "Processing" message. What am I doing wrong?

**Comment by gotev** [comment]
This is perfectly fine, as the connection to the server cannot be established and you directly get the error message after two failed attempts. Enable the debug log and you will see it.

The onProgress is invoked only if the connection is established and the transfer is ongoing.
