### ISSUE TITLE
Error during upload

### ISSUE THREAD

**Issue by djoxy032** [gotev/android-upload-service#367]
### What did you expect?
Expected to send multipart form data(image and size) but fails to upload data.
### What happened instead?
After a while of trying to upload image and parameter(size) just commes error during upload
### Version info
* Android Upload Service version:3.3
* Android version and API version: 26
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java   public void uploadMultipart() {
        //getting name for the image
        String name = editText.getText().toString().trim();

        //getting the actual path of the image
        String path = getPath(filePath);
        Integer size = 0;
        //Uploading code
        File file = new File(path);
        Bitmap bf = BitmapFactory.decodeFile(path);
        Integer height = bf.getHeight();
        Integer width = bf.getWidth();
        size = width*height;
        try {
            //Creating a multi part request
            new MultipartUploadRequest(this.getApplicationContext(), "", Constants.UPLOAD_URL)
                    .addFileToUpload(path, "file") //Adding file
                    .addParameter("size", size.toString()) //Adding text parameter to the request
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload(); //Starting the upload

        } catch (Exception exc) {
            Toast.makeText(this, exc.getMessage(), Toast.LENGTH_SHORT).show();
        }
    }

    public String getPath(Uri uri) {
        Cursor cursor = getContentResolver().query(uri, null, null, null, null);
        cursor.moveToFirst();
        String document_id = cursor.getString(0);
        document_id = document_id.substring(document_id.lastIndexOf(":") + 1);
        cursor.close();

        cursor = getContentResolver().query(
                android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
                null, MediaStore.Images.Media._ID + " = ? ", new String[]{document_id}, null);
        cursor.moveToFirst();
        String path = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DATA));
        cursor.close();

        return path;
    }
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [x ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Flask server works fine with postman that i tested. I set key:file, value:file(image) and key:size, value:text.
Working fine with postman.
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
As i mentioned i tested with postman and it works fine. No errors during execution of application but when it comes to uploading it shows message File Upload: Error during upload

**Comment by gotev** [comment]
Update to 3.4.2 which supports Oreo. 3.3 is old and has security issues.

**Comment by djoxy032** [comment]
I tried to use 3.4 but application crashes when it comes to upload.

**Comment by gotev** [comment]
Post the library debug log

**Comment by djoxy032** [comment]
I had a minor bug but still the same problem with upload error. There is not crash errors but only upload error.

**Comment by djoxy032** [comment]
![debug](https://user-images.githubusercontent.com/10166215/36617360-577f1c96-18e7-11e8-82eb-4b7a655a28d6.png)

**Comment by gotev** [comment]
Without a library log there's nothing I can do to help you based on the information you provided. There are too many things which can cause that error. I suggest you to open the Troubleshooting guide in the wiki a follow it. In the vast majority of the cases it can help you find what's wrong. I'm closing this :wink:

**Comment by ke-mo-sa-be** [comment]
Im having trouble uploading file... notification says "Error during upload". There is not log showing up ??

**Comment by gotev** [comment]
Check library debug logs in LogCat. On 4.x they are automatically enabled for debug builds. For more detailed debugging instructions, check the [wiki](https://github.com/gotev/android-upload-service/wiki) troubleshooting page

**Comment by ke-mo-sa-be** [comment]
> Check library debug logs in LogCat. On 4.x they are automatically enabled for debug builds. For more detailed debugging instructions, check the [wiki](https://github.com/gotev/android-upload-service/wiki) troubleshooting page

![image](https://user-images.githubusercontent.com/30124774/77742675-dd37ed00-703c-11ea-9634-1c20a127a16a.png)

**Comment by gotev** [comment]
Please open a new issue, providing all the information requested in the issue template.

**Comment by ke-mo-sa-be** [comment]
> Check library debug logs in LogCat. On 4.x they are automatically enabled for debug builds. For more detailed debugging instructions, check the [wiki](https://github.com/gotev/android-upload-service/wiki) troubleshooting page

![image](https://user-images.githubusercontent.com/30124774/77742750-fb055200-703c-11ea-9db9-7edc224237f5.png)
