### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by Mritunjay10** [gotev/android-upload-service#368]
### What did you expect?
I do want to know how to change the title of the file uploading notification?
### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Hi and thank you for this issue. I need some feedback. There's a wiki full of information, including the response to your question, but somehow people miss it or doesn't seem to find it, even if it's linked in the readme. You're not the first so don't worry : wink:

Since this is an open source projects aimed at continuous improvement, any suggestion on how to make it easier for anyone to find the wiki is very appreciated :wink:

Thank you

**Comment by Mritunjay10** [comment]
Sorry, but I failed to find the answer to my question even I read through the readme and the links given in it.
Can you give me the link or hint me the code.
Your help will be highly appreciated!

**Comment by Mritunjay10** [comment]
Sorry, to bother but I found the way out!

Your work is highly appreciated you created a full working code base on REST API and I must say it's easy to use and works like a charm.

Again, thanks, brother you rocked!

**Comment by gotev** [comment]
Glad you foind the answer! Any suggestions on how to make the wiki or the directions easier for a newcomer? :)

**Comment by gotev** [comment]
@Mritunjay10 any suggestion to make things easier to find or to improve the library and docs are really appreciated, feel free to open new issues with your proposals :wink: Open Source is great because of many people's point of views and feedbacks. I'm closing this :wink:
