### ISSUE TITLE
optional value in multipart upload request

### ISSUE THREAD

**Issue by harishrawal** [gotev/android-upload-service#370]
### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Please be more specific

**Comment by harishrawal** [comment]
I want to add path(image path) but my uri is null . how to send the null path in api.

**Comment by harishrawal** [comment]
try {
              String uploadId = UUID.randomUUID().toString();
              new MultipartUploadRequest(this, uploadId, Constant.add_member_signup)
                      .addFileToUpload(pathapplicant_imageS, "photograph")
                      .addFileToUpload(pathnominee_imageS, "nominee_photograph")
                      .addFileToUpload(path1, "photograph")
                      .addFileToUpload(path2, "nominee_photograph")
                      .addFileToUpload(path3, "docs[0][]") // path3 is not mendatory. if path3 is not available my api is not hit. Please suggest me!  
                      .addFileToUpload(path4, "docs[1][]")
                      .addFileToUpload(path5, "docs[2][]")              
                      .addParameter("api_token", api_token_string)
                      .addParameter("salutation", salutationS)
                      .addParameter("name", first_nameS)
                      .addParameter("father_husband_name", father_husband_nameS)
                      .addParameter("designation", designationS)
                      .addParameter("hq", hqS)
                      .addParameter("address", current_addressS)
                      .addParameter("dob", dobS)
                      .addParameter("doa", doaS)
                      .addParameter("dor", dorS)
                      .addParameter("permanent_address", permanent_addressS)
                      .addParameter("admission_cheque", addmissison_cheque_noS)
                      .addParameter("cheque_amount", amountS)
                      .addParameter("mobile_no", mobile_noS)
                      .addParameter("whatsapp_no", altmobile_noS)
                      .addParameter("acc_no", bank_acc_noS)
                      .addParameter("ifsc_code", ifscS)
                      .addParameter("bank_name", bank_nameS)
                      .addParameter("branch_name", branch_nameS)
                      .addParameter("pf_no", pf_noS)
                      .addParameter("pan_card", pancard_noS)
                      .addParameter("introduce_no", "")
                      .addParameter("railway_id", railway_idS)
                      .addParameter("id_number", voter_idS)
                      .addParameter("blood_group", blood_groupS)
                      .addParameter("nominee_salutation", nom_salutationS)
                      .addParameter("nominee_name", nom_first_nameS)
                      .addParameter("relationship", nom_relationshipS)
                      .addParameter("nominee_phone", nom_mobile_noS)
                      .addParameter("nominee_address", nom_current_addressS)
                      .addParameter("docs_name[0]", "voter ID / Aadhar card")
                      .addParameter("docs_name[1]", "Railways ID card")
                      .addParameter("docs_name[2]", "PAN Card")

                      .addHeader("Accept", "application/json")
                      .setNotificationConfig(new UploadNotificationConfig())
                      .setMaxRetries(2)
                      .startUpload(); //Starting the upload

          } catch (Exception exc) {
              Toast.makeText(this, exc.getMessage(), Toast.LENGTH_SHORT).show();
          }

**Comment by harishrawal** [comment]
path3 is not mendatory. if path3 is not available my api is not hit. Please suggest me!

**Comment by gotev** [comment]
`MultipartUploadRequest` is nothing more than a builder, so simply add optional fields to the request only if they have a value. 
```java
try {
    MultipartUploadRequest req = new MultipartUploadRequest(this, uploadId, Constant.add_member_signup)
                      .addFileToUpload(pathapplicant_imageS, "photograph")
                      .addFileToUpload(pathnominee_imageS, "nominee_photograph")
                      .addFileToUpload(path1, "photograph")
                      .addFileToUpload(path2, "nominee_photograph")
                      .addFileToUpload(path4, "docs[1][]")
                      .addFileToUpload(path5, "docs[2][]")              
                      .addParameter("api_token", api_token_string)
                      .addParameter("salutation", salutationS)
                      .addParameter("name", first_nameS)
                      .addParameter("father_husband_name", father_husband_nameS)
                      .addParameter("designation", designationS)
                      .addParameter("hq", hqS)
                      .addParameter("address", current_addressS)
                      .addParameter("dob", dobS)
                      .addParameter("doa", doaS)
                      .addParameter("dor", dorS)
                      .addParameter("permanent_address", permanent_addressS)
                      .addParameter("admission_cheque", addmissison_cheque_noS)
                      .addParameter("cheque_amount", amountS)
                      .addParameter("mobile_no", mobile_noS)
                      .addParameter("whatsapp_no", altmobile_noS)
                      .addParameter("acc_no", bank_acc_noS)
                      .addParameter("ifsc_code", ifscS)
                      .addParameter("bank_name", bank_nameS)
                      .addParameter("branch_name", branch_nameS)
                      .addParameter("pf_no", pf_noS)
                      .addParameter("pan_card", pancard_noS)
                      .addParameter("introduce_no", "")
                      .addParameter("railway_id", railway_idS)
                      .addParameter("id_number", voter_idS)
                      .addParameter("blood_group", blood_groupS)
                      .addParameter("nominee_salutation", nom_salutationS)
                      .addParameter("nominee_name", nom_first_nameS)
                      .addParameter("relationship", nom_relationshipS)
                      .addParameter("nominee_phone", nom_mobile_noS)
                      .addParameter("nominee_address", nom_current_addressS)
                      .addParameter("docs_name[0]", "voter ID / Aadhar card")
                      .addParameter("docs_name[1]", "Railways ID card")
                      .addParameter("docs_name[2]", "PAN Card")

                      .addHeader("Accept", "application/json")
                      .setNotificationConfig(new UploadNotificationConfig())
                      .setMaxRetries(2)

    if (path3 != null) {
        req.addFileToUpload(path3, "docs[0][]");
    }

    req.startUpload();

} catch (Exception exc) {
    Toast.makeText(this, exc.getMessage(), Toast.LENGTH_SHORT).show();
}
