### ISSUE TITLE
multiple files upload 

### ISSUE THREAD

**Issue by hmskhan** [gotev/android-upload-service#371]
my server side code

$myFile = $_FILES['image'];
$fileCount = count($myFile["name"]);

for ($i = 0; $i < $fileCount; $i++) {
      //file path to upload in the server
      $file_path = "uploads/". $myFile["name"][$i];
      move_uploaded_file($myFile["tmp_name"][$i], $file_path);
}

I add N files to the request using addFileToUpload method but it only uploads the last one.he last one.
Please provide me solution.

**Comment by gotev** [comment]
Check this: https://github.com/gotev/android-upload-service/issues/263
