### ISSUE TITLE
Ringotone notifications can not be disabled on Android O

### ISSUE THREAD

**Issue by dominolog** [gotev/android-upload-service#372]
I am setting 

`setNotificationConfig(new UploadNotificationConfig()
.setRingToneEnabled(false))`

for upload notification. It does work on all OS versions except for Android O (8.0). I can hear notification on that OS for any upload. Do you know how to disable it for Android O?

**Comment by gotev** [comment]
In Android O, the notification sound has to be set on the channel itself, so that method is no longer affecting the ringtone on newer Android versions. Suggest you to check some tutorial about android notification channels. Maybe we can put some info about this in the upload service wiki :wink:
