### ISSUE TITLE
Delegates are not called.

### ISSUE THREAD

**Issue by obaidjatoi** [gotev/android-upload-service#374]
### What did you expect?
I am implementing simple delegates without any configuration changes or any complex scenarios.
### What happened instead?
Delegates were not called. (onProgress , onError, onCompleted, onCancelled, onCompleted)
### Version info
* Android Upload Service version: 
* Android version and API version: Marshmallow : 6.0.1
* HTTP stack (e.g. HurlStack or OkHttpStack): OKhttp

### Steps to reproduce (if applicable): 
 new MultipartUploadRequest(context, URL_UPLOAD_IMAGE)
                            .addParameter("ftype", "Image")
                            .addFileToUpload(sourceImageFile, "uploadedfile", "fileImage", "image/*")
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .startUpload();
**and I have also used this with above code**-- > 
.setDelegate(new UploadStatusDelegate() {
                 @Override
                 public void onProgress(Context context, UploadInfo uploadInfo) {
                     // your code here
                 }

                 @Override
                 public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse,
                                     Exception exception) {
                    // your code here
                 }

                 @Override
                 public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
                    // your code here
                    // if you have mapped your server response to a POJO, you can easily get it:
                    // YourClass obj = new Gson().fromJson(serverResponse.getBodyAsString(), YourClass.class);

                 }

                 @Override
                 public void onCancelled(Context context, UploadInfo uploadInfo) {
                    // your code here
                 }
            })

also I have used global broadcast receiver as instructed in your documentation.

### Library initialization code: 3.4.2
```java
// the code you wrote in your Application subclass here
        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
```

### Request code:
```java
// the code you wrote to create the upload request
String uploadId =
                    new MultipartUploadRequest(context, URL_UPLOAD_IMAGE)
                            .addParameter("ftype", "Image")
                            .addFileToUpload(sourceImageFile, "uploadedfile", "fileImage", "image/*")
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
.setDelegate(new UploadStatusDelegate() {
                 @Override
                 public void onProgress(Context context, UploadInfo uploadInfo) {
                     // your code here
                 }

                 @Override
                 public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse,
                                     Exception exception) {
                    // your code here
                 }

                 @Override
                 public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
                    // your code here
                    // if you have mapped your server response to a POJO, you can easily get it:
                    // YourClass obj = new Gson().fromJson(serverResponse.getBodyAsString(), YourClass.class);

                 }

                 @Override
                 public void onCancelled(Context context, UploadInfo uploadInfo) {
                    // your code here
                 }
            })
                            .startUpload();
```
#### Where have you added the request code?
- [x] Activity  : Used in activity 
- [x] Service : also used your snippet in service but no delegates for monitoring were called.
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here : Nothing
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

Only problem i am facing is my delegates are not called. File / notification every other thing is working perfect. I want to use delegates in service or in global broadcast. but they were not invoked in activity, service or in global broadcast.

**Comment by sraka1** [comment]
@obaidjatoi did you resolve this issue?

**Comment by gotev** [comment]
Please check monitoring wiki page. There's a wide explanation of current state of the art and why you should not use delegates in your specific case. I'm open for new delegates implementation of course :)
