### ISSUE TITLE
Support library 25.0.0

### ISSUE THREAD

**Issue by AngleV** [gotev/android-upload-service#375]
after changing to support library from 25 to 26 i noticed some bugs that has nothing to do with your library but they come from android libs..
Is it possible to keep your latest version with android support library 25 ?

**Comment by gotev** [comment]
If you look at the setup wiki page, there's an example using gradle to force a certain library version. Not sure if v25 will work with latest 3.4.2, which uses support library 26 needed to support Oreo.
