### ISSUE TITLE
SSL handshake aborted

### ISSUE THREAD

**Issue by AlbertoMrFz** [gotev/android-upload-service#376]
### What did you expect?
Upload an image and text to a server
### What happened instead?
I have this error: 
W/System.err: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x72b0bd88: Failure in SSL library, usually a protocol error
W/System.err: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x72b447e8:0x00000000)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:468)
W/System.err:     at com.android.okhttp.Connection.upgradeToTls(Connection.java:1014)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:955)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:405)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:343)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:289)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
W/System.err:     at com.google.firebase.perf.network.zze.getResponseCode(Unknown Source)
W/System.err:     at com.google.firebase.perf.network.zzd.getResponseCode(Unknown Source)
W/System.err:     at net.gotev.uploadservice.http.impl.HurlStackConnection.getResponse(HurlStackConnection.java:148)
W/System.err:     at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:70)
W/System.err:     at net.gotev.uploadservice.UploadTask.run(UploadTask.java:150)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x72b0bd88: Failure in SSL library, usually a protocol error
W/System.err: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x72b447e8:0x00000000)
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:425)
W/System.err: 	... 17 more

### Version info
* Android Upload Service version:3.2.2
* Android version and API version: Android Nougat 7.0 Api 24 And Android kit kat 4.4 Api 19
* HTTP stack (e.g. HurlStack or OkHttpStack): i dont know

### Steps to reproduce (if applicable):
new MultipartUploadRequest(context, idArchivo, urlString)
                        .addFileToUpload(path, "aaaaaaaaa") //Adding file
                        .addParameter("aaaaaa", Metodos.getHashSeguridad()) //Adding text parameter to the request
                        .addParameter(nombreParametro, parametros.replaceAll("\n", "")) //Adding text parameter to the request
                        .setNotificationConfig(uploadConfig)
                        .setMaxRetries(2)
                        .startUpload(); //Starting the upload

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
This is a well known problem with TLS 1.2 on older Android devices. It's not a library problem, but n Android network layer limitation. I suggest you to use OkHttp (check setup wiki) and the suggestions mentioned here: https://github.com/square/okhttp/issues/2372#issuecomment-331623598

**Comment by AlbertoMrFz** [comment]
I have tried on a device with android 7 and the same thing happens to me. So it's not a problem with old devices

**Comment by gotev** [comment]
First, yoi should disable SSLv3, which is unsecure. You can do that independently from the library, acting on the default HttpUrlConnection class or of you use OkHttp, see the above mentioned thread.
