### ISSUE TITLE
Image Not uploaded on Oreo 

### ISSUE THREAD

**Issue by CHIRANJIT1988** [gotev/android-upload-service#378]
### What did you expect?
Image should upload in Oreo if note set m.setNotificationConfig(new UploadNotificationConfig());
### What happened instead?
Image is not uploading if m.setNotificationConfig(new UploadNotificationConfig()); not set in Oreo
### Version info
* Android Upload Service version: 3.4.2
* Android version and API version: 27
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
This has been already asked and responded to in past issues, please search before openinf new ones. However I suggest you to read the Android service documentation for Oreo. It's stated that you can't do background jobs if you don't set a Notification. Upload Service simply complies to standard android specs, so this is not an issue.

**Comment by danangww** [comment]
Thanks, I will try to find out the solution. :)

**Comment by gotev** [comment]
@danangww look [here](https://github.com/gotev/android-upload-service/wiki/Recipes#-notification-configuration)
