### ISSUE TITLE
How can I hide a notification?

### ISSUE THREAD

**Issue by TikTak123** [gotev/android-upload-service#383]
How can I hide a notification?

**Comment by gotev** [comment]
Please provide more details

**Comment by govindtank** [comment]
@TikTak123 if you just don't want to see the notification while uploading happens, just don't add the below line;
            **.setNotificationConfig(new UploadNotificationConfig())**

remove that line, so no notification will be shown on your device, hope it helps

**Comment by govindtank** [comment]
thank you @gotev for the information, i wasn't aware about that notification policy till now in oreo.

**Comment by TikTak123** [comment]
@gotev Thank you

**Comment by Pro-55** [comment]
I want to completely hide the notification while uploading. Can you give a code snippet that can be used to do this? Currently I'm setting the notification to a channel and that channel has lowest importance by default. While uploading the channel importance is set to medium automatically. Do you have any idea why this is happening? Code for my channel is:

`NotificationChannel channelGeneral = new NotificationChannel(channelIdGeneral, channelNameGeneral, NotificationManager.IMPORTANCE_MIN);
        channelGeneral.enableVibration(false);
        channelGeneral.enableLights(false);
        getNotificationManager().createNotificationChannel(channelGeneral);`

**Comment by Pro-55** [comment]
The notification configuration is: 

`private void notificationConfig() {
        config.setNotificationChannelId(channelIdGeneral);
        config.setRingToneEnabled(false);
        config.getProgress().autoClear = true;
        config.getError().autoClear = true;
        config.getCompleted().autoClear = true;
        config.getCancelled().autoClear = true;
    }`

**Comment by Pro-55** [comment]
I have displayed an UI progress bar in the main activity to show the upload progress. So can we expect any bypass for the system notification in the future updates?

**Comment by gotev** [comment]
@Pro-55 As I told you in my previous comment, Android Upload Service uses a Foreground Service to be able to complete the upload operation requested by the user in real time and with high priority, even when the device is idle. As stated by Android docs (https://developer.android.com/guide/components/services) in Android 8 and newer, foreground services MUST display a notification. In one of the paragraphs of the services page I linked, they also explicitly describe that if you set a notification channel to anything below LOW it will be automatically adjusted by the system to display the notification. Reading and studying the docs always pays off. It doesn't matter if you show progress status in your app, Android requires the notification to be there.

After saying that for clarification, let's see if Android service is really what you need.

Android Upload Service purpose is to upload data to a remote server as a result of an user's direct action, like selecting some photos or files to be sent or a sync operation which the user has explicitly set to be done. In this case the user has also the benefit of being informed of the progress even if not using the app.

On the other hand, if you want to do some stuff on the background which are not a consequence of a user-triggered actions, for example you want to send some data or files automatically to your server at some time each day, then you need a different approach and you have to use a Job. In that case have a look at the recently released Work Manager: https://developer.android.com/topic/libraries/architecture/workmanager/ 

Is this upload something which the user wants the app to do (e.g. select some photos to upload or has enabled some auto-backup option to be done after taking a photo)?
- Yes. Then use Upload Service. Displaying progress to the user means being a good citizen
- No, it's something internal of the app and the user doesn't even know. Then use Work Manager.

**Comment by Pro-55** [comment]
I agree with what you are saying but what got me confused here is that the code is working as expected on Android 8.0 devices and changing channel importance on devices with Android 8.1

**Comment by NLLAPPS** [comment]
I believe you still need to show notification for long processes even if you are using work manager if it is running O or above

**Comment by Pro-55** [comment]
Okay Thank you for helping.

**Comment by cannizarro** [comment]
> @govindtank beware that doing that works only for Android < Oreo, due to the policy introduced by Google which forces you to display a notification when a background service is run. When on Oreo, the Upload Service will throw an exception telling you to do so if you've not a set a notification configuration.
> 
> To automatically hide a notification after the upload completes:
> 
> ```java
> UploadNotificationConfig config = new UploadNotificationConfig();
> config.getCompleted().autoClear = true;
> 
> yourUploadRequest.setNotificationConfig(config);
> ```
> 
> You can also tune other settings or auto clear the notification also for the other states. Refer to [this JavaDoc](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/UploadNotificationConfig.html) and [the wiki](https://github.com/gotev/android-upload-service/wiki/Recipes#-notification-configuration).

This doesn't work now. So is it possible still or not, in Android 10.
