### ISSUE TITLE
does not upload the full image

### ISSUE THREAD

**Issue by pamela3010** [gotev/android-upload-service#386]
### What did you expect?
upload image to server
### What happened instead?
does not upload the full image
in the android simulator works perfectly, but in a real phone not.
[http://jobsearch.datavac.nl/avicolaApp/imagenes/JPEG_20180417_040910_419555243.jpg](url image upload from Nexus 5)

### Version info
* Android Upload Service version: 2.1
* Android version and API version: 26
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Steps to reproduce (if applicable):
I take a picture with the camera, when save it must upload the image, it does not show any error, but when looking for the image in the server, the image is not complete

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```
compile 'net.gotev:uploadservice:2.1'

### Request code:
```java
// the code you wrote to create the upload request
try {
            String uploadId = UUID.randomUUID().toString();
            new MultipartUploadRequest(getActivity(), uploadId, SERVER_URL)
                    .addFileToUpload(selectedFilePath, "picture")
                    //.addParameter("filename", archivo)
                    .setMaxRetries(5)
                    .setNotificationConfig(new UploadNotificationConfig())

                    .startUpload();

        } catch (Exception exc) {
            System.out.println(exc.getMessage()+" "+exc.getLocalizedMessage());
        }
```

#### Where have you added the request code?
- [. ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Upgrade to 3.4
