### ISSUE TITLE
Sometimes image is not upload in 'net.gotev:uploadservice:3.4'

### ISSUE THREAD

**Issue by desaikush210** [gotev/android-upload-service#387]

**Comment by gotev** [comment]
Please be more specific and provide full information to replicate

**Comment by gotev** [comment]
@gian123 the same response 😄 Please be more specific and provide full information to replicate

**Comment by gotev** [comment]
closing this due to lack of interaction and relevant information to replicate the problem and eventually see if it's a bug.
