### ISSUE TITLE
Redirecting to domain instead of the correct endpoint

### ISSUE THREAD

**Issue by akosijiji** [gotev/android-upload-service#390]
### What did you expect? 
I am expecting to get the correct API response

### What happened instead?
It happened when I used my Nexus phone and tried to upload an image. But the API response got redirected to the domain API not the correct endpoint

### Version info
* Android Upload Service version: latest
* Android version and API version: 26
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### Library initialization code:
```java
// the code you wrote in your Application subclass here
/ setup the broadcast action namespace string which will
        // be used to notify upload status.
        // Gradle automatically generates proper variable as below.
        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
        // Or, you can define it manually.
        UploadService.NAMESPACE = Constants.APP_NAMESPACE;
        // Set upload service debug log messages level
        Logger.setLogLevel(Logger.LogLevel.DEBUG);

        Logger.setLoggerDelegate(new Logger.LoggerDelegate() {
            @Override
            public void error(String tag, String message) {
                //your own implementation here
            }

            @Override
            public void error(String tag, String message, Throwable exception) {
                //your own implementation here
            }

            @Override
            public void debug(String tag, String message) {
                //your own implementation here
            }

            @Override
            public void info(String tag, String message) {
                //your own implementation here
            }
        });

        // Set up the Http Stack to use. If you omit this or comment it, HurlStack will be
        // used by default
        UploadService.HTTP_STACK = new OkHttpStack(getOkHttpClient());

### Request code:
```kotlin
// the code you wrote to create the upload request
```
            val uploadId = UUID.randomUUID().toString()
            val request = MultipartUploadRequest(this, uploadId,
                    Constants.HTTP_DEV_DOMAIN + Constants.API_IMAGE_UPLOAD
                    .setMethod("POST")
                    .setUtf8Charset()
                    .addFileToUpload(picturePath, Constants.PARAM_IMAGE)
                    .addParameter(Constants.PARAM_USER_ID, Constants.USER_ID)
                    .setNotificationConfig(getNotificationConfig(uploadId, R.string.uploading))
                    .setMaxRetries(2)
                    .setUsesFixedLengthStreamingMode(true)
                    .setDelegate(object : UploadStatusDelegate {
                        override fun onProgress(context: Context?, uploadInfo: UploadInfo?) {
                            Log.i(TAG, "onProgress eltstr=" + uploadInfo?.elapsedTimeString + " elt=" +
                                    uploadInfo?.elapsedTime + " ratestr=" +
                                    uploadInfo?.uploadRateString + " prc=" + uploadInfo?.progressPercent +
                                    " tb=" + uploadInfo?.totalBytes + " ub=" + uploadInfo?.uploadedBytes)
                        }
                        override fun onError(context: Context?, uploadInfo: UploadInfo?, serverResponse: ServerResponse?, exception: java.lang.Exception?) {
                            Log.e(TAG, "onError " + exception?.message + exception?.stackTrace)
                        }
                        override fun onCompleted(context: Context?, uploadInfo: UploadInfo?, serverResponse: ServerResponse?) {
                            Log.i(TAG, "onCompleted " + serverResponse?.httpCode + " " + serverResponse?.bodyAsString)
                            try {
                                parseJSON(serverResponse?.bodyAsString)
                            } catch (ex: Exception) {
                                Log.e(TAG, "Error: parseJSON " + ex.message)
                            }
                        }
                        override fun onCancelled(context: Context?, uploadInfo: UploadInfo?) {
                            Log.d(TAG, "onCancelled $uploadInfo")
                        }
                    })
            request.startUpload()

#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

I noticed that for those who have 6.0.1 Android versions below this happens. Please help as this is a show stopper in my app. Thanks!

**Comment by gotev** [comment]
Doible check your server first. Then provide steps to reproduce and detailed log by enabling library debug log, as described in the wiki.

**Comment by akosijiji** [comment]
Hello @gotev thanks for your response. Please check updated post of mine. I noticed that this happens in 6.0.1 version below.

**Comment by akosijiji** [comment]
@gotev thanks! I realised it's the file size issue!
