### ISSUE TITLE
Error on Android Oreo : "Android Oreo requires a notification configuration for the service to run. 

### ISSUE THREAD

**Issue by danangww** [gotev/android-upload-service#391]
Error caught when I run this app in Android Oreo : Android Oreo requires a notification configuration for the service to run. 
https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)

![img-20180506-wa0008](https://user-images.githubusercontent.com/18223663/39673369-135794d8-5165-11e8-91e4-3405dbf6ead2.jpg)

If this app run before Android Oreo, it's OK and run as expected. What should I do? Thank you so much. Sorry, I'm just newbie in mobile programming. :)

**Comment by gotev** [comment]
Check [this](https://github.com/gotev/android-upload-service/issues/378#issuecomment-372587127)

**Comment by danangww** [comment]
Thank you so much, this problem is solved.
