### ISSUE TITLE
after failed uploads it will not retry to upload particular URL in android?(when Internet is switch on/off state)

### ISSUE THREAD

**Issue by SunilKumarEvolgence** [gotev/android-upload-service#394]
### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [x] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by SunilKumarEvolgence** [comment]
Auto Retry is not working properly (automatically retry failed uploads, with a configurable exponential back off) Could you please elaborate this point?....

**Comment by SunilKumarEvolgence** [comment]
Auto Retry is not working properly (automatically retry failed uploads, with a configurable exponential back off)

hope you get my point i would like to hear more from you will waiting for your positive response...

**Comment by gotev** [comment]
Fill in required information in the issue (code and library debug log)

**Comment by gotev** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/gotev/android-upload-service/blob/master/ISSUE_TEMPLATE.md).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
