### ISSUE TITLE
Using Firebase as backend

### ISSUE THREAD

**Issue by ArcherEmiya05** [gotev/android-upload-service#397]
Just want to ask if I can use this with Firebase while uploading some files another question is since it uses Service, does it mean that it will continue to finish the task even my app gets destroyed or activity is no longer visible?

**Comment by gotev** [comment]
If your app gets killed, the service will be stopped, because it's part of your app, it doesn't run independently. To achieve the behavior you described, WorkManager from Android Architecture is the most appropriate.
