### ISSUE TITLE
set socket timeout \

### ISSUE THREAD

**Issue by pedped** [gotev/android-upload-service#398]
Hi

I am using the latest version of the android-upload-service, version **3.4.2**
but it do not have any socket timeout settings when using the MultipartUploadRequest.

how can I set the timeoout limit, like read timeout, socket timeout and write timeout.
 
I DO NOT use okhttp for connection

**Comment by gotev** [comment]
Just look at HttpUrlConnection socket timeout setting

**Comment by chayanc88** [comment]
@gotev Can you please put a link where it can be found? It will be helpful

**Comment by gotev** [comment]
By default Hurl stack has 15s of connect timeout and 30s of read timeout are set. If you need different values:

```
UploadServiceConfig.httpStack = HurlStack(...)
```

**Comment by chayanc88** [comment]
@gotev Thank you for the information. I don't know Kotlin. Can you please give me a link for Java. 
`UploadServiceConfig.httpStack = HurlStack(...)` is saying Cannot resolve symbol.

**Comment by gotev** [comment]
First, use 4.x release. Then use the corresponding setter method. The rest is the same. 

A tip: learn Kotlin, it improves your everyday job and life :wink:

**Comment by chayanc88** [comment]
@gotev Thank you for the feedback. I am upgrading the version. Let's see what happens. 
Also thanks for the tip. I have already taken that into account.
