### ISSUE TITLE
Action buttons and status issues on Android Oreo

### ISSUE THREAD

**Issue by XJIOP** [gotev/android-upload-service#399]
Tested example code from demoapp, and found issues on Android Oreo.

1. Action buttons not working, BroadcastReceiver gets nothing.
2. Status does not change if connection lost.

on Android Nougat it works.

**Comment by XJIOP** [comment]
Testing on emulator, after starting upload (Multipart) immediately open notification and click button (cancel upload), broadcast logs is empty. Same with connection lost, by enable fly mode get error status only after 10 min, on Nougat get error immediately.

**Comment by XJIOP** [comment]
About action buttons, I have tested and on Oreo and it only works with this sample
```
    public static PendingIntent getCancelUploadAction(final Context context,
                                                      final int requestCode,
                                                      final String uploadID) {
        Intent intent = new Intent(context, NotificationActionsReceiver.class);
        intent.setAction(INTENT_ACTION);
        intent.putExtra(PARAM_ACTION, ACTION_CANCEL_UPLOAD);
        intent.putExtra(PARAM_UPLOAD_ID, uploadID);

        return PendingIntent.getBroadcast(context, requestCode, intent, PendingIntent.FLAG_UPDATE_CURRENT);
    }
```

and on Nougat it works too.

**Comment by XJIOP** [comment]
About status, found that MultipartUpload not correctly working on Oreo.

I created a php web server for the test. On nougat I get the error "413 Request Entity Too Large" this is normal because need to increase client_max_body_size. But on Oreo no errors, looks like upload in progress and after uploading repeats again.

**Comment by XJIOP** [comment]
Found that on Oreo MultiPartUpload working incorrectly.

I created a php web server for the test. On nougat I get the error "413 Request Entity Too Large" this is normal because need to increase client_max_body_size. But on Oreo no errors, looks like upload in progress and after uploading completed repeats it again.

**Comment by XJIOP** [comment]
Another problem with the action buttons. Multiple uploads every single notification action button has same upload ID taked from last added upload.

example
> Created upload with ID: 74a7377d-49f3-405b-b3e3-885e2d0ccfc5
> Created upload with ID: faab050a-73ff-4f64-a694-49e16f236659
> 	
> Clicked action button with ID: 74a7377d-49f3-405b-b3e3-885e2d0ccfc5 
> return faab050a-73ff-4f64-a694-49e16f236659
> 
> Clicked action button with ID: faab050a-73ff-4f64-a694-49e16f236659 
> return faab050a-73ff-4f64-a694-49e16f236659

**Comment by gotev** [comment]
Thank you for the tests and the analysis. For the first part, regarding the detection of the connectivity, it may be because on Oreo and newer versions, connectivity change is not broadcasted anymore (see: https://stackoverflow.com/questions/48527171/detect-connectivity-change-in-android-7-and-above-when-app-is-killed-in-backgrou) and there are restrictions on background services. I'm considering re-implementing the library using the newly introduced work manager to mitigate those scenarios.

For the second part, you must have different request codes for different action buttons.
