### ISSUE TITLE
fail to upload multiple image files in one request

### ISSUE THREAD

**Issue by ankitdubey021** [gotev/android-upload-service#400]
when i uploaded three images, only one top image is uploaded to server.
please let me know, how can i upload multiple images in same request.

here is sample code:

new MultipartUploadRequest(ImageUploadActivity.this, uploadId, "url")                                     

                                        .addFileToUpload(ck.getEnrollmentPic(), "EnrollmentPic")
                                        .addFileToUpload(ck.getAttendancePic(), "attendancePic")
                                        .addFileToUpload(ck.getFeedbackFormPic(), "FeedbackFormPic")
                                        
                                        .addParameter("psi", paperId)
                                        .addParameter("batch_id", s.getBatchId()) 
                                        .addParameter("assessor_id", String.valueOf(assessor_id))
                                        .setNotificationConfig(new UploadNotificationConfig())
                                        .setMaxRetries(2)
                                        .startUpload();

**Comment by gotev** [comment]
Hi! This has been asked several times before in the issue. Check #263 :wink:
