### ISSUE TITLE
Issue on WIFI on some mobile phones like on OnePlus 5T 

### ISSUE THREAD

**Issue by manishshakyadevp** [gotev/android-upload-service#401]
Hello sir 

sometimes when i am using my android app with your example of file uploading at OnePlus 5T with wifi connection i am getting error SSLException.

**Comment by gotev** [comment]
This has to do with your server side certificates and not with the library itself. It is discussed widely in one of the OkHttp issues regarding this problem.

**Comment by manishshakyadevp** [comment]
V/NativeCrypto: Write error: ssl=0x76c0c7c208: I/O error during system call, Connection reset by peer 
V/NativeCrypto: SSL shutdown failed: ssl=0x76c0c7c208: I/O error during system call, Success

there messages comming

**Comment by manishshakyadevp** [comment]
its coming sometimes on some wifi connections

**Comment by gotev** [comment]
However the log you sent is not a library related issue. I suggest you to use latest OkHttp stack it you're not using it already :smile:

**Comment by manishshakyadevp** [comment]
ok thanks sir
