### ISSUE TITLE
Progress bar is not showing and text is stuck after uploading is complete.

### ISSUE THREAD

**Issue by VikasPawar2112** [gotev/android-upload-service#403]
### What did you expect?
When upload complete progress bar must be gone.

### What happened instead?
Progress bar is not hiding still appears in screen. Picture upload successful but progress bar did't hide.
 
### Version info
* Android Upload Service version:3.2.5
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
 .addFileToUpload(postNearByPicture.getPicture().getAbsolutePath(), "picture")
                            .addParameter("session_id", postNearByPicture.getSessionId())
                            .addParameter("lat", postNearByPicture.getLat() + "")
                            .addParameter("lon", postNearByPicture.getLon() + "")
                            .addParameter("location_name", postNearByPicture.getLocationName())
                            .addParameter("caption", postNearByPicture.getCaption())
                            .setUtf8Charset()
                            .setMaxRetries(1)
                            .startUpload();

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Try with latest version

**Comment by Pro-55** [comment]
I'm having the same issue. I have updated Android Upload Services to 3.4.2 & now it says that onError method does not override or implement a method from a supertype.

**Comment by Pro-55** [comment]
I was supposed to pass an extra parameter ServiceResponse to the method. The error went away but the upload for Oreo devices has stopped altogether.

**Comment by Pro-55** [comment]
I'm using it to display a progress bar while the image is uploaded to the server. It is displayed on top of one of the activities.

**Comment by gotev** [comment]
@Pro-55 without a code example of what you're doing, I can't help you
