### ISSUE TITLE
UploadStatusDelegate defines Interface Exception but null is sent in UploadTask

### ISSUE THREAD

**Issue by albinhubsch** [gotev/android-upload-service#404]
https://github.com/gotev/android-upload-service/blob/3702d9b9047000b7342f2f878dfba3f109164416/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L303

At the following line delegate.onError returns null as exception. According to [Interface UploadStatusDelegate](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/UploadStatusDelegate.html#onError-android.content.Context-net.gotev.uploadservice.UploadInfo-net.gotev.uploadservice.ServerResponse-java.lang.Exception-) this is expected to be an Exception object. 

I propose to return a new instance of an Exception object.

Reason to this propsal is because this triggered a crash for me in the library [react-native-background-upload](https://github.com/Vydia/react-native-background-upload), the library was expecting an Exception object and tried to call getMessage() on a null object.

**Comment by gotev** [comment]
The interface is correct but in Java the object may be null as well without causing problems. I suggest to properly update JavaScript bindings to handle null cases instead, because in the line cited there's no exception thrown and creating an empty one just to not fail wrapper JavaScript implementations seems a little bit of a hack.

**Comment by albinhubsch** [comment]
@gotev indeed it is! I was not paying attention to the complete documentation

_exception - exception that caused the error. It can be null if the request successfully reached the server, but it responded with a 4xx or 5xx status code._

thanks for making it clear. The crash in the external library has been resolved.
