### ISSUE TITLE
3GP video files are sent as application/octet-stream on android lower than Pie

### ISSUE THREAD

**Issue by albinhubsch** [gotev/android-upload-service#405]
When we're trying to upload a .3gp video file with the multipart upload, it is sent with application/octet-stream. Even if we set the MultipartUploadRequest contentType parameter to video/3gpp. We have been able to confirm this behavior on android 8.1, 7.1 and 5.1.1, It does not seem to apply on android P as our server detects the upload as a video/3gpp file.

### Version info
* Android Upload Service version: 3.4.2
* Android version and API version: fails on 8.1, 7.1, 5.1.1, works on 9

### Steps to reproduce (if applicable):
Upload a 3gpp file

### Solution
We have currently solved this by accepting application/octet-stream as a valid file on our server but we think the problem should tried to be solved at its source.

**Comment by gotev** [comment]
I doubt it is a bug in the library, however you haven't provided any useful details to eventually replicate the error. Enable debuf log and provide full code and debug logging dump during upload. Also, I recommend you to use OkHttp stack if you're not using it yet. Full information on how to integrate it in the wiki. In cases like this, I always recommend using my demo server (see troubleshooting wiki page) or tools like tcpdump, Charles or mitmproxy. Seeing what goes over the wire is always useful (and many times it's the only correct way) to debug networking apps.
