### ISSUE TITLE
Progress Percentage Not Updating

### ISSUE THREAD

**Issue by agherakevan** [gotev/android-upload-service#406]
MultipartUploadRequest

@override
public void onProgress(Context context, UploadInfo uploadInfo) {
int percent = uploadInfo.getProgressPercent();
percentage_txt.setVisibility(View.VISIBLE);
progress.setProgress(percent);
percentage_txt.setText(String.valueOf(uploadInfo.getProgressPercent()));
Log.e("Percentage",uploadInfo.getProgressPercent()+"");
}

percentage logging only one time and not getting progress percentage can u help me. what i am doing wrong?

**Comment by gotev** [comment]
Unfortunately I can't help you if you don't fill in all the information requested in the issue template. This code alone is not sufficient.

**Comment by gotev** [comment]
You need the Broadcast receiver instead of the delegate. All the details here: https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status
