### ISSUE TITLE
NotificationActionsReceiver not receiving cancel intent

### ISSUE THREAD

**Issue by Faiyyaz** [gotev/android-upload-service#409]
### What did you expect?

If a user click on cancel in the notification then the upload should cancel

### What happened instead?

On Oreo devices, the cancel button not working

### Version info
* Android Upload Service version: 3.4.2
* Android version and API version: 8.1 API 27
* HTTP stack (e.g. HurlStack or OkHttpStack): Okhttpstack

### Steps to reproduce (if applicable):
Check sample app for the same

**Comment by Aravindraj93** [comment]
Same issue here.

**Comment by gotev** [comment]
Hi there and thank you for the insight. This may be due to how Oreo enforces intents firing: https://stackoverflow.com/questions/46549109/pendingintent-is-not-working-on-android-o

Some rework needs to be done at library level. I'll see it asap. Of you find a solution in the meantime, feel free to send a PR.

**Comment by Faiyyaz** [comment]
But then how it works in the sample app in oreo devices?

**Comment by Aravindraj93** [comment]
In my case the cancel button is not working on any devices. But it works on sample app.

**Comment by Faiyyaz** [comment]
Did you add the class called NotificationActions &NotificationActionsReceiver and declared the latter class as a receiver in your manifest with your own package name?

**Comment by gotev** [comment]
Make sure you follow the example provided in the demo app. The NotificationActionsReceiver has to be registered in your app manifest.

**Comment by Faiyyaz** [comment]
But for me its not working even after that in my project so is it my issue or the library issue?

**Comment by gotev** [comment]
Are you targeting API 28 in your app? The demo app targets API 26. As I've written in my first post of this thread, Oreo enforces PendingIntents so at current state, the library is not Oreo and Pie compliant as some rework needs to be done.

**Comment by Faiyyaz** [comment]
Its targeted to 27 but not work on oreo devices only

**Comment by Aravindraj93** [comment]
> Did you add the class called NotificationActions & NotificationActionsReceiver and declared the latter class as a receiver in your manifest with your own package name?

Yes, I did.

`<receiver android:name="com.example.events.UploadReceiver" android:exported="false">
            <intent-filter>
                <action android:name="net.gotev.uploadservicedemo.uploadservice.broadcast.status" />
            </intent-filter>
        </receiver>

        <receiver android:name="com.example.events.NotificationActionsReceiver" android:exported="false">
            <intent-filter>
                <action android:name="net.gotev.uploadservicedemo.notification.action" />
            </intent-filter>
        </receiver>`

But the cancel button is not working.

**Comment by Faiyyaz** [comment]
> > Did you add the class called NotificationActions & NotificationActionsReceiver and declared the latter class as a receiver in your manifest with your own package name?
> 
> Yes, I did.
> `<receiver android:name="com.example.events.UploadReceiver" android:exported="false"> <intent-filter> <action android:name="net.gotev.uploadservicedemo.uploadservice.broadcast.status" /> </intent-filter> </receiver> <receiver android:name="com.example.events.NotificationActionsReceiver" android:exported="false"> <intent-filter> <action android:name="net.gotev.uploadservicedemo.notification.action" /> </intent-filter> </receiver>`
> 
> But the cancel button is not working.

Your action name is wrong it should contains your package name and then upload.broadcast.status

**Comment by Aravindraj93** [comment]
Thank you so much @Faiyyaz  It works now 👍 . But not on Oreo :(

**Comment by Faiyyaz** [comment]
> Thank you so much @Faiyyaz It works now  . But not on Oreo :( Thank you for helping me.

You are welcome @Aravindraj93.

Yes the oreo is the issue for me too
