### ISSUE TITLE
Global broadcast receiver callback not called

### ISSUE THREAD

**Issue by saran2somu** [gotev/android-upload-service#412]
### What did you expect?
I need to receive upload status as globally. So I used broadcast receiver class.

### What happened instead?
File uploaded successfully.
But I didn't receive the call back methods. 

### Version info
* Android Upload Service version: 3.4.2
* Android version and API version: 6.0 and 21 
* HTTP stack (e.g. HurlStack or OkHttpStack): OKHttp stack 3.4.2

### Steps to reproduce (if applicable):
My Manifest:
` <receiver android:name=".listeners.MyVideoReceiver" android:exported="false">
            <intent-filter>
                <action android:name="com.app.xxx.uploadservice.broadcast.status" />
            </intent-filter>
        </receiver>
`

### Library initialization code:
```java
// the code you wrote in your Application subclass here
 UploadService.NAMESPACE = "com.app.xxx"
        val interceptor = HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY)
        val httpClient = OkHttpClient.Builder().writeTimeout(2, TimeUnit.MINUTES).readTimeout(2, TimeUnit.MINUTES).connectTimeout(2, TimeUnit.MINUTES)
                .addInterceptor(interceptor).build()
        UploadService.HTTP_STACK = OkHttpStack(httpClient)
```

### Request code:
```java
 var request = MultipartUploadRequest(activity, Constants.BASE_URL+Constants.INDIVIDUAL_VIDEO_UPLOAD)
                    .addFileToUpload(videoList?.get(0)?.path, "file")
                    .setNotificationConfig(UploadNotificationConfig()
                            .setIconForAllStatuses(R.drawable.ic_app_logo)
                            .setTitleForAllStatuses(activity.getString(R.string.app_name)))
                    .setMaxRetries(3).setMethod("POST")
                    .addHeader("accept", "application/json")
                    .addHeader("Content-Type", "multipart/form-data")
                    .addHeader("authorization", UserDetailsManager(AppInstance.getInstance()!!.applicationContext).getUserInfo().token as String ?: "")
            request.startUpload()
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
The demo app provided in the examples of android upload service does exactly the same (the class is UploadReceiver) and it works. Try comparing what you have in your app and the demo app 😊I suggest you to clone upload service, add some debug logs in the demo app and try. If you are able to replicate the problem also in the demo app, then it may well be a bug and we'll investigate it further.

**Comment by CaliAlec** [comment]
I was having the same issue: the global broadcast receiver callbacks weren't being called even though I wasn't setting any delegates.

For me it was because I was setting an applicationIdSuffix for my debug builds such as below:

buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
            ...
        }
        release {
            debuggable false
            ...
        }
    }

The package name in the Intent Filter's action wasn't the same for my debug builds, so to fix the issue I'm using the packageName variable in my Manifest:

`<action android:name="${packageName}.uploadservice.broadcast.status" />`

**Comment by gotev** [comment]
@CaliAlec are you having issues on Android 8+ ?

**Comment by CaliAlec** [comment]
@gotev I'm on 9.0 but like I said, I think my issue was because of the package name prefix. It's solved for me.

**Comment by gotev** [comment]
It works for me either on Android 9.0 Pie, but some users told me thatthey have issues, so I wanted to have a confirmation from you. Thanks!

**Comment by mobileonekh** [comment]
Facing same issue on Android 8+, broadcast is not called.

**Comment by gotev** [comment]
Follow the directions described here: https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status#global-broadcast-receiver-
