### ISSUE TITLE
Remove progress bar

### ISSUE THREAD

**Issue by androidnoob123** [gotev/android-upload-service#413]
Hi,

Is there any way I could not show the progress bar when the upload is taking place? Just the notification, but without any progress bar/progress.

Thank you!

**Comment by gotev** [comment]
On Android 8.0+ is not possible due to Google Policy. On previous versions you can simply omit passing the notification config

**Comment by androidnoob123** [comment]
Thank you for the reply. Sorry for the trouble, but I think you misunderstood me.

I am not asking to hide the notification. I'm saying if there's a possibility of not showing the progress bar but still showing the notification during upload. Hiding notification is not allowed in 8+, but it is not mandatory to show progress bar, is it? 

I guess changing to `.setProgress(0, 0, false)` will do that. Is there any way I can achieve that without changing the base code? Or do I have to import the folder as module and make change in the base code (in `UploadTask.java`.) Please let me know. Thank you!
