### ISSUE TITLE
IllegalStateException: Timer was canceled

### ISSUE THREAD

**Issue by Sdghasemi** [gotev/android-upload-service#415]
First of all thank you for the great library. We've been experiencing an issue lately where the library calls `shutdownIfThereArentAnyActiveTasks` method. Apparently there is a timer instance which you try to reschedule but it has already been canceled so it throws the exception I mentioned in the title.
### What did you expect?
To not use a canceled timer instance.
### What happened instead?
Using the canceled timer instance to schedule for another time throws exception.
### Version info
* Android Upload Service version: 3.4.2
* Android version and API version: All of our supported versions (17 to 26 - Android 4 to 8)
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### Steps to reproduce (if applicable):
I don't know exactly but it's worth it to mention that we're using the library in three different places with three different upload id patterns which can be run simultaneously.

### Library initialization code:
```java
OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .writeTimeout(300, TimeUnit.SECONDS)
        .readTimeout(300, TimeUnit.SECONDS);
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
UploadService.HTTP_STACK = new OkHttpStack(okHttpBuilder.build());
```

### Request code:
The following is one of the three places I mentioned which has the most usage:
```java
public class NewPostRequest extends UploadServiceBroadcastReceiver {
    private void createNewPost(PostingMedia media) {
        try {
            String uploadId = String.valueOf(media.getId());
            MultipartUploadRequest multipartUploadRequest = new MultipartUploadRequest(MainApplication.getAppContext(), uploadId, Endpoints.getInstance().CREATE_POST).setUtf8Charset();
            multipartUploadRequest.addParameter("type", String.valueOf(media.getType()));
            multipartUploadRequest.addParameter("requestId", uploadId);
            if (media.getComposeBundle() != null) multipartUploadRequest.addFileToUpload(media.getComposeBundle().getFinalVideoUri().getPath(), "video");
            multipartUploadRequest.addFileToUpload(media.getPicture().getPath(), "picture");
            if (media.hasText()) multipartUploadRequest.addParameter("text", media.getText());
            if (media.getSponsoringUnits() != 0) multipartUploadRequest.addParameter("sponsoringUnits", String.valueOf(media.getSponsoringUnits()));
            multipartUploadRequest.addParameter("flags", String.valueOf(media.getFlags()));

            mUploadId = multipartUploadRequest
                    .addHeader("Authorization", "Bearer " + Config.makePref(MainApplication.getAppContext()).getString(Config.SharedPrefFields.ACCESS_TOKEN, ""))
                    .addHeader("X-Client-Version", String.valueOf(BuildConfig.VERSION_CODE))
                    .setMethod("POST")
                    .setMaxRetries(0)
                    .setDelegate(this)
                    .setAutoDeleteFilesAfterSuccessfulUpload(media.getComposeBundle() == null || media.getComposeBundle().isDisposable())
                    .setNotificationConfig(Build.VERSION.SDK_INT < Build.VERSION_CODES.O ? null :
                            new UploadNotificationConfig()
                                    .setNotificationChannelId("upload")
                                    .setTitleForAllStatuses(MainApplication.getAppContext().getString(R.string.sending_post))
                                    .setIconForAllStatuses(R.drawable.ic_notif)
                                    .setIconColorForAllStatuses(Color.RED)
                                    .setRingToneEnabled(false))
                    .startUpload();
        } catch (Exception exc) {
            Logger.log(TAG, "createPostError: ", exc);
        }
    }

    @Override
    protected boolean shouldAcceptEventFrom(UploadInfo uploadInfo) {
        try {
            for (PostingMedia media : NewPostPresenter.sPostingMedias)
                if (media.getId() == Integer.parseInt(uploadInfo.getUploadId())) return true;
        } catch (Exception ignored) {}
        return false;
    }
}
```
#### Where have you added the request code?
Fragment -> Presenter -> Request class which extends `UploadServiceBroadcastReceiver` to be the request delegate (Request code here)

### LogCat output
```
Fatal Exception: java.lang.IllegalStateException: Timer was canceled
       at java.util.Timer.scheduleImpl(Timer.java:558)
       at java.util.Timer.schedule(Timer.java:456)
       at net.gotev.uploadservice.UploadService.shutdownIfThereArentAnyActiveTasks(UploadService.java:305)
       at net.gotev.uploadservice.UploadService.taskCompleted(UploadService.java:413)
       at net.gotev.uploadservice.UploadTask.broadcastError(UploadTask.java:439)
       at net.gotev.uploadservice.UploadTask.run(UploadTask.java:162)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

### Server side
Microsoft .NetCore

### Additional info
The exception report from Crashlytics: http://crashes.to/s/0d8902486ff

**Comment by sepehr1014** [comment]
We're having this issue as well. Any solutions?

**Comment by sepehr1014** [comment]
@gotev Could you update us on this issue? Did you get a chance to look into this?

**Comment by gotev** [comment]
Unfortunately I didn't had time to look at it yet but I can tell you the logic which is implemented, so you could help me debug it and fix it.

After every upload task completes, the library calls `net.gotev.uploadservice.UploadService.shutdownIfThereArentAnyActiveTasks` which checks if there aren't any other upload tasks and if this is the case it schedules the service for shutdown in 5s with a timer. However, if another task comes in during this period, the timer is canceled, preventing the service to be stopped. As you have mentioned, this has issues which in my use cases simply never happened.

The automatic shutdown of the service is an energy saving policy to free up resources on the device if no upload tasks are running, since Upload service is a service with a thread pool which remains active during the whole lifecycle of the app once started. This has been done 3 years ago and during this time new Android versions made great job in battery saving, so this may be not necessary anymore, but I want to hear your opinions also and make a decision on how to proceed together.

**Comment by gotev** [comment]
I had a look and IMHO it's a race condition between the methods which interacts with the idle timer. What seems to happen is that a task completes and no other tasks are running at that moment, but while the idle timer gets recreated and scheduled for shutdown, another task comes in and cancels the timer right after it's created on line 304, so when the execution steps on line 305, the timer has been already cancelled and this causes the exception. 

Can you confirm it's a behavior which happens randomly and not every single time?

**Comment by Sdghasemi** [comment]
That's the exact point, it's totally random.
We're using your perfect library as one of our core features (social network app), but I myself have never got this error. Our users on the other hand might do a lot of uploading stuff which makes it more probable to happen. So yes, it happens randomly.

**Comment by gotev** [comment]
Ok! Can you send a PR with the fix? I'll be more than happy to provide guidance if you need.

**Comment by gotev** [comment]
It's really pleasant to see such a good analysis @Sdghasemi ! 

I would vote for option 3

**Comment by Sdghasemi** [comment]
Thanks @gotev, I'll keep you posted for the PR. Appreciate the assistance.

**Comment by gotev** [comment]
@Sdghasemi if you need some guidance I'm happy to help
