### ISSUE TITLE
I used your code for PHP it worked fine but in node.js I am stucked please review the code

### ISSUE THREAD

**Issue by Mritunjay10** [gotev/android-upload-service#416]
android side file parameter = "image";

node routes - 

const express = require('express');
const router  = express.Router();
const multer  = require('multer');
const fs = require("fs");
const path = require('path');

const postController = require('../controller/post.controller');
const homeController = require('../controller/home.controller');

const UPLOAD_PATH = "./uploads/";
let fileUploadCompleted = false;

let multerFiles = multer({

    dest: UPLOAD_PATH,
    rename: function (fieldname, filename) {
        return filename;
    },

    onParseEnd: function(req, next) {

        console.log("\nReceived Parameters");
        console.log("-------------------");

        for (var key in req.body) {
            console.log(key + ": " + req.body[key]);
        }

        if (Object.keys(req.body).length === 0)
            console.log("no text parameters\n");
        else
            console.log("");

        next();
    },

    onFileUploadStart: function (file) {

    },

    onFileUploadComplete: function (file) {

        let fullPath = path.resolve(UPLOAD_PATH, file.originalname);

        fileUploadCompleted = true;

        console.log("PRINTED_DATA "+fullPath);
    }

});

const multipartUploadHandler = function(req, res) {

    console.log("\n\nBinary Upload Request from: " + req.ip);
    //printRequestHeaders(req);

    var filename = req.headers["image"];
    console.log("Started binary upload of: " + filename);
    var filepath = path.resolve(UPLOAD_PATH, filename);
    var out = fs.createWriteStream(filepath, { flags: 'w', encoding: 'binary', fd: null, mode: '644' });
    req.pipe(out);
    req.on('end', function() {
        console.log("Finished binary upload of: " + filename + "\n  in: " + filepath);
        res.sendStatus(200);
    });
};

router.post('/create',  (req, res) => postController.create(req, res, multipartUploadHandler));

module.exports = router;

node controller - 

const fs = require("fs");
const multer = require('multer');
const path = require('path');

const db = require('../models');
const operations = require('../helper/operations');

exports.create = (req, res, multerFiles) => {

    req.assert('user_id', 'Invalid user').notEmpty();
    req.assert('price', 'Invalid price').notEmpty();
    req.assert('lat_lng','Invalid latitude and longitude').isLength({min:4});

    const errors = req.validationErrors();

    const  jj = multerFiles;
    //multipartUploadHandler(res, req);

    console.log(path);

}

**Comment by Mritunjay10** [comment]
The problem is I can't upload file

**Comment by gotev** [comment]
With which node.js version? What's the error are you seeing?

**Comment by Mritunjay10** [comment]
it just shows this in the console - 

resolve: [Function: resolve],
     normalize: [Function: normalize],
     isAbsolute: [Function: isAbsolute],
     join: [Function: join],
     relative: [Function: relative],
     _makeLong: [Function: _makeLong],
     dirname: [Function: dirname],
     basename: [Function: basename],
     extname: [Function: extname],
     format: [Function: format],
     parse: [Function: parse],
     sep: '/',
     delimiter: ':',
     win32: [Circular],
     posix: [Circular] }

but folder is created

**Comment by Mritunjay10** [comment]
My node is 8.11

**Comment by Mritunjay10** [comment]
Well, I fixed the code for multiple uploads so I am good now let me know if I can contribute to this amazing library.

**Comment by gotev** [comment]
Great! Awaiting your PR then :)

**Comment by Mritunjay10** [comment]
I didn't get you

**Comment by Mritunjay10** [comment]
Sorry, new to GitHub

**Comment by gotev** [comment]
No problems! You can start from here: https://help.github.com/articles/creating-a-pull-request/

**Comment by gotev** [comment]
Tried the actual implementation of the node.js server with node 10.15.0 and npm 6.4.1 on macOS Mojave 10.14.1 and it works out of the box with `npm i && npm start` from the server directory.
