### ISSUE TITLE
I got error httpCode 422 after upload 100%, actually the token has been disable for checking

### ISSUE THREAD

**Issue by derohimat** [gotev/android-upload-service#418]
### What did you expect?
Upload Success, because authentication token has been disable. And I try it on postman, it worked.

### What happened instead?
I got error httpCode 422, and application need upload again and again

### Version info
* Android Upload Service version: latest 3.4.2
* Android version and API version: 6.0.1 API 23
* HTTP stack (e.g. HurlStack or OkHttpStack): **OkHttpStack**

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ *] Activity
- [* ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Please give more context and information to replicate. From what you described it seems the request it's not composed as needed from your app. Have you tried using something like stetho to debug request/response and compare it with what you get from postman?
