### ISSUE TITLE
.addParameter Limitation

### ISSUE THREAD

**Issue by kishan2212** [gotev/android-upload-service#419]
is there any limitation to .addParameters() ? 
My image is showing upload finish but i cant see in my folder and i checked twice my web-service its working fine.
even i'm not getting any exception.
can you please help me to solve out ...?

**Comment by gotev** [comment]
Please share the code you use to upload

**Comment by kishan2212** [comment]
```
try {
            String uploadId = UUID.randomUUID().toString();
            //Creating a multi part request
            Log.d(TAG,"uploadId"+uploadId.toString());
            new MultipartUploadRequest(this, uploadId, GlobalVariable._ADDCHILDREQUEST)
                    .addFileToUpload(path, "image") //Adding file
                    .addParameter("parent_name", parentName) //Adding text parameter to the request
                    .addParameter("child_name", childName)
                    .addParameter("city", city)
                    .addParameter("country", country)
                    .addParameter("full_country", full_country)
                    .addParameter("birthdate", birthdate)
                    .addParameter("deathdate", deathdate)
                    .addParameter("gender", gender)
                    .addParameter("marital_status", marital_status)
                    .addParameter("mobile_number", mobile_number)
                    .addParameter("note_message", note_message)
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload(); //Starting the upload

        } catch (Exception exc) {
            Toast.makeText(this, exc.getMessage(), Toast.LENGTH_SHORT).show();
            Log.d("ErrorFile",""+exc.getMessage());
        }
```

**Comment by kishan2212** [comment]
how to store return value from webservice ?

**Comment by kishan2212** [comment]
> 
> 
> Please share the code you use to upload

Hey i'm done with it but now i want to store my json response after calling my webservice where can i find my json reponse ?

**Comment by gotev** [comment]
Nice! You can find what you need in the wiki monitoring section.

**Comment by kishan2212** [comment]
> 
> 
> Nice! You can find what you need in the wiki monitoring section.

sorry but i can't find anything in wiki monitoring section.
can you please tell me

**Comment by gotev** [comment]
Look at the onCompleted method of either delegate or broadcast receiver. What you need is inside serverResponse.

**Comment by kishan2212** [comment]
> 
> 
> Look at the onCompleted method of either delegate or broadcast receiver. What you need is inside serverResponse.

thanks but what if i want to put this on asynctask ?
