### ISSUE TITLE
Please specify a file path!

### ISSUE THREAD

**Issue by kishan2212** [gotev/android-upload-service#422]
D/ErrorFile: Please specify a file path!
 hey help me if user don't want to set image then how can ignore the file parameter ?

**Comment by kishan2212** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference

showing here error 

@Override
                        public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {
                            progressDialog.dismiss();
                        }

**Comment by gotev** [comment]
Yes that exception is right. Multipart file upload needs a file, otherwise you are simply sending an url encoded form data. For that I suggest you to use Retrofit together with OkHttp.

**Comment by gotev** [comment]
Multipart works only when you have a file to be uploaded, otherwise you simply need something different for your use case

**Comment by kishan2212** [comment]
> 
> 
> Multipart works only when you have a file to be uploaded, otherwise you simply need something different for your use case

okay thanks have to learn retrofit
