### ISSUE TITLE
Request : very basic file upload client with just callbacks and it shouldn't run on any service and no notifactions

### ISSUE THREAD

**Issue by iamdangerous** [gotev/android-upload-service#423]
It's a **request** I actually need a very basic version of this awesome library which just gives proper callbacks for eg 
onCompleted, onErrror, onProgress. 
It shouldn't run on any service but just on an executor. I know running on service makes the api calls to high priority.(It should be optional)
It shouldn't use any wake locks (too costly for batteries - it should be optional) 

Currently I have forked your code and I have manually edited the whole source code to meet the requirements but it would be very awesome, if you can provide these features out of the box.

Thanks and nice work 👍

**Comment by gotev** [comment]
@iamdangerous I see you simply need something different than what Android Upload Service was created for. Probably to meet your needs, OkHttp + Retrofit + Rx will suffice. However, wake locks are ignored on Android 8+ which has its own battery saving policies. Android Upload Service serves for background upload even if your app is idle and a service is a must in that case.
