### ISSUE TITLE
Duplicate Entry on Server In Slow network.

### ISSUE THREAD

**Issue by amitsharma492** [gotev/android-upload-service#424]
There is duplication entry on the server in the slow network.
One file uploaded multiple time. 
Please suggest a solution. 
I have tried to use following things.
`public static final int MAX_RETRIES = 0;` 

`.setMaxRetries(MAX_RETRIES)`

**Comment by gotev** [comment]
Please provide a way to replicate it systematically

**Comment by amitsharma492** [comment]
```
public static final int MAX_RETRIES = 0;
public static final boolean FIXED_LENGTH_STREAMING_MODE = true;


final MultipartUploadRequest request = new MultipartUploadRequest(this, uploadId, serverUrl)
        .setMethod("POST")
        .setUtf8Charset()
        .setNotificationConfig(getNotificationConfig(uploadId, R.string.multipart_upload))
        .setMaxRetries(MAX_RETRIES)
        //.setCustomUserAgent(getUserAgent())
        .setUsesFixedLengthStreamingMode(FIXED_LENGTH_STREAMING_MODE);

request.addParameter("ImageName", "");
request.addFileToUpload(filepath, "fielName");
request.startUpload();`

**Comment by gotev** [comment]
Clone the android-upload-service project, open the example directory and run the node js demo server provided (you can find directions in the Wiki). Does the file gets uploaded twice every time?

**Comment by gotev** [comment]
Never happened to my projects in production, however, I can't help you without a test which replicates the issue systematically. 

It's difficult to investigate by just guessing what may have happened. Too much variables. It may be the server, it may be the device, it may be the default Android networking (OkHttp is always recommended) and it may be a bug in the library as well.

Some steps in the right direction:

be able to replicate the issue on a device, then using Wireshark or the app I suggest in the Wiki Troubleshooting page trace down what happens on the wire. Then, by inspecting the network traffic it will be possible to debug what's wrong and in turn make the required patches to the backend or the library.

**Comment by gotev** [comment]
Closing this. If you have feedback and replication code, feel free to reopen it.

**Comment by chayanc88** [comment]
Any solutions on this? I am getting the same problem and I am not even on slow network. 
And It is uploading duplicates even if I set `.setMaxRetries(0)`

**Comment by gotev** [comment]
@chayanc88 create a new issue

**Comment by knowamit** [comment]
@chayanc88  I was using okhttp client that's why I was facing duplicate entry issue. I have removed the okhttp client and using default configuration. Also, changed the initial wait time to 3 seconds instead of 1 second.

`UploadService.INITIAL_RETRY_WAIT_TIME = 3000;`

**Comment by chayanc88** [comment]
Hi,
Thanks for the quick response.
I am using HurlStack actually. Still I am getting this issue.
I will try your solution now and will get back to you.
