### ISSUE TITLE
Add Feature: set Upload Progress report Frequency

### ISSUE THREAD

**Issue by Mahan3340** [gotev/android-upload-service#427]
### What did you expect?
   set Upload progress update frequency  
### What happened instead?
   its not nice when the progress bar has an animation when its progress is updated 
   because the upload service keeps reporting the new progress and interrupting the animation
   I can handle this by running a timer and keeping tracks of latest progress updates but I would     appreciate that if it was possible to be included in the lib
### Version info
* Android Upload Service version:
 3.5.0
* Android version and API version:
   Android Pie - 28 
* HTTP stack (e.g. HurlStack or OkHttpStack):
  OkHttpStack
### Library initialization code:
`UploadService.NAMESPACE = "com.example";
        UploadService.HTTP_STACK = new OkHttpStack();`

#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

**Comment by gotev** [comment]
There's a property called [PROGRESS_REPORT_INTERVAL](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadService.java#L121) which controls the minimum interval between two progress updates. Making it publicly accessible should do what you want

**Comment by Mahan3340** [comment]
@gotev is it possible to add it as feature because I don't want to clone the whole lib just for a private. to public conversion

**Comment by gotev** [comment]
Ok, then just update to `3.5.1` and you're good to go 😉
