### ISSUE TITLE
Feature Request (Already Exists?) : Serial Upload - Disable concurrency

### ISSUE THREAD

**Issue by Mahan3340** [gotev/android-upload-service#428]
### What did you expect?
    Serial Upload
### What happened instead?
`Concurrent Upload`
### Version info
* Android Upload Service version:
3.5.1
* Android version and API version:
Android 9, API 28
* HTTP stack (e.g. HurlStack or OkHttpStack):
OkHttpStack

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
I have implemented this behavior via a Queue in my app but I was just wondering if the library supports serial upload (one by one) through a queue or something? I guess it would be more cleaner if it there was a built-in function for that.

**Comment by gotev** [comment]
That's already available: https://github.com/gotev/android-upload-service/wiki/Recipes#-tune-the-number-of-parallel-uploads

**Comment by Parag2385** [comment]
Hello @gotev 
I'm having the same issue I wanna restrict to 1 upload at a time, the link you gave above is broken, But I did find the section of parallel uploads. It states that I've to set UploadService.UPLOAD_POOL_SIZE to 1. But the problem is I'm not able to find this variable in UploadService. 

I checked the source code, you've used ThreadPoolExecutor here:

    @JvmStatic
    var threadPool: AbstractExecutorService = ThreadPoolExecutor(
        Runtime.getRuntime().availableProcessors(), // Initial pool size
        Runtime.getRuntime().availableProcessors(), // Max pool size
        5.toLong(), // Keep Alive Time
        TimeUnit.SECONDS,
        LinkedBlockingQueue<Runnable>()
    )

I think max pool size here should be customizable in order to restrict to a number of uploads, right? Correct me if I'm wrong.

Thanks.

**Comment by gotev** [comment]
In 4.x you have full control, as you can set your own `ThreadPoolExecutor` if the default one does not suit your needs.

https://github.com/gotev/android-upload-service/blob/a902ce3c9ce8754e6edde8ee17f84ac7f3e00e0d/uploadservice/src/main/java/net/gotev/uploadservice/UploadServiceConfig.kt#L90-L101

So for your use-case it's:

```kotlin
UploadServiceConfig.threadPool = Executors.newSingleThreadExecutor()
```

where you perform the initialization of the library

**Comment by Parag2385** [comment]
Cool, It works, Thank you :)
