### ISSUE TITLE
Multi binary file upload with one notification. 

### ISSUE THREAD

**Issue by lkvr** [gotev/android-upload-service#429]
Hello. Some help wanted.
If there is a possibility to perform many binary uploads having only one notification?
Currently it seems that new notification created each time when new file from queue starts to be uploaded, with about 10 small files it's pretty blinking.

Would be nice to have notification looks like "3 of 10 uploaded". But is it currently possible?

Thanks!

**Comment by gotev** [comment]
Grouped notifications are not available yet. You get a notification for every upload.

**Comment by gotev** [comment]
Closing this due to prolonged inactivity. Feel free to reopen it if you are willing to implement this feature with a PR :wink:

**Comment by gotev** [comment]
@lkvr with Upload Service 4 Alpha 4: #468 you can now implement your own notification handler and accomplish what you asked for 😃
