### ISSUE TITLE
Multiple Upload not showing all status in notification bar

### ISSUE THREAD

**Issue by ChadhaAashish** [gotev/android-upload-service#435]
### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Please fill in the details in the issue to be able to replicate the behavior you encountered

**Comment by ChadhaAashish** [comment]
hey gotev,
so i am uploading multiple images at same time but the issue is i am not getting status bar for each call 
for ex if i am making 6 api calls to upload the images only 3-4 status bar are visible

**Comment by gotev** [comment]
This depends on the number of parallel uploads: https://github.com/gotev/android-upload-service/wiki/Recipes#-tune-the-number-of-parallel-uploads

Probably you are making more requests than what your device can handle in a certain window of time. The tasks are not lost, they are simply in the upload queue: https://github.com/gotev/Android-upload-service/wiki/Recipes#-upload-tasks-and-service-management

**Comment by ChadhaAashish** [comment]
so can i add delay in the api call so that it waits for the last response before calling next api?

**Comment by gotev** [comment]
It depends on what are your requirements and your business logic

**Comment by ChadhaAashish** [comment]
so i just want that if i am making 8 calls to the api the 2nd call must go once i have the response of the 1st call
is that possible ?

**Comment by gotev** [comment]
Yes but it gets a little complicated. You have to trigger the second call from the global broadcast receiver once you receive confirmation of success from the first one. Check also the monitoring wiki page.

**Comment by ChadhaAashish** [comment]
so for that i have to maintain a queue for global broadcast receiver and call the api when i have the response ?

**Comment by gotev** [comment]
This is going well beyond the scope of the library, as this is an issue tracker for bugs, however in scenario like this where the first API call acts as authorization or upload preparation, I recommend you to use OkHttp + Retrofit and trigger the upload service call only after it succeeds. As a rule of thumb, if you are tempted to manage queues on your own, there's surely something wrong in the logic.

**Comment by ChadhaAashish** [comment]
Cool thanks for responding to the query soo fast 
Cheers
One more thing can we set notification config in broadcast receiver
