### ISSUE TITLE
How to use this upload service library

### ISSUE THREAD

**Issue by AbubakerShekhani** [gotev/android-upload-service#436]
Thank you for this awesome library. Looks promising. 

I have the following scenario:
1. User takes many photos during the day
2. At day end, user presses upload button and all the photos taken in that day should be uploaded

I have two questions
a. Can I use this library for this purpose?
b. If yes, can I get a step by step guide to implement this library in a simple basic Android project?

I checked the Setup in Wiki. But it has very less information in order to implement this library. 

Thanks in advance.  I am new to Android.

**Comment by gotev** [comment]
1. Yes
2. Check the demo project and the Wiki

There's not a ready implementation for you specific use case and I cannot afford coding it for you, but by playing with the examples and studying Android SDK you can do what you need.
