### ISSUE TITLE
Can we make UploadNotificationConfig dynamic 

### ISSUE THREAD

**Issue by ChadhaAashish** [gotev/android-upload-service#437]
### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Please add a concrete example where you are unable to achieve what you need because of the library and what you wanted instead. Without that information I can't do anything about your question.

**Comment by ChadhaAashish** [comment]
so i want to update the notification config in the onError and onCompleted methods of my global broadcast receiver

**Comment by gotev** [comment]
Notification Config is created once and then it's immutable once you start the upload until it finishes.
