### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by Sunaina015** [gotev/android-upload-service#438]
Fatal Exception: android.os.FileUriExposedException
file:///storage/emulated/0/MIUI/.ringtone/Sneeze_%26_539fe0ae-efce-4b28-9eb6-5e52b18dcd12.mp3 exposed beyond app through Notification.sound

android.os.StrictMode.onFileUriExposed (StrictMode.java:1796)
android.net.Uri.checkFileUriExposed (Uri.java:2354)
android.app.NotificationManager.notifyAsUser (NotificationManager.java:303)
android.app.NotificationManager.notify (NotificationManager.java:287)
android.app.NotificationManager.notify (NotificationManager.java:271)
net.gotev.uploadservice.UploadTask.updateNotification (UploadTask.java:545) *******Please check this line
net.gotev.uploadservice.UploadTask.broadcastError (UploadTask.java:419)
net.gotev.uploadservice.UploadTask.run (UploadTask.java:162)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:760)

**Comment by gotev** [comment]
Please fill in the [issue template](https://github.com/gotev/android-upload-service/blob/master/ISSUE_TEMPLATE.md) with the missing information, mainly the code you used to launch the upload. [Line 545](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L545) applies the click intent you set in the notification config to the notification that's displayed.

**Comment by gotev** [comment]
Closing this due to lack of information and evidence of bug
