### ISSUE TITLE
Fatal Exception: java.lang.VerifyError

### ISSUE THREAD

**Issue by Sunaina015** [gotev/android-upload-service#439]
Hey, i am getting this exception only on this device , please help me how we can solve this problem -

**Brand: Xiaomi
Model: HM NOTE 1S CT
Orientation: Portrait
RAM free: 852.8 MB
Disk free: 2.59 GB**

**Operating System
Version: 4.4.4
Orientation: Portrait
Rooted: No**

Fatal Exception: java.lang.VerifyError
**at this line -   .setNotificationConfig(new UploadNotificationConfig())**

       at android.view.View.performClick(View.java:4444)
       at android.view.View$PerformClick.run(View.java:18457)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5113)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by gotev** [comment]
Please post your full code where you invoke that method. The posted stack Trace is completely unrelated to the library.

**Comment by Sunaina015** [comment]
Please check below code -
try {
            final String uploadId = UUID.randomUUID().toString();
            new MultipartUploadRequest(context, uploadId, url)
                    .addFileToUpload(path, "voice") //Adding file
                    .setMaxRetries(2)
                    .addParameter("auth_token", PreferenceManager.getAuthToken())
                    .addParameter("user_id", PreferenceManager.getUserId())
                    .addParameter("type", "voice")
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setDelegate(new UploadStatusDelegate() {
                        @Override
                        public void onProgress(Context context, UploadInfo uploadInfo) {
                           
                        }

                        @Override
                        public void onError(Context contextt, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {
                           
                        }

                        @Override
                        public void onCompleted(Context contextt, UploadInfo uploadInfo, ServerResponse serverResponse) {
                            
                        }

                        @Override
                        public void onCancelled(Context contextt, UploadInfo uploadInfo) {
                          
                        }
                    })
                    .startUpload(); //Starting the upload
          

        } catch (Exception exc) {
         
        }

**Comment by gotev** [comment]
Thanks. So it seems it's due to your dependencies. 
https://stackoverflow.com/questions/100107/causes-of-getting-a-java-lang-verifyerror

**Comment by Sunaina015** [comment]
Please help me to find out the solution because i using the current dependency -
 implementation 'net.gotev:uploadservice:3.5.2'
Can u please tell my why this library version not supported tot this version ?

**Comment by gotev** [comment]
Make sure your other dependencies all use androidX and that your project uses androidX too.

**Comment by Sunaina015** [comment]
No my project dependencies are not using androidX.

**Comment by gotev** [comment]
That is the cause.

**Comment by Prateekflexiloans** [comment]
Can you please share the Proguard specific rules for this lib

**Comment by gotev** [comment]
Open a new issue for that

**Comment by mevinDhun** [comment]
@gotev Is it necessary for all dependencies to use androidX? i am using this library in a cordova plugin [cordova-plugin-background-upload](https://github.com/spoonconsulting/cordova-plugin-background-upload). This means that the cordova project will have along many other plugins which wil not support androidx. Is there any way to use it with other non-androidx dependencies in the same project?

**Comment by gotev** [comment]
All the dependencies must be AndroidX compliant or you have to use the Jetifier Gradle option which is described in detail in Google docs. Bear in Mind Android Q is going to support AndroidX only apps.
