### ISSUE TITLE
Global broadcast receiver callback not called after switching fragment.

### ISSUE THREAD

**Issue by Shuvajit-Das** [gotev/android-upload-service#440]
### What did you expect?

I am using global broadcast receiver, upload a image from one fragment, in this scenario I am getting callback from global broadcast receiver, but if I switch fragment while uploading is not complete yet, I want to get the callback from global broadcast receiver too.

### What happened instead?

After switching fragment, global broadcast receiver callback does not call.

### Version info
* Android Upload Service version: 3.5.2
* Android version and API version: 28
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### Library initialization code:

UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
OkHttpClient client = new OkHttpClient();
UploadService.HTTP_STACK = new OkHttpStack(client);

<receiver android:name=".events.UploadReceiver" android:exported="false">
            <intent-filter>
                <action android:name="net.gotev.uploadservicedemo.uploadservice.broadcast.status" />
            </intent-filter>
        </receiver>

### Request code:
public void uploadBinary(Uri uri, String serverURL) {
        try {
            String uploadId = UUID.randomUUID().toString();
            uploadReceiver.setUploadID(uploadId);

            new BinaryUploadRequest(getActivity().getApplicationContext(), uploadId, serverURL)
                    .setMethod("PUT")
                    .setFileToUpload(getPath(uri))
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload();

        } catch (Exception exc) {
            Log.e(TAG, exc.getMessage(), exc);
        }
    }

    @Override
    public void onProgress(Context context, UploadInfo uploadInfo) {
        // your implementation
    }

    @Override
    public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {
        // your implementation
    }

    @Override
    public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
        // your implementation

        updateStatus(contentID);

    }

    @Override
    public void onCancelled(Context context, UploadInfo uploadInfo) {
        // your implementation
    }

//This is my global broadcast receiver class UploadReceiver 

public class UploadReceiver extends UploadServiceBroadcastReceiver {

    private WeakReference<UploadStatusDelegate> mDelegate;
    private String mUploadID = null;

    public UploadReceiver(UploadStatusDelegate delegate) {
        mDelegate = new WeakReference<>(delegate);
    }

    public void setUploadID(String uploadID) {
        mUploadID = uploadID;
    }

    @Override
    protected boolean shouldAcceptEventFrom(UploadInfo uploadInfo) {
        return mUploadID != null && uploadInfo.getUploadId().equals(mUploadID);
    }

    @Override
    public final void onProgress(Context context, UploadInfo uploadInfo) {
        if (mDelegate != null && mDelegate.get() != null) {
            mDelegate.get().onProgress(context, uploadInfo);

            Log.e("uploadInfo_OP_global", "____" + uploadInfo.getProgressPercent());

        }
    }

    @Override
    public final void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {
        if (mDelegate != null && mDelegate.get() != null) {
            mDelegate.get().onError(context, uploadInfo, serverResponse, exception);
        }
    }

    @Override
    public final void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
        if (mDelegate != null && mDelegate.get() != null) {
            mDelegate.get().onCompleted(context, uploadInfo, serverResponse);
        }
    }

    @Override
    public final void onCancelled(Context context, UploadInfo uploadInfo) {
        if (mDelegate != null && mDelegate.get() != null) {
            mDelegate.get().onCancelled(context, uploadInfo);

            Log.e("uploadInfo_OCom_global", "____");

        }
    }

#### Where have you added the request code?
- fragment

**Comment by gotev** [comment]
Set the broadcast receiver delegate in the activity containing the Fragments, not in each fragment

**Comment by Shuvajit-Das** [comment]
Yes I did this, broadcast receiver delegate also get called from the container activity, but still when I switch fragment broadcast receiver delegate from the container activity stop giving me callback.

**Comment by gotev** [comment]
Try using a broadcast receiver directly in the activity, tied to its lifecycle instead of a global one with a weak reference to the delegate in the activity
