### ISSUE TITLE
Error on starting Node.js Server

### ISSUE THREAD

**Issue by KaelInvoker** [gotev/android-upload-service#441]
Hello，when I start node server, it crashed.
![image](https://user-images.githubusercontent.com/37531571/57772234-82a8e180-7747-11e9-9c00-28e67491a6a3.png)

**Comment by gotev** [comment]
Something else is already bound to Port 3000

**Comment by KaelInvoker** [comment]
thanks. But How do I specify the port of the service?

**Comment by gotev** [comment]
Just edit this line :wink:
https://github.com/gotev/android-upload-service/blob/master/examples/server-nodejs/index.js#L11
