### ISSUE TITLE
Support chunked streaming mode？

### ISSUE THREAD

**Issue by KaelInvoker** [gotev/android-upload-service#442]
Hello，How to use the streaming mode when uploading large files By Okhttp?

**Comment by gotev** [comment]
What issues do you have with the current implementation?

**Comment by KaelInvoker** [comment]
I mean when I upload a large file, can this library support automatically splitting the file into multiple pieces one by one?

**Comment by gotev** [comment]
It streams data in a single connection, but for uploads like AWS S3, a dedicated implementation is needed as a plugin
