### ISSUE TITLE
implementation 'net.gotev:uploadservice:3.5.2'

### ISSUE THREAD

**Issue by Norberto123456789** [gotev/android-upload-service#443]
Hi, my name is Norberto Davila and i have a little bit problem with your library, because it works excelente with sdk lower than 22, but when i try to use with android 25 or higher it doesn´t work.

I am using Fragments, at the begining I had a lot of problems to get full the path and solve the problem when I check the sdk version and now it was working succesfully.

All the code works awesome, but the image in version 22 or higher does not send to the php server.

I hope to know how can i upload the image.

**Comment by gotev** [comment]
Have you tried the upload service demo app on the same emulators and devices in which you experienced problems?

**Comment by Norberto123456789** [comment]
yes and it returns de the id, but the file do not insert in the database and it is not upload

**Comment by gotev** [comment]
Tried also your app with the demo server?

**Comment by gotev** [comment]
Closing this due to incativity
