### ISSUE TITLE
Issue for 3.5.2 

### ISSUE THREAD

**Issue by juanfegonzalez** [gotev/android-upload-service#444]
### What did you expect?
Hi alex i like very much your library but i find the problem with my app, i waiting for your request.

### What happened instead?
when a put the Uri on the file path is correct but when a click the button the app was crashing. because the message is error during upload and i dont know to know the problem because the logs are poor
### Version info
* Android Upload Service version:3.5.2
* Android version and API version:28
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java

 public void uploadMultipart(final Context context, String ruta, String idup, String nombre, String API) {
        String APIUP = DOMINIO + API;
        try {
            UploadNotificationConfig unc = new UploadNotificationConfig();

            new MultipartUploadRequest(context, APIUP)
                    .addFileToUpload(ruta, nombre)
                    .addParameter("proceso","TB")
                    .addParameter("descripcion","adios")
                    .setNotificationConfig(unc)
                    .setMaxRetries(2)
                    .startUpload();
        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }
    }
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [x] Activity
- [x] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
i use the angular in forms to upload the files
```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Hi Juan, if the app is crashing there's some exception being thrown and I need to know that to help you. The library has different log levels and you need to set the level to debug: https://github.com/gotev/android-upload-service/wiki/Recipes#logging-

A part from that, I strongly recommend you to add a crash reporting library to your app, like Crashlytics, so you will always know why the app crashed.
