### ISSUE TITLE
UploadService in Android 9.0

### ISSUE THREAD

**Issue by apoloJava** [gotev/android-upload-service#446]
hi people, 

I'm implementing UploadService-3.4.2 on Android 7.1.1, 8.1 up here all right with the indications here: https://github.com/gotev/android-upload-service/wiki/Setup.

I have problems to implement UploadService-3.4.2 for Android 9.0, 9.1 ...

What I found to implement in Android-9.0 are:
@ <application android: name = ".Initializer" 
@ <uses-permission android: name = "android.permission.FOREGROUND_SERVICE" />
@ I'm using
.setDelegate (new UploadStatusDelegate () {
onError ...
} ...

Is any more configuration missing? Is there any way that can be implemented in Android 9.0?

Thanks in advance.
Ben

**Comment by gotev** [comment]
Please add some more details of what you expect, what happens and how you implemented the service

**Comment by apoloJava** [comment]
**What did you expect?**

Implement UploadService 3.4.2 (or 3.5.2) on Android 9.0 or +


**What happened instead?**

I implemented UploadService-3.4.2 on Android 7.1.1 and 8.1. 
The problem arises when I want to implement UploadService 3.4.2 on Android-9.0 or +

**Version info**

    - Android UploadService version: 3.4.2

    - compileSdkVersion 28
      defaultConfig {
        applicationId "com.myapp"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"


**Steps to reproduce (if applicable):**

AndroidManifest.xml

... uses-permission android:name="android.permission.FOREGROUND_SERVICE"
... android:name=".Initializer"


**Library initialization code: Initializer.java**

// the code you wrote in your Application subclass here
    // setup the broadcast action namespace string which will
    // be used to notify upload status.
    // Gradle automatically generates proper variable as below.
    UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
    

**Request code:**

 String urlString = Constants.UPLOAD_URL;
 Log.d(MainActivity.TAG, "URL Complete: " + urlString);
 
 String uploadId = UUID.randomUUID().toString();
 
 new MultipartUploadRequest(activity, uploadId, urlString)
                    .addFileToUpload(fileName, "uploaded_file")
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .setDelegate(new UploadStatusDelegate() {
                        
                        @Override
                        public void onProgress(Context context, UploadInfo uploadInfo) {

                        }

                        @Override
                        public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception e) {
                            Toast.makeText(activity, R.string.connectionFailed, Toast.LENGTH_SHORT).show();
                        }

                        @Override
                        public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
                            if (serverResponse.getHttpCode() == 200) { // OK Server
                                Toast.makeText(activity, "The " + uploadFileName + " " + activity.getResources().getString(R.string.okFileUpload),Toast.LENGTH_LONG).show();
                            }


                        @Override
                        public void onCancelled(Context context, UploadInfo uploadInfo) {
                            Toast.makeText(activity, R.string.canceledService, Toast.LENGTH_SHORT).show();
                        }
                    }).startUpload();


**LogCat output (please set log level to DEBUG first)**

// your LogCat output here

java.io.IOException: Cleartext HTTP traffic to example.com not permitted


Thanks in advance.
Ben

**Comment by felixdivo** [comment]
This is not a problem with this library. This arises because you use HTTP (=cleartext) instead of HTTPS (=encrypted). This is blocked unless you explicitly allow it (see [here](https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6) for example). But if you can, simply use HTTPS, the warning/error is there for a reason (security).

**Comment by haibingxu** [comment]
can upload or create folder for andriod ?

**Comment by gotev** [comment]
@apoloJava use the broadcast receiver instead of the Delegate

@haibingxu open a new issue for that with as much details as you can. It's off topic here
