### ISSUE TITLE
Request: update Min SDK to 17

### ISSUE THREAD

**Issue by elena-p** [gotev/android-upload-service#449]
Hi @gotev,

Thank you for maintaining the library and keeping it up to date with latest android SDK releases!

We use uploadservice 3.5.2 in [nativescript-background-http](https://github.com/NativeScript/nativescript-background-http) plugin. However, NativeScript supports min api 17 (having 1.5% of android users seems reasonable to do so) and we have received complaints related to the latest change. 

Could you update the min SDK requirement of the library to 17, as there are more android 17 users than 18?

**Comment by gotev** [comment]
Hi there! It can be done, but some tests on API 17 have to be made as well and I have no plan for that. Going forward the plan is to migrate to Kotlin and to support API 21+ only for security reasons and ease of maintenance. OkHttp already moved to API 21+ in their latest 3.x and 4.x versions and I will follow with subsequent releases with Q support.
