### ISSUE TITLE
Notification not Show after change Releases

### ISSUE THREAD

**Issue by SaifRaheem** [gotev/android-upload-service#452]
Hi, Thanks for this library 
i have problem with Notifications ,I was using 2.1 Release and Notifications show correctly  , and when update Releases +3.0 the Notifications Started not show only upload , and return to  2.1 Release the problem remained (Notifications not show ) !!
I don't know exactly what the problem is with my project or with the library ? 
Thanks for your helps

**Comment by gotev** [comment]
Without the code or an example project where you replicate the problem I can't help you. 3.5.2 is the best and most stable version to date. There's probably something in the code. Open the Wiki amd follow examples. Also, take a look at the demo app.

**Comment by SaifRaheem** [comment]
now maked a new project and add   2.1 relaeas
` public void uploadMultipart() {
        //getting name for the image
        String name = editText.getText().toString().trim();

        //getting the actual path of the image
        String path = getPath(filePath);

        //Uploading code
        try {
            String uploadId = UUID.randomUUID().toString();

            //Creating a multi part request
            new MultipartUploadRequest(this, uploadId, "http://bagolearn.net/keyjsonfilessr/po_sr/s_p_sr.php")
                    .addFileToUpload(path, "image") //Adding file
                    .addParameter("name", name) //Adding text parameter to the request
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload(); //Starting the upload
            Toast.makeText(this, "upload", Toast.LENGTH_SHORT).show();

        } catch (Exception exc) {
            Toast.makeText(this, exc.getMessage(), Toast.LENGTH_SHORT).show();
        }
    }`

my app crashed when setNotificationConfig is there and work  correctly when remove line                      .setNotificationConfig(new UploadNotificationConfig())


I am using this correct code for the article owner [simplifiedcoding](https://www.simplifiedcoding.net/android-upload-image-to-server/)

**Comment by gotev** [comment]
That article reference a pretty old Upload Service which I discourage using for security reasons. Security beaches have been found in that version (you can see details in 3.4 release). Step up to `3.5.2` in your demo app. Enable debug logs and if you still have problems post Android version, Upload Service version or a demo project which replicates the problem.

**Comment by SaifRaheem** [comment]
i have this problem when use  3.5.2
[https://i.ibb.co/8NPRVM8/Capture.png](https://i.ibb.co/8NPRVM8/Capture.png)

**Comment by gotev** [comment]
You need to use [AndroidX](https://developer.android.com/jetpack/androidx/migrate) instead of old Android Support Libraries. Upcoming Android 10 will support AndroidX only.

**Comment by SaifRaheem** [comment]
I don't want to convert now to  AndroidX 
can  i make custom notifaction from through
`private val broadcastReceiver = object : UploadServiceBroadcastReceiver() {
        override fun onProgress(uploadId: String?, progress: Int) {
            loadToast("onProgress")
        }

        override fun onError(uploadId: String?, exception: java.lang.Exception?) {
            loadToast("onError")


        }

        override fun onCompleted(uploadId: String?, serverResponseCode: Int, serverResponseBody: ByteArray?) {
            loadToast("onCompleted")
            if (serverResponseBody != null) {
                loadToast(serverResponseBody.toString())
            }
        }

        override fun onCancelled(uploadId: String?) {
            loadToast("onCancelled")
        }`

**Comment by gotev** [comment]
Then you have to go back to [3.4.2](https://github.com/gotev/android-upload-service/releases/tag/3.4.2) but bear in mind you don't have official support for Android API 26+ (Oreo and newer) with that version.

[This](https://github.com/gotev/android-upload-service/wiki/Recipes#notification-config) is what you can customize in notifications.

**Comment by SaifRaheem** [comment]
Okay, so I'll switch to AndroidX ..thanks

**Comment by gotev** [comment]
It will require you some extra work now, but you won't regret it. It's the present and future of Android and solves many problems we always had with support libraries.

**Comment by SaifRaheem** [comment]
Hello my friend ,
The library worked well  , thank you very much .
It took about 3 days you updated :
1-Android Studio to last version
2- gradil and kotlin  to last version
3- compileSdkVersion to 28
4-and Convert Project to AndroidX

thanks my friend ^-^

**Comment by gotev** [comment]
Great!!
