### ISSUE TITLE
change title notifaction after complete upload ?

### ISSUE THREAD

**Issue by SaifRaheem** [gotev/android-upload-service#455]
Hi my friend
i try to upload image :
if  there any problem in upload return message error and this message show in title notification after upload  on function : override fun onCompleted(){}

I tried change message notification after complete upload but not work !
any Solutions ?

**Comment by gotev** [comment]
Notification messages are static and set like described here https://github.com/gotev/android-upload-service/wiki/Usage#notification-config 
They cannot be overwritten.

**Comment by SaifRaheem** [comment]
ok 
can i send only size image for my server  , No Upload image file (only size image for check befor upload )
