### ISSUE TITLE
Broadcast receiver in a library

### ISSUE THREAD

**Issue by allinelara** [gotev/android-upload-service#460]
I created an android library (name **MyOwnLibrary**) and I am using android-upload-service as a dependence in **MyOwnLibrary**. 

I integrate my **MyOwnLibrary** in **TestApp**. 

In **MyOwnLibrary** I created a Global Broadcast receiver. 

`package com.test.MyOwnLibrary.upload
class UploadReceiver : UploadServiceBroadcastReceiver() {

    override fun onProgress(context: Context?, uploadInfo: UploadInfo?) {
       }

    override fun onError(context: Context, uploadInfo: UploadInfo?, serverResponse: ServerResponse?, exception: Exception?) {      
    }

    override fun onCompleted(context: Context?, uploadInfo: UploadInfo?, serverResponse: ServerResponse?) {
         }

    override fun onCancelled(context: Context, uploadInfo: UploadInfo) {
    }
}`

I read that I need to register my broadcast receiver inside the AndroidManisfest of my App and not in the AndroidManisfest of my Library. 

In the AndroidManisfest.xml from **TestApp** I inserted this code: 

`<receiver android:name="com.test.MyOwnLibrary.upload.UploadReceiver" android:exported="false">
    <intent-filter>
        <action android:name="com.test.MyOwnLibrary.uploadservice.broadcast.status" />
    </intent-filter>
</receiver>
`

But the broadcast receiver UploadReceiver is never call.

**Comment by gotev** [comment]
On newer Androids is advised to register the global broadcast receivers at runtime. Make a static init method in your library and when you call it make it register the broadcast receiver and configure Android Upload Service to target the correct namespace. If you're not receiving events, some configuration is missing. Enable the library debug log to help you spot what happens.
