### ISSUE TITLE
Error access permissions in android when using addFileToUpload

### ISSUE THREAD

**Issue by Geowan** [gotev/android-upload-service#469]
### What did you expect?
To perform the upload without an issue

### What happened instead?
Throws an error open failed: EACCES (Permission denied)

### Version info
* Android Upload Service version:3.5.2
* HTTP stack :OkHttpStack

### Library initialization code:
```java
        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
         UploadService.HTTP_STACK = new OkHttpStack();
```

### Request code:
```java
      public void uploadImage(String path) {
        try {
            String uploadUrl = AppDetailsHelpers.API_URL + "/v1/sites/default/upload-site-image";
            String uploadId =
                    new MultipartUploadRequest(getContext(), uploadUrl)
                            // starting from 3.1+, you can also use content:// URI string instead of absolute file
                            .addFileToUpload(path, "image")
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .setDelegate(new UploadStatusDelegate() {

                                @Override
                                public void onProgress(Context context, UploadInfo uploadInfo) {
                                    LogUtil.i("A little bit of progress");
                                }

                                @Override
                                public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {
                                    LogUtil.i("we have an error "+exception.getMessage());
                                }

                                @Override
                                public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
                                    LogUtil.i("Yay completed "+serverResponse.getBodyAsString());
                                }

                                @Override
                                public void onCancelled(Context context, UploadInfo uploadInfo) {
                                    LogUtil.i("Oppos is cancelled");
                                }
                            })
                            .startUpload();
            LogUtil.i("the id has "+uploadId);
            //add file to the recyclerview and show loading uploader

        } catch (Exception exc) {
            LogUtil.i("AndroidUploadService"+ exc.getMessage());
        }
    }
```
From the above the path of the image is absolute and contains path eg:
    /storage/emulated/0/DCIM/Camera/IMG_20191012_195843.jpg

#### Where have you added the request code?
- [ ] Fragment

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging) first)
```
// we have an error /storage/emulated/0/DCIM/Camera/IMG_20191012_195843.jpg: open failed: EACCES (Permission denied)
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

      public function actionUploadSiteImage(){
        return $_FILES; //just testing to see if it works
    }

More info the LogUtil class is used to log on the console. Its similar to the Log.i(TAG, message);
I have also added the storage permission on the manifest file like
  
      <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

**Comment by Geowan** [comment]
I had to add android:requestLegacyExternalStorage="true" to the manifest file to make this work.
Seems an issue with android 10.

**Comment by gotev** [comment]
@geowan could you please try the 4.0 release? Also, I strongly recommend you don't use the delegates, which does not survive rotations and activity Lifecycle. I've updated the Wiki recently, but more importantly, 4.0 fixes all those issues and gives you more stability, specially on Android 10. It's in alpha 04 only because I'm going to fine tune some APIs, but for what you need it's already stable. Check the demo app. If you encounter problems, post an issue :wink:

**Comment by Geowan** [comment]
But then looking at [this issue](https://github.com/gotev/android-upload-service/issues/440) seems the fragments arent getting callbacks after upload. Can you clarify on which option to use to receive callbacks after an image or file is uploaded successifully especially when using this in a fragment

**Comment by gotev** [comment]
In 4.0 I've introduced the concept of RequestObserver. It's a Lifecycle aware Broadcast Receiver, which sticks to your Lifecycle automatically. Fragments are switched inside activities. Data requests and listeners should be in Android ViewModels. What I advice is to use 4.0 and make data requests and to listen for changes inside the ViewModels. When using multiple fragments, attach the ViewModel to the Activity containing them. When doing more complex operations which involves also switching activities, switch to global request observers attached to your App context.

**Comment by marmoniasqli** [comment]
Hi !
Sorry to bring it back. I have the same issue in 4.2.0.
The `android:requestLegacyExternalStorage="true"` worked for me but it seems like copying the file in the application cache directory solves the issue.
Source : https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df

**Comment by gotev** [comment]
If you request runtime permissions to access external storage prior to starting the upload request, what happens?

**Comment by marmoniasqli** [comment]
How would you do it please ?
I didn't manage to find the Android 10 specific way to request the runtime permission as the permission is already set in the manifest.
In the documentation, I only found that you must use the `query` function of the `ContentResolver` to query for media files that are outside of the application directory via the `MediaStore`.
Do you have a better understanding of the matter ? I could really use some help.

**Comment by gotev** [comment]
Starting from Android 6 it's not sufficient to declare requested permissions in the manifest, but also request some of them at runtime, as the user can give/revoke them whenever he wants. Start from here: https://developer.android.com/distribute/best-practices/develop/runtime-permissions

**Comment by gotev** [comment]
You have to request permissions if you want to make your own file selector. Easy way is to use the system content provider, for which there's a full example in the Wiki and a working project: https://github.com/gotev/android-upload-service/wiki/Getting-Started-with-4.x

**Comment by marmoniasqli** [comment]
Alright thank you.
It seems that we're already doing that in the app but still, we have the error `open failed: EACCES (Permission denied)` on Android 10.

**Comment by gotev** [comment]
Can you make a demo project and replicate the problem?

**Comment by marmoniasqli** [comment]
Hi !
I do not manage to create a demo project that reproduces the bug.
Sorry for the inconvenience.
I will delete my comments !
