### ISSUE TITLE
Upload Service 4 Beta 1

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#470]
Fasten your seatbelt, Upload Service 4 Beta 1 is here! #450 checkmarks reflects what you will find in this version as compared to 3.5.2. Use this issue to provide feedback about this release.

**THIS IS SUITABLE FOR PRODUCTION AND RECOMMENDED FOR ANDROID 10. IF YOU FEEL UNCOMFORTABLE USING BETA, [USE 3.5.2](https://github.com/gotev/android-upload-service/wiki/Setup)**

For those who wants to experience the new Upload Service, here we go. Upgrade your Gradle (by adding only the artifacts you need):

```gradle
def uploadServiceVersion = "4.0.0-beta01"
implementation "net.gotev:uploadservice:$uploadServiceVersion"
implementation "net.gotev:uploadservice-okhttp:$uploadServiceVersion"
implementation "net.gotev:uploadservice-ftp:$uploadServiceVersion"
```

Docs are not ready yet, because it's time consuming all the time dedicated so far has been to the development to improve the library. They will be started soon. [The demo app example](https://github.com/gotev/android-upload-service/tree/master/examples/app/demoapp/src/main/java/net/gotev/uploadservicedemo) is fully functional and can be used as reference. If you're coming from 3.x version, prepare a cup of coffee and enter in refactoring mood.

Feel free to tell here anything about this version.

### Changelog since 4.0 Alpha 4
- All the enums are now following the standard Kotlin styleguide, being in camel case with first capital letter
- Library has now a bundled notification actions observer, which receives broadcast PendingIntents associated to notifications actions and handles cancellation action by default.
  - To add a cancel action to your progress notification, follow this example: https://github.com/gotev/android-upload-service/blob/74536005405aadf28024a463f15a89e6e80fb162/examples/app/demoapp/src/main/java/net/gotev/uploadservicedemo/BaseActivity.java#L59-L63
  - You can implement your custom notification actions observer by extending `NotificationActionsObserver` and set it to be the default with: 
    ```kotlin
    UploadServiceConfig.notificationActionsObserverFactory = { uploadId -> 
        YourCustomNotificationActionsObserver(uploadId) 
    }
    ```
- `setNotificationConfig` is now a lambda with `uploadId` as the parameter, making it easier to use it to create your custom notification config. This is essential to be able to add notification actions which references the `UploadId`. Example: https://github.com/gotev/android-upload-service/blob/74536005405aadf28024a463f15a89e6e80fb162/examples/app/demoapp/src/main/java/net/gotev/uploadservicedemo/MultipartUploadActivity.java#L42
- `UploadNotificationStatusConfig` *title* and *message* are now mandatory
- Removed `setCustomUserAgent` from request builders. This is a notion of the underlying HttpStack. You can customize it based on the Http Stack you're using:
  - If using `HurlStack`, you can set your custom user agent with `UploadServiceConfig.httpStack = HurlStack("YourCustomUserAgent")`
  - If using `OkHttpStack`, you can set custom user agent with `UploadServiceConfig.httpStack =  OkHttpStack(yourCustomOkHttpClient)`. Example (open the class to see it better): https://github.com/gotev/android-upload-service/blob/74536005405aadf28024a463f15a89e6e80fb162/examples/app/demoapp/src/main/java/net/gotev/uploadservicedemo/App.java#L84-L89

**Comment by gotev** [comment]
@ChristinaGit this integrates all your feedbacks + new additions

**Comment by jxl715** [comment]
use version  4.0.0-beta1，UploadService crash.
follow is crash log:
java.lang.RuntimeException: Unable to start service net.gotev.uploadservice.UploadService@3dae0f5e with Intent { act=com.ubtech.filetransfer.uploadservice.action.upload cmp=com.ubtech.sample.filetransfer/net.gotev.uploadservice.UploadService (has extras) }: java.util.concurrent.RejectedExecutionException: Task net.gotev.uploadservice.protocols.multipart.MultipartUploadTask@17440d55 rejected from java.util.concurrent.ThreadPoolExecutor@8c7c36a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3079)
        at android.app.ActivityThread.access$2100(ActivityThread.java:164)

**Comment by gotev** [comment]
Please provide more information following the issue template

**Comment by jxl715** [comment]
follow is my code:

init:
  public static void init(Context context) {
        sContext = context;
        UploadServiceConfig.setNamespace(BuildConfig.LIBRARY_PACKAGE_NAME);
        UploadServiceConfig.setHttpStack(getOkHttpStack());
        UploadServiceLogger.setDevelopmentMode(BuildConfig.DEBUG);

        createNotificationChannel();
    }

use: 
     UploadRequest request = new AUploadRequest(context, url)
                    .addFileToUpload(path, "upload", null);
  
            request.subscribe(mContext, uploadRequestObserver);

first time upload file it run ok, but second time it crash. And I think it's because threadPool only init one time, when  UploadService onDestroy, and the function call threadPool.shutdown(),  so second time I upload file ,it crash. 

service onDestroy log:
Service will be shut down in 10s if no new tasks are received

**Comment by gotev** [comment]
@jxl715 thank you for the issue report. It's foxed and will be released in beta 2

**Comment by gotev** [comment]
Beta 1 stage is over! Please welcome Beta 2 🎉 #471
