### ISSUE TITLE
Multiple notification issue in android while concurrent upload

### ISSUE THREAD

**Issue by rajeev15june** [gotev/android-upload-service#473]
### Version info
* Android Upload Service version:
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
It's how library works until 4.0. Notification IDs are handled internally. In 4.0 you can write your own notification handler if you want a single notification for multiple uploads

**Comment by Justin-Credible** [comment]
@gotev Apologies for bumping an old thread, but is this now possible in 4.0 via a custom notification handler? Issue #450 says:

> Custom notification handler. It's possible to use your own notification handler implementation.

I'm assuming this is done by setting a custom notification handler factory which returns a custom notification handler:

```
UploadServiceConfig.setNotificationHandlerFactory((uploadService) -> new MyNotificationHandler(uploadService));
```

Is there an example of how `MyNotificationHandler` would be implemented?

**Comment by gotev** [comment]
Hi @justin-credible, with a custom notification handler you can implement many different behaviors, having full control of notification creation. You can start from the current bundled implementation as an example: https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/observer/task/NotificationHandler.kt

**Comment by nickadna** [comment]
@gotev using a custom notification handler with concurrent uploads set to 2, the notification is created two times even with the same notificationId. Do you know how to avoid it?

**Comment by gotev** [comment]
Post a link to a project where it's replicated

**Comment by sc-nick** [comment]
Here is the custom notification handler https://github.com/nickadna/uploads/blob/master/CustomNotificationHandler.java

And the init

`public class TransferBackground {
    
    private void initManager(String options, final CallbackContext callbackContext) throws IllegalStateException {
        UploadServiceConfig.setNotificationHandlerFactory((uploadService) -> new CustomNotificationHandler(uploadService));

        UploadServiceConfig.setHttpStack(new OkHttpStack());
        ExecutorService threadPoolExecutor =
                new ThreadPoolExecutor(
                        2,
                        2,
                        5000,
                        TimeUnit.MILLISECONDS,
                        new LinkedBlockingQueue<Runnable>()
                );
        UploadServiceConfig.setThreadPool((AbstractExecutorService) threadPoolExecutor);
}`

**Comment by nickadna** [comment]
Here is the custom notification handler https://github.com/nickadna/uploads/blob/master/CustomNotificationHandler.java

And the init

`UploadServiceConfig.setNotificationHandlerFactory((uploadService) -> new CustomNotificationHandler(uploadService));

        UploadServiceConfig.setHttpStack(new OkHttpStack());
        ExecutorService threadPoolExecutor =
                new ThreadPoolExecutor(
                        2,
                        2,
                        5000,
                        TimeUnit.MILLISECONDS,
                        new LinkedBlockingQueue<Runnable>()
                );
        UploadServiceConfig.setThreadPool((AbstractExecutorService) threadPoolExecutor);`

**Comment by nickadna** [comment]
Here is the custom notification handler https://github.com/nickadna/uploads/blob/master/CustomNotificationHandler.java

And the init
https://github.com/nickadna/uploads/blob/master/Init.java

**Comment by gotev** [comment]
TaskObserver methods are called for each upload task at each state. Every upload has its own notification ID. If you want to have a single notification which groups all the uploads, you have to deal with each upload task's status and act accordingly, creating the notification only once and then updating it after each significant status change for you, ignoring the notification ID passed to you and using your own.

**Comment by nickadna** [comment]
That's what I tried in onStart, create the notification once / update it. Or what do you mean by deal with each upload task's status? If you can give me an example, like that things are more clearer.

**Comment by nickadna** [comment]
That's what I tried in onStart, create the notification once / update it. Hence 2 notifications are created in parallel or what do you mean by deal with each upload task's status? If you can give me an example, like that things are more clearer.

**Comment by nickadna** [comment]
For those who need the solution
https://github.com/gotev/android-upload-service/issues/494

**Comment by gotev** [comment]
Starting from `4.3.0` onwards, Upload Service has a bundled-in abstract single notification handler which displays a single notification for all the uploads. Visit [Notification Handler Wiki](https://github.com/gotev/android-upload-service/wiki/Configuration#notification-handler)
