### ISSUE TITLE
Uploading Bitmaps files or a way to scale down files before uploading it

### ISSUE THREAD

**Issue by Geowan** [gotev/android-upload-service#475]
How can we upload bitmaps since sometimes we need to resize images from a camera image.
That is from my camera am using the following code

     public static Bitmap scaleDown(Bitmap realImage, float maxImageSize,
                               boolean filter) {
         float ratio = Math.min(
            (float) maxImageSize / realImage.getWidth(),
            (float) maxImageSize / realImage.getHeight());
        int width = Math.round((float) ratio * realImage.getWidth());
        int height = Math.round((float) ratio * realImage.getHeight());

       Bitmap newBitmap = Bitmap.createScaledBitmap(realImage, width,
            height, filter);
       return newBitmap;
    }

Now on my image camera action i have 

                         @Override
      public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        List<Image> pickedImages = ImagePicker.getImages(data);
        if (pickedImages != null && !pickedImages.isEmpty()) {

        for (Image item:pickedImages){
             String imagePath = item.getPath() //this is the correct path

             Bitmap scaledBitmap = scaleDown(BitmapFactory.decodeFile(item.getPath()),80,true);
           //upload scaled bitmap here
        }
    }
    super.onActivityResult(requestCode, resultCode, data);
   }

Currently in the upload service i can see it requires a string file path
                  new MultipartUploadRequest(getContext(),uploadId, uploadUrl)
                            .addFileToUpload(path, "temporary_file") //this requires a path

Is there an option to upload a bitmap as above or is there a way to go about this uploading the scaled file.

**Comment by gotev** [comment]
Get the photo, do what you need to do, save to your app cache directory and use that path in your upload
