### ISSUE TITLE
Callback when success

### ISSUE THREAD

**Issue by aqitmalinzda** [gotev/android-upload-service#476]
How get callback when upload success?

**Comment by gotev** [comment]
On which Upload Service version?

**Comment by aqitmalinzda** [comment]
> On which Upload Service version?

version 4.0.0-rc1

**Comment by gotev** [comment]
It depends on what you need.
- Listen at app level: create your request observer delegate, then create a new request observer, assign the delegate to it and register it.
- Listen in the current lifecycle: use .subscribe on the upload request

**Comment by aqitmalinzda** [comment]
`private fun uploadFile(filePath: String) {
        MultipartUploadRequest(this, serverUrl = ApiServices().UPLOAD_SCHEDULE)
            .setMethod("POST")
            .addFileToUpload(filePath = filePath, parameterName = "file")
            .addParameter("token", "${App.getInstance(this).getToken()}")
            .addParameter("schedule_id", schedule?.id.toString())
            .subscribe(this, object : RequestObserverDelegate {
                override fun onProgress(@NotNull context: Context, @NotNull uploadInfo: UploadInfo) {}
                override fun onSuccess(@NotNull context: Context, @NotNull uploadInfo: UploadInfo, @NotNull serverResponse: ServerResponse) {}
                override fun onError(@NotNull context: Context, @NotNull uploadInfo: UploadInfo, @NotNull exception: Throwable) {}
                override fun onCompleted(@NotNull context: Context, @NotNull uploadInfo: UploadInfo) {}
                override fun onCompletedWhileNotObserving() {}
            }).startUpload()
    }`

> It depends on what you need.
> 
> * Listen at app level: create your request observer delegate, then create a new request observer, assign the delegate to it and register it in your Application subclass
> * Listen in the current lifecycle: use .subscribe on the upload request from activity/fragment/ViewModel

Thanks. Work form me

**Comment by aqitmalinzda** [comment]
> It depends on what you need.
> 
> * Listen at app level: create your request observer delegate, then create a new request observer, assign the delegate to it and register it in your Application subclass
> * Listen in the current lifecycle: use .subscribe on the upload request from activity/fragment/ViewModel

Thanks. Work for me :)
