### ISSUE TITLE
How to do binary file upload instead of Multipart File upload 

### ISSUE THREAD

**Issue by TechRova** [gotev/android-upload-service#480]
I want to upload files to Backblaze storage in this way 

![image](https://user-images.githubusercontent.com/47471431/70979791-35736080-20d8-11ea-9adf-d4ecc5091f0c.png)

That is , they need to append the File as binary body instead of Form Data

The documentation link https://www.backblaze.com/b2/docs/b2_upload_file.html

In your library , there is no mention about binary body . Only `.addFileUpload` which id s Form Data type or Multipart 

So I am struck 

Please help to upload file as in the backblaze docs

**Comment by gotev** [comment]
There's the BinaryUploadRequest which does exactly what you need. Check it also ok the demo app

**Comment by TechRova** [comment]
> There's the BinaryUploadRequest which does exactly what you need. Check it also on the demo app.

  new BinaryUploadRequest(this,URL.uploadImage)
                .addHeader("myheader","jj")
                .setFileToUpload(redFile.getAbsolutePath())
                .setNotificationConfig(new UploadNotificationConfig())
                .setDelegate(new UploadStatusDelegate() {
                    @Override
                    public void onProgress(Context context, UploadInfo uploadInfo) {
                        
                    }

                    @Override
                    public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {

                    }

                    @Override
                    public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {

                    }

                    @Override
                    public void onCancelled(Context context, UploadInfo uploadInfo) {

                    }
                }).startUpload();

**Comment by gotev** [comment]
I strongly advise you:
- to not use delegates (detailed info in wiki)
- to use new 4.0
