### ISSUE TITLE
Pass LifecycleOwner as a parameter to the RequestObserver

### ISSUE THREAD

**Issue by bitvale** [gotev/android-upload-service#482]
Hi! Good library, thanks!

I think it will be good if we can pass `LifecycleOwner` as a parameter to the `RequestObserver`.

In this case, for example, we can use fragment's `viewLifecycleOwner` instead of context's `LifecycleOwner`, because context represents LifecycleOwner that observe `Activity` callbacks.

**Comment by gotev** [comment]
Hi @bitvale nice suggestion! I'll be glad to see a PR with it!

**Comment by gotev** [comment]
This is now available in `4.1.0`
