### ISSUE TITLE
Background service

### ISSUE THREAD

**Issue by DimalPerera** [gotev/android-upload-service#484]
Great library. 
I'm using your library since last year. It's working well in my old project. 

Recently I got new requirement to upload multiple images (one by one) on background and image upload status should be update on local SQLite database (upload success or fail status). Users might be close the application but image upload and updating SQLite database should be work.

How to achieve this kind of requirement?

**Comment by gotev** [comment]
Glad the library is useful! For this new requirement I suggest you to use newer 4.0.0 and to experiment launching upload tasks directly using WorkManager, which is now possible. Never attempted though, but it will be useful to many users, so feel free to try and report here how it goes.
