### ISSUE TITLE
Please add notificationID

### ISSUE THREAD

**Issue by tobias-r** [gotev/android-upload-service#485]
Could you please add the notificationID as a property to the UploadNotificationConfig?

Therefore we can achieve that when calling the upload service multiple times, the notification doesn't always disappear and reappear.

THANKS!

**Comment by gotev** [comment]
Send a PR with your idea and we can discuss about it!

**Comment by tobias-r** [comment]
Hi gotev, thanks so much for your reply.

My motivation is pretty easy, it's described above. I would like to upload multiple files, but I cannot use your multifile upload logic. So I need to create a new upload request everytime a file is finished. With setting a notificationID I could guarantuee, that the same notification is overwritten anytime. Currently for every new file the notification closes and reopens, which is not really a good experience.

Could you do the PR for me please? I am not familiar with this?

Thanks for the awesome work, Tobias

**Comment by gotev** [comment]
Sorry @tobias-r don't mean to be rude but that's not the spirit of Open Source Projects, as this is not a commercial product you are paying for, nor a free consultancy service where you ask someone to do something for you. Open Source is getting your hands dirty, exploring and studying code to make it better for the benefit of all. It also means starting out by messing around and trying new ideas together with the community.

To achieve what you described you need to implement a custom notification handler. You can take the existing one as an example to start with. What I can do is to review the solution you propose and guide you through the implementation.

**Comment by tobias-r** [comment]
Hi gotev, I cannot do it, sorry. It's not that I don't want, but I don't know how to code Kotlin, I cannot even make it to implement your v4 version, because there is too little documentation. Sorry

**Comment by gotev** [comment]
Follow the Getting Started information: https://github.com/gotev/android-upload-service/wiki/Getting-Started-with-4.x
