### ISSUE TITLE
background without notification

### ISSUE THREAD

**Issue by jxl715** [gotev/android-upload-service#486]
### What did you expect?
I need to upload file without notification. Because I need to upload hundreds of files to server,  now there is hundreds of notification. I try set notification config to null, in android 5.x it is ok, but in android 10, it throw a exception. Can I use this library upload files without notification? I only need upload file in background like in background threads.

### Version info
* Android Upload Service version:4.0.0-beta1
* Android version and API version: android 10
* HTTP stack (e.g. HurlStack or OkHttpStack):okhttp stack

**Comment by gotev** [comment]
Hi, this is intended behavior as of Android API 26: https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadServiceConfig.kt#L209-L223
