### ISSUE TITLE
Allow customization of delete intent through UploadNotificationStatusConfig

### ISSUE THREAD

**Issue by mvasquezb** [gotev/android-upload-service#488]
It would be useful to be able to customize the notification's delete intent through the notification status config. A use case I found would be to delete the resources associated with an upload (files, metadata, etc) whenever the user deletes an upload notification after cancellation/error.

What do you think  ?

**Comment by gotev** [comment]
Hi @mvasquezb what you describe is more of a custom action to be performed in response of a particular event (success/cancellation/error) rather than a configuration. `NotificationConfig` role is to configure appearance, data and actions to perform for each notification state. It's meant to be declarative, as it has to go through Android's internal Intent mechanism, so you cannot have custom business logic functions in it, but you can add custom triggers to additional custom actions via the Actions Pending Intents.

With 4.x you can achieve what you described pretty easily by implementing a custom `RequestObserverDelegate` and using that as monitor for your uploads. When you receive an event in the Request Observer, you have full access to the `UploadInfo`, which in turn gives you access to all the files included in the upload request. In case of upload failure, through the handler of each file, you can also delete it.

**Comment by mvasquezb** [comment]
I meant it more as an extension of the actions allowed on a notification, for example, on the `error` or `cancelled`, I've got actions that allow the user to either retry or delete the upload and it's associated data. I'm also setting the `clickIntent` in the status config to retry the upload and I'm doing all that through `PendingIntent`s handled by an action receiver which manages all of queueing the uploads, cleaning up, etc.
But I can't handle the case where the user deletes the notification, it just does nothing, that's why I thought this would be useful to have as an enhancement.
For example, if this is my `UploadNotificationStatusConfig`:
```kotlin
UploadNotificationConfig(
    notificationChannelId = UploadServiceConfig.defaultNotificationChannel!!,
    isRingToneEnabled = true,
    progress = UploadNotificationStatusConfig(
        ...
    ),
    success = UploadNotificationStatusConfig(
        ...
    ),
    error = UploadNotificationStatusConfig(
        title = title,
        message = context.getString(R.string.msg_upload_error),
        clearOnAction = true,
        actions = getErrorActions(context, uploadId),
        iconResourceID = R.drawable.logo_notification,
        clickIntent = getRetryIntent(context, uploadId)
    ),
    cancelled = UploadNotificationStatusConfig(
        title = title,
        message = context.getString(R.string.msg_upload_cancelled),
        clearOnAction = true,
        actions = getCancelActions(context, uploadId),
        iconResourceID = R.drawable.logo_notification,
        clickIntent = getRetryIntent(context, uploadId)
       // This is where I'd like to put the `cancelIntent`
    )
)
```
My actions for the `cancelled` status are:
```kotlin
fun getCancelActions(context: Context, uploadId: String): ArrayList<UploadNotificationAction> {
    return arrayListOf(
        UploadNotificationAction(
            icon = R.drawable.ic_delete_white,
            title = context.getString(R.string.txt_delete),
            intent = UploadNotificationActions.delete(context, uploadId)
        ),
        UploadNotificationAction(
            icon = R.drawable.ic_refresh_white,
            title = context.getString(R.string.txt_retry),
            intent = UploadNotificationActions.retry(context, uploadId)
        )
    )
}
```
Regardless of implementation, you can see that the notification gives the user the choice to either delete or retry the upload if necessary. What I'm asking is basically the same configuration for the `delete` action but through the notification's `deleteIntent`.
I think it would still be inline with the configuration perspective, it'd just be an additional optional one.

**Comment by gotev** [comment]
I intended a different thing from the initial statement. You mean an action to be performed when the user swipes out the notification from the notification center?

**Comment by mvasquezb** [comment]
Yes, exactly

**Comment by gotev** [comment]
It sounds good then and it will be a valuable addition! I'm pretty busy in this period, but you don't have to wait for me. If you need it, go ahead and send me a PR. 😃

**Comment by mvasquezb** [comment]
Great ! Sure thing

**Comment by gotev** [comment]
The user can dismiss a notification which is in either cancelled, successful or error state. With the bundled in notification handler, the only non dismissable notification is progress. I would add an `onDismissed` property in `UploadNotificationStatusConfig` which allows to set a Pending Intent (same as clickIntent). In the case of progress notification it can simply be ignored. It's not the most beautiful thing, but the only alternative I see to is to have a dedicate class, called for example `DismissableUploadNotificationStatusConfig` which has the same properties as `UploadNotificationStatusConfig` plus `onDismissed` and use that for completed, successful and error statuses, while keep using `UploadNotificationStatusConfig` for the progress.

I'm open to further ideas and proposals.

**Comment by mvasquezb** [comment]
Sounds about right, I think adding another class with practically the same properties as the current `UploadNotificationStatusConfig` is unnecessary. The goal of this feature is: if the `onDismissed` is not provided, behaviour remains the same, if it is, it just adds an action. That makes me think the optional `onDismissed` property makes more sense and is simpler

**Comment by gotev** [comment]
> That makes me think the optional onDismissed property makes more sense and is simpler

Exactly, with default set to `null`. If it's declared and not null, we set it when creating the notification for that state.
