### ISSUE TITLE
App terminated/closed handling upload Response

### ISSUE THREAD

**Issue by ycharbel88** [gotev/android-upload-service#491]
hi,
First I, need to thank you for this amazing library.
I need to ask you the best way to handle the upload response in case we killed the app 
I am using version 4.2.1 
**Scenario:**

- I did an upload request for a video 
- then I killed the app 
- the notification continue the upload normally 
- and its succeed uploading 
- so I need to save this state to delete the file from local db when the app is reopened (it is possible to delete file from db when the app is background (closed)...)

Thank you

**Comment by gotev** [comment]
Hi @ycharbel88 and thanks for this scenario report. On which Android version have you tested it? On many Android versions, when you swipe out the app from the pager, the root process gets killed as well and the upload halts, so it never completes.

**Comment by ycharbel88** [comment]
I am using android 9.
It's a Samsung note 8 device.
upload on this device continues without any corruption and its success.
is there a way to save the response or in case no way to save the upload response and status can i force the process to stop uploading when the app is killed 
thank you

**Comment by gotev** [comment]
Try with a global Request Observer and check if the callbacks are called. If the upload continues it means the process is still alive, so it should work. Check che monitor uploads Wiki for an example.
