### ISSUE TITLE
RequestObserverDelegate method not triggering inside service

### ISSUE THREAD

**Issue by Parag2385** [gotev/android-upload-service#495]
First of all, thank you so much for this great library, It saved me at least a week of time in development.

Secondly, this might be some silly mistake I'm doing, but I've invested an entire day, even dived into source code of this library but not getting what's wrong am I doing.

### What did you expect?
I expected that I'll get a response inside RequestObserverDelegate onCompleted or any other method.

### What happened instead?
Nothing, I'm not getting any response inside RequestObserverDelegate, though my files are successfully uploaded.

### Version info
* Android Upload Service version: 4.2.1
* Android version and API version: Android 10 and API 29
* HTTP stack (e.g. HurlStack or OkHttpStack): not sure (have been using okhttp3:okhttp:3.12.1 for Retrofit debugging)

### Steps to reproduce (if applicable):
Just put your request code inside the service as shown below.

### Library initialization code:
     UploadServiceConfig.initialize(
            context = this,
            defaultNotificationChannel = notificationChannelID,
            debug = BuildConfig.DEBUG
        )

### Request code:
    class FileUploadService : DaggerService() , LifecycleOwner {
    
        @Inject
        lateinit var mSharedPrefs: SharedPreferences
    
        @Inject
        lateinit var mCcsRepository: CcsRepository
    
        private val mDispatcher = ServiceLifecycleDispatcher(this)
    
        private val binder = FileUploadBinder()
    
        @CallSuper
        override fun onCreate() {
            mDispatcher.onServicePreSuperOnCreate()
            super.onCreate()
        }
    
        @CallSuper
        override fun onBind(intent: Intent): IBinder? {
            mDispatcher.onServicePreSuperOnBind()
            return binder
        }
    
        @CallSuper
        override fun onStart(intent: Intent?, startId: Int) {
            mDispatcher.onServicePreSuperOnStart()
            super.onStart(intent, startId)
        }
    
        @CallSuper
        override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
            return super.onStartCommand(intent, flags, startId)
        }
    
        @CallSuper
        override fun onDestroy() {
            mDispatcher.onServicePreSuperOnDestroy()
            super.onDestroy()
        }
    
        override fun getLifecycle(): Lifecycle {
            return mDispatcher.lifecycle
        }
    
        fun startUploading(mFileList: ArrayList<UploadFileModel>, mFileURLList: ArrayList<FileURLModel>){
            for (i in 0 until mFileList.size)
                uploadService(mFileURLList[i], mFileList[i])
        }
    
        private fun uploadService(mFileURLModel: FileURLModel, mFile: UploadFileModel){
            val request = BinaryUploadRequest(this, mFileURLModel.mSignedURL)
                .setMethod("PUT")
                .setNotificationConfig { _, _ ->
                    UploadNotificationConfig(
                        notificationChannelId = UploadServiceConfig.defaultNotificationChannel!!,
                        isRingToneEnabled = true,
                        progress = UploadNotificationStatusConfig(
                            title = "Uploading File",
                            message = ""
                        ),
                        success = UploadNotificationStatusConfig(
                            title = "File Upload Successful",
                            message = ""
                        ),
                        error = UploadNotificationStatusConfig(
                            title = "Error Occurred",
                            message = ""
                        ),
                        cancelled = UploadNotificationStatusConfig(
                            title = "Cancelled Upload",
                            message = ""
                        )
                    )
                }
    
            val mMimeType = FileUtils.getMimeType(Uri.parse(mFile.mFileUri!!), this)
    
            Log.e("FileUploadService", "uploadService: $mMimeType")
    
            request.addHeader("Content-Type", mMimeType!!)
            request.setFileToUpload(mFile.mFileUri)
            request.setUploadID(UUID.randomUUID().toString())
            request.startUpload()
    
            request.subscribe(this, this, object : RequestObserverDelegate {
                override fun onCompleted(context: Context, uploadInfo: UploadInfo) {
                    Toast.makeText(this@FileUploadService, "Upload Completed", LENGTH_LONG).show()
                    Log.e("FileUploadService", "onCompleted: ")
                }
    
                override fun onCompletedWhileNotObserving() {
                    Log.e("FileUploadService", "onCompletedWhileNotObserving: ")
                }
    
                override fun onError(context: Context, uploadInfo: UploadInfo, exception: Throwable) {/*Not Require*/}
    
                override fun onProgress(context: Context, uploadInfo: UploadInfo) {
                    Log.e("FileUploadService", "onProgress: ")
                }
    
                override fun onSuccess(
                    context: Context,
                    uploadInfo: UploadInfo,
                    serverResponse: ServerResponse
                ) {
                    Toast.makeText(this@FileUploadService, "Upload Success", LENGTH_LONG).show()
                    Log.e("FileUploadService", "onSuccess: ")
                }
    
            })
        }
    
        inner class FileUploadBinder : Binder() {
            // Return this instance of LocalService so clients can call public methods
            fun getService(): FileUploadService = this@FileUploadService
        }
    }
    
#### Where have you added the request code?
Service

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging) first)
    I/UploadService: NotificationActionsObserver - (uploadId: N/A) - registered
    I/UploadService: UploadService - (uploadId: N/A) - Starting UploadService. Debug info: {
            "uploadServiceVersion": "4.2.1",
            "androidApiVersion": 29,
            "namespace": "com.scogo.scogonetworks",
            "deviceProcessors": 8,
            "idleTimeoutSeconds": 10,
            "bufferSizeBytes": 4096,
            "httpStack": "net.gotev.uploadservice.network.hurl.HurlStack",
            "uploadProgressNotificationIntervalMillis": 333,
            "retryPolicy": {"initialWaitTimeSeconds": 1, "maxWaitTimeSeconds": 100, "multiplier": 2, "defaultMaxRetries": 3},
            "isForegroundService": true,
            "schemeHandlers": {"/": "net.gotev.uploadservice.schemehandlers.FileSchemeHandler", "content://": "net.gotev.uploadservice.schemehandlers.ContentResolverSchemeHandler"}
        }
    I/UploadService: UploadService - (uploadId: N/A) - Successfully created new task with class: net.gotev.uploadservice.protocols.binary.BinaryUploadTask
    I/UploadService: UploadService - (uploadId: N/A) - Starting UploadService. Debug info: {
            "uploadServiceVersion": "4.2.1",
            "androidApiVersion": 29,
            "namespace": "com.scogo.scogonetworks",
            "deviceProcessors": 8,
            "idleTimeoutSeconds": 10,
            "bufferSizeBytes": 4096,
            "httpStack": "net.gotev.uploadservice.network.hurl.HurlStack",
            "uploadProgressNotificationIntervalMillis": 333,
            "retryPolicy": {"initialWaitTimeSeconds": 1, "maxWaitTimeSeconds": 100, "multiplier": 2, "defaultMaxRetries": 3},
            "isForegroundService": true,
            "schemeHandlers": {"/": "net.gotev.uploadservice.schemehandlers.FileSchemeHandler", "content://": "net.gotev.uploadservice.schemehandlers.ContentResolverSchemeHandler"}
        }
    E/UploadService: UploadService - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - Preventing upload! An upload with the same ID is already in progress. Every upload must have unique ID. Please check your code and fix it!
    I/UploadService: UploadService - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - now holds foreground notification
    I/UploadService: BinaryUploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - Starting upload task
    I/UploadService: HurlStackRequest - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - creating new HttpURLConnection (uuid: 3e0f43b6-6f33-4de9-8456-630e6f15302d)
    V/FA: Inactivity, disconnecting from the service
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - uploaded 0%, 4096 of 3255923 bytes
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - uploaded 16%, 528384 of 3255923 bytes
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - uploaded 37%, 1208320 of 3255923 bytes
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - uploaded 52%, 1724416 of 3255923 bytes
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - uploaded 68%, 2240512 of 3255923 bytes
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - uploaded 84%, 2756608 of 3255923 bytes
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - uploaded 100%, 3255923 of 3255923 bytes
    I/UploadService: HurlStackRequest - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - closing HttpURLConnection (uuid: 3e0f43b6-6f33-4de9-8456-630e6f15302d)
    I/UploadService: BinaryUploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - Server response: code 200, body 
    I/UploadService: UploadTask - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - upload completed
    I/UploadService: UploadService - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - now un-holded foreground notification
    I/UploadService: UploadService - (uploadId: N/A) - All tasks completed, stopping foreground execution
    I/UploadService: UploadService - (uploadId: N/A) - Service will be shut down in 10s if no new tasks are received
    I/UploadService: UploadService - (uploadId: N/A) - Service is about to be stopped because idle timeout of 10s has been reached
    I/UploadService: NotificationActionsObserver - (uploadId: N/A) - unregistered
    I/UploadService: UploadService - (uploadId: N/A) - Stopping foreground execution
    I/UploadService: UploadService - (uploadId: N/A) - UploadService destroyed

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?
##Have used node.js  that's the only thing I know

Hope this clears my problem. Thanks again for this awesome library.

**Comment by gotev** [comment]
When you see
```
E/UploadService: UploadService - (uploadId: c21c8173-17c3-4f46-b764-aad084e8ac86) - Preventing upload! An upload with the same ID is already in progress. Every upload must have unique ID. Please check your code and fix it!
```
There's something wrong which is the following:

```
request.startUpload()
request.subscribe(this, this, object : RequestObserverDelegate {
```
You should use either `startUpload()` (which returns the uploadID you can monitor in an existing RequestObserver) or `subscribe`. Both methods starts the upload. The second starts the upload a creates a RequestObserver. In this case you're starting the upload twice.

In the code I've seen  you have 
```
request.setUploadID(UUID.randomUUID().toString())
```
which you can safely remove, as the library takes care of generating a random upload ID for you.

Another thing which I couldn't understand is why you have created a service just to make a bunch of uploads. Library has no blocking code and you can safely trigger uploads from any Activity/Fragment and monitor progress independently from their lifecycle, as the actual upload happens inside UploadService.

**Comment by Parag2385** [comment]
First, thank you so much for such a quick response.

Okay, I got your point, I didn't know that subscribe also starts upload. I removed the startUpload() call. But still, the methods inside RequestObserverDelegate did not trigger.

About set upload ID I'm gonna use custom ID's there to map it with stored data into local SQLite storage.

I created service because the user can close the app any time after starting the upload, I need the status of those uploaded files so that I can update my local storage accordingly.

I checked the sample app you've provided, I saw you have used GlobalBroadcastReceiver. So I used it inside my code as well and voila it worked, I'm getting the response there.  But If I close the app then I'm not getting any response as of course, GlobalBroadcastReceiver is running on the app process which will not live outside the app process. 

So what should I do to get a response after the app process is killed, thank you.

**Comment by gotev** [comment]
Use [LifecycleService](https://developer.android.com/reference/androidx/lifecycle/LifecycleService) instead of making your own implementation. Example: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#from-service

Forgot to tell you in the previous review.

>So what should I do to get a response after the app process is killed, thank you.

Nothing. Everything gets terminated when you kill the app, there's no way for a service to survive, therefore all the uploads will be aborted by the system. For that reason google came out with WorkManager. Theoretically, given the composable nature of Android Upload Service 4, you could write a job which uses upload tasks internally, however I haven't experimented with it yet.

**Comment by Parag2385** [comment]
Okay, I tried LifecycleService, instead of custom implementation. But did not receive updates even when the app process was alive. Files are getting uploaded in every scenario the only problem is with status updates.

I tried upgrading to 4.2.2 but still no luck. Getting updates in the background is 2nd step, but I'm not getting updates even when I'm in the foreground.

I'd try creating worker thread and use workManager to execute it. But what am I going to pass for lifecycleOwner parameter to subscribe method in the worker thread?

Thank you.

**Comment by gotev** [comment]
> But did not receive updates even when the app process was alive. Files are getting uploaded in every scenario the only problem is with status updates.
On Android 10 the system requires you start it in foreground, which requires you to display a notification for your service.

Current `RequestObserver` implementation is tied to the `LifecycleOwner`. With a lifecycle-less implementation you could receive events also while your app is in background, not requiring you to set up a whole new service just to receive status updates. Such implementation will be provided in the next release, estimated before the end of this week.

**Comment by Parag2385** [comment]
Okay, thanks that would be great. Waiting for the next release :)

**Comment by gotev** [comment]
You can update to `4.3.0` and follow this guide: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-all-upload-requests

**Comment by prashantpag26** [comment]
I got the same issue in JobIntentService(), RequestObserverDelegate was not calling. Can you please help me to sort out this issue.

**Comment by prashantpag26** [comment]
May be its pass wrong parameter in lifecycleowner.
   .subscribe(context = this,
                            lifecycleOwner = this, //how to get lifecycleOwner  in JobIntentService()
                            delegate = object : RequestObserverDelegate {})

**Comment by gotev** [comment]
@prashantpag26 try using GlobalRequestObserver inside your service
