### ISSUE TITLE
How to auto dismiss notification when upload completed?

### ISSUE THREAD

**Issue by huynguyennovem** [gotev/android-upload-service#499]
**What do you want to achieve?**
How to auto dismiss notification when upload completed?

**What have you tried to do?**
When upload completed, I tried this, but it does not work
```java
NotificationManager notificationManager = (NotificationManager) getActivity().getSystemService(Context.NOTIFICATION_SERVICE);
notificationManager.cancelAll();
```

**Which Upload Service Version are you using?**
4.1.0

**On which Android version?**
Android 6

**Additional info**
This solution does not work by `UploadNotificationConfig` does not have empty constructor anymore:
```java
UploadNotificationConfig config = new UploadNotificationConfig();
config.getCompleted().autoClear = true;
yourUploadRequest.setNotificationConfig(config);
```

**Comment by gotev** [comment]
Configuration objects are immutable. You have to pass in the required values in the constructor. Take a look at: https://github.com/gotev/android-upload-service/wiki/Configuration#uploadnotificationconfig

**Comment by huynguyennovem** [comment]
> Configuration objects are immutable once created. You have to pass in the required values in the constructor. Take a look at: https://github.com/gotev/android-upload-service/wiki/Configuration#uploadnotificationconfig

Thank you for referring to this document. But how to pass `uploadNotificationConfig` into `UploadServiceConfig` ?
```java
UploadNotificationConfig uploadNotificationConfig = new UploadNotificationConfig(
                    UploadServiceConfig.getDefaultNotificationChannel(),
                    true,
                    new UploadNotificationStatusConfig(
                            "Test",
                            "Video uploading..."
                    ),
                    new UploadNotificationStatusConfig(
                            "Test",
                            "Video upload success"
                    ),
                    new UploadNotificationStatusConfig(
                            "Test",
                            "Video upload error"
                    ),
                    new UploadNotificationStatusConfig(
                            "Test",
                            "User cancel"
                    )
            );
uploadNotificationConfig.getSuccess().getAutoClear();
UploadServiceConfig.setNotificationConfigFactory(/*how to passing param here*/);
```

**Comment by huynguyennovem** [comment]
> Configuration objects are immutable once created. You have to pass in the required values in the constructor. Take a look at: https://github.com/gotev/android-upload-service/wiki/Configuration#uploadnotificationconfig

Thanks! I have successfully implemented it. :)

**Comment by gotev** [comment]
You're welcome!
