### ISSUE TITLE
Poll: still using 3.x? Let me know!

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#501]
Upload Service 4 development started last year's summer. Now it reached 4.3.0. Many major improvements have been made: new features, better stability, security, maintainability, ease of customization, less error-prone code to write.

However, when I looked at the statistics of the latest 10 releases in the past 30 days:

<img width="812" alt="Schermata 2020-05-16 alle 16 31 45" src="https://user-images.githubusercontent.com/16792495/82122373-9096a580-9793-11ea-8b75-319f12142d77.png">

74% of the user base is still on `3.x`, so `4.x` where all my efforts have been concentrated, still fails to reach the majority of users.

**If you are a 3.x user, comment and let me know what prevents you to upgrade to 4.x**

based on comments, new voting options will be added. Vote using a reaction or comment to express a new opinion.

- 😕for current `minApi` of your Apps tied to API < 21

**Comment by Sdghasemi** [comment]
We're still using 3.5.2 with a min SDK version override to 17. The min SDK version is preventing us to upgrade I'm afraid.

**Comment by gotev** [comment]
> Thanks for the effort but we're still using 3.5.2 with a min SDK version override to 17. The min SDK version is preventing us to upgrade I'm afraid.

Thanks for sharing. How many active users do you have on API < 21? How much chances do you have to upgrade them? 4.x decision to support API 21+ is mainly for security issues and maintenance, to be able to support newer Androids in less time. Also, Apps on which I work have over 99% of the user base on API 21+. API 17 (2012) is 8 years old now. Most of the times, minApi locks are a business decision. That decision should be refreshed every year supported by a cost/effort/results analysis. Every product is different, but in my experience, that kind of analysis allowed my team to often unlock the minApi constraint.

**Comment by Sdghasemi** [comment]
@gotev 20% of our users are still on API < 21 which is about ~100k members. The APIs are old no argue in that but the user base seems insisting on keeping them, not to mention the current pandemic made it harder for users to purchase newer devices, I mean both financially and hygienically. Considering this circumstances the team decision was to unlock the minApi constraint in about a year or so to 21.

**Comment by gotev** [comment]
@Sdghasemi that's huge, I fully understand your current decision. Added a reaction option for you to vote. Tough times ahead of us, the future is unpredictable, but if I have you and other library users which are stuck in the same situation onboard, we can together make an `api17-backport` branch from current `4.3.0` and make PRs there, with the goal to have a fully functional new version suitable also for old devices. This means downgrading a bunch of dependencies (e.g. OkHttp) and implementing some compat functions to deal with old APIs. This should be a win-win for both developers and end users. @elena-p I remembered your request in #449 and I'm ready to change my decision if you want to contribute.

Let me know if you're interested in this proposal. I can't make it alone for lack of time and test devices, but together I'm sure it's possible. Open to other ideas, too.

**Comment by gotev** [comment]
@Sdghasemi @elena-p are you still interested in contributing in the backport branch? In [3.5.2](https://github.com/gotev/android-upload-service/blob/e96aa2a9b0beab1180647401ae1c3b5aec9cde07/manifest.gradle#L14) minSDK is `18`, so the backport branch will target that minSDK.

Let me know 😉

**Comment by Mayank1904** [comment]
Yeah I have the same suggestion please support atleast minSDK version to 20 , so that I can ugrade to 4.3.0 your latest version

**Comment by gotev** [comment]
The point is: I don't have time nor interest in doing that support because I don't need it and I couldn't afford providing support for it, but since there are people interested, I can open a branch where it's possible to contribute to create a backport for API < 21. Do you want to take part in this initiative?

**Comment by Mayank1904** [comment]
Ok can you please help me in giving the latest version which supports minsdk version 20

**Comment by gotev** [comment]
It's 3.5.2

**Comment by Mayank1904** [comment]
Hi, I have changed my minSDk version to 21 and library version updated to 4.3.1 but there are some issues because every class is changed in the new version 

Can you please help me in updating the class , I need callback for success in uploading the post 
Previously I was using UploadServiceBroadcastReceiver and there is overrided onComplete method in which I am updating UI 

I have used MultiPartRequest in ViewModel and I need callback in Actiivity

**Comment by tobiastromm** [comment]
@gotev I am trying to upgrade but version 4.3.1 remove support for Java and it just working for Kotlin right?

**Comment by gotev** [comment]
@tobiastromm no problems for Java at all, Kotlin is 100% interoperable. At the end the library it's JVM byte code, just as when you code it in Java. Kept [one of the the Demo Apps](https://github.com/gotev/android-upload-service/blob/master/examples/app/demoapp/src/main/java/net/gotev/uploadservicedemo/App.java) in Java as well and no problems at all.

**Comment by tobiastromm** [comment]
@gotev OK, I made it work. My suggestion is to also show Java code on wiki.

The one thing I don't know how to make work is to clear notification after a sucess upload.

This is what I was using before update 

`UploadNotificationConfig config = new UploadNotificationConfig();
config.getCompleted().autoClear = true;`

and

`.setNotificationConfig(config)`

Can you tell me whats the equivalent now?

**Comment by gotev** [comment]
This is getting OT here in this thread. You're free to contribute Java examples to be added in the wiki as well. Refer to the wiki examples: https://github.com/gotev/android-upload-service/wiki/Configuration#notifications To Jav-ize them just remove the labels `something =` and add `new` operator when creating new instances. 4.x promotes immutability, so everything is created and injected instead of creating an empty object and setting things up as it was in 3.x. 😎

**Comment by gotev** [comment]
Closing this since I don't have time nor need to do a backport and no one is interested in contributing that part and maintain it.

This is the situation of the last 30 days at the time of this writing:
<img width="835" alt="Schermata 2020-10-11 alle 00 17 05" src="https://user-images.githubusercontent.com/16792495/95666135-270a9f80-0b57-11eb-856c-c2d3786ccc0d.png">

More than 51% percent are using 4.x versions. Adoption of newer versions has doubled in the last 5 months.
