### ISSUE TITLE
sometimes retry 3 times per request , how to make retry 1 time only

### ISSUE THREAD

**Issue by pranayansaikia** [gotev/android-upload-service#502]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: [e.g. 4.3.0]
- Android version and API version: [e.g. Android 10]
- HTTP stack: [e.g. HurlStack or OkHttpStack]

**Request code:**
```kotlin
// the code you wrote to create the upload request
```
**Where have you added the request code?**
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

**Debug Log**:
```
// your debug log
```

**Comment by gotev** [comment]
Sure: https://github.com/gotev/android-upload-service/wiki/Configuration#retry-policy
