### ISSUE TITLE
Preserve Image Exif metadata

### ISSUE THREAD

**Issue by rad-ost** [gotev/android-upload-service#506]
Thank you so much for your time and effort to create this masterpiece. 

**What do you want to achieve?**
I was using a BinaryUploadRequest  to upload a file to a Blob Container in Azure Storage.
Everything seems to be working as expected, even better. 
There is a small problem, I am losing the metadata of the original image, is there something that I am missing, is it even possible?   

I was trying to find a way to pass byte arrays instead of image path...

**Which Upload Service Version are you using?**
4.3.1

Any advice would be appreciated 
Thank you

**Comment by gotev** [comment]
Hi! The library simply sends binary data as they are from the selected files to the server you configure. If there's an alteration in the uploaded file, it's not made by the library. 

There's a simple test you can make. Select the image you want to upload and check if the exif data are there. Make an md5 or sha1 checksum of that file. Perform the upload and re-do the md5 or sha1 on the file downloaded from the server. Compare the two checksums. If they are different it means the server is doing some kind of data transformation. 

You can retry the same scenario using ptsv2 (post test server v2). In the getting started wiki of 4.x there's an example about how to use that service.

Let me know how it goes 😀

**Comment by rad-ost** [comment]
You were right, thank you for you time and work

**Comment by gotev** [comment]
Glad you solved the issue or at least you understood what caused it! Is it a content provider or the server-side which makes the transformations?
