### ISSUE TITLE
Manifest merger failed 

### ISSUE THREAD

**Issue by Mayank1904** [gotev/android-upload-service#508]
I need to update the library to version 4.3.0 but it shows 

Manifest merger failed : uses-sdk:minSdkVersion 20 cannot be smaller than version 21 declared in library [net.gotev:uploadservice:4.0.0] /home/sqyuser/.gradle/caches/transforms-2/files-2.1/6ab7e8aa1624bc24ca24bd8ac421faf6/AndroidManifest.xml as the library might be using APIs not available in 20
  	Suggestion: use a compatible library with a minSdk of at most 20,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="net.gotev.uploadservice" to force usage (may lead to runtime failures)
If min sdk version is 20 then which latest version can i update this library, please help

**Comment by gotev** [comment]
Moving discussion to #501 for old API support request
