### ISSUE TITLE
How to turn off retry policy

### ISSUE THREAD

**Issue by pranayansaikia** [gotev/android-upload-service#515]
UploadServiceConfig.retryPolicy = RetryPolicyConfig(
    initialWaitTimeSeconds = 1,
    maxWaitTimeSeconds = 100,
    multiplier = 2,
    defaultMaxRetries = 3
)

how to achieve retry policy turn off as don't need retry

**Comment by gotev** [comment]
You can set all values to zero

**Comment by pranayansaikia** [comment]
ok
