### ISSUE TITLE
How to add retry option

### ISSUE THREAD

**Issue by ahmedsalemelzeiny** [gotev/android-upload-service#516]
**What do you want to achieve?**
I want to add retry option so when the uploading failed the user can click retry without adding max retries 
**What have you tried to do?**
I didn't find any options if I can add extra actions

**Which Upload Service Version are you using?**
 4.3.0

**Comment by gotev** [comment]
You can do that with a custom notification action. Check the wiki and the existing action code to get a starter.

**Comment by ahmedsalemelzeiny** [comment]
@gotev Thank you for your feedback, there is any way to retry current uploading or should add my pending intent to start the upload again ?

**Comment by gotev** [comment]
Yes there's a way, by setting the Retry Policy, which is going to be applied without any user intervention. If for example you set 3 retries, the user will be notified of failure only when all the 3 attempts have been made without success.

**Comment by ahmedsalemelzeiny** [comment]
Great, I already tried it I mean if I added custom action after error called retry and when the user click on it, So there is any ready intent to call like 
`fun Context.getCancelUploadIntent(uploadId: String) =
    getNotificationActionIntent(uploadId, cancelUploadAction)
`

So when I added my action and user clicked on it then this intent will work then ? or should implement new pending intent and start uploading again in this case ?

**Comment by gotev** [comment]
When you use the retry policy, upload service handles the retries transparently for you, throwing an error only once after all the attempts have failed. You can see this by checking the library debug logs. Your error handler will be called only once, after all the attempts have failed, giving you the last error. So, if you want to provide your users a retry option, it means adding a custom Pending Intent and handling it on your own, creating a new upload with the same parameters.
