### ISSUE TITLE
Not able to upload files 

### ISSUE THREAD

**Issue by chandmohd** [gotev/android-upload-service#518]
ERROR:  **Server response: code 400, body Error parsing Content Disposition**

Hi I'm trying to upload file using *Android-upload-service* but geetting error

here is what i have tried 

```
MultipartUploadRequest(
            baseActivityContext, "https://ptsv2.com/t/mzopj-1598531358/post")
            .setMethod("POST")
            .addFileToUpload(path,Gson().toJson(param))
            .startUpload()
```

**Comment by gotev** [comment]
You're using a JSON as a Parameter Name. That's not protocol compliant. Use something like `MyParam` or `MyParam1`.

**Comment by chandmohd** [comment]
But I want to send multiple paramters along with path. How can i do that?

**Comment by gotev** [comment]
Let's say you want to send a file called `myfile.txt`. You have to give it a parameter name for the backend to be able to receive it. For example: `MyFile`.

Then, you want to add the following parameters:
```
user = "myself"
region = "europe"
```

It's done like this:

```kotlin
MultipartUploadRequest(context, serverUrl)
  .addFileToUpload(filePath, "MyFile")
  .addParameter("user", "myself")
  .addParameter("region", "europe")
```

**Comment by chandmohd** [comment]
Thank, This resolve my issue

**Comment by gotev** [comment]
You're welcome!
