### ISSUE TITLE
Mime type is application/octet-stream when sending video/mp4

### ISSUE THREAD

**Issue by ahmedsalemelzeiny** [gotev/android-upload-service#519]
When trying to upload video to the server using version `4.4.0`, the mime type of the video received in backend side as `application/octet-stream` but the file information was resolved as video/mp4 also I added the content type as the following 

`            .addFileToUpload(
                filePath = filePath,
                parameterName = "intro",
                contentType = "video/mp4"
            )`

and the same issue still exist.

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: [4.4.0]
- Android version and API version: [Android 9]

**Comment by ahmedsalemelzeiny** [comment]
@gotev Can you help me please on this?

**Comment by gotev** [comment]
@ahmedsalemelzeiny I understand you may be in a hurry, but pushing to get a response on a community project is not a best practice 😉 

Made a test with a PDF file using Upload Service's Demo Server. You can find it in the examples directory of the repo.

### Uploading the file with content type auto detection
Relevant code

```kotlin
.addFileToUpload(filePath = filePath, parameterName = "MyFile")
```

Log:
```
HTTP/Multipart Upload Request from: ::ffff:192.168.1.132

Received headers
----------------
connection: close
user-agent: AndroidUploadService/4.4.0
content-type: multipart/form-data; boundary=-------UploadService4.4.0-60126767499
content-length: 1983720
host: 192.168.1.132:3000
accept-encoding: gzip

Started file upload
  parameter name: MyFile
  file name: UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf
  mime type: application/pdf
Completed file upload
  parameter name: MyFile
  file name: UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf
  mime type: application/pdf
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf
```
Backend received mime type is `application/pdf`.

### Uploading the file with custom mime type
Relevant code

```kotlin
.addFileToUpload(filePath = filePath, parameterName = "MyFile", contentType = "video/mp4")
```

Log:
```
HTTP/Multipart Upload Request from: ::ffff:192.168.1.132

Received headers
----------------
connection: close
user-agent: AndroidUploadService/4.4.0
content-type: multipart/form-data; boundary=-------UploadService4.4.0-180419254935
content-length: 1983716
host: 192.168.1.132:3000
accept-encoding: gzip

Started file upload
  parameter name: MyFile
  file name: UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf
  mime type: video/mp4
Completed file upload
  parameter name: MyFile
  file name: UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf
  mime type: video/mp4
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf
```
Backend received mime type is `video/mp4`

So, I don't see any evidence of library bugs here. I suggest you to dump the traffic which is going out from your app with either wireshark, tcpdump or Charles. Don't look at what the backend is receiving. Many things happen on the wire between your app's output and your backend's input.

By looking at the dump, you should be in one of the following cases:
- The app is sending the correct mime type -> then it's a backend problem
- The app is still sending octet stream -> double check your upload code

If you are in the second case and you can't find the problem, download the repo and try the demo app. You can force a custom mime type by modifying MultipartUploadActivity.java at line 64, with this:

```java
request.addFileToUpload(item.getSubtitle(), item.getTitle(), null, "video/mp4");
```

Then launch the demo app on your device and perform a multipart upload. You should see the correct mime type in the dump.

**Comment by gotev** [comment]
Closing this for now. Reopen it if you have replicable evidence of a library bug.
