### ISSUE TITLE
Want to set customized notification param in Multipart Request.

### ISSUE THREAD

**Issue by LLSAndroid** [gotev/android-upload-service#520]
Hello Alex,

I am using java and want to set a custom notification config.

Currently using the 4.4.0 version of your library. and also my min SDK version is 21

MultipartUploadRequest request = new MultipartUploadRequest(MainActivity.this, UPLOAD_URL)
                    .setMethod("POST")
                    .addParameter("name", etMain.getText().toString())
                    .addFileToUpload(filePath, "file_path")
                    .addFileToUpload(imagePath, "image_path")
                    .setNotificationConfig((context, uploadId)->getNotificationConfig(uploadId, R.string.app_name))
                    .setMaxRetries(2);
request.startUpload();

here is my code but it gives me an error while I'm passing uploadId as a parameter. Error is required String, Found lambda parameter. If I pass UUID.randomUUID().toString() instead of uploaded. Then Error looks like this.

Function2<? super Context, ? super String, UploadNotificationConfig> is not a functional interface

public UploadNotificationConfig getNotificationConfig(final String uploadId, int title) {
        PendingIntent clickIntent = PendingIntent.getActivity(
                this, 1, new Intent(this, SecondActivity.class), PendingIntent.FLAG_UPDATE_CURRENT);

        final boolean autoClear = false;
        final Bitmap largeIcon = null;
        final boolean clearOnAction = true;
        final boolean ringToneEnabled = true;
        final ArrayList<UploadNotificationAction> noActions = new ArrayList<>(1);

        final UploadNotificationAction cancelAction = new UploadNotificationAction(
                android.R.drawable.ic_menu_close_clear_cancel,
                "Cancel Upload",
                ContextExtensionsKt.getCancelUploadIntent(this, uploadId)
        );

        final ArrayList<UploadNotificationAction> progressActions = new ArrayList<>(1);
        progressActions.add(cancelAction);

        UploadNotificationStatusConfig progress = new UploadNotificationStatusConfig(
                getString(title),
                "Uploading",
                android.R.drawable.ic_menu_upload,
                Color.BLUE,
                largeIcon,
                clickIntent,
                progressActions,
                clearOnAction,
                autoClear
        );

        UploadNotificationStatusConfig success = new UploadNotificationStatusConfig(
                getString(title),
                "Upload Success",
                android.R.drawable.ic_menu_upload,
                Color.GREEN,
                largeIcon,
                clickIntent,
                noActions,
                clearOnAction,
                autoClear
        );

        UploadNotificationStatusConfig error = new UploadNotificationStatusConfig(
                getString(title),
                "Upload Error",
                android.R.drawable.ic_menu_upload,
                Color.RED,
                largeIcon,
                clickIntent,
                noActions,
                clearOnAction,
                autoClear
        );

        UploadNotificationStatusConfig cancelled = new UploadNotificationStatusConfig(
                getString(title),
                "Upload Cancelled",
                android.R.drawable.ic_menu_close_clear_cancel,
                Color.YELLOW,
                largeIcon,
                clickIntent,
                noActions,
                clearOnAction
        );

        return new UploadNotificationConfig(App.notificationChannelID, ringToneEnabled, progress, success, error, cancelled);
    }

I've created this function in the same MainActivity.class and on Button click, I am calling the Multipart service function.

**Comment by gotev** [comment]
Hi! Your Java code is perfectly fine. Do you have this setting in your `build.gradle` `android` section?

```groovy
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by LLSAndroid** [comment]
yes, I've written this in my build.gradle

**Comment by gotev** [comment]
That same code you posted works fine in the library demo app which uses Java, so I don't see any evidence of a library bug here or something to be addressed on library side.

The following works and compiles successfully

```java
    private void test(String uploadURL, String parameterName, String filePath, String imagePath) throws IOException {
        MultipartUploadRequest request = new MultipartUploadRequest(this, uploadURL)
                .setMethod("POST")
                .addParameter("name", parameterName)
                .addFileToUpload(filePath, "file_path")
                .addFileToUpload(imagePath, "image_path")
                .setNotificationConfig((context, uploadId)->getNotificationConfig(uploadId, R.string.app_name))
                .setMaxRetries(2);
        request.startUpload();
    }

    protected UploadNotificationConfig getNotificationConfig(final String uploadId, @StringRes int title) {
        PendingIntent clickIntent = PendingIntent.getActivity(
                this, 1, new Intent(this, MainActivity.class), PendingIntent.FLAG_UPDATE_CURRENT);

        final boolean autoClear = false;
        final Bitmap largeIcon = null;
        final boolean clearOnAction = true;
        final boolean ringToneEnabled = true;
        final ArrayList<UploadNotificationAction> noActions = new ArrayList<>(1);

        final UploadNotificationAction cancelAction = new UploadNotificationAction(
                R.drawable.ic_cancelled,
                getString(R.string.cancel_upload),
                ContextExtensionsKt.getCancelUploadIntent(this, uploadId)
        );

        final ArrayList<UploadNotificationAction> progressActions = new ArrayList<>(1);
        progressActions.add(cancelAction);

        UploadNotificationStatusConfig progress = new UploadNotificationStatusConfig(
                getString(title),
                getString(R.string.uploading),
                R.drawable.ic_upload,
                Color.BLUE,
                largeIcon,
                clickIntent,
                progressActions,
                clearOnAction,
                autoClear
        );

        UploadNotificationStatusConfig success = new UploadNotificationStatusConfig(
                getString(title),
                getString(R.string.upload_success),
                R.drawable.ic_upload_success,
                Color.GREEN,
                largeIcon,
                clickIntent,
                noActions,
                clearOnAction,
                autoClear
        );

        UploadNotificationStatusConfig error = new UploadNotificationStatusConfig(
                getString(title),
                getString(R.string.upload_error),
                R.drawable.ic_upload_error,
                Color.RED,
                largeIcon,
                clickIntent,
                noActions,
                clearOnAction,
                autoClear
        );

        UploadNotificationStatusConfig cancelled = new UploadNotificationStatusConfig(
                getString(title),
                getString(R.string.upload_cancelled),
                R.drawable.ic_cancelled,
                Color.YELLOW,
                largeIcon,
                clickIntent,
                noActions,
                clearOnAction
        );

        return new UploadNotificationConfig(App.CHANNEL, ringToneEnabled, progress, success, error, cancelled);
    }
```

You can try it yourself in [BaseActivity](https://github.com/gotev/android-upload-service/blob/master/examples/app/demoapp/src/main/java/net/gotev/uploadservicedemo/BaseActivity.java)

**Comment by azinmapar** [comment]
I have the same problem
