### ISSUE TITLE
OnError called all the time during MultipartUploadRequest version 3.4.2

### ISSUE THREAD

**Issue by KyluAce** [gotev/android-upload-service#521]
What did you expect?
Wanted to upload zip file into server

What happened instead?
Got error notification "File Upload Error during upload"

Version info
Android Upload Service version: 3.4.2
Android version and API version: Pie
MultipartUploadRequest inside AsyncTask java class

Hello, I recently noticed that I have problem with MultipartUploadRequest. It happen only on devices with android 8 and higher So I was thinking that's all about needed notification (logs confirms that).  So I created notification for devices with android 8+ but still upload doesn;t work. All the time when I'm trying to use this function OnError it's called.  There is no issue with server, because for example devices with android 6 send file without problem.

Code: 
```
 MultipartUploadRequest uploadRequest = new MultipartUploadRequest(context,SERVER_URL)
                    .setUtf8Charset()
                    .setMethod("POST")
                    .setMaxRetries(0)
                    .addFileToUpload(zipDir.getAbsolutePath()+"/"+emailAddress+".zip","file")
                    .setDelegate(new UploadStatusDelegate() {
                        @Override
                        public void onProgress(Context context, UploadInfo uploadInfo)
                        {
//                            giveMeThatData.returnProgress(uploadInfo.getProgressPercent());
                            Log.i("Progress", String.valueOf(uploadInfo.getProgressPercent()));
                            asyncResponse.returnProgress(uploadInfo.getProgressPercent());
                        }

                        @Override
                        public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {
                            Log.i("error","error");
                            asyncResponse.returnHttpStatus(50);
                        }
                        @Override
                        public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {

                            asyncResponse.returnHttpStatus(serverResponse.getHttpCode());
                            Log.i("SEND DONE", String.valueOf(serverResponse.getHttpCode()));
                        }

                        @Override
                        public void onCancelled(Context context, UploadInfo uploadInfo) {
                            Log.i("Progress","Cancelled");
                        }
                    })
                    .addParameter("email",emailAddress);


                    // For Android > 8, we need to set an Channel to the UploadNotificationConfig.
                    // So, here, we create the channel and set it to the MultipartUploadRequest
            if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                NotificationManager notificationManager = (NotificationManager) context.getSystemService(Service.NOTIFICATION_SERVICE);
                NotificationChannel channel = new NotificationChannel("Upload", "Upload service", NotificationManager.IMPORTANCE_DEFAULT);
                notificationManager.createNotificationChannel(channel);

                UploadNotificationConfig config = new UploadNotificationConfig();
                config.getCompleted().autoClear = true;

                uploadRequest.setNotificationConfig(config);

                uploadRequest.setNotificationConfig(config);
            } else {
                // If android < Oreo, just set a simple notification (or remove if you don't wanna any notification
                // Notification is mandatory for Android > 8
                uploadRequest.setNotificationConfig(new UploadNotificationConfig());
            }
            uploadRequest.startUpload();

        }
        catch (Exception e){
            Log.e("Sending",e.getMessage(),e);
            errorInSending=true;

        }
```
After called onError i get notification  "File Upload" "Error during upload".

**Comment by KyluAce** [comment]
First code line missing "MultipartUploadRequest uploadRequest = new MultipartUploadRequest(context,SERVER_URL)"

**Comment by KyluAce** [comment]
It looks like similar issue to this one: https://github.com/gotev/android-upload-service/issues/493 but i'm sure that server is fine.

**Comment by gotev** [comment]
Hi! That version is really old. I suggest you to upgrade to recent 4.x releases.

**Comment by KyluAce** [comment]
@gotev yea I know that there i a newest version but when I tryied do it it gives me a lot of errors, it's quite old app which targets  19-28 api, So you know can't update it easily

**Comment by gotev** [comment]
Ok then first of all get rid of the delegate and use a broadcast receiver: https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status

**Comment by KyluAce** [comment]
But how should I use it inside asynctask you think there the problem is in setDelegate ?

**Comment by gotev** [comment]
`AsyncTask` does not exist 😄 Seriously, if you still use it in your apps, get rid of it. Register the BroadcastReceiver inside your Activity or Fragment if you need contextual only indication of the upload. Otherwise, use a global broadcast receiver, which will be called regardless where you are in your app.

**Comment by KyluAce** [comment]
Anyway I added this broadcastReceiver but it doesn't help

**Comment by KyluAce** [comment]
It's quite strange that the problems occur only on devices android 8+.

**Comment by gotev** [comment]
Was in a hurry before, and noticed this only now:
```
NotificationManager notificationManager = (NotificationManager) context.getSystemService(Service.NOTIFICATION_SERVICE);
                NotificationChannel channel = new NotificationChannel("Upload", "Upload service", NotificationManager.IMPORTANCE_DEFAULT);
                notificationManager.createNotificationChannel(channel);
```

Do this only once when your App starts and before declaring the channel in Upload Service initialization, not at every upload.

Also, `MultipartUploadRequest inside AsyncTask java class` is wrong as an approach. The multipart upload request is only a builder for an intent which launches a service. You should launch it directly within your Activity of Fragment and then listen for events with the BroadcastReceiver inside that activity or fragment. There aren't any blocking calls in the library. The AsyncTask is causing you the upload issue.

Those approaches combined are causing you the issue. As a demonstration of this, you can checkout the demo project at the tag version you're using and try it on an Oreo or newer and it will work. Follow the examples in the demo app and in the wiki.

**Comment by KyluAce** [comment]
moving this lines to other place doesn't fix the problem either

**Comment by gotev** [comment]
Enable library debug log and post here what you're getting. I've also prepared a basic minimal example with Java on `3.5.2` (to which you can safely upgrade) here: https://github.com/gotev/android-upload-service/releases/download/3.5.2/BasicJavaExample.zip

**Comment by KyluAce** [comment]
When I tryied update to 3.5.2 verson i get errors "Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:22:5-79:19 to override" but adding this line cause more problems

**Comment by gotev** [comment]
That's caused by different AppCompat versions. 3.5.2 uses AppCompat 1.0.2.

It's worth to check those issues. However, let me know what kind of logs are you getting.

**Comment by KyluAce** [comment]
I updated to 3.5.2 i will try it now.

**Comment by KyluAce** [comment]
tell me the 3.5.2 version is the last one that can I use in Java ?

**Comment by gotev** [comment]
No, you can use all the versions up to the latest. The fact it's written in Kotlin does not affect Java.  It's 100% interoperable.
