### ISSUE TITLE
Upload service callbacks not working from a service.

### ISSUE THREAD

**Issue by cannizarro** [gotev/android-upload-service#528]
I want to attach callbacks to a `MultipartUploadRequest` by subscribing to it in my service. I make my service the `LifecycleOwner` and the service is not destroying itself as it is called by `startService(intent)`. But the callbacks aren't doing anything. I am new to this lifecycle aware components, please help.

Here is the code for my service:

`
public class CustomUploadService extends LifecycleService {
    
    private final String TAG = "UploadService";

    public CustomUploadService() {
    }

    @Override
    public void onCreate() {
        super.onCreate();
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        String path = intent.getStringExtra("path");
        sendToUpload(new File(path), startId);
        return super.onStartCommand(intent, flags, startId);
    }

    @Override
    public void onDestroy() {
        Log.d(TAG, "service destroyed");
        super.onDestroy();
    }

    private void sendToUpload(File file, int startID) {
        try {
            new MultipartUploadRequest(this, "https://ptsv2.com/t/1ypm6-1602799657/post/")
                    .setMethod("POST")
                    .addFileToUpload(file.getPath(), "myFile")
                    .subscribe(this, this, new RequestObserverDelegate() {
                        @Override
                        public void onProgress(@NotNull Context context, @NotNull UploadInfo uploadInfo) {
                            Log.d(TAG, "progress");
                        }
                        @Override
                        public void onSuccess(@NotNull Context context, @NotNull UploadInfo uploadInfo, @NotNull ServerResponse serverResponse) {
                            Log.d(TAG, "uploaded");
                            stopSelf(startID);
                        }
                        @Override
                        public void onError(@NotNull Context context, @NotNull UploadInfo uploadInfo, @NotNull Throwable throwable) {
                            Log.d(TAG, "service");
                            stopSelf(startID);
                        }
                        @Override
                        public void onCompleted(@NotNull Context context, @NotNull UploadInfo uploadInfo) {
                            Log.d(TAG, "completed");
                            stopSelf(startID);
                        }
                        @Override
                        public void onCompletedWhileNotObserving() {
                            stopSelf(startID);
                        }
                    });
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}

`

Here is the manifest declaration of my service:

`
<service
            android:name=".CustomUploadService"
            android:enabled="true"
            android:exported="true" />
`

I am using uploadServiceVersion = "4.4.0" and running on an Android 10 device.

Should I go with the `GlobalUploadObserver` approach? As I have seen this problem in previously closed issues here only.

**Comment by josephmangmang** [comment]
same https://github.com/gotev/android-upload-service/issues/592#issue-916953878
