### ISSUE TITLE
Want to get progress from notification?

### ISSUE THREAD

**Issue by LLSAndroid** [gotev/android-upload-service#530]
How to get progress from uploading document when we reopen/restart app? In other words when i start upload task in background i want to reflect notification progress in my recyclerview item.

**Comment by gotev** [comment]
So, you perform an upload request while your app is in the background, and you want to display progress also when the user comes back to your UI.

One possible way is to save your `uploadID` somewhere when you launch the upload in the background and then [use a RequestObserver like described here](https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-specific-upload-requests) and comparing the uploadID with the one you saved. In the delegate you will receive only the events coming from that upload request.

**Comment by LLSAndroid** [comment]
Worked perfectly thanks.
