### ISSUE TITLE
Require function for passing other data types in multipart request.

### ISSUE THREAD

**Issue by UmangMadani118** [gotev/android-upload-service#531]
This is great library for background upload service.

If possible then add function which allows other data types.

addParameter() only accept string key and value.

In my Scenario i want to send boolean parameter in request. so if possible then add function which can accept these kind of data types.

**Comment by gotev** [comment]
That's already possible. Just [.toString()](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/to-string.html) your boolean input when invoking `addParameter` method. 

Actually, exposing only `String` key and value parameters is a design choice:
- Multipart parameter names are strings
- Multipart parameter values other than files are sent as UTF-8 strings

So if you need to pass other data types as values, you have full control over how they are transformed into strings, leaving the implementation details completely in your hands.
