### ISSUE TITLE
How to get lifecycleOwner for monitoring in WorkManager

### ISSUE THREAD

**Issue by arifaizin** [gotev/android-upload-service#533]
**What do you want to achieve?**
I want to this library inside WorkManager, it's running well, but i have trouble when i want to monitoring my upload, because it need lifecycleowner. How to get it?

**What have you tried to do?**
I've tried this but not work https://code.luasoftware.com/tutorials/android/android-implement-lifecycleowner-for-workmanager/

**Which Upload Service Version are you using?**
e.g. 4.4.0

**On which Android version?**
e.g. Android 10

**Comment by gotev** [comment]
Currently the library is not designed to work with WorkManager and I think supporting it it's the next natural step in its evolution: to get rid of the service architecture completely and rely solely on WorkManager, using the request builders to launch WorkManager jobs and invoke the Tasks inside WorkManager Jobs. Ideas, suggestions and PRs are very welcome.

Getting back to the possible things you can do with the current state of the art, start from the [Global request observer](https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-all-upload-requests)

It's a Broadcast Receiver with all the boilerplate needed to get notification statuses, so you can focus on what really matters in your use-case.

**Comment by arifaizin** [comment]
Okay.. nice to know if it support WorkManager, and i'll try using Global RequestObserver.. thanks for your reply..

**Comment by gotev** [comment]
@arifaizin you're welcome! Since you're already using WorkManager, it's useful to know your use cases and suggestions for improvement
