### ISSUE TITLE
Replace upload file title on the notification by the file name

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#535]
I'm using single notification for each uploading file in my app, but the following object of the getProgressUploadingNotificationStatusConfig() display the name hard coded

UploadNotificationStatusConfig(
        **title = title,**
        message = "${Placeholder.Progress}",
        iconResourceID = R.drawable.ic_file_upload,
        largeIcon = BitmapFactory.decodeResource(context.resources, R.mipmap.ic_launcher_round),
        actions = arrayListOf(
            UploadNotificationAction(
                icon = android.R.drawable.ic_menu_close_clear_cancel,
                title = context.getString(R.string.cancel),
                intent = context.getCancelUploadIntent(uploadId)
            )
        )
    )   

I'm using 
        .addFileToUpload(queryParams[0], parameterName = "attachment", fileName = queryParams[1]).setNotificationConfig(notificationConfigFactory)

with => 
var notificationConfigFactory: (context: Context, uploadId: String) -> UploadNotificationConfig
    get() = { context, uploadId ->
        val title = context.getString(R.string.upload_file)
        UploadNotificationConfig(
            notificationChannelId = NotificationHelperUtils.UPLOADING_CHANNEL_ID,
            isRingToneEnabled = false,
            progress = getProgressUploadingNotificationStatusConfig(context, title, uploadId),
            success = getSuccessUploadingNotificationStatusConfig(context),
            error = getErrorUploadingNotificationStatusConfig(context),
            cancelled = getCancelledUploadingNotificationStatusConfig(context)
        )
    }
    set(value) = TODO()

so how can I replace the title by the file name?

Thanks you in advance.

**Comment by gotev** [comment]
[AbstractSingleNotificationHandler](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/observer/task/AbstractSingleNotificationHandler.kt) does not replace placeholders out of the box as it's a generic implementation you can use to create your fully customized UX and appearance, thus providing you only the primitives.

When in doubt, you can always look at the default implementation to see how certain things are implemented. In this case:
https://github.com/gotev/android-upload-service/blob/e6b75f46ad6f3e28cc61b3c208c9047720ffe4b9/uploadservice/src/main/java/net/gotev/uploadservice/observer/task/NotificationHandler.kt#L55-L67

**Comment by gotev** [comment]
@EngKhAboshama Added the following paragraph to the wiki which gives a primer on custom placeholders processors: https://github.com/gotev/android-upload-service/wiki/Configuration#placeholders-processor which is the way to accomplish what you're asking 😉

**Comment by EngKhAboshama** [comment]
@gotev 
Thanks for your reply. I'm sorry, you couldn't understand the main issue of my side. I want to customize each uploading notification using dynamic title, so 
var notificationConfigFactory: (context: Context, uploadId: String) -> UploadNotificationConfig
 
I want to replace the above line by the following line 
var notificationConfigFactory: (fileName: String, context: Context, uploadId: String) -> UploadNotificationConfig

so can I do this?

Thanks

**Comment by EngKhAboshama** [comment]
FYI, I'm using the following code to upload single file

    MultipartUploadRequest(context, "${RetrofitClient.API_HOST}/documents")
        .setMethod("POST")
        .addParameter("title", queryParams[1])
        .addFileToUpload(queryParams[0], parameterName = "attachment", fileName = queryParams[1]).setNotificationConfig(notificationConfigFactory)
        .subscribe(context, lifecycleOwner = lifecycleOwner, delegate = requestObserverDelegate)

**Comment by gotev** [comment]
> you couldn't understand the main issue of my side. I want to customize each uploading notification using dynamic title

I'm pretty sure I had. Let me make a demo of my previous answer with some code:

```kotlin
class CustomPlaceholderProcessor : DefaultPlaceholdersProcessor() {
    companion object {
        const val FILENAME_PLACEHOLDER = "[[FILENAME]]"
    }

    override fun processPlaceholders(message: String?, uploadInfo: UploadInfo): String {
        val processedMessage = super.processPlaceholders(message, uploadInfo)

        // if you have more than one file, change this accordingly to your needs
        val fileName = uploadInfo.files.firstOrNull()?.properties?.get("multipartRemoteFileName") ?: ""

        return processedMessage.replace(FILENAME_PLACEHOLDER, fileName)
    }
}
```
```kotlin
UploadServiceConfig.placeholdersProcessor = CustomPlaceholderProcessor()
```
```kotlin
var notificationConfigFactory: (context: Context, uploadId: String) -> UploadNotificationConfig
    get() = { context, uploadId ->
        val title = context.getString(R.string.upload_file) + CustomPlaceholdersProcessor.FILENAME_PLACEHOLDER
        UploadNotificationConfig(
            notificationChannelId = NotificationHelperUtils.UPLOADING_CHANNEL_ID,
            isRingToneEnabled = false,
            progress = getProgressUploadingNotificationStatusConfig(context, title, uploadId),
            success = getSuccessUploadingNotificationStatusConfig(context),
            error = getErrorUploadingNotificationStatusConfig(context),
            cancelled = getCancelledUploadingNotificationStatusConfig(context)
        )
    }
```
```kotlin
MultipartUploadRequest(context, "serverUrl")
    .setMethod("POST")
    .addFileToUpload("path to file", parameterName = "attachment", fileName = "large_test_file")
    .setNotificationConfig(notificationConfigFactory)
    .subscribe(context, lifecycleOwner = lifecycleOwner, delegate = requestObserverDelegate)
```
Final result:

<img width="307" alt="Schermata 2020-11-04 alle 13 53 33" src="https://user-images.githubusercontent.com/16792495/98114624-d06a5a00-1ea5-11eb-90ae-66599ffb0e5b.png">

**Comment by EngKhAboshama** [comment]
@gotev 
Thank you for your demo code. That's what I needed💯.

**Comment by EngKhAboshama** [comment]
@gotev I have another question about the notification. How can I set the priority of displaying it as PRIORITY_LOW using the above code?

Thanks you in advance.

**Comment by EngKhAboshama** [comment]
I created the following class:
class CustomNotificationHandler(private val service: UploadService) : UploadTaskObserver {
    private val notificationCreationTimeMillis by lazy { System.currentTimeMillis() }

    private val notificationManager by lazy {
        service.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    }

    private fun NotificationCompat.Builder.addActions(config: UploadNotificationStatusConfig): NotificationCompat.Builder {
        config.actions.forEach { addAction(it.asAction()) }
        return this
    }

    private fun NotificationCompat.Builder.setRingtoneCompat(isRingToneEnabled: Boolean): NotificationCompat.Builder {
        if (isRingToneEnabled && Build.VERSION.SDK_INT < 26) {
            setSound(
                RingtoneManager.getActualDefaultRingtoneUri(
                    service,
                    RingtoneManager.TYPE_NOTIFICATION
                )
            )
        }

        return this
    }

    private fun NotificationCompat.Builder.notify(uploadId: String, notificationId: Int) {
        build().apply {
            if (service.holdForegroundNotification(uploadId, this)) {
                notificationManager.cancel(notificationId)
            } else {
                notificationManager.notify(notificationId, this)
            }
        }
    }

    private fun NotificationCompat.Builder.setCommonParameters(
        statusConfig: UploadNotificationStatusConfig,
        info: UploadInfo
    ): NotificationCompat.Builder {
        return setGroup(namespace)
            .setContentTitle(placeholdersProcessor.processPlaceholders(statusConfig.title, info))
            .setContentText(placeholdersProcessor.processPlaceholders(statusConfig.message, info))
            .setContentIntent(statusConfig.getClickIntent(service))
            .setPriority(IMPORTANCE_LOW)
            .setSmallIcon(statusConfig.iconResourceID)
            .setLargeIcon(statusConfig.largeIcon)
            .setColor(statusConfig.iconColorResourceID)
            .addActions(statusConfig)
    }

    private fun ongoingNotification(
        notificationConfig: UploadNotificationConfig,
        info: UploadInfo
    ): NotificationCompat.Builder {
        return NotificationCompat.Builder(service, notificationConfig.notificationChannelId)
            .setWhen(notificationCreationTimeMillis)
            .setCommonParameters(notificationConfig.progress, info)
            .setOngoing(true)
    }

    private fun NotificationCompat.Builder.setDeleteIntentIfPresent(
        intent: PendingIntent?
    ): NotificationCompat.Builder {
        return intent?.let { setDeleteIntent(it) } ?: this
    }

    private fun updateNotification(
        notificationId: Int,
        info: UploadInfo,
        notificationChannelId: String,
        isRingToneEnabled: Boolean,
        statusConfig: UploadNotificationStatusConfig
    ) {
        notificationManager.cancel(notificationId)

        if (statusConfig.autoClear) return

        val notification = NotificationCompat.Builder(service, notificationChannelId)
            .setCommonParameters(statusConfig, info)
            .setProgress(0, 0, false)
            .setOngoing(false)
            .setDeleteIntentIfPresent(statusConfig.onDismissed)
            .setAutoCancel(statusConfig.clearOnAction)
            .setRingtoneCompat(isRingToneEnabled)
            .build()

        // this is needed because the main notification used to show progress is ongoing
        // and a new one has to be created to allow the user to dismiss it
        notificationManager.notify(notificationId + 1, notification)
    }

    override fun onStart(
        info: UploadInfo,
        notificationId: Int,
        notificationConfig: UploadNotificationConfig
    ) {
        notificationManager.validateNotificationChannel(notificationConfig.notificationChannelId)

        ongoingNotification(notificationConfig, info)
            .setProgress(100, 0, true)
            .notify(info.uploadId, notificationId)
    }

    override fun onProgress(
        info: UploadInfo,
        notificationId: Int,
        notificationConfig: UploadNotificationConfig
    ) {
        ongoingNotification(notificationConfig, info)
            .setProgress(100, info.progressPercent, false)
            .notify(info.uploadId, notificationId)
    }

    override fun onSuccess(
        info: UploadInfo,
        notificationId: Int,
        notificationConfig: UploadNotificationConfig,
        response: ServerResponse
    ) {
        updateNotification(
            notificationId,
            info,
            notificationConfig.notificationChannelId,
            notificationConfig.isRingToneEnabled,
            notificationConfig.success
        )
    }

    override fun onError(
        info: UploadInfo,
        notificationId: Int,
        notificationConfig: UploadNotificationConfig,
        exception: Throwable
    ) {
        val statusConfig = if (exception is UserCancelledUploadException) {
            notificationConfig.cancelled
        } else {
            notificationConfig.error
        }

        updateNotification(
            notificationId,
            info,
            notificationConfig.notificationChannelId,
            notificationConfig.isRingToneEnabled,
            statusConfig
        )
    }

    override fun onCompleted(
        info: UploadInfo,
        notificationId: Int,
        notificationConfig: UploadNotificationConfig
    ) {
    }
}

private fun NotificationManager.validateNotificationChannel(notificationChannelId: String) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        getNotificationChannel(notificationChannelId)
            ?: throw IllegalArgumentException("The provided notification channel ID $notificationChannelId does not exist! You must create it at app startup and before Upload Service!")
    }
}

So what can I do to use it?

**Comment by gotev** [comment]
Sorry this further question is completely OT and this is an issue tracker. That kind of stuff is standard Android knowledge, so I suggest you to check Android docs regarding notifications. I'm closing this issue as the initial request has been answered.

**Comment by EngKhAboshama** [comment]
I want to know if this custom class can I use it or not. I will create a ticket issue in another one. 

Thank you :)
