### ISSUE TITLE
Chinese devices: Upload doesn't complete in case app in background 

### ISSUE THREAD

**Issue by ahmedsalemelzeiny** [gotev/android-upload-service#542]
**Describe the bug**
In Chinese devices like OPPPO the upload task is working fine when the app in foreground but when the app goes to background the issue happens and the upload task is failed and the file is auto deleted.

**OS and Lib versions:**
- Android Upload Service version:  4.40 and 4.5.1
- Android version and API version:  Android 10

**Request code:**
```
    val uploadRequest = MultipartUploadRequest(
        context,
        serverUrl = this.url
    )

    uploadRequest.setBearerAuth(userToken)

    for (param in this.extraParams) {
        if (param.key.isNotEmpty() && param.value.isNotEmpty()) {
            uploadRequest.addParameter(param.key, param.value)
        }
    }
    for (header in this.extraHeaders) {
        uploadRequest.addHeader(header.key, header.value)
    }

    uploadRequest.addHeader("Device-Type", BuildConfig.DEVICE_TYPE)
    uploadRequest.setMethod("POST")
    uploadRequest.setMaxRetries(0)
    uploadRequest.addFileToUpload(
        filePath = this.videoPath,
        parameterName = this.uploadParameterName,
        contentType = "video/mp4"
    )
    uploadRequest.setAutoDeleteFilesAfterSuccessfulUpload(true)
    uploadRequest.startUpload()
```
**Where have you added the request code?**
-  Activity with applicationContext

**Comment by gotev** [comment]
there's nothing which can be done to prevent that at library level as it's a system override which does not adhere to stock android services lifecycle. Check with OPPO how to make your app run services when it's in the background. This could be useful: https://github.com/urbandroid-team/dont-kill-my-app/issues/51

Closing this as there's no action to take at development level.
