### ISSUE TITLE
Compressing an image before upload

### ISSUE THREAD

**Issue by Geowan** [gotev/android-upload-service#543]
Currently am uploading the file via

         @Override
           public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
                    Image image  = ImagePicker.getImage(data)
                    new MultipartUploadRequest(getContext(), AppDetailsHelpers.API_URL + "temp-file")
                            .addFileToUpload(image.getPath(), "image")
                            .addParameter("site_id",String.valueOf(site_details.getId()))
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(2)
                            .addHeader("Authorization", "Bearer "+tokenService.getToken(AppDetailsHelpers.ACTIVE_USER_PREFERENCE_KEYS.ACCESS_TOKEN))
                            .startUpload();

             }

The above works fine, but i would to compress the image using

                    Uri uri = Uri.fromFile((new File(image.getPath())));
                    Bitmap bitmap = MediaStore.Images.Media.getBitmap(getContext().getContentResolver(),uri);
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    bitmap.compress(Bitmap.CompressFormat.JPEG, 30, baos);

Is there a way to upload the bitmap compressed using this service.
I have tried using it via

                  .addFileToUpload(bitmap, "image") //this doesnt work

I understand the upload requires a file path, but is there a way to compress the file before uploading?

**Comment by gotev** [comment]
Hi! Compressing features are beyond the scope of Upload Service. Right now if you want to do so you have to compress the file yourself, save it somewhere and use that path for the actual upload.

**Comment by gotev** [comment]
For example you could save the compressed file to your app cache dir, use that path and the Upload Service's automatic deletion feature of successfully uploaded files.
