### ISSUE TITLE
Unable to upload file from downloads folder

### ISSUE THREAD

**Issue by LLSAndroid** [gotev/android-upload-service#545]
We are using android 11 (API 30) and the latest version of your service 4.5.1 still unable to upload a pdf file that is located in the Downloads folder without giving MANAGE_EXTERNAL_STORAGE permission in the manifest file.

**Comment by gotev** [comment]
That's correct. 

WRITE_EXTERNAL_STORAGE does not affect Android 11 files permission. It works on Android < 11, before the privacy enforcement was added.

For privacy protection reasons, the library does not explicitly add the MANAGE_EXTERNAL_STORAGE in the manifest.

Some apps may be fine with the scoped storage access, while others may require full access. It depends on the specific use case and Upload Service must not limit apps with strict privacy requirements.
 https://developer.android.com/training/data-storage/manage-all-files
