### ISSUE TITLE
Gradle 6.5 Update?

### ISSUE THREAD

**Issue by Borna-f** [gotev/android-upload-service#546]
Hi Again,
I tried to make a new push to my PR but the build fails saying gradle is old. I updated the gradle but then everything stopped working with a lot of errors :(

Can you please update the gradle to 6.5 and fix any issues you encounter while building the project?

Thanks

**Comment by gotev** [comment]
Problems are in AGP 4.1.1. Google introduced some breaking changes without previous notice. Fixed them. You can find exhaustive explanations by following the links I added in this commit: https://github.com/gotev/android-upload-service/commit/2f179c3fc0aedcbeeda84b69e8246f12bbade1b1. @Borna-f waiting for your feedback on #541 😉
