### ISSUE TITLE
How to get the response of the upload on calling `onCompletedWhileNotObserving`

### ISSUE THREAD

**Issue by minamak91** [gotev/android-upload-service#550]
First of all, I want to say a big thanks for the great effort in this library and the very good support.

**What do you want to achieve?**
Show that the upload is succeeded or not after locking the screen and opening it again. 

**What have you tried to do?**
I tried to use this callback `onCompletedWhileNotObserving` but I need to get the response of the server to do some additional logic.

**Which Upload Service Version are you using?**
4.4.2

**On which Android version?**
Android 10

When the app is in the foreground, I can easily get the response from `onSuccess` callback but if the app is in the background and the upload is finished, this callback is called `onCompletedWhileNotObserving` and I need to get the response, how should I get it then?

**Comment by minamak91** [comment]
<!--
First of all, I want to say a big thanks for the great effort in this library and the very good support.

**What do you want to achieve?**
Show that the upload is succeeded or not after locking the screen and opening it again. 

**What have you tried to do?**
I tried to use this callback `onCompletedWhileNotObserving` but I need to get the response of the server to do some additional logic.

**Which Upload Service Version are you using?**
4.4.2

**On which Android version?**
Android 10

When the app is in the foreground, I can easily get the response from `onSuccess` callback but if the app is in the background and the upload is finished, this callback is called `onCompletedWhileNotObserving` and I need to get the response, how should I get it then?

**Comment by gotev** [comment]
@minamak91 I suggest you to upgrade to latest 4.5.1. This is the case for [GlobalRequestObserver](https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#the-requestobserver) which can be tied to your app lifecycle instead of an Activity or Fragment.
