### ISSUE TITLE
Start upload files display TransactionTooLargeException

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#554]
Please can you give me information about how can I upload large files?

Caused by java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 10516560 bytes
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1692)
       at android.app.ContextImpl.startForegroundService(ContextImpl.java:1638)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:688)
       at net.gotev.uploadservice.extensions.ContextExtensionsKt.startNewUpload(ContextExtensions.kt:31)
       at net.gotev.uploadservice.UploadRequest.startUpload(UploadRequest.kt:54)
       at net.gotev.uploadservice.observer.request.RequestObserver.subscribe(RequestObserver.kt:52)
       at net.gotev.uploadservice.UploadRequest.subscribe(UploadRequest.kt:82)

**Comment by gotev** [comment]
Plase can you post the code which generates this request?

**Comment by EngKhAboshama** [comment]
I couldn't give you the request because It's a live crash on firebase. I checked the steps and I found that this happened when the user want to upload large files data, so does this question related to this issue 
https://github.com/gotev/android-upload-service/issues/342
?

**Comment by gotev** [comment]
Take a look at https://github.com/gotev/android-upload-service/wiki/Troubleshooting-Procedure#androidostransactiontoolargeexception-when-server-returns-a-large-response-after-upload

**Comment by gotev** [comment]
> I couldn't give you the request because It's a live crash on firebase

But you have written the code which triggers that exception. The library has not any problem sending big files (recently I made a test with 2.2 GB file: https://github.com/gotev/android-upload-service/issues/517#issuecomment-711166476), so check how you are constructing the upload request. Bear in mind request parameters should not have big strings as values.

**Comment by EngKhAboshama** [comment]
I checked it, but the file is small size not a big one.
I checked the firebase crash and found that the "startForegroundService(intent)" causes exception inside lib class. 
fun Context.startNewUpload(taskClass: Class<out UploadTask>, params: UploadTaskParameters): String {
    val intent = Intent(this, UploadService::class.java).apply {
        action = UploadServiceConfig.uploadAction
        putExtra(taskClassKey, taskClass.name)
        putExtra(taskParametersKey, params)
    }

    if (Build.VERSION.SDK_INT >= 26) {
        startForegroundService(intent)
    } else {
        startService(intent)
    }

    return params.id
}

**Comment by EngKhAboshama** [comment]
Please I don't handle this exception. This exception inside the lib in the code above "startForegroundService(intent)"

**Comment by gotev** [comment]
@EngKhAboshama of course, because that's the point where the request gets validated, but the problem resides surely in how you are building the `MultipartUploadRequest` or `BinaryUploadRequest`.

**Comment by EngKhAboshama** [comment]
@gotev My code is 

MultipartUploadRequest(context, "${RetrofitClient.API_HOST}/documents")
        .setMethod("POST")
        .addParameter("subject_id", queryParams[2])
        .addParameter("available_to_id", queryParams[3])
        .addParameter("title", queryParams[1])
        .addParameter("available_from", queryParams[5])
        .addFileToUpload(
            queryParams[0],
            parameterName = "attachment",
            fileName = queryParams[1]
        ).setNotificationConfig(notificationConfigFactory)
        .subscribe(context, lifecycleOwner = lifecycleOwner, delegate = requestObserverDelegate)

So, what is the problem of my code?

**Comment by gotev** [comment]
Check `queryParams` values length and also `notificationConfigFactory`. More specifically the icons set for the upload. Total size reported by Android in the exception is around 10MB:
```
Caused by java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 10516560 bytes
```
so it means the total size of the parameters exceeds the maximum allowed by the system. In this case the file size does not count as files are referenced only by path when building the request.

**Comment by gotev** [comment]
Please also post Upload Service version used and please follow the issue template given next time, thanks 😉

**Comment by EngKhAboshama** [comment]
@gotev Thank you very much. I found that the icon of the notification bitmap is a large one. I have to use the options parameter in the BitmapFactory.decodeResource() to decrease the size of the bitmap.

Sure, I will use it 👍

**Comment by EngKhAboshama** [comment]
@gotev If I want to pass a bitmap with the lib, so can you provide me steps to do this?

**Comment by gotev** [comment]
Save it to a temp file and then use its path

**Comment by EngKhAboshama** [comment]
I'm using UploadNotificationStatusConfig class which inside the package package "net.gotev.uploadservice.data", so I have to customize the "NotificationHandler" class to use this way, isn't it?

**Comment by gotev** [comment]
I thought `I want to pass a bitmap with the lib` meant uploading it to the server as a file. Then I haven't understood what do you mean.

**Comment by EngKhAboshama** [comment]
Sorry for my last comment. If you check the following function 
`fun successConfig(context: Context): UploadNotificationStatusConfig {
    return UploadNotificationStatusConfig(
        title = context.getString(R.string.file_uploaded),
        message = context.getString(R.string.failed_upload),
        iconResourceID = R.drawable.ic_file_upload,
    )
}`
so, I want to add the following line 
`        largeIcon = BitmapFactory.decodeResource(context.resources, R.mipmap.ic_launcher_round)
`
,but the largeIcon is too large about 12MB, so You advise me to save the path of the bitmap. My question is how can I save the path? Shall I customize the  "UploadNotificationStatusConfig" class to do this? or what?

**Comment by gotev** [comment]
Ok, so in that case the only advice I can give is to shrink your original icon resource using photoshop or similar program. It's not good to have such big assets in your app. 

Closing this as it's not a library bug.
