### ISSUE TITLE
Uploading files with fake progress in the beginning of the process 

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#555]
**Describe the bug**
After integrate the OkHttpStack from the following link https://github.com/gotev/android-upload-service/wiki/Configuration#okhttpstack
with the GlobalUploadObserver class, onProgress function called by fake percentage 0, then 100, then 0, then 100, then valid percentage such as 5%, 9%, ... 

**To Reproduce**
1. Open android screen
2. Start uploading function
3. See the logcat to see the error

**Expected behavior**
The progress starts from 0 to 100 with sequential steps

**Screenshots**
I/UploadService: UploadTask - (uploadId: a10942c7-0ef1-4897-a01d-1d81a1b3f152) - uploaded 0%, 101 of 3980819 bytes
 I/UploadService: UploadTask - (uploadId: a10942c7-0ef1-4897-a01d-1d81a1b3f152) - uploaded 100%, 3980819 of 3980819 bytes
 I/UploadService: UploadTask - (uploadId: a10942c7-0ef1-4897-a01d-1d81a1b3f152) - uploaded 1%, 69894 of 3980819 bytes

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: [e.g. 4.5.1]
- Android version and API version: [e.g. Android 8.1 APi 27]
- HTTP stack: [OkHttpStack version 4.5.1]

**Request code:**
```kotlin
fun uploadStudentHomework(
    context: Context,
    params: Map<String, String>,
    homework: Homework
) {
    val url = "${RetrofitClient.API_HOST}/subject_homeworks/${homework.id}/submit"
    MultipartUploadRequest(context, url).apply {
        setMethod("POST")
        addHeader(ACCESS_TOKEN, params[ACCESS_TOKEN] ?: error(""))
        addHeader(UID, params[UID] ?: error(""))
        addHeader(CLIENT, params[CLIENT] ?: error(""))
        addParameter(STUDENT_NOTE, homework.studentComment.comment)
        homework.studentAttachmentList?.filter { it.uri.toString() != "null" }?.let {
            for (value in it) {
                addFileToUpload(value.uri.toString(), parameterName = ATTACHMENTS, fileName = value.attachmentName)
            }
        }
        setMaxRetries(0)
        setNotificationConfig(getNotificationConfigFactory(false))
        startUpload()
    }
}
// in the Application class
UploadServiceConfig.initialize(
    context = this,
    defaultNotificationChannel = NotificationHelperUtils.UPLOADING_CHANNEL_ID,
    debug = BuildConfig.DEBUG
)
val client = getOkHttpClient(this)
UploadServiceConfig.httpStack = OkHttpStack(client)
UploadServiceConfig.placeholdersProcessor = CustomPlaceholdersProcessor(this)
GlobalRequestObserver(this, GlobalUploadObserver(this))

```
**Where have you added the request code?**
- [ ] Activity
- [ ] Service
- [yes] Other class. It is a normal class for uploading files in all app as static one

**Debug Log**:
```
// your debug log
```

**Other info**:

**Comment by gotev** [comment]
Thank you for the report.

This behavior may happen when the underlying Ok Http stack is receiving a TCP error from the server (it's due to unstable network connectivity) and the automatic retry mechanism of OkHttp retries the upload.

It's an edge case which needs to be replicated systematically in an unit test before going further.

**Comment by EngKhAboshama** [comment]
I will check this and I will contact you again for the result.
