### ISSUE TITLE
Upload files one by one using MultipartUploadRequest GlobalUploadObserver

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#559]
**Describe the bug**
I want to upload file list one by one using GlobalUploadObserver so that the user can run or close the app and the uploading is cont without any problem with the lifecycle of the android. 

**To Reproduce**

**Expected behavior**
I expected to find a function in the MultipartUploadRequest so that I can set this function boolean parameter to start uploading files one by one or parallel. 

**Screenshots**

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: [e.g. 4.4.1]

**Request code:**
**Where have you added the request code?**
- [ ] Activity
- [ ] Service
- [0 ] Other class (add additional info about it)

**Debug Log**:

**Other info**:

**Comment by gotev** [comment]
You can achieve serialized uploads by tuning the upload thread pool: https://github.com/gotev/android-upload-service/wiki/Configuration#number-of-parallel-uploads

**Comment by EngKhAboshama** [comment]
So, to upload files I will use the following code 
`
    MultipartUploadRequest(context, "${RetrofitClient.API_HOST}/documents").apply {
        setMethod("POST")
        fileList.filter { it.uri.toString() == "null" }.let {
            for (value in it) {
                addFileToUpload(value.uri.toString(), parameterName = ATTACHMENTS, fileName = value.subjectName)
            }
        }
        setNotificationConfig(notificationConfigFactory)
        startUpload()
`
isn't it?

**Comment by gotev** [comment]
In this way you are adding multiple files to a single upload request. To make multiple separated upload requests, one after the previous one (given you have already set https://github.com/gotev/android-upload-service/wiki/Configuration#number-of-parallel-uploads) based on your example:

```kotlin
fileList.filter { it.uri.toString() == "null" }.map {
  MultipartUploadRequest(context, "${RetrofitClient.API_HOST}/documents")
    .setMethod("POST")
    .addFileToUpload(it.uri.toString(), parameterName = ATTACHMENTS, fileName = it.subjectName)
    .setNotificationConfig(notificationConfigFactory)
    .startUpload()
}
```

**Comment by gotev** [comment]
Updated the wiki with some examples and further guidance: https://github.com/gotev/android-upload-service/wiki/4.x-Usage#multiple-uploads

this should answer to your initial request. However, to be more precise:

> So that the user can run or close the app and the uploading is continued without any problem with the android lifecycle

Uploads are going to continue while the app is in the background, but not when the users kills the app, as it's standard android behavior. More details here: https://github.com/gotev/android-upload-service/issues/100#issuecomment-188933450
