### ISSUE TITLE
Upload speed issue

### ISSUE THREAD

**Issue by wahib922** [gotev/android-upload-service#561]
@gotev as discussed in previous issue 

https://github.com/gotev/android-upload-service/issues/558#issuecomment-766397362

the increase buffer size has impact on the speed but its not matching ios like if ios is uploading 150mbps on lan then android app goes to 100mbps max on same connection can you let me know what buffer size should i set and what should be the okhttp stack settings in order to achieve the above.

**Comment by gotev** [comment]
What settings are you currently using to achieve that speed?

**Comment by wahib922** [comment]
UploadServiceConfig.setHttpStack(new OkHttpStack(getOkHttpClient()));
  UploadServiceConfig.setBufferSizeBytes(65536);
  
  this is the function used to get okhttpclient
  
      public static OkHttpClient getOkHttpClient() {
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        try {
            final TrustManager[] trustAllCerts = new TrustManager[]{
                    new X509TrustManager() {
                        @Override
                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) {
                        }

                        @Override
                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {
                        }

                        @Override
                        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                            return new java.security.cert.X509Certificate[]{};
                        }
                    }
            };
            builder.protocols(Collections.singletonList(Protocol.HTTP_1_1));
            final SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
			final SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();

            builder.followRedirects(true)
                    .followSslRedirects(true)
                    .retryOnConnectionFailure(true)
                    .connectTimeout(15, TimeUnit.SECONDS)
                    .writeTimeout(30, TimeUnit.SECONDS)
                    .readTimeout(30, TimeUnit.SECONDS)
                    .connectionPool(new ConnectionPool(Constants.CONNECTION_COUNT, 15, TimeUnit.SECONDS))
                    .addInterceptor(chain -> {
                        Request request = chain.request().newBuilder().build();
                        return chain.proceed(request);
                    })
                    .addNetworkInterceptor(chain -> {
                        Request.Builder request = chain.request().newBuilder();
                        return chain.proceed(request.build());
                    })
					.cache(null);
            builder.sslSocketFactory(sslSocketFactory, (X509TrustManager) trustAllCerts[0]);
            builder.hostnameVerifier(new HostnameVerifier() {
                @Override
                public boolean verify(String hostname, SSLSession session) {
                    return Utils.verifyHostname(hostname);
                }
            });
            return builder.build();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return builder.build();
    }

**Comment by gotev** [comment]
Setting the buffer size to 65K will impact the progress shown in the notifications. You will receive less updates.

After some further research, I found this: https://github.com/square/okhttp/issues/1078

Out of the box, OkHttp performs some internal buffering (check the linked issue). By reading through the linked thread, 16K buffer size seems reasonable, together with this custom socket factory (which I haven't tried yet): https://github.com/square/okhttp/issues/1078#issuecomment-205179152

In that thread is stated that calling `flush()` too often impacts speed. I have no clear evidence about that, yet. Some performance testing needs to be done. I would appreciate your help to do this.

Upload Service calls `flush()` every time the buffer gets written to the output (so every 4K with the default settings):

https://github.com/gotev/android-upload-service/blob/2ec525cd806782d4aa8cfccc3e49bf53f944d325/uploadservice/src/main/java/net/gotev/uploadservice/network/BodyWriter.kt#L47-L56

When using OkHttp:

https://github.com/gotev/android-upload-service/blob/2ec525cd806782d4aa8cfccc3e49bf53f944d325/uploadservice-okhttp/src/main/java/net/gotev/uploadservice/okhttp/OkHttpBodyWriter.kt#L11-L32
