### ISSUE TITLE
Fork lib with ERROR: No build artifacts found

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#562]
**Describe the bug**
I want to update the original logic of the lib in some classes from the fork. I fork the lib in local machine, but the error display to me in jitpack while I'm trying to get the snapshot. The following link is the log of the error 
https://jitpack.io/com/github/EngKhAboshama/android-upload-service/feature~add_http_method-3.5.2-final-before-kotlin-migration-g5fc5934-147/build.log

so, what is wrong?

**To Reproduce**
1. fork the lib
2. create a new branch from master
3. update come files in the lib 
4. push your code in github
5. open jitpack to get the branch using the snapshot

**Expected behavior**
jitpack generate the snapshot of my new branch 

**Screenshots**
![image](https://user-images.githubusercontent.com/67324107/105709212-14f21880-5f1e-11eb-932b-c42558e6f1c8.png)

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: [e.g. 4.4.1]

**Request code:**
**Where have you added the request code?**
- [ ] Activity
- [ ] Service
- [  ] Other class (add additional info about it)

**Debug Log**:
```
// your debug log
```

**Other info**:

**Comment by gotev** [comment]
Sorry, but I'm not using JitPack and this seems a JitPack specific issue. The build works just fine in local and on bintray. Closing this as there's no action I can take. If you find the issue and the resolution, you can open a PR.
