### ISSUE TITLE
How to get custom response in simple multipart request?

### ISSUE THREAD

**Issue by MuhammadIbrahimSE** [gotev/android-upload-service#563]
**What do you want to achieve?**
Describe us with all the details.

**What have you tried to do?**
Tell us which pages of the wiki you looked at and show us some code. What is blocking you from achieving the desired outcome?

**Which Upload Service Version are you using?**
e.g. 4.4.2

**On which Android version?**
e.g. Android 11

**Additional info**
Any information which you want to add to better explain your issue.

**Comment by gotev** [comment]
The issue template has not been filled with relevant info and the request is not clear. No action to take here.
