### ISSUE TITLE
Unable to get the custom respone from server like, any specific integer or status or additional data.

### ISSUE THREAD

**Issue by MuhammadIbrahimSE** [gotev/android-upload-service#564]
I am using 4.5.2 version.
I am uploading multipart file, but not able to see in wiki page, where and how to get custom json response.
I am currently looking at [https://github.com/gotev/android-upload-service/wiki/4.x-Usage].

**Comment by gotev** [comment]
Take a look here: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads

**Comment by gotev** [comment]
Does this answer your question? Also, if you searched for this info but you were unable to find it at first, what can be done in the docs to make it easily reachable? 

Thank you 😊

**Comment by MuhammadIbrahimSE** [comment]
yes, this is my answer. You can use some more specific phrase, like customize request, or you can make separate section for it. Thank you @gotev for the response.
