### ISSUE TITLE
Upload without notification

### ISSUE THREAD

**Issue by Brblol** [gotev/android-upload-service#565]
My App already has a notification in the foreground to keep it alive when the app is closed. Is it possible and if so how can I use this library without showing an additional foreground notification when uploading?

**Comment by gotev** [comment]
Hi! That's not possible as per Android requirements. Upload Services needs its own notification and you can't reuse other notifications or upload without a notification. It's just how the state of the art is.

**Comment by gajicm93** [comment]
@gotev is it possible not to show the "success" notification when the upload is finished? It's obviously not required by Android for background operation. Thanks.

**Comment by gotev** [comment]
@gajicm93 yes, just set autoClear = true on the statuses you don't want

https://github.com/gotev/android-upload-service/blob/7bb6ffb308a7d0a8387d1b7a8c0338a838ec2cf5/uploadservice/src/main/java/net/gotev/uploadservice/data/UploadNotificationStatusConfig.kt#L57-L62
