### ISSUE TITLE
Drop jCenter and publish only on Maven Central

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#568]
Given the recent announcement made by JFrog: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/?utm_source=mkto&utm_medium=email&utm_campaign=bintray-sunset&utm_content=global-02-2021

Deploy pipelines have to be modified to publish directly on Maven Central: https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/?s=09

Currently only the stablest versions of Upload Service are also published on Maven Central, therefore missing old versions will not be synced.

**Comment by gotev** [comment]
this is the next step needed to publish the library again after jcenter closed new submissions

**Comment by r0b0t3d** [comment]
Hi @gotev, could you release a new version in favor of this change?

**Comment by gotev** [comment]
What do you mean? Releases are on maven central for months now.
