### ISSUE TITLE
Server Response Code in onError Method

### ISSUE THREAD

**Issue by mukul-prabhakar** [gotev/android-upload-service#572]
Need to get server response code. In override onError method

I am trying to mke multipart requested. In some cases it give Unauthorised server code(401)
But using this current version of library it is only possible to get server code in onSucess method.

I would like to get server code in onError method. But I unable to do so. Please help me how can it be done.

Upload service library 4.4.2 - Android 10

**Comment by gotev** [comment]
Hi! I recommend you to update to 4.5.2 for stability and improvements.

Check the examples in the Wiki: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads

Server Response is already available also in onError

**Comment by mukul-prabhakar** [comment]
Thanks for your support it was really helpful.

**Comment by mukul-prabhakar** [comment]
> Hi! I recommend you to update to 4.5.2 for stability and improvements.
> 
> Check the examples in the Wiki: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads
> 
> Server Response is already available also in onError

Thanks for your support it was really helpful.

**Comment by yozeinc** [comment]
serverResponse is not available in the onError. Only throwable.

**Comment by gotev** [comment]
@yozeinc check the wiki: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-a-single-upload-request
