### ISSUE TITLE
Update view of fragment from GlobalRequestObserver

### ISSUE THREAD

**Issue by rahul4452** [gotev/android-upload-service#573]
First of all, thank you so much for this great library.It's my first time working with uploading so i'm little stuck.

**What do you want to achieve?**
I want to show UI update of upload on fragment from GlobalRequestObserver.

**What have you tried to do?**
I already try to use RequestObserver and subscribe but both stop observing when we close app and restart  the app.

**Which Upload Service Version are you using?**
4.5.2

**On which Android version?**
 Android 11

**Comment by gotev** [comment]
Hi! You should use the RequestObserver. Check the examples and explanations in the wiki 😉

**Comment by rahul4452** [comment]
@gotev thanks for reply. I read your Monitor upload and use Request observer.

I simply add Request Observer in onViewCreated.
` RequestObserver( requireContext(),viewLifecycleOwner,uploadDelegate,shouldAcceptEventsFrom = { uploadInfo ->
                uploadInfo.uploadId == uploadRequestId}) `

and create an object of Request Observer.

`

        object uploadDelegate : RequestObserverDelegate {
        override fun onCompleted(context: Context, uploadInfo: UploadInfo) {

        }

        override fun onCompletedWhileNotObserving() {

        }

        override fun onError(context: Context, uploadInfo: UploadInfo, exception: Throwable) {
            when (exception) {
                is UserCancelledUploadException -> {
                    e("RECEIVER Error, user cancelled upload: $uploadInfo")
                }

                is UploadError -> {
                    e("RECEIVER Error, upload error: ${exception.serverResponse}")
                }

                else -> {

                }
            }

        }

        override fun onProgress(context: Context, uploadInfo: UploadInfo) {

            e("RECEIVER Progress: $uploadInfo")

        }

        override fun onSuccess(
            context: Context,
            uploadInfo: UploadInfo,
            serverResponse: ServerResponse
        ) {
            e("RECEIVER Success: $serverResponse")

        }

    }


`

is this right way to do it.

**Comment by rahul4452** [comment]
@gotev Thanks for your reply and support it was really helpful. Now upload is working as i wanted. Thanks again

**Comment by gotev** [comment]
You're welcome! 😉
