### ISSUE TITLE
Can we use the library with ACTION_GET_CONTENT instead of ACTION_OPEN_DOCUMENT?

### ISSUE THREAD

**Issue by minamak3031** [gotev/android-upload-service#576]
**Describe the bug**
Currenty, as mentioned in the sample of the library, we only can use ACTION_OPEN_DOCUMENT to be able to upload files successfully, but unfortunately some file providers don't exist with ACTION_OPEN_DOCUMENT like the Gallery, google photos, ... These file providers only exist with ACTION_GET_CONTENT

**To Reproduce**
1. Use ACTION_GET_CONTENT to open file picker
2. Select a file and upload it

**Actual behavior**
Permission denial error appeared in some real devices.

**Expected behavior**
File is uploaded successfully.

**Comment by gotev** [comment]
That's only an example. You can also directly invoke other third party file browsers or make your own 😉
