### ISSUE TITLE
OnProgress notification is not dismissed when upload successfully finished

### ISSUE THREAD

**Issue by WarrenFaith** [gotev/android-upload-service#577]
**Describe the bug**
When I upload an image via multipart, the ongoing notification stays when the upload was finished successfully. The "cancel" action also does nothing and the notification can't be swiped to dismiss.

**To Reproduce**
1. Basic implementation:
```kotlin
// in the Application class
val notificationChannelId = "UPLOADING"
if (Build.VERSION.SDK_INT >= 26) {
    val channel = NotificationChannel(notificationChannelId, "Picture Upload", NotificationManager.IMPORTANCE_LOW)
    val manager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    manager.createNotificationChannel(channel)
}
UploadServiceConfig.initialize(this, notificationChannelId, BuildConfig.DEBUG)
UploadServiceConfig.httpStack = OkHttpStack()
```
2. Trigger upload (see code below)

**Expected behavior**
I expect the ongoing notification to dismiss automatically when an upload finishes (regardless of error or success) and be replaced by a notification stating the result.

**Screenshots**
![upload_service_notification](https://user-images.githubusercontent.com/152264/112621560-31310980-8e2a-11eb-83fd-e155f6339906.png)

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: 4.5.2
- Android version and API version: Pixel 4 with Android 11, Redmi 9A with Android 10
- HTTP stack: OkHttpStack

**Request code:**
```kotlin
MultipartUploadRequest(requireContext(), "https://company.tld/media/upload")
    .setMethod("POST")
    .addParameter("category", "picture")
    .apply {
        incidentViewModel.incidentImages.value?.forEach { file ->
            addFileToUpload(file, parameterName = "files")
        }
    }
    .addHeader(
        "Authorization",
        "xxxxxxx"
    )
    .startUpload()
```

**Where have you added the request code?**
- [ ] Activity
- [ ] Service
- [x] Other class: Fragment (AndroidX)

**Debug Log**:
```
	11:45:30.290	UploadService		NotificationActionsObserver - (uploadId: N/A) - registered
	11:45:30.380	UploadService		UploadService - (uploadId: N/A) - Starting UploadService. Debug info: {
    "uploadServiceVersion": "4.5.2",
    "androidApiVersion": 29,
    "namespace": "tld.company",
    "deviceProcessors": 8,
    "idleTimeoutSeconds": 10,
    "bufferSizeBytes": 4096,
    "httpStack": "net.gotev.uploadservice.okhttp.OkHttpStack",
    "uploadProgressNotificationIntervalMillis": 333,
    "retryPolicy": {"initialWaitTimeSeconds": 1, "maxWaitTimeSeconds": 100, "multiplier": 2, "defaultMaxRetries": 3},
    "isForegroundService": true,
    "schemeHandlers": {"/": "net.gotev.uploadservice.schemehandlers.FileSchemeHandler", "content://": "net.gotev.uploadservice.schemehandlers.ContentResolverSchemeHandler"}
}
	11:45:30.415	UploadService		UploadService - (uploadId: N/A) - Successfully created new task with class: net.gotev.uploadservice.protocols.multipart.MultipartUploadTask
	11:45:30.443	UploadService		UploadService - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - now holds foreground notification
	11:45:30.449	UploadService		MultipartUploadTask - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - Starting upload task
	11:45:30.513	UploadService		OkHttpStackRequest - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - creating new OkHttp connection (uuid: 6b7acdd7-e726-4085-98e6-4ef8f3cbdd83)
	11:45:30.814	UploadService		UploadTask - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - uploaded 0%, 108 of 210142 bytes
	11:45:30.900	UploadService		UploadTask - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - uploaded 100%, 210142 of 210142 bytes
	11:45:31.252	UploadService		OkHttpStackRequest - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - closing OkHttp connection (uuid: 6b7acdd7-e726-4085-98e6-4ef8f3cbdd83)
	11:45:31.253	UploadService		MultipartUploadTask - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - Server response: code 201, body {"processedFiles":[{"originalName":"picture.jpg","publicUrl":"https://company.tld/picture/cf2f1e0d-ade5-4dfd-bdd0-90a81750b655.jpg"}]}
	11:45:31.253	UploadService		UploadTask - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - upload completed
	11:45:31.268	UploadService		UploadService - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - now un-holded foreground notification
	11:45:31.269	UploadService		UploadService - (uploadId: N/A) - All tasks completed, stopping foreground execution
	11:45:31.272	UploadService		UploadService - (uploadId: N/A) - Service will be shut down in 10s if no new tasks are received
	11:45:41.274	UploadService		UploadService - (uploadId: N/A) - Service is about to be stopped because idle timeout of 10s has been reached
	11:45:41.281	UploadService		NotificationActionsObserver - (uploadId: N/A) - unregistered
	11:45:41.282	UploadService		UploadService - (uploadId: N/A) - Stopping foreground execution
	11:45:41.285	UploadService		UploadService - (uploadId: N/A) - UploadService destroyed
```

**Comment by gotev** [comment]
Hi! Thank you for the detailed report 😉 

Looking at the screenshot, that specific case happens when the payload has been transfered to the server and the client is waiting for the response. It's a transitional period, after which the upload either completes successfully or fails and the notification gets updated. For how long it depends on the server and the connection.

> The "cancel" action also does nothing

While you are waiting for the server to respond after the transfer is completed, the task is waiting at this point in its thread:
https://github.com/gotev/android-upload-service/blob/4c5d44f3b5fdb3a67c8de41d584d2bb18916881a/uploadservice/src/main/java/net/gotev/uploadservice/HttpUploadTask.kt#L47

and the behaviour you observe is that you could not cancel the operation in this specific scenario.

Looking at the debug log I could however see only the first upload, which is all good

**Comment by WarrenFaith** [comment]
Thanks for the very fast response.
In the logs you can see the server responds with a 201
```
MultipartUploadTask - (uploadId: cd53c89d-6a01-43b9-895b-ad03dd046020) - Server response: code 201, body {"processedFiles":[{"originalName":"picture.jpg","publicUrl":"https://company.tld/picture/cf2f1e0d-ade5-4dfd-bdd0-90a81750b655.jpg"}]}
```

> I could however see only the first upload, which is all good

Which is also correct, there was just one triggered with one image.

***BUT***
While doing lunch I had a shower thought kind of realization: We are also creating a foreground service with a notification ourself and I realized this notification disappears as soon as I upload an image. A bit digging I found out that you are using the same "base id" for notifications as I did: 1234

```kotlin
private const val UPLOAD_NOTIFICATION_BASE_ID = 1234 // Something unique
```

So I changed my identifier for my foreground service notification and it worked! Therefore I close this issue and say again thank you for your fast response!

**Comment by gotev** [comment]
@WarrenFaith you're welcome!
