### ISSUE TITLE
Set NotificationID manually

### ISSUE THREAD

**Issue by tobias-r** [gotev/android-upload-service#585]
Hi, I love this API, thank you so much.

I do have one question, or request. Is it maybe possible to manually set the notificationID?

Reason is, that before and after the upload I need to do some processing. And I'd like to do those tasks in the same notification, just adjust the content of the notification. For this I'd need to get and set the notificationID.

Thank you for your consideration.

Tobias

**Comment by gotev** [comment]
Hi! Glad that you find the library useful! Actually what you are looking for is a custom notification handler: https://github.com/gotev/android-upload-service/wiki/Configuration#notification-handler

**Comment by tobias-r** [comment]
Yeah, I checked this already, but I can only find an abstract one without any features. I'd need exactly what it is. Can I simply extend the standard notification handler? Sorry, I am a bit confused here. Thanks for any tip.

**Comment by gotev** [comment]
For a starter, just copy and paste [NotificationHandler](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/observer/task/NotificationHandler.kt) and and adjust it for your needs. It's not open for subclassing on purpose.
