### ISSUE TITLE
Subscribing ends, when I open another activity

### ISSUE THREAD

**Issue by tobias-r** [gotev/android-upload-service#587]
Hi there,

sorry to bother you again, but these things all worked with your API. Since upgrading to v4 I am having a lot of problems.

My question:

Isn't the upload global? If so, why do I not get any callbacks when opening another activity while uploading? Is there a way of doing it or what am I doing wrong?

I simply subscribe to a request (java, not kotlin).

Thanks for your help! Can I do donations anywhere?

Tobias

**Comment by gotev** [comment]
Hi! I think you should check the wiki first before opening issues: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads and only if something isn't clear enough.

<img width="1254" alt="Schermata 2021-05-25 alle 01 24 13" src="https://user-images.githubusercontent.com/16792495/119418309-0105ca00-bcf8-11eb-8780-d33535de1242.png">
