### ISSUE TITLE
Removing a GlobalRequestObserver

### ISSUE THREAD

**Issue by tobias-r** [gotev/android-upload-service#588]
Hi there,

I couldn't find a way to remove a GlobalRequestObserver and I couldn't find any info in the help section.

Can you help or isn't it possible?

Thank you

Tobias

**Comment by gotev** [comment]
Hi! 😃

`GlobalRequestObserver` inherits from `BaseRequestObserver`, auto registering itself when you create it.

https://github.com/gotev/android-upload-service/blob/496230b76a4ffb0085bfb45a428dd44ca0bc782e/uploadservice/src/main/java/net/gotev/uploadservice/observer/request/GlobalRequestObserver.kt#L6-L14

You can always call both `register()` and `unregister()` on the instance based on your specific need.

https://github.com/gotev/android-upload-service/blob/496230b76a4ffb0085bfb45a428dd44ca0bc782e/uploadservice/src/main/java/net/gotev/uploadservice/observer/request/BaseRequestObserver.kt#L35-L41

How would you document it in the existing docs to be clearer for other users? 😉

**Comment by gotev** [comment]
Added this to https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads

> Both `RequestObserver` and `GlobalRequestObserver` auto registers themselves once created for convenience. `RequestObserver` takes care of automatically unregister itself once the lifecycle in which is created gets destroyed. `GlobalRequestObserver` does not auto unregister itself automatically, but you can call `unregister()` and then `register()` again on its instance based on your specific needs.

I'm open for suggestions and improvements 😃

**Comment by tobias-r** [comment]
Looks good, easy to use, good solution if you ask me. Thanks!
