### ISSUE TITLE
Repeating upload after successfully uploading

### ISSUE THREAD

**Issue by thedeveloper19** [gotev/android-upload-service#590]
Everything is fine now! Uploading successfully. But there is one problem. Its repeating upload task twice even sometime more than 4 or 5 time after successfully uploading.

uploadSuccessfull not calling, But file sucessfully uploaded and it start uploading automatically after a successfull task.

**Comment by gotev** [comment]
File a test case or a demo app which replicates this behavior 😉

**Comment by gotev** [comment]
Without more context, logs and a test to replicate this behavior systematically it's not possible to take any action here. Filling in all the required fields in the issue template helps.

Only known reasons for that kind of behavior are documented here:  https://github.com/gotev/android-upload-service/wiki/Troubleshooting-Procedure#sockettimeout-or-broken-pipe-while-uploading

But in those cases it's not a library bug.

Feel free to open a new issue if you find a systematic way to replicate the behavior with a demo app or test.
