### ISSUE TITLE
`onCompletedWhileNotObserving` is called beginning of the every upload request

### ISSUE THREAD

**Issue by sendtodilanka** [gotev/android-upload-service#591]
First of all, I want to say a big thanks for the great effort in this library and the very good support.

**What do you want to achieve?**
Change some UI elements of the UploadFragment if upload is succeeded or not when re-opening app from background.

**What have you tried to do?**
I have used `onCompletedWhileNotObserving` as describe in documentation. But the problem is `onCompletedWhileNotObserving` called beginning of the every upload request.

UploadFragment.kt

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

         requireContext().upload(uploadArgs.path, viewLifecycleOwner)

        binding.btnCancelUpload.setOnSingleClickListener {
            UploadService.stopAllUploads()
        }
    }

    fun Context.upload(
        path: String,
        lifecycleOwner: LifecycleOwner
    ) {
        MultipartUploadRequest(this, serverUrl = "https://abc.com/")
            .setMethod("POST")
            .addFileToUpload(filePath = path, parameterName = "file")
            .subscribe(this, lifecycleOwner, delegate = object : RequestObserverDelegate {

                override fun onProgress(context: Context, uploadInfo: UploadInfo) {
                    Timber.d("Upload -> onProgress")

                    val progress = uploadInfo.progressPercent
                    binding.txtTitle.text = "Uploading $progress%"
                    binding.progressbar.progress = progress
                }

                override fun onSuccess(
                    context: Context,
                    uploadInfo: UploadInfo,
                    serverResponse: ServerResponse
                ) {
                    Timber.d("Upload -> onSuccess")

                    if (serverResponse.isSuccessful) {
                        serverResponse.bodyString.stringToResponse().whatIfNotNull {
                            val direction = UploadFragmentDirections
                                .actionUploadFragmentToResultFragment(it.toFileModel())
                            findNavController().navigateSafe(direction)
                        }
                    }
                }

                override fun onError(
                    context: Context,
                    uploadInfo: UploadInfo,
                    exception: Throwable
                ) {
                    when (exception) {
                        is UserCancelledUploadException -> {
                            Timber.d("Upload -> Error, user cancelled upload: $uploadInfo")
                            findNavController().navigateUp()
                        }

                        is UploadError -> {
                            Timber.d("Upload -> Error: ${exception.serverResponse}")
                            context.toast("upload error: ${exception.serverResponse}")
                            val direction =
                                UploadFragmentDirections.actionUploadFragmentToErrorFragment(path)
                            findNavController().navigateSafe(direction)
                        }

                        else -> {
                            Timber.e(exception, "Upload -> Error: $uploadInfo")
                            context.toast("Error: $uploadInfo")
                            val direction =
                                UploadFragmentDirections.actionUploadFragmentToErrorFragment(path)
                            findNavController().navigateSafe(direction)
                        }
                    }
                }

                override fun onCompleted(context: Context, uploadInfo: UploadInfo) {
                    Timber.d("Upload -> onCompleted")
                }

                override fun onCompletedWhileNotObserving() {
                    Timber.d("Upload -> onCompletedWhileNotObserving")
                }
            })
    }

**Which Upload Service Version are you using?**
4.5.5

**On which Android version?**
Android 11

`onCompletedWhileNotObserving` is called beginning of the every upload request. You can see, onCompletedWhileNotObserving is called twice both beginning of the request and end of request in following logcat output. Please help me to solve this problem.

    2021-06-08 13:48:41.303 25268-25268/com.fileupload.abc.com D/UploadFragment$upload: Upload ->   onCompletedWhileNotObserving
	2021-06-08 13:48:42.163 25268-25268/com.fileupload.abc.com D/UploadFragment$upload: Upload -> onProgress
	2021-06-08 13:48:44.931 25268-25268/com.fileupload.abc.com D/UploadFragment$upload: Upload -> onProgress
	2021-06-08 13:51:32.481 25268-25268/com.fileupload.abc.com D/UploadFragment$upload: Upload ->   onCompletedWhileNotObserving

**Comment by gotev** [comment]
after some tests, this scenario cannot be replicated. Closing.
