### ISSUE TITLE
RequestObserverDelegate is not triggered.

### ISSUE THREAD

**Issue by josephmangmang** [gotev/android-upload-service#592]
**Describe the bug**
`RequestObserverDelegate` is not triggered. 

the `register() `is not called when initialize inside `LifecycleService` I need to manually call `register` and `unregister`  
```
RequestObserver.class

    /**
     * Register this upload receiver to listen for events.
     */
    @OnLifecycleEvent(Lifecycle.Event.ON_RESUME)
    override fun register() {
        super.register()

        subscribedUploadID?.let {
            if (!UploadService.taskList.contains(it)) {
                delegate.onCompletedWhileNotObserving()
            }
        }
    }
```

**To Reproduce**
1.  Create a class that extend `LifecycleService` and initialize `RequestObserver`()

**Expected behavior**
`RequestObserver` is register and `RequestObserverDelegate` callbacks is called.

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: [4.6.0]
- Android version and API version: [Android 11]
- HTTP stack: [HurlStack]

**Where have you added the request code?**
- [ ] Service

**Comment by gotev** [comment]
You're right and the docs are misleading in this case. 

LifecycleService does not have the resume event at all: https://android.googlesource.com/platform/frameworks/support/+/a9ac247af2afd4115c3eb6d16c05bc92737d6305/lifecycle/service/src/main/java/androidx/lifecycle/LifecycleService.java

So inside a service you should use GlobalRequestObserver.

**Comment by gotev** [comment]
Docs updated, thank you for this issue 😉
