### ISSUE TITLE
Ftp progress

### ISSUE THREAD

**Issue by SudoDios** [gotev/android-upload-service#594]
Hello developer.
Please add progress listener to FtpUploadRequest.
Thanks

**Comment by gotev** [comment]
it's already there: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads

**Comment by SudoDios** [comment]
How to disable notification ?

**Comment by SudoDios** [comment]
> it's already there: https://github.com/gotev/android-upload-service/tree/master/uploadservice-ftp

I did not understand how to use?

**Comment by gotev** [comment]
Check the wiki:
- lib configuration: https://github.com/gotev/android-upload-service/wiki/Configuration
- upload events monitoring: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads

if something's not clear, please describe all the relevant details, what you've tried and what you expect (the info already requested in the issue template).
