### ISSUE TITLE
Custom Name

### ISSUE THREAD

**Issue by SudoDios** [gotev/android-upload-service#595]
how to set custom name on upload file

**Comment by gotev** [comment]
Please follow the issue template when asking for help. Your request lacks all the details needed to help you.

**Comment by SudoDios** [comment]
When I want to upload a file, I do not want it to have the same name on the server. So I upload it with another name

**Comment by gotev** [comment]
The answer is in:
- MultipartUploadRequest addFileToUpload
- BinaryUploadRequest setFileToUpload
- FTPUploadRequest addFileToUpload

javadocs depending on the protocol you are using.

**Comment by SudoDios** [comment]
But I did not see anything about renaming in FTPUploadRequest addFileToUpload

**Comment by SudoDios** [comment]
I really apologize.
Sorry I took your time.
that was my fault.

**Comment by gotev** [comment]
https://github.com/gotev/android-upload-service/blob/a427d73b46ebb87ec1f22283a377b04d2ecd950d/uploadservice-ftp/src/main/java/net/gotev/uploadservice/ftp/FTPUploadRequest.kt#L47

https://github.com/gotev/android-upload-service/blob/a427d73b46ebb87ec1f22283a377b04d2ecd950d/uploadservice-ftp/src/main/java/net/gotev/uploadservice/ftp/FTPUploadRequest.kt#L60-L68
