### ISSUE TITLE
Reopen View

### ISSUE THREAD

**Issue by Tahaelhosseny** [gotev/android-upload-service#597]
First, I want to advance a big thanks to you for working on this awesome library which solves many of our problems.
Second I want to ask you some questions:
- if this library support auto-upload when the connection is out then returned.
-if I can reset the request listener after I close the fragment/activity and reopen it to show the progress and status.

**Comment by gotev** [comment]
Hi! Glad the library is useful!

Your questions already have answers in the wiki

Regarding the first question: https://github.com/gotev/android-upload-service/wiki/Advanced-topics

Regarding the second one:
https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads
