### ISSUE TITLE
Upload file without Content-Type set

### ISSUE THREAD

**Issue by Bodata** [gotev/android-upload-service#601]
Hi,

I am trying to get this to work with ruby-on-rails active-storage. (counting in days, not hours anymore)

The ruby server gives me an url to upload to gcs (google cloud services)
But the upload fails with a 403 error

<Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message>

So i found out what the problems seems to be....  
active-storage does not use a content-type to sign the upload to gcs.
BinaryUploadRequest adds this automaticly in BinaryUploadTask.
I wrote a local version of  the BinaryUploadRequest/BinarayUploadTask classes to disable adding content-type.
But it seems still to add content-type application/x-www-form-urlencoded somewhere.
I cannot find where this is added or how to prevent adding content-type in the request header.
If i could remove it before the header is send would also be ok.

Could anyone help me ?

Regards,
Peter

**Comment by gotev** [comment]
Hi,

I see a bunch of backend stuff independent from the library. Let's keep that aside.

Binary upload request allows you to define a `Content-Type`. If not defined it is inferred from the binary data:

https://github.com/gotev/android-upload-service/blob/3c707d4503e0f4677c86799a53d2e7254f7de28b/uploadservice/src/main/java/net/gotev/uploadservice/protocols/binary/BinaryUploadTask.kt#L18-L22

unless you are using a known format (e.g. jpeg, mp3, mp4, ...), when no specific type is inferred, `application/octet-stream` is used.

[RFC2046](http://www.rfc-editor.org/rfc/rfc2046.txt) says `octet-stream` subtype is used to indicate that a body contains arbitrary binary data, so if you want to be sure to skip automatic mimetype discovery, you'll be good by simply setting octent stream on the request. Sending requests without any Content-Type is somethong not standard and not advisable to do.

Take a look at the tests: https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/androidTest/java/net/gotev/uploadservice/BinaryUploadTests.kt#L28

**Comment by Bodata** [comment]
Hi,
It found the code segments you mentioned. Thanks!

But what you wrote made me wonder if the solution activestorage was offering is the correct one.

So i looked in the github and found there has been alot of changes, but they are not added to the stable versions i understand.

I managed today to install rails 7 alpha.... 

Now the whole concept has changed, but it is mutch simpler now.
I can use the "MultipartUploadRequest" and every thing is working ;-)

Still have to do alot of cleaning up, but the uploading works for now.

Thanks for you time and input.

Regards,
Peter

**Comment by gotev** [comment]
Great!
As all the stuff in IT, follow the standards and you'll be fine every time 😉
