### ISSUE TITLE
Question:  Are Group Notifications supported?

### ISSUE THREAD

**Issue by oevad** [gotev/android-upload-service#602]
Hi:  I tried reading through the wiki documentation for Notifications and the example app, and I am not sure if creating Group Notifications (https://developer.android.com/training/notify-user/group)  are supported.  Are they?  If they are, do you mind pointing me in the right direction?  (Sorry, I am only just a beginner in Android, so I may have missed something while looking over the code.)

Thanks for the making the Upload Service!  It really helps coders like me!

**Comment by gotev** [comment]
Hi @oevad 😃 glad it's useful!
That feature is long supported in the lib, but it was missing in the wiki. Just added it 😉 Thank you for the report!

The namespace you configure at the startup of the library 

https://github.com/gotev/android-upload-service/blob/3c707d4503e0f4677c86799a53d2e7254f7de28b/uploadservice/src/main/java/net/gotev/uploadservice/UploadServiceConfig.kt#L66-L76

is also used as the group ID for your notifications:

https://github.com/gotev/android-upload-service/blob/3c707d4503e0f4677c86799a53d2e7254f7de28b/uploadservice/src/main/java/net/gotev/uploadservice/observer/task/NotificationHandler.kt#L59
