### ISSUE TITLE
Support android 12

### ISSUE THREAD

**Issue by MichalFrSN** [gotev/android-upload-service#604]
Hi,
We're using an older version of the library and when we try to upload a file from a device with Android 12 OS the app crashes with the following exception:

`java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at net.gotev.uploadservice.UploadNotificationStatusConfig.getClickIntent(UploadNotificationStatusConfig.java:69)
        at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:457)
        at net.gotev.uploadservice.UploadTask.run(UploadTask.java:145)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)`
        
Is the latest release version of the library supports android 12?
If not, are you planning to release a new version soon with API 31 support?

Thank you

**Comment by gotev** [comment]
You're welcome to make a PR 😉

**Comment by psmorandi** [comment]
Really apreciate if someone make a PR to support Android 12. Also worth mention that this library uses android services which will no longer be usable if your app is not visible, not even if it's a foreground service (https://developer.android.com/guide/components/foreground-services#background-start-restrictions). Probably should migrate to something with WorkManager expedite jobs or some observable work.

**Comment by gotev** [comment]
WorkManager is the way to go for the future. I have limited time now and the next months for such an implementation, but I can support people willing to contribute.

**Comment by gotev** [comment]
Android 12 is now supported https://github.com/gotev/android-upload-service/releases/tag/4.7.0 ! Please allow some time to Maven Central to process the new release 😉

**Comment by psmorandi** [comment]
Not sure if this fixes everything in Android 12. Have you tested starting the upload inside a workmanager while the app is not visible/destroyed? I see that you still uses Service and due new restrictions in apps targeting Android 12 this won't be possible anymore (if the app does not respect this exceptions: https://developer.android.com/guide/components/foreground-services#bg-access-restriction-exemptions).

**Comment by gotev** [comment]
@psmorandi the library is intended for uploads to be started from activities/fragments/viewmodels. Starting stuff while the app is in the background is a known limitation at the current state of the art, even before Android 12. https://github.com/gotev/android-upload-service/pull/578#issuecomment-818140639

**Comment by gotev** [comment]
I'm also wondering if is does make sense to still maintain the lib, as moving to WorkManager will mean to be "just" a bunch of jobs to be used with WorkManager APIs.

**Comment by psmorandi** [comment]
> @psmorandi the library is intended for uploads to be started from activities/fragments/viewmodels. Starting stuff while the app is in the background is a known limitation at the current state of the art, even before Android 12. [#578 (comment)](https://github.com/gotev/android-upload-service/pull/578#issuecomment-818140639)
> 
> https://github.com/gotev/android-upload-service/blob/c34b27544b6d95d84fa7177808da177d2d1cd7f2/uploadservice/src/main/java/net/gotev/uploadservice/extensions/ContextExtensions.kt#L35-L75

I know, but with the service and foreground service it worked pretty well for me. Until now of course.

> I'm also wondering if it does make sense to still maintain the lib, as moving to WorkManager will mean a total rewrite from the ground up, to be "just" a bunch of job implementations to be used with WorkManager APIs.
> 
> Current internal architecture revolves around the now "old school" android way of doing stuff:
> 
> * Create an intent
> * Start a service with that intent
> * Do stuff in the service
> * Send broadcast intents from the service
> * Listen to broadcast intents coming from the service to display the notification or to update some app UI
> 
> With WorkManager it will be completely different. Also the library name as it is now won't be representative anymore.

That got me think too. But you know, there are a lot of stuff in WorkManager to observe the work being done. And your lib would be very useful to help build an easy way to display progress. Even if you are using WorkManager you still have some boiler plate to get progress done. But I got you point, maybe we need to update to a more "modern school" of doing stuff. Maybe some android-upload-work/worker.

**Comment by gotev** [comment]
@psmorandi created a dedicated thread to continue the discussion: https://github.com/gotev/android-upload-service/issues/610
