### ISSUE TITLE
Add support for uploading from within a WorkManager

### ISSUE THREAD

**Issue by natidykstein** [gotev/android-upload-service#607]
**Is your feature request related to a problem? Please describe.**
We're using WorkManager to handle all of our POST requests to the server along with upload requests.
The problem is that when uploading a file you can't subscribe to the generated events since you are forced to provide a lifecycleOwner which is not available when running from with a WorkManager thread. (Even if you provide the globally available ProcessLifecycleOwner.get() you'll fail since addObserver() must be called on the main thread)

**Describe the solution you'd like**
A way to subscribe to an upload request without providing a lifecycleOwner

**Describe alternatives you've considered**
Using the GlobalRequestObeserver?...

**Additional context**
N/A

**Are you willing to implement it and maintain it?**
- [ ] Yes 
- [ X ] Can implement it with a Pull Request, but not maintain it
- [ ] No

**Comment by gotev** [comment]
@natidykstein currently the library does not use WorkManager internally. By reading your issue, it seems a help request on WorkManager usage rather than a request or feature regarding this library.

**Comment by gotev** [comment]
Trying to elaborate your request further, you need to start an upload from within a WorkManager task and listen for status updates inside your app, right? If so, you could use this approach: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#example-1 or a GlobalRequestObserver instead of RequestObserver depending on your needs.

**Comment by natidykstein** [comment]
Thanks.
I ended up using the GlobalRequestServer.
But I think the library should support performing an upload from a background thread in a synchronous manner.

You can see for example how the volley network library supports network calls both asynchronous using a listener and synchronous using Future.get()
https://stackoverflow.com/questions/16904741/can-i-do-a-synchronous-request-with-volley

**Comment by gotev** [comment]
Future is WorkManager
