### ISSUE TITLE
FAILED BINDER TRANSACTION

### ISSUE THREAD

**Issue by gauravbarthwal** [gotev/android-upload-service#617]
Hi,

I am working on an app where users can upload multiple images/videos without any limit and have an option to cancel all the uploades. The upload is sequential and once I call `UploadService.stopAllUploads();` the app gets crashed. This happens if I select 35+ images/videos.

> UploadServiceConfig.setThreadPool(new ThreadPoolExecutor(
        1, // Initial pool size
        1, // Max pool size
        5, // Keep Alive Time
        TimeUnit.SECONDS,
        new LinkedBlockingQueue()));

To make upload request I am using below code:

> BinaryUploadRequest requestObserver = new BinaryUploadRequest(ctx, url)
                .setFileToUpload(file.getAbsolutePath())
                .setUploadID(uploadId)
                .setNotificationConfig(UploadUtils.Companion::getUploadNotificationConfig)
                .addHeader(X_WANT_SESSION_NOTIFICATION_MESSAGES, "true")
                .addHeader(CONTENT_TYPE, contentType);

**To Reproduce**
1. Select more than 35 images.
2. Start the upload sequentially.
3. Cancel all the uploads with `UploadService.stopAllUploads()`

**Error Logs:**
> 2022-04-14 16:26:21.732 973-1056/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1756)
2022-04-14 16:26:21.732 973-1056/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1756)
2022-04-14 16:26:21.733 973-1056/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1756)
2022-04-14 16:26:21.733 973-1056/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1756)
2022-04-14 16:26:21.733 973-1056/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 136)

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: 4.7.0
- Android version and API version: I have tested on Android 11
- HTTP stack: OkHttpStack

**Comment by gotev** [comment]
Can you please make a PR with a test which replicates the issue?

**Comment by gauravbarthwal** [comment]
@gotev  I tried to add multi-file upload in the sample app but could not able to reproduce it until I enable `Profiler`. In my implementation, the issue is related to the Broadcast.

> AndroidRuntime: android.app.RemoteServiceException: can't deliver broadcast
AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2150)
AndroidRuntime: 	at android.app.ActivityThread.access$2900(ActivityThread.java:310)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

I am trying to upload 50 files at once and cancel them immediately then the app does not crash but for the second time, it gets crashed. I checked the implementation of the library and it is similar to the sample app.

**Comment by gauravbarthwal** [comment]
I am passing `RequestObserverDelegate` to the below code and if I comment on that code then everything works fine.

> fun subscribe(
        context: Context,
        lifecycleOwner: LifecycleOwner,
        delegate: RequestObserverDelegate
    ): RequestObserver {
        return RequestObserver(
            context,
            lifecycleOwner,
            delegate
        ).apply { subscribe(this@UploadRequest) }
    }
    
I found a [link](https://stackoverflow.com/questions/46971153/fatal-exception-android-app-remoteserviceexception-cant-deliver-broadcast-at/48866003#48866003) where it is mentioned to use `LocalBroadcastManager` for in-app broadcast. Don't know if that is the issue or something else.

**Comment by gauravbarthwal** [comment]
@gotev for multiple files I am using the below code in the loop. If I use `GlobalRequestObserver` in place of subscribing each request with `RequestObserverDelegate` then the app does not crash. 

>  BinaryUploadRequest binaryUploadRequest = new BinaryUploadRequest(context, url)
                .setFileToUpload(file.getAbsolutePath())
                .setUploadID(uploadId)
                .setNotificationConfig(UploadUtils.Companion::getUploadNotificationConfig)
                .addHeader(X_WANT_SESSION_NOTIFICATION_MESSAGES, "true")
                .addHeader(CONTENT_TYPE, contentType);
>       binaryUploadRequest.subscribe(context, ProcessLifecycleOwner.get(), new RequestObserverDelegate() {});

**Comment by gotev** [comment]
So, I guess doing it like that just screates too many references and that in turn causes the error. [GlobalRequestObserver](https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-all-upload-requests) is certainly an option if you want to do things in the background and not interact with the UI directly. Another option would be to use a single [RequestObserver](https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-specific-upload-requests) listening to all the events.

In your specific case this should work:
```kotlin
val requestObserver = RequestObserver(context, lifecycleOwner, delegate)

val binaryUploadRequest = BinaryUploadRequest(context, url)
    .setFileToUpload(file.getAbsolutePath())
    .setUploadID(uploadId)
    .setNotificationConfig(UploadUtils.getUploadNotificationConfig)
    .addHeader(X_WANT_SESSION_NOTIFICATION_MESSAGES, "true")
    .addHeader(CONTENT_TYPE, contentType)
    .startUpload();
```
So you have a single request observer listening to all the uploads.

**Comment by gauravbarthwal** [comment]
Thank you @gotev , this solved the problem.

**Comment by gotev** [comment]
Great 😃
