### ISSUE TITLE
Get Oncompleted callback whole appwide.

### ISSUE THREAD

**Issue by MuhammadIbrahimSE** [gotev/android-upload-service#618]
I want to get the oncompleted callback not in a specific activity, as user can navigate to some other screen, while uploading. I tried using service, but lifecycleowner is another issue in subsrcibe. Tried using broadcast receiver(in application class), but of no use when lifecycleowner itself is  destroyed and broadcast not sent on complete callback.

**Comment by gotev** [comment]
You need [GlobalRequestObserver](https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-all-upload-requests)

**Comment by MuhammadIbrahimSE** [comment]
I tried using globalRequestObserver and I am getting this error in Application class. Java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass

**Comment by gotev** [comment]
The solution is as the error message says. You are not initializing the lub properly. Please check setup info from the wiki.

**Comment by MuhammadIbrahimSE** [comment]
@gotev thanks for guiding, fixed my issue. was registering observer before initialization.
