### ISSUE TITLE
Misleading Android 12 documentation

### ISSUE THREAD

**Issue by thomasttvo** [gotev/android-upload-service#620]
> Android 5.0 (API 21) to Android 12 (API 31) support. Beware you cannot start uploads while your app is the background on Android 12 due to recent Service limitations

This part of the doc is misleading. The library does work when started from the background on Android 12 unless the main app or the library that imports it specifically sets `targetSdkVersion` to `31` and up.

Would also be great to add suggestions to work around the issue should the `targetSdkVersion` is `31+`

**Comment by gotev** [comment]
Hi @thomasttvo and thanks for the feedback!

> The library does work when started from the background on Android 12 unless the main app or the library that imports it specifically sets targetSdkVersion to 31 and up.

That's true, I added an explanation.

> Would also be great to add suggestions to work around the issue should the targetSdkVersion is 31+

The only option going forward is to migrate to WorkManager: https://github.com/gotev/android-upload-service/issues/610

**Comment by AlkanV** [comment]
hello @gotev do you plan any support for android 12 ( targetSdk  31+) for background services, 

best,

alkan.

**Comment by gotev** [comment]
@AlkanV added a note which better explain Android 12 support status: https://github.com/gotev/android-upload-service/blob/master/README.md#features-
