### ISSUE TITLE
Server response: code 415 

### ISSUE THREAD

**Issue by vedraj360** [gotev/android-upload-service#623]
Getting Server response: code 415 when uploading need to pass content type with the object but not able to find any way to pass it.

    val multipartUploadRequest = MultipartUploadRequest(
                context,
                Constants.SERVER_IP
            )
                .setMethod("POST")
                .setUploadID(imgPath)
                .setBearerAuth(sessionToken)
                .addHeader("Content-Type", "application/json")=
                .addFileToUpload(
                    imgPath,
                    "file"
                ).addFileToUpload(
                    imgPath,
                    "thumbnail"
                ).addParameter(
                    "shopDto", "{\n" +
                            "\"retailerId\" : 3,\n" +
                            "\"lat\" : 28.123,\n" +
                            "\"lon\" : 75.098,\n" +
                            "}"
                )

**Comment by gotev** [comment]
Custom Content Type is set using the addHeader method, as you have done.

**Comment by vedraj360** [comment]
> Custom Content Type is set using the addHeader method, as you have done.

but still it is failing

**Comment by vedraj360** [comment]
@gotev Right it was server side issue. I worked as made content type string instead of json.
