### ISSUE TITLE
memory leak  

### ISSUE THREAD

**Issue by ttdazi** [gotev/android-upload-service#625]
├─ android.os.PowerManager$WakeLock instance
│    Leaking: UNKNOWN
│    Retaining 3.5 kB in 51 objects
│    ↓ PowerManager$WakeLock.this$0
│                            ~~~~~~
├─ android.os.PowerManager instance
│    Leaking: UNKNOWN
│    Retaining 3.3 kB in 48 objects
│    mContext instance of net.gotev.uploadservice.UploadService
│    ↓ PowerManager.mContext
│                   ~~~~~~~~
╰→ net.gotev.uploadservice.UploadService instance
​     Leaking: YES (ObjectWatcher was watching this because net.gotev.uploadservice.UploadService received Service#onDestroy() callback and Service not held by ActivityThread)
​     Retaining 1.8 kB in 31 objects

**Comment by gotev** [comment]
Hey @ttdazi can you replicate this behaviour systematically with a test?
