### ISSUE TITLE
java.lang.InstantiationException

### ISSUE THREAD

**Issue by winnerawan** [gotev/android-upload-service#633]
Got this exception when using **`minifyEnabled true`**
`Caused by: java.lang.InstantiationException: java.lang.Class<net.gotev.uploadservice.schemehandlers.FileSchemeHandler> cannot be instantiated`

everything's fine when i set it `false`
any proguard example for this? or it because r8 or d8?

- targetSdk 33
- compileSdk 33
- tested in Android 12

EDIT: Closed, its proguard issue, you should place proguard doc in front readme

**Comment by gotev** [comment]
Feel free to open a PR with the contribution
