### ISSUE TITLE
Google Play will soon require that apps target API level 33 or higher. This will be required for new apps and updates starting on August 31, 2023.

### ISSUE THREAD

**Issue by takmilul** [gotev/android-upload-service#638]
"Google Play will soon require that apps target API level 33 or higher. This will be required for new apps and updates starting on August 31, 2023."

We are getting the above warning from Google to upgrade the target API level to 33 or higher by 31st August. Requesting you to update the library accordingly so that we can match it with our project and continue using your library. Thanks.

**Comment by gotev** [comment]
Hi, Upload Service is not a blocker in this case. You just have to bump your app's target sdk to 33 and manually request POST_NOTIFICATIONS request permission when on API 33+ as per Google latest guidelines.

A new Upload Service is on its way, but in the meantime you can go ahead with your app.

**Comment by takmilul** [comment]
I have bumped the target sdk to 33. But I got a compile error.

`Class 'UploadTaskParameters' is not abstract and does not implement abstract base class member public abstract fun writeToParcel(dest: Parcel, flags: Int): Unit defined in net.gotev.uploadservice.persistence.PersistableData`

Here my UploadTaskParameters extended your PersistableData class. In the PersistableData class, you have overridden the following method: override fun writeToParcel(dest: Parcel?, flags: Int). In SDK 33+ the method has been changed to override fun writeToParcel(dest: Parcel, flags: Int) where the parameter destination Parcel is non-nullable.

I also tried to override the method which leads me the following error: 
`Accidental override: The following declarations have the same JVM signature (writeToParcel(Landroid/os/Parcel;I)V)`

can you please help me find a way to fix the compile error here?

**Comment by gotev** [comment]
`4.8.0` has been released in the meantime. Bump to it and simply remove the optionality here: https://github.com/gotev/android-upload-service/commit/f2254d47b33a3891e33c600f39fef7abfa9ffdf9#diff-9821d08b4f2ceb9d7eed1d58514f4a079a4cc4f31112f919e7f3ad00d4a3cbfcL45

**Comment by takmilul** [comment]
Thank you very much for your quick support and a great library.
