### ISSUE TITLE
register gotev receiver

### ISSUE THREAD

**Issue by amirhossinD** [gotev/android-upload-service#654]
when I Run Gotev code after taking picture and confirm that i face the error that says:
` Unable to create service net.gotev.uploadservice.UploadService: java.lang.SecurityException: com.arh.intellimage: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`
how should i register this for android 14?

**Comment by gotev** [comment]
Which version of the library are you using? Android 14 is supported in the latest version

**Comment by amirhossinD** [comment]
My bad. I was using 4.7.0. I did update, and everything is good. Tnx
