### ISSUE TITLE
Bitrise CI Build Failing with New Version

### ISSUE THREAD

**Issue by sayantanLudimos** [gotev/android-upload-service#656]
**Describe the bug**
Bitrise CI Build failing with the new version of the library but working fine for the version 'net.gotev:uploadservice:4.7.0'

**To Reproduce**
1. Push the code to a branch
2. Bitrise will start automated building
3. Build failed after few time.

**Expected behavior**
Build should not be failed for the library.

**Debug Log**:
> Task :app:kaptLudimosReleaseKotlin
/bitrise/src/app/build/tmp/kapt3/stubs/[REDACTED]Release/com/[REDACTED]app/presentation/ui/uploadvideoai/uploaddetails/PendingUploadsFragment.java:61: error: cannot access UploadInfo
    private final int getTimeRemaining(net.gotev.uploadservice.data.UploadInfo uploadInfo) {
                                                                   ^
  bad class file: /root/.gradle/caches/transforms-3/05ed049cbeb6603da12042d7fb163bed/transformed/jetified-uploadservice-4.9.2-api.jar(/net/gotev/uploadservice/data/UploadInfo.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/bitrise/src/app/build/tmp/kapt3/stubs/[REDACTED]Release/com/[REDACTED]app/presentation/utils/videouploadmodule/VideoUploadManager.java:10: error: cannot access RequestObserverDelegate
    private final net.gotev.uploadservice.observer.request.RequestObserverDelegate delegate = null;
                                                          ^
  bad class file: /root/.gradle/caches/transforms-3/05ed049cbeb6603da12042d7fb163bed/transformed/jetified-uploadservice-4.9.2-api.jar(/net/gotev/uploadservice/observer/request/RequestObserverDelegate.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/bitrise/src/app/build/tmp/kapt3/stubs/[REDACTED]Release/com/[REDACTED]app/presentation/foundation/workmanager/SingleNotificationHandler.java:6: error: cannot access AbstractSingleNotificationHandler
public final class SingleNotificationHandler extends net.gotev.uploadservice.observer.task.AbstractSingleNotificationHandler {
                                                                                          ^
  bad class file: /root/.gradle/caches/transforms-3/05ed049cbeb6603da12042d7fb163bed/transformed/jetified-uploadservice-4.9.2-api.jar(/net/gotev/uploadservice/observer/task/AbstractSingleNotificationHandler.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/bitrise/src/app/build/tmp/kapt3/stubs/[REDACTED]Release/com/[REDACTED]app/presentation/foundation/workmanager/SingleNotificationHandler.java:9: error: cannot access UploadService
    net.gotev.uploadservice.UploadService service) {
                           ^
  bad class file: /root/.gradle/caches/transforms-3/05ed049cbeb6603da12042d7fb163bed/transformed/jetified-uploadservice-4.9.2-api.jar(/net/gotev/uploadservice/UploadService.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

> Task :app:kaptLudimosReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptLudimosReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by gotev** [comment]
You need to change Java from 11 to at least 17 in your Bitrise CI pipeline
