### ISSUE TITLE
Android Upload Service for KMM (Koltin Multiplateform)

### ISSUE THREAD

**Issue by Vaxela** [gotev/android-upload-service#658]
**Is your feature request related to a problem? Please describe.**
We are in the process of upgrading our koltin project for android to cross-platform kotlin for iOS, I wanted to know if there were already any leads if the plugins were going to be compatible?

**Describe the solution you'd like**
Be able to use the service on both Android and iOS platforms 

**Are you willing to implement it and maintain it?**
 NO :/

**Comment by gotev** [comment]
Hi! The Library is Android-specific and iOS has a completely different architecture, so an iOS-specific solution has to be written from scratch. Multiplatform can then be used to wrap the two solutions.

**Comment by Vaxela** [comment]
Ok thank you for your answer :)
