### ISSUE TITLE
Upload media (small video, image) in base64 string

### ISSUE THREAD

**Issue by idanbar134** [gotev/android-upload-service#67]
Hello Dear Alex,

can you please help me to understand how can I use your amazing library to send base64 String and more values as Body to my server instead of file?

I will really appreciate your answer.
Thank

```java
    /**
     * upload media (movie, picture, voice file) with upload service.
     * @param context context
     * @param base64 the media convert to Base64 format
     */
    public void uploadMedia(final Context context, String base64) {
        final String token =sp.getString(KEY_TOKEN);
        final String uploadID = UUID.randomUUID().toString();
        final String serverUrlString = NetworkDefines.Servers.DATA_SERVER_HTTP;

        try {
            new MultipartUploadRequest(context, uploadID, serverUrlString)
                    .addFileToUpload("/absolute/path/to/your/file", "your-param-name") //FIXME instead of file i want to send Base64 String
                    .addParameter(KEY_TOKEN ,token)
                    .addParameter(ROWIDX, ROWIDX_VALUE)
                    .addParameter(MEDIA_DATA, base64)
                    .addParameter(CHAT_ID, chatInfo.getChatId())
                    .addParameter(KEY_BASE64, String.valueOf(base64.length()))
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload();
        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }
    }
```

**Comment by alexbbb** [comment]
Hi. As I've stated in my last comment in https://github.com/alexbbb/android-upload-service/issues/54 you can't use `MultipartUploadRequest` for what you are trying to achieve, because for a request to be a HTTP/Multipart, it needs at least one file, but you have only parameters. What you need is to extend base class libraries (refer to my comment in #54) to be able to make a standard HTTP POST request. Feel free to fork the project and implement what you need :)

**Comment by gotev** [comment]
As of 2.0, you can simply extend `MultipartUploadRequest` class directly in your app's code to add the desired feature. No need to fork the library, just add the dependency and you're good to go :)
