### ISSUE TITLE
We need to support download service!

### ISSUE THREAD

**Issue by OnClickListener2048** [gotev/android-upload-service#671]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Are you willing to implement it and maintain it?**
- [ ] Yes 
- [ ] Can implement it with a Pull Request, but not maintain it
- [ ] No

**Comment by gotev** [comment]
No need, you can simply use Android Download manager system service
