### ISSUE TITLE
problem with utf-8 charset in filename

### ISSUE THREAD

**Issue by asafbennatan** [gotev/android-upload-service#82]
hi ,
i am using android-upload-service to upload a file with filename written in hebrew (utf-8 encoding),
on the other end i'm getting ????????? instead of the filename,
is there any way to set the charset ?
(i have currently tried setting the content-type to :multipart/form-data; charset=utf-8 but this breaks the upload entirely as the server returns error)
Thanks.

**Comment by alexbbb** [comment]
Hi,
the behaviour you described is perfectly normal. I'm going to explain you why. 
First, setting the content type as you've done is wrong and it's normal that your server side complains about it. The content type specifies the MIME type of the file and has nothing to do with the filename.
 
Android Upload Service is compliant to RFC2388. In [section 4.4](https://tools.ietf.org/html/rfc2388#section-4.4) is stated that:
>   The original local file name may be supplied as well, either as a
   "filename" parameter either of the "content-disposition: form-data"
   header or, in the case of multiple files, in a "content-disposition:
   file" header of the subpart. The sending application MAY supply a
   file name; if the file name of the sender's operating system is not
   in US-ASCII, the file name might be approximated, or encoded using
   the method of RFC 2231.

In the current release 1.6 and in the upcoming 2.0, the filename is encoded in US-ASCII (as you can see [here](https://github.com/alexbbb/android-upload-service/blob/2.0/uploadservice/src/main/java/com/alexbbb/uploadservice/UploadFile.java#L104)) and RFC 2231 is not supported. I suggest you to use ASCII file names though, to have the maximum compatibility across all the platforms.

**Comment by asafbennatan** [comment]
would it be possible to expose file name field charset in-order for it to be set?
(in future versions)

**Comment by alexbbb** [comment]
Of course it's possible. That means implementing RFC 2231 and applying it when the filename charset is explicitly set and differs from US-ASCII. Unfortunately I don't have time to implement it, cause it's not requested in my actively running projects, but here comes the cool side of Github! If you want, you can fork the sources and implement it, then I'll merge your pull request :)

**Comment by asafbennatan** [comment]
ok its done (took a while for it to compile under android studio...)
here is my updated repository https://github.com/asafbennatan/android-upload-service
how do we merge it ?

**Comment by alexbbb** [comment]
Wow you've been blazingly fast! :)
I've just merged 2.0 development branch into master release and released 2.0, so you have to pull in the changes and implement the modifications on the new code base. Then send me a pull request.

**Comment by asafbennatan** [comment]
done

**Comment by gotev** [comment]
I've made some other research on the internet, to try to find the standard which defines how to handle non `US-ASCII` file names in Multipart upload, in response to pull request #85. What I've found corresponds to the RFCs referred to in the previous posts, so I thought:
> This can't be the way it's handled today! Almost 19 years passed since November 1997 ([RFC 2231](http://tools.ietf.org/html/rfc2231)). Thousands of people around the world works every day to improve the internet, its standards and its protocols. There must be a better and more modern way. Let's check how three of the major browsers handles this with some tests!
>
> You can skip to the end results at the bottom of this post if you don't want to enter into the details.

## Test material
### Software
Tests have been done on Apple OS X 10.11.2 "El Capitan", with:
*  Android Upload Service example node.js server (node v4.2.1 with express 4.12.0 and multer 0.1.8)
*  Safari 9.0.2
*  Firefox 43
*  Google Chrome 47.0.2526.111
*  Wireshark v2.0.0-0-g9a73b82

*Why not Internet Explorer?*
It's a relic from the past, it's obsolete and not really a good browser. Its development has (fortunately) stopped, as Microsoft is working on Edge, so it's pointless to test how it behaves.

### Html pages

`noencoding.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Multipart Upload Test</title>
  </head>
  <body>
    <form action="http://localhost:3000/upload/multipart" method="post" enctype="multipart/form-data">
      text parameter: <input type="text" name="param1"><br>
      file: <input type="file" name="file1"><br>
      <input type="submit" value="Upload">
    </form>
  </body>
</html>
```

`utf8.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Multipart Upload Test</title>
  </head>
  <body>
    <form action="http://localhost:3000/upload/multipart" method="post" enctype="multipart/form-data">
      text parameter: <input type="text" name="param1"><br>
      file: <input type="file" name="file1"><br>
      <input type="submit" value="Upload">
    </form>
  </body>
</html>
```

the two files are identical, except the meta tag in `utf8.html`.

### Form parameters
param1: `тест`
file name: `тест файл.txt` with content (UTF-8 encoding):
```
sometext
нещо на кирилица

```

## Tests
### Safari 9.0.2
#### noencoding.html
Multipart Request dump (shown in UTF-8):
```
POST /upload/multipart HTTP/1.1
Host: localhost:3000
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarygr71kAhqi4tgO1Nx
Origin: file://
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
Content-Length: 349
Accept-Language: it-it
Accept-Encoding: gzip, deflate

------WebKitFormBoundarygr71kAhqi4tgO1Nx
Content-Disposition: form-data; name="param1"

&#1090;&#1077;&#1089;&#1090;
------WebKitFormBoundarygr71kAhqi4tgO1Nx
Content-Disposition: form-data; name="file1"; filename="???? ????.txt"
Content-Type: text/plain

sometext
нещо на кирилица

------WebKitFormBoundarygr71kAhqi4tgO1Nx--
```

node.js server output:
```
HTTP/Multipart Upload Request from: ::ffff:127.0.0.1

Received headers
----------------
host: localhost:3000
content-type: multipart/form-data; boundary=----WebKitFormBoundarygr71kAhqi4tgO1Nx
origin: file://
connection: keep-alive
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
content-length: 349
accept-language: it-it
accept-encoding: gzip, deflate

Started file upload
  parameter name: file1
  file name: ???? ????.txt
  mime type: text/plain
Completed file upload
  parameter name: file1
  file name: ???? ????.txt
  mime type: text/plain
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/???? ????.txt

Received Parameters
-------------------
param1: &#1090;&#1077;&#1089;&#1090;
```

#### utf8.html
Multipart Request dump (shown in UTF-8):
```
POST /upload/multipart HTTP/1.1
Host: localhost:3000
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarydg4PpHkZAtlllqGk
Origin: file://
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
Content-Length: 339
Accept-Language: it-it
Accept-Encoding: gzip, deflate

------WebKitFormBoundarydg4PpHkZAtlllqGk
Content-Disposition: form-data; name="param1"

текст
------WebKitFormBoundarydg4PpHkZAtlllqGk
Content-Disposition: form-data; name="file1"; filename="тест файл.txt"
Content-Type: text/plain

sometext
нещо на кирилица

------WebKitFormBoundarydg4PpHkZAtlllqGk--
```

node.js server output:
```
HTTP/Multipart Upload Request from: ::ffff:127.0.0.1

Received headers
----------------
host: localhost:3000
content-type: multipart/form-data; boundary=----WebKitFormBoundarydg4PpHkZAtlllqGk
origin: file://
connection: keep-alive
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
content-length: 339
accept-language: it-it
accept-encoding: gzip, deflate

Started file upload
  parameter name: file1
  file name: тест файл.txt
  mime type: text/plain
Completed file upload
  parameter name: file1
  file name: тест файл.txt
  mime type: text/plain
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/тест файл.txt

Received Parameters
-------------------
param1: текст
```

### Firefox 43
#### noencoding.html
Multipart Request dump (shown in UTF-8):
```
POST /upload/multipart HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: it,it-IT;q=0.9,en;q=0.8,en-US;q=0.6,ru;q=0.5,en-GB;q=0.4,bg-BG;q=0.3,bg;q=0.1
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Content-Type: multipart/form-data; boundary=---------------------------68979457712607291332000877029
Content-Length: 457

-----------------------------68979457712607291332000877029
Content-Disposition: form-data; name="param1"

&#1090;&#1077;&#1089;&#1090;
-----------------------------68979457712607291332000877029
Content-Disposition: form-data; name="file1"; filename="&#1090;&#1077;&#1089;&#1090; &#1092;&#1072;&#1080;&#774;&#1083;.txt"
Content-Type: text/plain

sometext
нещо на кирилица

-----------------------------68979457712607291332000877029--
```

node.js server output:
```
HTTP/Multipart Upload Request from: ::1

Received headers
----------------
host: localhost:3000
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
accept-language: it,it-IT;q=0.9,en;q=0.8,en-US;q=0.6,ru;q=0.5,en-GB;q=0.4,bg-BG;q=0.3,bg;q=0.1
accept-encoding: gzip, deflate
dnt: 1
connection: keep-alive
content-type: multipart/form-data; boundary=---------------------------68979457712607291332000877029
content-length: 457

Started file upload
  parameter name: file1
  file name: &#1090;&#1077;&#1089;&#1090; &#1092;&#1072;&#1080;&#774;&#1083;.txt
  mime type: text/plain
Completed file upload
  parameter name: file1
  file name: &#1090;&#1077;&#1089;&#1090; &#1092;&#1072;&#1080;&#774;&#1083;.txt
  mime type: text/plain
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/&#1090;&#1077;&#1089;&#1090; &#1092;&#1072;&#1080;&#774;&#1083;.txt

Received Parameters
-------------------
param1: &#1090;&#1077;&#1089;&#1090;
```

#### utf8.html
Multipart Request dump (shown in UTF-8):
```
POST /upload/multipart HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: it,it-IT;q=0.9,en;q=0.8,en-US;q=0.6,ru;q=0.5,en-GB;q=0.4,bg-BG;q=0.3,bg;q=0.1
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Content-Type: multipart/form-data; boundary=---------------------------12937980301591564335365471313
Content-Length: 393

-----------------------------12937980301591564335365471313
Content-Disposition: form-data; name="param1"

тест
-----------------------------12937980301591564335365471313
Content-Disposition: form-data; name="file1"; filename="тест файл.txt"
Content-Type: text/plain

sometext
нещо на кирилица

-----------------------------12937980301591564335365471313--
```

node.js server output:
```
HTTP/Multipart Upload Request from: ::1

Received headers
----------------
host: localhost:3000
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
accept-language: it,it-IT;q=0.9,en;q=0.8,en-US;q=0.6,ru;q=0.5,en-GB;q=0.4,bg-BG;q=0.3,bg;q=0.1
accept-encoding: gzip, deflate
dnt: 1
connection: keep-alive
content-type: multipart/form-data; boundary=---------------------------12937980301591564335365471313
content-length: 393

Started file upload
  parameter name: file1
  file name: тест файл.txt
  mime type: text/plain
Completed file upload
  parameter name: file1
  file name: тест файл.txt
  mime type: text/plain
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/тест файл.txt

Received Parameters
-------------------
param1: тест
```

### Google Chrome 47.0.2526.111
#### noencoding.html
Multipart Request dump (shown in UTF-8):
```
POST /upload/multipart HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 350
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Origin: null
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryHrDjBtr7cxYDaB6k
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: session=

------WebKitFormBoundaryHrDjBtr7cxYDaB6k
Content-Disposition: form-data; name="param1"

&#1090;&#1077;&#1089;&#1090;
------WebKitFormBoundaryHrDjBtr7cxYDaB6k
Content-Disposition: form-data; name="file1"; filename="???? ?????.txt"
Content-Type: text/plain

sometext
нещо на кирилица

------WebKitFormBoundaryHrDjBtr7cxYDaB6k--
```

node.js server output:
```
HTTP/Multipart Upload Request from: ::1

Received headers
----------------
host: localhost:3000
connection: keep-alive
content-length: 350
cache-control: max-age=0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
origin: null
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
content-type: multipart/form-data; boundary=----WebKitFormBoundaryHrDjBtr7cxYDaB6k
accept-encoding: gzip, deflate
accept-language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
cookie: session=

Started file upload
  parameter name: file1
  file name: ???? ?????.txt
  mime type: text/plain
Completed file upload
  parameter name: file1
  file name: ???? ?????.txt
  mime type: text/plain
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/???? ?????.txt

Received Parameters
-------------------
param1: &#1090;&#1077;&#1089;&#1090;
```

#### utf8.txt
Multipart Request dump (shown in UTF-8):
```
POST /upload/multipart HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 339
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Origin: null
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryUoSMJPN5VXIDa2Vy
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: session=

------WebKitFormBoundaryUoSMJPN5VXIDa2Vy
Content-Disposition: form-data; name="param1"

тест
------WebKitFormBoundaryUoSMJPN5VXIDa2Vy
Content-Disposition: form-data; name="file1"; filename="тест файл.txt"
Content-Type: text/plain

sometext
нещо на кирилица

------WebKitFormBoundaryUoSMJPN5VXIDa2Vy--
```

node.js server output:
```
HTTP/Multipart Upload Request from: ::1

Received headers
----------------
host: localhost:3000
connection: keep-alive
content-length: 339
cache-control: max-age=0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
origin: null
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
content-type: multipart/form-data; boundary=----WebKitFormBoundaryUoSMJPN5VXIDa2Vy
accept-encoding: gzip, deflate
accept-language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
cookie: session=

Started file upload
  parameter name: file1
  file name: тест файл.txt
  mime type: text/plain
Completed file upload
  parameter name: file1
  file name: тест файл.txt
  mime type: text/plain
  in: /Users/alex/workspace/android-upload-service/examples/server-nodejs/uploads/тест файл.txt

Received Parameters
-------------------
param1: тест
```

## Results
### Safari 9.0.2 and Google Chrome 47.0.2526.111
If charset is not specified, non US-ASCII characters in multipart headers are replaced by `?`. Parameter values are converted in [HTML Entities](http://dev.w3.org/html5/html-author/charref). The content of the file gets encoded using the original file encoding.

If charset UTF-8 is specified, all the multipart headers and parameter values are encoded in UTF-8.
The content of the file gets encoded using the original file encoding.

### Firefox 43
If charset is not specified, non US-ASCII characters in multipart headers and parameter values are converted in [HTML Entities](http://dev.w3.org/html5/html-author/charref). The content of the file gets encoded using the original file encoding.

If charset UTF-8 is specified, all the multipart headers and parameter values are encoded in UTF-8. The content of the file gets encoded using the original file encoding.

### Final thoughts
As I've seen from the tests, if the charset is not specified, US-ASCII is used. Non US-ASCII characters in file names can be replaced by `?` or with their [HTML Entity](http://dev.w3.org/html5/html-author/charref) representation. Personally I prefer the first option, which is adopted by Safari and Google Chrome. Non US-ASCII characters in parameter values are replaced with their HTML Entity representation.

So, to make the library act like one of the modern browsers:
*  Add a method called `setUtf8Charset()` in `MultipartUploadRequest` class. The method sets an internal boolean flag, called for example `utf8request`, which value is false by default
*  In `MultipartUploadTask`, implement the following:
 * when `utf8request = false`, convert all the parameter values in html entities.
 * when `utf8request = true`, encode all the multipart headers and parameter values in UTF-8

This way it will be simple for the library user to use UTF-8 when having to deal with non US-ASCII character encoding, beding sure that every value (file name, parameter name or parameter value) will be properly encoded.

**Comment by gotev** [comment]
@asafbennatan 2.0.1 just released. Update your dependencies and you will be able to set UTF 8 Charset in your requests :smiley:

**Comment by asafbennatan** [comment]
Cool Thanks!


2016-02-10 22:43 GMT+02:00 Alex Gotev <notifications@github.com>:

**Comment by rohitPagare** [comment]
want to send header with hindi characters...
but when i do like this
multipartUploadRequest.addHeader("headline", "श्री सिद्धिविनायक");

it gives error
Header headline must be ASCII only! Read http://stackoverflow.com/a/4410331

please help me
