### ISSUE TITLE
Publish library on Maven Central

### ISSUE THREAD

**Issue by alexbbb** [gotev/android-upload-service#84]
Hi folks! I need your opinion.
I've just released 2.0 tonight and I've prepared all the necessary to be able to publish the library also on Maven Central (as you know it's already linked in jcenter). 
Well...not exactly. There's only an thing which I've not considered! A BIG thing...

Once upon a time, when I started this project, a was a younger dumb boy and I decided to use the namespace `com.alexbbb`. Later on, I've bought the domain associated to my surname. To be able to publish the artifacts also on Maven Central, I have to own `alexbbb.com`. The domain I own is `gotev.net`, so to be able to publish the library there, I would have to change the namespace of all the library classes. That means updating all the projects which uses the library, so before doing anything like that, I want to ask you what do you think:
1. stick with `com.alexbbb` and forget about Maven Central
2. refactor to `net.gotev` and publish the library on Maven Central and Jcenter with the new namespace.

My intention is to go with the solution 2 for the next release as soon as possible.

Vote!

**Comment by ProgramAPE** [comment]
I also prefer solution 2.

**Comment by mabdurrahman** [comment]
Vote for option 2, and congrats for 2.0 release :+1:

**Comment by gotev** [comment]
All the needed namespace refactorings has been done (code & docs)! Now the library is hosted on jcenter and maven central as well.
#### Maven

```
<dependency>
  <groupId>net.gotev</groupId>
  <artifactId>uploadservice</artifactId>
  <version>2.0</version>
  <type>aar</type>
</dependency>
```

#### Gradle

```
dependencies {
    compile 'net.gotev:uploadservice:2.0'
}
```
