### ISSUE TITLE
onError Restart Uploading

### ISSUE THREAD

**Issue by yaseenayahya** [gotev/android-upload-service#89]
onError Restart Uploading the same file anyhow is this possible i can get upload details by uploadid??

**Comment by gotev** [comment]
You mean restarting the upload if an error occurs?

**Comment by yaseenayahya** [comment]
yes sir.

**Comment by gotev** [comment]
As shown in the example [here](https://github.com/gotev/android-upload-service/wiki/Create%20and%20stop%20upload%20requests), this is accomplished by calling `setMaxRetries` method on your upload request. If the upload fails, it will be automatically retried by the library without notifying you errors for the number of times that you specify. If the upload fails even after those retries, your broadcast receiver's `onError`method will be called. 

Practice suggests that if a request fails for more than 2 or 3 times in a row, maybe the device is not connected to the internet or your server is not reachable at that moment, so you have to implement a proper strategy to handle that. I suggest you to read https://github.com/gotev/android-upload-service/issues/30 and https://github.com/gotev/android-upload-service/issues/35 to get a hint.
