### ISSUE TITLE
Upload Error on JellyBeans

### ISSUE THREAD

**Issue by TechValensJava** [gotev/android-upload-service#90]
Hi ,

When I run this service on JellyBeans. I get Bad Request error from my server.
Does this not support Jellybeans (API 17,18)

**Comment by gotev** [comment]
Please [read this](https://github.com/gotev/android-upload-service/wiki/Resolve%20common%20setup%20issues) and provide some additional info. If yu received Bad Request, check your server implementation, too. The library supports [API >= 10](https://github.com/gotev/android-upload-service/blob/master/uploadservice/build.gradle#L18)

**Comment by TechValensJava** [comment]
Hi,

I have tried this with Tag 1.3.1 of your repository and its working with that on Jellybeans.
So I was wondering why it was not working with gradle dependency.

**Comment by gotev** [comment]
Until you provide some details about how you've configured the dependencies in your project and which exact code you use to make a request to your server, I'm unable to help you. I actively use 2.0 release without problems in production.

**Comment by TechValensJava** [comment]
I had used 2.0 release and configured it as per direction and it works fine on kitkat ,Lolipop but it gives error in Jellybeans (my server sent Bad Request) but if I use 1.3.1 release it worked fine.

**For 2.0 , I used below snippet**

     new MultipartUploadRequest(QueueService.this, String.valueOf(bean.getUploadID()), bean.getAction())
                    .addFileToUpload(bean.getLocalFilePath(), "media")
                    .addHeader("Authorization", "Token " + SharedPref.getSharedPrefData(QueueService.this, SharedPref.PREFRENCE_KEY_TOKEN))
                    .addHeader("X-APP-ID", WebServiceConstants.APP_ID)
                    .setNotificationConfig(new UploadNotificationConfig().setIcon(R.drawable.notification_icon).setTitle("VuNote shot upload"))
                    .setMaxRetries(2)
                    .startUpload();

Also I have added the dependency and used NameSpace declaration in Application.

**For 1.3.1, I have used below snippet**

 UploadRequest request = new UploadRequest(QueueService.this,
                String.valueOf(bean.getUploadID())
                , bean.getAction());

        request.addHeader("Authorization", "Token " + SharedPref.getSharedPrefData(QueueService.this, SharedPref.PREFRENCE_KEY_TOKEN));
        request.addHeader("X-APP-ID", WebServiceConstants.APP_ID);
        request.addFileToUpload(bean.getLocalFilePath(), "media", System.currentTimeMillis() + ".mp4", ContentType.APPLICATION_OCTET_STREAM);


        System.out.println("request of Upload img : " + request.toString());
        request.setNotificationConfig(R.drawable.notification_icon, getString(R.string.app_name)+" shot upload",
                "Uploading...", "Upload completed",
                "Upload Error", false);

        try {
            UploadService.startUpload(request);

        } 

I have added the service in manifest.

**Comment by gotev** [comment]
with 2.0 you add file like this:
```java
addFileToUpload(bean.getLocalFilePath(), "media")
```
and with 1.3.1:
```java
addFileToUpload(bean.getLocalFilePath(), "media", 
            System.currentTimeMillis() + ".mp4", 
            ContentType.APPLICATION_OCTET_STREAM);
```
that's the only difference I see in your code. In 2.0, when you use [addFileToUpload(String, String)](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/MultipartUploadRequest.html#addFileToUpload-java.lang.String-java.lang.String-), you are leaving the mime type detection to the system. First thing to try is to explicitly set the content type when using 2.0. If still does not work on Jelly Bean, I think the best thing to do is perform a tcpdump of a request made with 2.0 on KitKat and above and a tcpdump of a request made with 2.0 on JellyBean. The difference between the two will tell us where the problem is.

**Comment by gotev** [comment]
Made a test with latest library master revision and the example node.js server. 
Dumped the requests with Wireshark.

Code to generate the request (inside an Activity):
```java
new MultipartUploadRequest(this, "http://10.0.2.2:3000/upload/multipart")
                        .addFileToUpload(fileToUploadPath, "file1")
                        .setCustomUserAgent("UploadServiceDemo/2.0")
                        .addParameter("param1", "value1")
                        .setMaxRetries(2)
                        .startUpload();
```

### Test on Android 4.2.2 (API 17)

#### Test #1

Parameters:
```
param1=value1
```

Files: Text file without extension

```
POST /upload/multipart HTTP/1.1
Connection: close
Content-Type: multipart/form-data; boundary=-------AndroidUploadService1454961376057
User-Agent: UploadServiceDemo/2.0
Host: 10.0.2.2:3000
Accept-Encoding: gzip
Content-Length: 331


---------AndroidUploadService1454961376057
Content-Disposition: form-data; name="param1"

value1
---------AndroidUploadService1454961376057
Content-Disposition: form-data; name="file1"; filename="test"
Content-Type: application/octet-stream

test file
with something in it

---------AndroidUploadService1454961376057--
```

#### Test #2

Parameters:
```
param1=value1
```

Files: Text file with .txt extension

```
POST /upload/multipart HTTP/1.1
Connection: close
Content-Type: multipart/form-data; boundary=-------AndroidUploadService1454961490761
User-Agent: UploadServiceDemo/2.0
Host: 10.0.2.2:3000
Accept-Encoding: gzip
Content-Length: 321


---------AndroidUploadService1454961490761
Content-Disposition: form-data; name="param1"

value1
---------AndroidUploadService1454961490761
Content-Disposition: form-data; name="file1"; filename="test.txt"
Content-Type: text/plain

test file
with something in it

---------AndroidUploadService1454961490761--
```
in both cases I' havent had any errors. Retried the same on Android API 19, ad the requests are exactly the same, except for the boundary which is different, so I can't reproduce your issue. Have you managed to solve it by following the indications which I've posted?
