### ISSUE TITLE
File Uploaded Successful message show but not upload

### ISSUE THREAD

**Issue by younas-bangash** [gotev/android-upload-service#99]
I try to upload video file with in the range of the upload limit which is set on server message show that file successfully uploaded but not comes to server and how i send extra parameter with it ?

**Comment by gotev** [comment]
Check [this](https://github.com/gotev/android-upload-service/wiki/Create%20and%20stop%20upload%20requests) for setup instructions, in which you can find how to add parameters, and [this](https://github.com/gotev/android-upload-service/wiki/Resolve%20common%20setup%20issues) to be sure you've setup everything correctly. After that, if you still have problems, do a dump with Wireshark and report what you've discovered here.

**Comment by younas-bangash** [comment]
My server is reachable and i recheck again the setup everything is fine suppose i have 5 parameter to send to server i.e Key pair values i am not able to send and also i not able to send file using example project also

**Comment by gotev** [comment]
Ok, so post here the code you wrote to make the request and the Android API version on which you are running it.

**Comment by younas-bangash** [comment]
```
  MultipartUploadRequest req = new MultipartUploadRequest(this,"https://abc.ae/phpfiles/progress_file_upload.php")
                        .addFileToUpload(''/storage/sdcard0/Download/video.mp4", "uploaded_file")
                        .setNotificationConfig(getNotificationConfig(filename))
                        .setCustomUserAgent(USER_AGENT)
                        .setAutoDeleteFilesAfterSuccessfulUpload(autoDeleteUploadedFiles.isChecked())
                        .setUsesFixedLengthStreamingMode(fixedLengthStreamingMode.isChecked())
                        .setMaxRetries(2);
```

//progress_file_upload.php
```
/*
//i am not able to add below parameters
$EventID=$_REQUEST["EventID"]; 
$Image=$_REQUEST["Image"];
*/
 if ($_FILES["uploaded_file"]["error"] > 0) {
        echo "Error: " . $_FILES["uploaded_file"]["error"] . "<br>";
    } else {
        echo "Upload: " . $_FILES["uploaded_file"]["name"] . "<br>";
        echo "Type: " . $_FILES["uploaded_file"]["type"] . "<br>";
        echo "Size: " . ($_FILES["uploaded_file"]["size"] / 1024) . " kB<br>";
        echo "Stored in: " . $_FILES["uploaded_file"]["tmp_name"];
    }
```

**Comment by gotev** [comment]
Checked `https://abc.ae/phpfiles/progress_file_upload.php` and you have either expired, non trusted or self signed SSL certificates, so by default for security reasons, the library does not accept that and your upload does not happen. In development stage, use [this](https://gist.github.com/gotev/6784c1303793c6ee9e56) but get valid certificates before going in production. Actually, the class mentioned in that gist is part fo the 2.0.1 release, but I've just dropped that from current master due to #96

**Comment by younas-bangash** [comment]
I hope and wish you include the log in that good library but actually nothing help

**Comment by gotev** [comment]
custom logging is in schedule #97 :smile: but your case does not display a bug in the library at the moment.
Have you fixed your certificate exceptions? Also when the exception is ignored and I point my browser at the URL you provided, I got this:
<img width="1167" alt="schermata 2016-02-20 alle 09 54 48" src="https://cloud.githubusercontent.com/assets/16792495/13195641/10c66ad8-d7b8-11e5-83f8-c73378ad3b72.png">
Which doesn't seem to be the error output of the PHP script you provided. Also, are you able to perform multipart upload with other tools to the same URL?

**Comment by younas-bangash** [comment]
I use other tools and it upload successfully but not uploading from your library it show message Error in Uploading file now

**Comment by younas-bangash** [comment]
The url i provide is the test url i cant provide you the actual url due to my company security reason

**Comment by gotev** [comment]
Ok :+1: If you are in a test environment then what would be helpful to address a possible bug in the library, is to make a dump with wireshark or tcpdump when the upload succeeds using one of your other tools or libraries, then repeat the same with android upload service. The difference between the two will tell you where exactly the problem is.

**Comment by younas-bangash** [comment]
Thanks dear i solve the problem really thanks for your help

**Comment by gotev** [comment]
I'm curious now, what caused the upload issue?

**Comment by younas-bangash** [comment]
I am really apologize the error was from my side thanks again wish you best of luck
